#include "cslr_mdio.h"
CSL_MdioRegs CSL_Mdio_ResetVals;

void *Mdio_Reset_Val_Read()
{
    CSL_Mdio_ResetVals.VERSION_REG = CSL_MDIO_VERSION_REG_RESETVAL;
    CSL_Mdio_ResetVals.CONTROL_REG = CSL_MDIO_CONTROL_REG_RESETVAL;
    CSL_Mdio_ResetVals.ALIVE_REG = CSL_MDIO_ALIVE_REG_RESETVAL;
    CSL_Mdio_ResetVals.LINK_REG = CSL_MDIO_LINK_REG_RESETVAL;
    CSL_Mdio_ResetVals.LINK_INT_RAW_REG = CSL_MDIO_LINK_INT_RAW_REG_RESETVAL;
    CSL_Mdio_ResetVals.LINK_INT_MASKED_REG = CSL_MDIO_LINK_INT_MASKED_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_INT_RAW_REG = CSL_MDIO_USER_INT_RAW_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_INT_MASKED_REG = CSL_MDIO_USER_INT_MASKED_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_INT_MASK_SET_REG = CSL_MDIO_USER_INT_MASK_SET_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_INT_MASK_CLEAR_REG = CSL_MDIO_USER_INT_MASK_CLEAR_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_GROUP[0].USER_ACCESS_REG = CSL_MDIO_USER_ACCESS_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_GROUP[0].USER_PHY_SEL_REG = CSL_MDIO_USER_PHY_SEL_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_GROUP[1].USER_ACCESS_REG = CSL_MDIO_USER_ACCESS_REG_RESETVAL;
    CSL_Mdio_ResetVals.USER_GROUP[1].USER_PHY_SEL_REG = CSL_MDIO_USER_PHY_SEL_REG_RESETVAL;
    return ((void *)&CSL_Mdio_ResetVals);
}
