/********************************************************************
 * Copyright (C) 2013-2014 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#ifndef CSLR_DSSRFBI_H_
#define CSLR_DSSRFBI_H_

#ifdef __cplusplus
extern "C"
{
#endif
#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>


/**************************************************************************
* Register Overlay Structure for REGSET
**************************************************************************/
typedef struct {
    volatile Uint32 RFBI_CONFIG;
    volatile Uint32 RFBI_ONOFF_TIME;
    volatile Uint32 RFBI_CYCLE_TIME;
    volatile Uint32 RFBI_DATA_CYCLE1;
    volatile Uint32 RFBI_DATA_CYCLE2;
    volatile Uint32 RFBI_DATA_CYCLE3;
} CSL_DssrfbiRegsetRegs;


/**************************************************************************
* Register Overlay Structure for SYNC_WIDTH
**************************************************************************/
typedef struct {
    volatile Uint32 RFBI_VSYNC_WIDTH;
    volatile Uint32 RFBI_HSYNC_WIDTH;
} CSL_DssrfbiSync_widthRegs;


/**************************************************************************
* Register Overlay Structure
**************************************************************************/
typedef struct {
    volatile Uint32 RFBI_REVISION;
    volatile Uint8  RSVD0[12];
    volatile Uint32 RFBI_SYSCONFIG;
    volatile Uint32 RFBI_SYSSTATUS;
    volatile Uint8  RSVD1[40];
    volatile Uint32 RFBI_CONTROL;
    volatile Uint32 RFBI_PIXEL_CNT;
    volatile Uint32 RFBI_LINE_NUMBER;
    volatile Uint32 RFBI_CMD;
    volatile Uint32 RFBI_PARAM;
    volatile Uint32 RFBI_DATA;
    volatile Uint32 RFBI_READ;
    volatile Uint32 RFBI_STATUS;
    CSL_DssrfbiRegsetRegs	REGSET[2];
    CSL_DssrfbiSync_widthRegs	SYNC_WIDTH;
} CSL_DssRfbiRegs;




/**************************************************************************
* Register Macros
**************************************************************************/

/* This register contains the IP revision code */
#define CSL_DSSRFBI_RFBI_REVISION                               (0x0U)

/* This register controls various parameters of the OCP interface. */
#define CSL_DSSRFBI_RFBI_SYSCONFIG                              (0x10U)

/* This register provides status information about the module, excluding the
 * interrupt status information. */
#define CSL_DSSRFBI_RFBI_SYSSTATUS                              (0x14U)

/* The register configures the RFBI module. */
#define CSL_DSSRFBI_RFBI_CONTROL                                (0x40U)

/* The register configures the RFBI pixel count value */
#define CSL_DSSRFBI_RFBI_PIXEL_CNT                              (0x44U)

/* The register configures the number of lines to synchronize the beginning of
 * the transfer. */
#define CSL_DSSRFBI_RFBI_LINE_NUMBER                            (0x48U)

/* The register configures the RFBI command */
#define CSL_DSSRFBI_RFBI_CMD                                    (0x4CU)

/* The register configures the RFBI parameter */
#define CSL_DSSRFBI_RFBI_PARAM                                  (0x50U)

/* The register configures the RFBI data */
#define CSL_DSSRFBI_RFBI_DATA                                   (0x54U)

/* The register configures the RFBI read */
#define CSL_DSSRFBI_RFBI_READ                                   (0x58U)

/* The register configures the RFBI status */
#define CSL_DSSRFBI_RFBI_STATUS                                 (0x5CU)

/* The control register sets the configuration for the LCD#0 and LCD#1 */
#define CSL_DSSRFBI_RFBI_CONFIG(n)                              (0x60U + ((n) * (0x18U)))

/* The control register configures the RFBI timings for the LCD#0 and LCD#1 */
#define CSL_DSSRFBI_RFBI_ONOFF_TIME(n)                          (0x64U + ((n) * (0x18U)))

/* The control register configures the RFBI timings for the LCD#0 and LCD#1 */
#define CSL_DSSRFBI_RFBI_CYCLE_TIME(n)                          (0x68U + ((n) * (0x18U)))

/* The control register configures the RFBI data format for 1st cycle for the
 * LCD#0 and LCD#1 */
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1(n)                         (0x6CU + ((n) * (0x18U)))

/* The control register configures the RFBI data format for 2nd cycle for the
 * LCD#0 and LCD#1 */
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2(n)                         (0x70U + ((n) * (0x18U)))

/* The control register configures the RFBI data format for 3rd cycle for the
 * LCD#0 and LCD#1 */
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3(n)                         (0x74U + ((n) * (0x18U)))

/* The register configures the RFBI VSYNC minimum pulse width */
#define CSL_DSSRFBI_RFBI_VSYNC_WIDTH                            (0x90U)

/* The register configures the RFBI HSYNC minimum pulse width */
#define CSL_DSSRFBI_RFBI_HSYNC_WIDTH                            (0x94U)


/**************************************************************************
* Field Definition Macros
**************************************************************************/

/* RFBI_REVISION */

#define CSL_DSSRFBI_RFBI_REVISION_REV_MASK                      (0x000000FFU)
#define CSL_DSSRFBI_RFBI_REVISION_REV_SHIFT                     (0U)
#define CSL_DSSRFBI_RFBI_REVISION_REV_RESETVAL                  (0x00000010U)
#define CSL_DSSRFBI_RFBI_REVISION_REV_MAX                       (0x000000ffU)

#define CSL_DSSRFBI_RFBI_REVISION_RESETVAL                      (0x00000010U)

/* RFBI_SYSCONFIG */

#define CSL_DSSRFBI_RFBI_SYSCONFIG_AUTOIDLE_MASK                (0x00000001U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_AUTOIDLE_SHIFT               (0U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_AUTOIDLE_RESETVAL            (0x00000001U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_AUTOIDLE_FREERUNNING         (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_AUTOIDLE_GATING              (0x00000001U)

#define CSL_DSSRFBI_RFBI_SYSCONFIG_SIDLEMODE_MASK               (0x00000018U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SIDLEMODE_SHIFT              (3U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SIDLEMODE_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SIDLEMODE_FORCEIDLE          (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SIDLEMODE_NOIDLE             (0x00000001U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SIDLEMODE_SMARTIDLE          (0x00000002U)

#define CSL_DSSRFBI_RFBI_SYSCONFIG_SOFTRESET_MASK               (0x00000002U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SOFTRESET_SHIFT              (1U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SOFTRESET_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SOFTRESET_NORMALMODE         (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSCONFIG_SOFTRESET_RESETDONE          (0x00000001U)

#define CSL_DSSRFBI_RFBI_SYSCONFIG_RESETVAL                     (0x00000001U)

/* RFBI_SYSSTATUS */

#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSY_MASK                    (0x00000100U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSY_SHIFT                   (8U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSY_RESETVAL                (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSY_NOSTALL                 (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSY_STALL                   (0x00000001U)

#define CSL_DSSRFBI_RFBI_SYSSTATUS_RESETDONE_MASK               (0x00000001U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_RESETDONE_SHIFT              (0U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_RESETDONE_RESETVAL           (0x00000001U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_RESETDONE_ONGOING            (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_RESETDONE_COMPLETED          (0x00000001U)

#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSYRFBIDATA_MASK            (0x00000200U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSYRFBIDATA_SHIFT           (9U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSYRFBIDATA_RESETVAL        (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSYRFBIDATA_NOTHINGPENDING  (0x00000000U)
#define CSL_DSSRFBI_RFBI_SYSSTATUS_BUSYRFBIDATA_PENDINGDATA     (0x00000001U)

#define CSL_DSSRFBI_RFBI_SYSSTATUS_RESETVAL                     (0x00000001U)

/* RFBI_CONTROL */

#define CSL_DSSRFBI_RFBI_CONTROL_BYPASSMODE_MASK                (0x00000002U)
#define CSL_DSSRFBI_RFBI_CONTROL_BYPASSMODE_SHIFT               (1U)
#define CSL_DSSRFBI_RFBI_CONTROL_BYPASSMODE_RESETVAL            (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONTROL_BYPASSMODE_NOBYPASS            (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_BYPASSMODE_BYPASS              (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONTROL_ITE_MASK                       (0x00000010U)
#define CSL_DSSRFBI_RFBI_CONTROL_ITE_SHIFT                      (4U)
#define CSL_DSSRFBI_RFBI_CONTROL_ITE_RESETVAL                   (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_ITE_RESET                      (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_ITE_SET                        (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONTROL_ENABLE_MASK                    (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONTROL_ENABLE_SHIFT                   (0U)
#define CSL_DSSRFBI_RFBI_CONTROL_ENABLE_RESETVAL                (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_ENABLE_DISABLE                 (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_ENABLE_ENABLE                  (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONTROL_CONFIGSELECT_MASK              (0x0000000CU)
#define CSL_DSSRFBI_RFBI_CONTROL_CONFIGSELECT_SHIFT             (2U)
#define CSL_DSSRFBI_RFBI_CONTROL_CONFIGSELECT_RESETVAL          (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_CONFIGSELECT_NOCSSELECTED      (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_CONFIGSELECT_CS0ANDCSI1SELECTED  (0x00000003U)
#define CSL_DSSRFBI_RFBI_CONTROL_CONFIGSELECT_CS0SELECTED       (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONTROL_CONFIGSELECT_CS1SELECTED       (0x00000002U)

#define CSL_DSSRFBI_RFBI_CONTROL_HIGHTHRESHOLD_MASK             (0x00000060U)
#define CSL_DSSRFBI_RFBI_CONTROL_HIGHTHRESHOLD_SHIFT            (5U)
#define CSL_DSSRFBI_RFBI_CONTROL_HIGHTHRESHOLD_RESETVAL         (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_HIGHTHRESHOLD_F4X32            (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_HIGHTHRESHOLD_F16X32           (0x00000002U)
#define CSL_DSSRFBI_RFBI_CONTROL_HIGHTHRESHOLD_F8X32            (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONTROL_DISABLE_DMA_REQ_MASK           (0x00000080U)
#define CSL_DSSRFBI_RFBI_CONTROL_DISABLE_DMA_REQ_SHIFT          (7U)
#define CSL_DSSRFBI_RFBI_CONTROL_DISABLE_DMA_REQ_RESETVAL       (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_DISABLE_DMA_REQ_ENABLE         (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_DISABLE_DMA_REQ_DISABLE        (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONTROL_SMART_DMA_REQ_MASK             (0x00000100U)
#define CSL_DSSRFBI_RFBI_CONTROL_SMART_DMA_REQ_SHIFT            (8U)
#define CSL_DSSRFBI_RFBI_CONTROL_SMART_DMA_REQ_RESETVAL         (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_SMART_DMA_REQ_DISABLE          (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONTROL_SMART_DMA_REQ_ENABLE           (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONTROL_RESETVAL                       (0x00000002U)

/* RFBI_PIXEL_CNT */

#define CSL_DSSRFBI_RFBI_PIXEL_CNT_PIXELCNT_MASK                (0xFFFFFFFFU)
#define CSL_DSSRFBI_RFBI_PIXEL_CNT_PIXELCNT_SHIFT               (0U)
#define CSL_DSSRFBI_RFBI_PIXEL_CNT_PIXELCNT_RESETVAL            (0x00000000U)
#define CSL_DSSRFBI_RFBI_PIXEL_CNT_PIXELCNT_MAX                 (0xffffffffU)

#define CSL_DSSRFBI_RFBI_PIXEL_CNT_RESETVAL                     (0x00000000U)

/* RFBI_LINE_NUMBER */

#define CSL_DSSRFBI_RFBI_LINE_NUMBER_LINENUMBER_MASK            (0x000007FFU)
#define CSL_DSSRFBI_RFBI_LINE_NUMBER_LINENUMBER_SHIFT           (0U)
#define CSL_DSSRFBI_RFBI_LINE_NUMBER_LINENUMBER_RESETVAL        (0x00000000U)
#define CSL_DSSRFBI_RFBI_LINE_NUMBER_LINENUMBER_MAX             (0x000007ffU)

#define CSL_DSSRFBI_RFBI_LINE_NUMBER_RESETVAL                   (0x00000000U)

/* RFBI_CMD */

#define CSL_DSSRFBI_RFBI_CMD_CMD_MASK                           (0x0000FFFFU)
#define CSL_DSSRFBI_RFBI_CMD_CMD_SHIFT                          (0U)
#define CSL_DSSRFBI_RFBI_CMD_CMD_RESETVAL                       (0x00000000U)
#define CSL_DSSRFBI_RFBI_CMD_CMD_MAX                            (0x0000ffffU)

#define CSL_DSSRFBI_RFBI_CMD_RESETVAL                           (0x00000000U)

/* RFBI_PARAM */

#define CSL_DSSRFBI_RFBI_PARAM_PARAM_MASK                       (0x0000FFFFU)
#define CSL_DSSRFBI_RFBI_PARAM_PARAM_SHIFT                      (0U)
#define CSL_DSSRFBI_RFBI_PARAM_PARAM_RESETVAL                   (0x00000000U)
#define CSL_DSSRFBI_RFBI_PARAM_PARAM_MAX                        (0x0000ffffU)

#define CSL_DSSRFBI_RFBI_PARAM_RESETVAL                         (0x00000000U)

/* RFBI_DATA */

#define CSL_DSSRFBI_RFBI_DATA_DATA_MASK                         (0xFFFFFFFFU)
#define CSL_DSSRFBI_RFBI_DATA_DATA_SHIFT                        (0U)
#define CSL_DSSRFBI_RFBI_DATA_DATA_RESETVAL                     (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_DATA_MAX                          (0xffffffffU)

#define CSL_DSSRFBI_RFBI_DATA_RESETVAL                          (0x00000000U)

/* RFBI_READ */

#define CSL_DSSRFBI_RFBI_READ_READ_MASK                         (0x0000FFFFU)
#define CSL_DSSRFBI_RFBI_READ_READ_SHIFT                        (0U)
#define CSL_DSSRFBI_RFBI_READ_READ_RESETVAL                     (0x00000000U)
#define CSL_DSSRFBI_RFBI_READ_READ_MAX                          (0x0000ffffU)

#define CSL_DSSRFBI_RFBI_READ_RESETVAL                          (0x00000000U)

/* RFBI_STATUS */

#define CSL_DSSRFBI_RFBI_STATUS_STATUS_MASK                     (0x0000FFFFU)
#define CSL_DSSRFBI_RFBI_STATUS_STATUS_SHIFT                    (0U)
#define CSL_DSSRFBI_RFBI_STATUS_STATUS_RESETVAL                 (0x00000000U)
#define CSL_DSSRFBI_RFBI_STATUS_STATUS_MAX                      (0x0000ffffU)

#define CSL_DSSRFBI_RFBI_STATUS_RESETVAL                        (0x00000000U)

/* RFBI_CONFIG */

#define CSL_DSSRFBI_RFBI_CONFIG_UNUSEDBITS_MASK                 (0x00001800U)
#define CSL_DSSRFBI_RFBI_CONFIG_UNUSEDBITS_SHIFT                (11U)
#define CSL_DSSRFBI_RFBI_CONFIG_UNUSEDBITS_RESETVAL             (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_UNUSEDBITS_LOWLEVEL             (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_UNUSEDBITS_HIGHLEVEL            (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_UNUSEDBITS_UNCHANGED            (0x00000002U)

#define CSL_DSSRFBI_RFBI_CONFIG_REPOLARITY_MASK                 (0x00020000U)
#define CSL_DSSRFBI_RFBI_CONFIG_REPOLARITY_SHIFT                (17U)
#define CSL_DSSRFBI_RFBI_CONFIG_REPOLARITY_RESETVAL             (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_REPOLARITY_ACTIVELOW            (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_REPOLARITY_ACTIVEHIGH           (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONFIG_OCPFORMAT_MASK                  (0x00000180U)
#define CSL_DSSRFBI_RFBI_CONFIG_OCPFORMAT_SHIFT                 (7U)
#define CSL_DSSRFBI_RFBI_CONFIG_OCPFORMAT_RESETVAL              (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_OCPFORMAT__1PIXELPEROCPACCESS   (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_OCPFORMAT__2PIXELSPEROCPACCESS2  (0x00000003U)
#define CSL_DSSRFBI_RFBI_CONFIG_OCPFORMAT__2PIXELSPEROCPACCESS  (0x00000002U)

#define CSL_DSSRFBI_RFBI_CONFIG_CSPOLARITY_MASK                 (0x00080000U)
#define CSL_DSSRFBI_RFBI_CONFIG_CSPOLARITY_SHIFT                (19U)
#define CSL_DSSRFBI_RFBI_CONFIG_CSPOLARITY_RESETVAL             (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_CSPOLARITY_CSACTIVELOW          (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_CSPOLARITY_CSACTIVEHIGH         (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONFIG_A0POLARITY_MASK                 (0x00010000U)
#define CSL_DSSRFBI_RFBI_CONFIG_A0POLARITY_SHIFT                (16U)
#define CSL_DSSRFBI_RFBI_CONFIG_A0POLARITY_RESETVAL             (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_A0POLARITY_A0ACTIVELOW          (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_A0POLARITY_A0ACTIVEHIGH         (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONFIG_TIMEGRANULARITY_MASK            (0x00000010U)
#define CSL_DSSRFBI_RFBI_CONFIG_TIMEGRANULARITY_SHIFT           (4U)
#define CSL_DSSRFBI_RFBI_CONFIG_TIMEGRANULARITY_RESETVAL        (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_TIMEGRANULARITY_ENABLED         (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_TIMEGRANULARITY_DISABLED        (0x00000000U)

#define CSL_DSSRFBI_RFBI_CONFIG_CYCLEFORMAT_MASK                (0x00000600U)
#define CSL_DSSRFBI_RFBI_CONFIG_CYCLEFORMAT_SHIFT               (9U)
#define CSL_DSSRFBI_RFBI_CONFIG_CYCLEFORMAT_RESETVAL            (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_CYCLEFORMAT__1CYCLEFOR1PIXEL    (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_CYCLEFORMAT__3CYCLESFOR1PIXEL   (0x00000002U)
#define CSL_DSSRFBI_RFBI_CONFIG_CYCLEFORMAT__2CYCLESFOR1PIXEL   (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_CYCLEFORMAT__3CYCLESFOR2PIXELS  (0x00000003U)

#define CSL_DSSRFBI_RFBI_CONFIG_TRIGGERMODE_MASK                (0x0000000CU)
#define CSL_DSSRFBI_RFBI_CONFIG_TRIGGERMODE_SHIFT               (2U)
#define CSL_DSSRFBI_RFBI_CONFIG_TRIGGERMODE_RESETVAL            (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_TRIGGERMODE_INTERNAL            (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_TRIGGERMODE_EXTERNAL2           (0x00000002U)
#define CSL_DSSRFBI_RFBI_CONFIG_TRIGGERMODE_EXTERNAL            (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONFIG_DATATYPE_MASK                   (0x00000060U)
#define CSL_DSSRFBI_RFBI_CONFIG_DATATYPE_SHIFT                  (5U)
#define CSL_DSSRFBI_RFBI_CONFIG_DATATYPE_RESETVAL               (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_DATATYPE__12BIT                 (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_DATATYPE__24BIT                 (0x00000003U)
#define CSL_DSSRFBI_RFBI_CONFIG_DATATYPE__18BIT                 (0x00000002U)
#define CSL_DSSRFBI_RFBI_CONFIG_DATATYPE__16BIT                 (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONFIG_PARALLELMODE_MASK               (0x00000003U)
#define CSL_DSSRFBI_RFBI_CONFIG_PARALLELMODE_SHIFT              (0U)
#define CSL_DSSRFBI_RFBI_CONFIG_PARALLELMODE_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_PARALLELMODE__8BITPARALLE       (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_PARALLELMODE__12BITPARALLEL     (0x00000002U)
#define CSL_DSSRFBI_RFBI_CONFIG_PARALLELMODE__9BITPARALLEL      (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_PARALLELMODE__16BITPARALLEL     (0x00000003U)

#define CSL_DSSRFBI_RFBI_CONFIG_HSYNCPOLARITY_MASK              (0x00200000U)
#define CSL_DSSRFBI_RFBI_CONFIG_HSYNCPOLARITY_SHIFT             (21U)
#define CSL_DSSRFBI_RFBI_CONFIG_HSYNCPOLARITY_RESETVAL          (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_HSYNCPOLARITY_HSYNCACTIVELOW    (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_HSYNCPOLARITY_HSYNCACTIVEHIGH   (0x00000001U)

#define CSL_DSSRFBI_RFBI_CONFIG_WEPOLARITY_MASK                 (0x00040000U)
#define CSL_DSSRFBI_RFBI_CONFIG_WEPOLARITY_SHIFT                (18U)
#define CSL_DSSRFBI_RFBI_CONFIG_WEPOLARITY_RESETVAL             (0x00000000U)
#define CSL_DSSRFBI_RFBI_CONFIG_WEPOLARITY_ACTIVEHIGH           (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_WEPOLARITY_ACTIVELOW            (0x00000000U)

#define CSL_DSSRFBI_RFBI_CONFIG_TE_VSYNC_POLARITY_MASK          (0x00100000U)
#define CSL_DSSRFBI_RFBI_CONFIG_TE_VSYNC_POLARITY_SHIFT         (20U)
#define CSL_DSSRFBI_RFBI_CONFIG_TE_VSYNC_POLARITY_RESETVAL      (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_TE_VSYNC_POLARITY_ACTIVEHIGH    (0x00000001U)
#define CSL_DSSRFBI_RFBI_CONFIG_TE_VSYNC_POLARITY_ACTIVELOW     (0x00000000U)

#define CSL_DSSRFBI_RFBI_CONFIG_RESETVAL                        (0x00310000U)

/* RFBI_ONOFF_TIME */

#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSONTIME_MASK               (0x0000000FU)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSONTIME_SHIFT              (0U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSONTIME_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSONTIME_MAX                (0x0000000fU)

#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REONTIME_MASK               (0x00F00000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REONTIME_SHIFT              (20U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REONTIME_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REONTIME_MAX                (0x0000000fU)

#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEOFFTIME_MASK              (0x000FC000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEOFFTIME_SHIFT             (14U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEOFFTIME_RESETVAL          (0x00000000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEOFFTIME_MAX               (0x0000003fU)

#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEONTIME_MASK               (0x00003C00U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEONTIME_SHIFT              (10U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEONTIME_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_WEONTIME_MAX                (0x0000000fU)

#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSOFFTIME_MASK              (0x000003F0U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSOFFTIME_SHIFT             (4U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSOFFTIME_RESETVAL          (0x00000000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_CSOFFTIME_MAX               (0x0000003fU)

#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REOFFTIME_MASK              (0x3F000000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REOFFTIME_SHIFT             (24U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REOFFTIME_RESETVAL          (0x00000000U)
#define CSL_DSSRFBI_RFBI_ONOFF_TIME_REOFFTIME_MAX               (0x0000003fU)

#define CSL_DSSRFBI_RFBI_ONOFF_TIME_RESETVAL                    (0x00000000U)

/* RFBI_CYCLE_TIME */

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WECYCLETIME_MASK            (0x0000003FU)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WECYCLETIME_SHIFT           (0U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WECYCLETIME_RESETVAL        (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WECYCLETIME_MAX             (0x0000003fU)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WRENABLE_MASK               (0x00200000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WRENABLE_SHIFT              (21U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WRENABLE_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WRENABLE_WRDISABLE          (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WRENABLE_WRENABLE           (0x00000001U)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RWENABLE_MASK               (0x00040000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RWENABLE_SHIFT              (18U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RWENABLE_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RWENABLE_MAX                (0x00000001U)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WWENABLE_MASK               (0x00100000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WWENABLE_SHIFT              (20U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WWENABLE_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WWENABLE_WWDISABLE          (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_WWENABLE_WWENABLE           (0x00000001U)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_CSPULSEWIDTH_MASK           (0x0003F000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_CSPULSEWIDTH_SHIFT          (12U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_CSPULSEWIDTH_RESETVAL       (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_CSPULSEWIDTH_MAX            (0x0000003fU)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RECYCLETIME_MASK            (0x00000FC0U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RECYCLETIME_SHIFT           (6U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RECYCLETIME_RESETVAL        (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RECYCLETIME_MAX             (0x0000003fU)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RRENABLE_MASK               (0x00080000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RRENABLE_SHIFT              (19U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RRENABLE_RESETVAL           (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RRENABLE_RRDISABLE          (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RRENABLE_RRENABLE           (0x00000001U)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_ACCESSTIME_MASK             (0x0FC00000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_ACCESSTIME_SHIFT            (22U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_ACCESSTIME_RESETVAL         (0x00000000U)
#define CSL_DSSRFBI_RFBI_CYCLE_TIME_ACCESSTIME_MAX              (0x0000003fU)

#define CSL_DSSRFBI_RFBI_CYCLE_TIME_RESETVAL                    (0x00000000U)

/* RFBI_DATA_CYCLE1 */

#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL1_MASK          (0x0000001FU)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL1_SHIFT         (0U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL1_RESETVAL      (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL1_MAX           (0x0000001fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL2_MASK          (0x001F0000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL2_SHIFT         (16U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL2_RESETVAL      (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_NBBITSPIXEL2_MAX           (0x0000001fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL1_MASK    (0x00000F00U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL1_SHIFT   (8U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL1_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL1_MAX     (0x0000000fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL2_MASK    (0x0F000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL2_SHIFT   (24U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL2_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_BITALIGNMENTPIXEL2_MAX     (0x0000000fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE1_RESETVAL                   (0x00000000U)

/* RFBI_DATA_CYCLE2 */

#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL1_MASK    (0x00000F00U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL1_SHIFT   (8U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL1_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL1_MAX     (0x0000000fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL2_MASK    (0x0F000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL2_SHIFT   (24U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL2_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_BITALIGNMENTPIXEL2_MAX     (0x0000000fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL1_MASK          (0x0000001FU)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL1_SHIFT         (0U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL1_RESETVAL      (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL1_MAX           (0x0000001fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL2_MASK          (0x001F0000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL2_SHIFT         (16U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL2_RESETVAL      (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_NBBITSPIXEL2_MAX           (0x0000001fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE2_RESETVAL                   (0x00000000U)

/* RFBI_DATA_CYCLE3 */

#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL1_MASK    (0x00000F00U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL1_SHIFT   (8U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL1_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL1_MAX     (0x0000000fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL2_MASK    (0x0F000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL2_SHIFT   (24U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL2_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_BITALIGNMENTPIXEL2_MAX     (0x0000000fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL1_MASK          (0x0000001FU)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL1_SHIFT         (0U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL1_RESETVAL      (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL1_MAX           (0x0000001fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL2_MASK          (0x001F0000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL2_SHIFT         (16U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL2_RESETVAL      (0x00000000U)
#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_NBBITSPIXEL2_MAX           (0x0000001fU)

#define CSL_DSSRFBI_RFBI_DATA_CYCLE3_RESETVAL                   (0x00000000U)

/* RFBI_VSYNC_WIDTH */

#define CSL_DSSRFBI_RFBI_VSYNC_WIDTH_MINVSYNCPULSEWIDTH_MASK    (0x0000FFFFU)
#define CSL_DSSRFBI_RFBI_VSYNC_WIDTH_MINVSYNCPULSEWIDTH_SHIFT   (0U)
#define CSL_DSSRFBI_RFBI_VSYNC_WIDTH_MINVSYNCPULSEWIDTH_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_VSYNC_WIDTH_MINVSYNCPULSEWIDTH_MAX     (0x0000ffffU)

#define CSL_DSSRFBI_RFBI_VSYNC_WIDTH_RESETVAL                   (0x00000000U)

/* RFBI_HSYNC_WIDTH */

#define CSL_DSSRFBI_RFBI_HSYNC_WIDTH_MINHSYNCPULSEWIDTH_MASK    (0x0000FFFFU)
#define CSL_DSSRFBI_RFBI_HSYNC_WIDTH_MINHSYNCPULSEWIDTH_SHIFT   (0U)
#define CSL_DSSRFBI_RFBI_HSYNC_WIDTH_MINHSYNCPULSEWIDTH_RESETVAL  (0x00000000U)
#define CSL_DSSRFBI_RFBI_HSYNC_WIDTH_MINHSYNCPULSEWIDTH_MAX     (0x0000ffffU)

#define CSL_DSSRFBI_RFBI_HSYNC_WIDTH_RESETVAL                   (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
