/********************************************************************
 * Copyright (C) 2013-2014 Texas Instruments Incorporated.
 * 
 *  Redistribution and use in source and binary forms, with or without 
 *  modification, are permitted provided that the following conditions 
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the   
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#ifndef CSLR_ICSSM_MII_MDIO_H_
#define CSLR_ICSSM_MII_MDIO_H_

#ifdef __cplusplus
extern "C"
{
#endif
#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>


/**************************************************************************
* Register Overlay Structure for mii_mdioaddressBlockTable
**************************************************************************/
typedef struct {
    volatile Uint32 VER;
    volatile Uint32 CONTROL;
    volatile Uint32 ALIVE;
    volatile Uint32 LINK;
    volatile Uint32 LINKINTRAW;
    volatile Uint32 LINKINTMASKED;
    volatile Uint8  RSVD0[8];
    volatile Uint32 USERINTRAW;
    volatile Uint32 USERINTMASKED;
    volatile Uint32 USERINTMASKSET;
    volatile Uint32 USERINTMASKCLR;
    volatile Uint8  RSVD1[80];
    volatile Uint32 USERACCESS0;
    volatile Uint32 USERPHYSEL0;
    volatile Uint32 USERACCESS1;
    volatile Uint32 USERPHYSEL1;
} CSL_icssm_mii_mdioRegs;


/**************************************************************************
* Register Macros
**************************************************************************/
#define CSL_ICSSM_MII_MDIO_VER                                  (0x0U)
#define CSL_ICSSM_MII_MDIO_CONTROL                              (0x4U)
#define CSL_ICSSM_MII_MDIO_ALIVE                                (0x8U)
#define CSL_ICSSM_MII_MDIO_LINK                                 (0xCU)
#define CSL_ICSSM_MII_MDIO_LINKINTRAW                           (0x10U)
#define CSL_ICSSM_MII_MDIO_LINKINTMASKED                        (0x14U)
#define CSL_ICSSM_MII_MDIO_USERINTRAW                           (0x20U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKED                        (0x24U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKSET                       (0x28U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKCLR                       (0x2CU)
#define CSL_ICSSM_MII_MDIO_USERACCESS0                          (0x80U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0                          (0x84U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1                          (0x88U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1                          (0x8CU)


/**************************************************************************
* Field Definition Macros
**************************************************************************/

/* VER */

#define CSL_ICSSM_MII_MDIO_VER_REVMIN_MASK                      (0x000000FFU)
#define CSL_ICSSM_MII_MDIO_VER_REVMIN_SHIFT                     (0x00000000U)
#define CSL_ICSSM_MII_MDIO_VER_REVMIN_RESETVAL                  (0x00000005U)
#define CSL_ICSSM_MII_MDIO_VER_REVMIN_MAX                       (0x000000ffU)

#define CSL_ICSSM_MII_MDIO_VER_REVMAJ_MASK                      (0x0000FF00U)
#define CSL_ICSSM_MII_MDIO_VER_REVMAJ_SHIFT                     (0x00000008U)
#define CSL_ICSSM_MII_MDIO_VER_REVMAJ_RESETVAL                  (0x00000001U)
#define CSL_ICSSM_MII_MDIO_VER_REVMAJ_MAX                       (0x000000ffU)

#define CSL_ICSSM_MII_MDIO_VER_MODID_MASK                       (0xFFFF0000U)
#define CSL_ICSSM_MII_MDIO_VER_MODID_SHIFT                      (0x00000010U)
#define CSL_ICSSM_MII_MDIO_VER_MODID_RESETVAL                   (0x00000007U)
#define CSL_ICSSM_MII_MDIO_VER_MODID_MAX                        (0x0000ffffU)

#define CSL_ICSSM_MII_MDIO_VER_RESETVAL                         (0x00070105U)

/* CONTROL */

#define CSL_ICSSM_MII_MDIO_CONTROL_CLKDIV_MASK                  (0x0000FFFFU)
#define CSL_ICSSM_MII_MDIO_CONTROL_CLKDIV_SHIFT                 (0x00000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_CLKDIV_RESETVAL              (0x000000ffU)
#define CSL_ICSSM_MII_MDIO_CONTROL_CLKDIV_MAX                   (0x0000ffffU)

#define CSL_ICSSM_MII_MDIO_CONTROL_INT_TEST_ENABLE_MASK         (0x00020000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_INT_TEST_ENABLE_SHIFT        (0x00000011U)
#define CSL_ICSSM_MII_MDIO_CONTROL_INT_TEST_ENABLE_RESETVAL     (0x00000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_INT_TEST_ENABLE_MAX          (0x00000001U)

#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_DETECT_ENABLE_MASK     (0x00040000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_DETECT_ENABLE_SHIFT    (0x00000012U)
#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_DETECT_ENABLE_RESETVAL  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_DETECT_ENABLE_MAX      (0x00000001U)

#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_MASK                   (0x00080000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_SHIFT                  (0x00000013U)
#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_RESETVAL               (0x00000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_FAULT_MAX                    (0x00000001U)

#define CSL_ICSSM_MII_MDIO_CONTROL_PREAMBLE_MASK                (0x00100000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_PREAMBLE_SHIFT               (0x00000014U)
#define CSL_ICSSM_MII_MDIO_CONTROL_PREAMBLE_RESETVAL            (0x00000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_PREAMBLE_MAX                 (0x00000001U)

#define CSL_ICSSM_MII_MDIO_CONTROL_HIGHEST_USER_CHANNEL_MASK    (0x1F000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_HIGHEST_USER_CHANNEL_SHIFT   (0x00000018U)
#define CSL_ICSSM_MII_MDIO_CONTROL_HIGHEST_USER_CHANNEL_RESETVAL  (0x00000001U)
#define CSL_ICSSM_MII_MDIO_CONTROL_HIGHEST_USER_CHANNEL_MAX     (0x0000001fU)

#define CSL_ICSSM_MII_MDIO_CONTROL_ENABLE_MASK                  (0x40000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_ENABLE_SHIFT                 (0x0000001EU)
#define CSL_ICSSM_MII_MDIO_CONTROL_ENABLE_RESETVAL              (0x00000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_ENABLE_MAX                   (0x00000001U)

#define CSL_ICSSM_MII_MDIO_CONTROL_IDLE_MASK                    (0x80000000U)
#define CSL_ICSSM_MII_MDIO_CONTROL_IDLE_SHIFT                   (0x0000001FU)
#define CSL_ICSSM_MII_MDIO_CONTROL_IDLE_RESETVAL                (0x00000001U)
#define CSL_ICSSM_MII_MDIO_CONTROL_IDLE_MAX                     (0x00000001U)

#define CSL_ICSSM_MII_MDIO_CONTROL_RESETVAL                     (0x810000ffU)

/* ALIVE */

#define CSL_ICSSM_MII_MDIO_ALIVE_ALIVE_MASK                     (0xFFFFFFFFU)
#define CSL_ICSSM_MII_MDIO_ALIVE_ALIVE_SHIFT                    (0x00000000U)
#define CSL_ICSSM_MII_MDIO_ALIVE_ALIVE_RESETVAL                 (0x00000000U)
#define CSL_ICSSM_MII_MDIO_ALIVE_ALIVE_MAX                      (0xffffffffU)

#define CSL_ICSSM_MII_MDIO_ALIVE_RESETVAL                       (0x00000000U)

/* LINK */

#define CSL_ICSSM_MII_MDIO_LINK_LINK_MASK                       (0xFFFFFFFFU)
#define CSL_ICSSM_MII_MDIO_LINK_LINK_SHIFT                      (0x00000000U)
#define CSL_ICSSM_MII_MDIO_LINK_LINK_RESETVAL                   (0x00000000U)
#define CSL_ICSSM_MII_MDIO_LINK_LINK_MAX                        (0xffffffffU)

#define CSL_ICSSM_MII_MDIO_LINK_RESETVAL                        (0x00000000U)

/* LINKINTRAW */

#define CSL_ICSSM_MII_MDIO_LINKINTRAW_LINKINTRAW_MASK           (0x00000003U)
#define CSL_ICSSM_MII_MDIO_LINKINTRAW_LINKINTRAW_SHIFT          (0x00000000U)
#define CSL_ICSSM_MII_MDIO_LINKINTRAW_LINKINTRAW_RESETVAL       (0x00000000U)
#define CSL_ICSSM_MII_MDIO_LINKINTRAW_LINKINTRAW_MAX            (0x00000003U)

#define CSL_ICSSM_MII_MDIO_LINKINTRAW_RESETVAL                  (0x00000000U)

/* LINKINTMASKED */

#define CSL_ICSSM_MII_MDIO_LINKINTMASKED_LINKINTMASKED_MASK     (0x00000003U)
#define CSL_ICSSM_MII_MDIO_LINKINTMASKED_LINKINTMASKED_SHIFT    (0x00000000U)
#define CSL_ICSSM_MII_MDIO_LINKINTMASKED_LINKINTMASKED_RESETVAL  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_LINKINTMASKED_LINKINTMASKED_MAX      (0x00000003U)

#define CSL_ICSSM_MII_MDIO_LINKINTMASKED_RESETVAL               (0x00000000U)

/* USERINTRAW */

#define CSL_ICSSM_MII_MDIO_USERINTRAW_USERINTRAW_MASK           (0x00000003U)
#define CSL_ICSSM_MII_MDIO_USERINTRAW_USERINTRAW_SHIFT          (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTRAW_USERINTRAW_RESETVAL       (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTRAW_USERINTRAW_MAX            (0x00000003U)

#define CSL_ICSSM_MII_MDIO_USERINTRAW_RESETVAL                  (0x00000000U)

/* USERINTMASKED */

#define CSL_ICSSM_MII_MDIO_USERINTMASKED_USERINTMASKED_MASK     (0x00000003U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKED_USERINTMASKED_SHIFT    (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKED_USERINTMASKED_RESETVAL  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKED_USERINTMASKED_MAX      (0x00000003U)

#define CSL_ICSSM_MII_MDIO_USERINTMASKED_RESETVAL               (0x00000000U)

/* USERINTMASKSET */

#define CSL_ICSSM_MII_MDIO_USERINTMASKSET_USERINTMASKEDSET_MASK  (0x00000003U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKSET_USERINTMASKEDSET_SHIFT  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKSET_USERINTMASKEDSET_RESETVAL  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKSET_USERINTMASKEDSET_MAX  (0x00000003U)

#define CSL_ICSSM_MII_MDIO_USERINTMASKSET_RESETVAL              (0x00000000U)

/* USERINTMASKCLR */

#define CSL_ICSSM_MII_MDIO_USERINTMASKCLR_USERINTMASKEDCLR_MASK  (0x00000003U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKCLR_USERINTMASKEDCLR_SHIFT  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKCLR_USERINTMASKEDCLR_RESETVAL  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERINTMASKCLR_USERINTMASKEDCLR_MAX  (0x00000003U)

#define CSL_ICSSM_MII_MDIO_USERINTMASKCLR_RESETVAL              (0x00000000U)

/* USERACCESS0 */

#define CSL_ICSSM_MII_MDIO_USERACCESS0_DATA_MASK                (0x0000FFFFU)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_DATA_SHIFT               (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_DATA_RESETVAL            (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_DATA_MAX                 (0x0000ffffU)

#define CSL_ICSSM_MII_MDIO_USERACCESS0_PHYADR_MASK              (0x001F0000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_PHYADR_SHIFT             (0x00000010U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_PHYADR_RESETVAL          (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_PHYADR_MAX               (0x0000001fU)

#define CSL_ICSSM_MII_MDIO_USERACCESS0_REGADR_MASK              (0x03E00000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_REGADR_SHIFT             (0x00000015U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_REGADR_RESETVAL          (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_REGADR_MAX               (0x0000001fU)

#define CSL_ICSSM_MII_MDIO_USERACCESS0_ACK_MASK                 (0x20000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_ACK_SHIFT                (0x0000001DU)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_ACK_RESETVAL             (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_ACK_MAX                  (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERACCESS0_WRITE_MASK               (0x40000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_WRITE_SHIFT              (0x0000001EU)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_WRITE_RESETVAL           (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_WRITE_MAX                (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERACCESS0_GO_MASK                  (0x80000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_GO_SHIFT                 (0x0000001FU)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_GO_RESETVAL              (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS0_GO_MAX                   (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERACCESS0_RESETVAL                 (0x00000000U)

/* USERPHYSEL0 */

#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_PHYADR_MON_MASK          (0x0000001FU)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_PHYADR_MON_SHIFT         (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_PHYADR_MON_RESETVAL      (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_PHYADR_MON_MAX           (0x0000001fU)

#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKINT_ENABLE_MASK      (0x00000040U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKINT_ENABLE_SHIFT     (0x00000006U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKINT_ENABLE_RESETVAL  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKINT_ENABLE_MAX       (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKSEL_MASK             (0x00000080U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKSEL_SHIFT            (0x00000007U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKSEL_RESETVAL         (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_LINKSEL_MAX              (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERPHYSEL0_RESETVAL                 (0x00000000U)

/* USERACCESS1 */

#define CSL_ICSSM_MII_MDIO_USERACCESS1_DATA_MASK                (0x0000FFFFU)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_DATA_SHIFT               (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_DATA_RESETVAL            (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_DATA_MAX                 (0x0000ffffU)

#define CSL_ICSSM_MII_MDIO_USERACCESS1_PHYADR_MASK              (0x001F0000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_PHYADR_SHIFT             (0x00000010U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_PHYADR_RESETVAL          (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_PHYADR_MAX               (0x0000001fU)

#define CSL_ICSSM_MII_MDIO_USERACCESS1_REGADR_MASK              (0x03E00000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_REGADR_SHIFT             (0x00000015U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_REGADR_RESETVAL          (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_REGADR_MAX               (0x0000001fU)

#define CSL_ICSSM_MII_MDIO_USERACCESS1_ACK_MASK                 (0x20000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_ACK_SHIFT                (0x0000001DU)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_ACK_RESETVAL             (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_ACK_MAX                  (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERACCESS1_WRITE_MASK               (0x40000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_WRITE_SHIFT              (0x0000001EU)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_WRITE_RESETVAL           (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_WRITE_MAX                (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERACCESS1_GO_MASK                  (0x80000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_GO_SHIFT                 (0x0000001FU)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_GO_RESETVAL              (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERACCESS1_GO_MAX                   (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERACCESS1_RESETVAL                 (0x00000000U)

/* USERPHYSEL1 */

#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_PHYADR_MON_MASK          (0x0000001FU)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_PHYADR_MON_SHIFT         (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_PHYADR_MON_RESETVAL      (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_PHYADR_MON_MAX           (0x0000001fU)

#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKINT_ENABLE_MASK      (0x00000040U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKINT_ENABLE_SHIFT     (0x00000006U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKINT_ENABLE_RESETVAL  (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKINT_ENABLE_MAX       (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKSEL_MASK             (0x00000080U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKSEL_SHIFT            (0x00000007U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKSEL_RESETVAL         (0x00000000U)
#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_LINKSEL_MAX              (0x00000001U)

#define CSL_ICSSM_MII_MDIO_USERPHYSEL1_RESETVAL                 (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
