/**
 * Note: This file was auto-generated by TI PinMux on 2/23/2015 at 12:30:42 PM.
 *
 * \file  am335x_icev1_pinmux_data.c
 *
 * \brief  This file contains the pin mux configurations for the boards.
 *         These are prepared based on how the peripherals are extended on
 *         the boards.
 *
 * \copyright Copyright (CU) 2015 Texas Instruments Incorporated -
 *             http://www.ti.com/
 */

/**
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "types.h"
#include "pinmux.h"
#include "am335x_pinmux.h"

/** Peripheral Pin Configurations */

#if defined(BUILDCFG_MOD_UART)

static pinmuxPerCfg_t gUart0PinCfg[] =
{
    {
        /* UART 0 -> uart0_rxd -> E15 */
        PIN_UART0_RXD, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* UART 0 -> uart0_txd -> E16 */
        PIN_UART0_TXD, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL) & (~PIN_PULL_UD_EN & ~PIN_RX_ACTIVE)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gUart1PinCfg[] =
{
    {
        /* UART1 -> uart1_rxd -> D16 */
        PIN_UART1_RXD, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* UART1 -> uart1_txd -> D15 */
        PIN_UART1_TXD, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL) & (~PIN_PULL_UD_EN & ~PIN_RX_ACTIVE)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gUart3PinCfg[] =
{
    {
        /* UART3 -> uart3_rxd -> G15 */
        PIN_MMC0_DAT1, 0, \
        ( \
            PIN_MODE(3) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* UART3 -> uart3_txd -> C18 */
        PIN_ECAP0_IN_PWM0_OUT, 0, \
        ( \
            PIN_MODE(1) | \
            ((PIN_PULL_TYPE_SEL) & (~PIN_PULL_UD_EN & ~PIN_RX_ACTIVE)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gUart4PinCfg[] =
{
    {
        /* UART 4 -> uart4_rxd -> E18 */
        PIN_UART0_CTSN, 0, \
        ( \
            PIN_MODE(1) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* UART 4 -> uart4_txd -> E17 */
        PIN_UART0_RTSN, 0, \
        ( \
            PIN_MODE(1) | \
            ((PIN_PULL_TYPE_SEL) & (~PIN_PULL_UD_EN & ~PIN_RX_ACTIVE)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gUart5PinCfg[] =
{
    {
        /* UART5 -> uart5_rxd -> H16 */
        PIN_GMII1_COL, 0, \
        ( \
            PIN_MODE(3) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* UART5 -> uart5_txd -> J17 */
        PIN_GMII1_RXDV, 0, \
        ( \
            PIN_MODE(3) | \
            ((PIN_PULL_TYPE_SEL) & (~PIN_PULL_UD_EN & ~PIN_RX_ACTIVE)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gUartPinCfg[] =
{
    {0, TRUE, gUart0PinCfg},
    {1, TRUE, gUart1PinCfg},
    {3, TRUE, gUart3PinCfg},
    {4, TRUE, gUart4PinCfg},
    {5, TRUE, gUart5PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_UART) */

#if defined(BUILDCFG_MOD_GPIO)

static pinmuxPerCfg_t gGpio0PinCfg[] =
{
    {
        /* GPIO0 -> gpio0[17] -> K15 */
        PIN_GMII1_TXD2, 17, \
        ( \
            PIN_MODE(7) | \
            ((PIN_PULL_UD_EN) & (~PIN_PULL_TYPE_SEL & ~PIN_RX_ACTIVE)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gGpioPinCfg[] =
{
    {0, TRUE, gGpio0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_GPIO) */

#if defined(BUILDCFG_MOD_I2C)

static pinmuxPerCfg_t gI2c0PinCfg[] =
{
    {
        /* I2C 0 -> I2C0_SCL -> C16 */
        PIN_I2C0_SCL, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_UD_EN | PIN_RX_ACTIVE) & (~PIN_PULL_TYPE_SEL)) \
        ) \
    },
    {
        /* I2C 0 -> I2C0_SDA -> C17 */
        PIN_I2C0_SDA, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_UD_EN | PIN_RX_ACTIVE) & (~PIN_PULL_TYPE_SEL)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gI2cPinCfg[] =
{
    {0, TRUE, gI2c0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_I2C) */

#if defined(BUILDCFG_MOD_MCSPI)

static pinmuxPerCfg_t gMcspi0PinCfg[] =
{
    {
        /* SPI0 -> spi0_sclk -> A17 */
        PIN_SPI0_SCLK, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* SPI0 -> spi0_d0 -> B17 */
        PIN_SPI0_D0, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* SPI0 -> spi0_d1 -> B16 */
        PIN_SPI0_D1, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* SPI0 -> spi0_cs0 -> A16 */
        PIN_SPI0_CS0, 0, \
        ( \
            PIN_MODE(0) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gMcspiPinCfg[] =
{
    {0, TRUE, gMcspi0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_SPI) */

#if defined(BUILDCFG_MOD_MMCSD)

static pinmuxPerCfg_t gMmcsd1PinCfg[] =
{
    {
        /* MMC1 -> mmc1_clk -> U9 */
        PIN_GPMC_CSN1, 0, \
        ( \
            PIN_MODE(2) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* MMC1 -> mmc1_cmd -> V9 */
        PIN_GPMC_CSN2, 0, \
        ( \
            PIN_MODE(2) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* MMC1 -> mmc1_dat0 -> U7 */
        PIN_GPMC_AD0, 0, \
        ( \
            PIN_MODE(1) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* MMC1 -> mmc1_dat1 -> V7 */
        PIN_GPMC_AD1, 0, \
        ( \
            PIN_MODE(1) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* MMC1 -> mmc1_dat2 -> R8 */
        PIN_GPMC_AD2, 0, \
        ( \
            PIN_MODE(1) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* MMC1 -> mmc1_dat3 -> T8 */
        PIN_GPMC_AD3, 0, \
        ( \
            PIN_MODE(1) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {
        /* MMC1 -> mmc1_sdcd -> B13 */
        PIN_MCASP0_FSX, 0, \
        ( \
            PIN_MODE(4) | \
            ((PIN_PULL_TYPE_SEL | PIN_RX_ACTIVE) & (~PIN_PULL_UD_EN)) \
        ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gMmcsdPinCfg[] =
{
    {1, TRUE, gMmcsd1PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_MMCSD) */

/** EVM pin configurations for EVM */

pinmuxBoardCfg_t gIceV1PinmuxData[] =
{
#if defined(BUILDCFG_MOD_UART)
    {CHIPDB_MOD_ID_UART, gUartPinCfg},
#endif /* if defined(BUILDCFG_MOD_UART) */
#if defined(BUILDCFG_MOD_GPIO)
    {CHIPDB_MOD_ID_GPIO, gGpioPinCfg},
#endif /* if defined(BUILDCFG_MOD_GPIO) */
#if defined(BUILDCFG_MOD_I2C)
    {CHIPDB_MOD_ID_I2C, gI2cPinCfg},
#endif /* if defined(BUILDCFG_MOD_I2C) */
#if defined(BUILDCFG_MOD_MCSPI)
    {CHIPDB_MOD_ID_MCSPI, gMcspiPinCfg},
#endif /* if defined(BUILDCFG_MOD_SPI) */
#if defined(BUILDCFG_MOD_MMCSD)
    {CHIPDB_MOD_ID_MMCSD, gMmcsdPinCfg},
#endif /* if defined(BUILDCFG_MOD_MMCSD) */
    {CHIPDB_MOD_ID_INVALID}
};
