/********************************************************************
*
* SOC ISC PROPERTIES. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_SOC_ISC_H_
#define CSLR_SOC_ISC_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* Auto-generated CSL definitions for SoC ISC Instances:
*/

#define CSL_ISC_DEFAULT                                                                            (0U)
#define CSL_ISC_CC                                                                                 (1U)

/* Properties of firewall at master: WKUP_DMSC0 */
#define CSL_ISC_WKUP_DMSC0_QUASAR_I_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_WKUP_DMSC0_QUASAR_I_ID                                                             (32U)
#define CSL_ISC_WKUP_DMSC0_QUASAR_I_DEFAULT_PRIV_ID                                                (202U)
#define CSL_ISC_WKUP_DMSC0_QUASAR_I_MMR_BASE                                                       (0x45808000UL)
#define CSL_ISC_WKUP_DMSC0_QUASAR_I_REGION_COUNT                                                   (1U)
#define CSL_ISC_WKUP_DMSC0_QUASAR_D_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_WKUP_DMSC0_QUASAR_D_ID                                                             (33U)
#define CSL_ISC_WKUP_DMSC0_QUASAR_D_DEFAULT_PRIV_ID                                                (202U)
#define CSL_ISC_WKUP_DMSC0_QUASAR_D_MMR_BASE                                                       (0x45808400UL)
#define CSL_ISC_WKUP_DMSC0_QUASAR_D_REGION_COUNT                                                   (1U)
#define CSL_ISC_WKUP_DMSC0_IQUASAR_S_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_WKUP_DMSC0_IQUASAR_S_ID                                                            (34U)
#define CSL_ISC_WKUP_DMSC0_IQUASAR_S_DEFAULT_PRIV_ID                                               (202U)
#define CSL_ISC_WKUP_DMSC0_IQUASAR_S_MMR_BASE                                                      (0x45808800UL)
#define CSL_ISC_WKUP_DMSC0_IQUASAR_S_REGION_COUNT                                                  (1U)

/* Properties of firewall at master: MCU_R5FSS0 */
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST0_TYPE                                                       (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST0_ID                                                         (64U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST0_DEFAULT_PRIV_ID                                            (96U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST0_MMR_BASE                                                   (0x45810000UL)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST0_REGION_COUNT                                               (4U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST0_TYPE                                                       (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST0_ID                                                         (65U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST0_DEFAULT_PRIV_ID                                            (96U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST0_MMR_BASE                                                   (0x45810400UL)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST0_REGION_COUNT                                               (4U)
#define CSL_ISC_MCU_R5FSS0_CPU0_PMST_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_R5FSS0_CPU0_PMST_ID                                                            (66U)
#define CSL_ISC_MCU_R5FSS0_CPU0_PMST_DEFAULT_PRIV_ID                                               (96U)
#define CSL_ISC_MCU_R5FSS0_CPU0_PMST_MMR_BASE                                                      (0x45810800UL)
#define CSL_ISC_MCU_R5FSS0_CPU0_PMST_REGION_COUNT                                                  (4U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST1_TYPE                                                       (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST1_ID                                                         (68U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST1_DEFAULT_PRIV_ID                                            (97U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST1_MMR_BASE                                                   (0x45811000UL)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_RMST1_REGION_COUNT                                               (4U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST1_TYPE                                                       (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST1_ID                                                         (69U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST1_DEFAULT_PRIV_ID                                            (97U)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST1_MMR_BASE                                                   (0x45811400UL)
#define CSL_ISC_MCU_R5FSS0_MEMBDG_WMST1_REGION_COUNT                                               (4U)
#define CSL_ISC_MCU_R5FSS0_CPU1_PMST_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_R5FSS0_CPU1_PMST_ID                                                            (70U)
#define CSL_ISC_MCU_R5FSS0_CPU1_PMST_DEFAULT_PRIV_ID                                               (97U)
#define CSL_ISC_MCU_R5FSS0_CPU1_PMST_MMR_BASE                                                      (0x45811800UL)
#define CSL_ISC_MCU_R5FSS0_CPU1_PMST_REGION_COUNT                                                  (4U)

/* Properties of firewall at master: MCU_SA2_UL0 */
#define CSL_ISC_MCU_SA2_UL0_CTXCACH_EXT_DMA_TYPE                                                   (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_SA2_UL0_CTXCACH_EXT_DMA_ID                                                     (76U)
#define CSL_ISC_MCU_SA2_UL0_CTXCACH_EXT_DMA_DEFAULT_PRIV_ID                                        (152U)
#define CSL_ISC_MCU_SA2_UL0_CTXCACH_EXT_DMA_MMR_BASE                                               (0x45813000UL)
#define CSL_ISC_MCU_SA2_UL0_CTXCACH_EXT_DMA_REGION_COUNT                                           (4U)

/* Properties of firewall at master: MCU_NAVSS0 */
#define CSL_ISC_MCU_NAVSS0_PROXY0_DST_TYPE                                                         (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_NAVSS0_PROXY0_DST_ID                                                           (96U)
#define CSL_ISC_MCU_NAVSS0_PROXY0_DST_DEFAULT_PRIV_ID                                              (80U)
#define CSL_ISC_MCU_NAVSS0_PROXY0_DST_MMR_BASE                                                     (0x45818000UL)
#define CSL_ISC_MCU_NAVSS0_PROXY0_DST_REGION_COUNT                                                 (1U)
#define CSL_ISC_MCU_NAVSS0_SEC_PROXY0_DST_TYPE                                                     (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_NAVSS0_SEC_PROXY0_DST_ID                                                       (97U)
#define CSL_ISC_MCU_NAVSS0_SEC_PROXY0_DST_DEFAULT_PRIV_ID                                          (81U)
#define CSL_ISC_MCU_NAVSS0_SEC_PROXY0_DST_MMR_BASE                                                 (0x45818400UL)
#define CSL_ISC_MCU_NAVSS0_SEC_PROXY0_DST_REGION_COUNT                                             (1U)
#define CSL_ISC_MCU_NAVSS0_RINGACC0_DST_TYPE                                                       (CSL_ISC_DEFAULT)
#define CSL_ISC_MCU_NAVSS0_RINGACC0_DST_ID                                                         (98U)
#define CSL_ISC_MCU_NAVSS0_RINGACC0_DST_DEFAULT_PRIV_ID                                            (82U)
#define CSL_ISC_MCU_NAVSS0_RINGACC0_DST_MMR_BASE                                                   (0x45818800UL)
#define CSL_ISC_MCU_NAVSS0_RINGACC0_DST_REGION_COUNT                                               (1U)
#define CSL_ISC_MCU_NAVSS0_RING_TYPE                                                               (CSL_ISC_CC)
#define CSL_ISC_MCU_NAVSS0_RING_ID                                                                 (128U)
#define CSL_ISC_MCU_NAVSS0_RING_DEFAULT_PRIV_ID                                                    (0U)
#define CSL_ISC_MCU_NAVSS0_RING_MMR_BASE                                                           (0x45820000UL)
#define CSL_ISC_MCU_NAVSS0_RING_REGION_COUNT                                                       (286U)

/* Properties of firewall at master: A72SS0_CORE0 */
#define CSL_ISC_A72SS0_CORE0_CPU_0_CPU_0_MSMC_TYPE                                                 (CSL_ISC_CC)
#define CSL_ISC_A72SS0_CORE0_CPU_0_CPU_0_MSMC_ID                                                   (192U)
#define CSL_ISC_A72SS0_CORE0_CPU_0_CPU_0_MSMC_DEFAULT_PRIV_ID                                      (0U)
#define CSL_ISC_A72SS0_CORE0_CPU_0_CPU_0_MSMC_MMR_BASE                                             (0x45830000UL)
#define CSL_ISC_A72SS0_CORE0_CPU_0_CPU_0_MSMC_REGION_COUNT                                         (5U)

/* Properties of firewall at master: C71SS0 */
#define CSL_ISC_C71SS0_CPU_0_CPU_1_MSMC_TYPE                                                       (CSL_ISC_CC)
#define CSL_ISC_C71SS0_CPU_0_CPU_1_MSMC_ID                                                         (193U)
#define CSL_ISC_C71SS0_CPU_0_CPU_1_MSMC_DEFAULT_PRIV_ID                                            (16U)
#define CSL_ISC_C71SS0_CPU_0_CPU_1_MSMC_MMR_BASE                                                   (0x45830400UL)
#define CSL_ISC_C71SS0_CPU_0_CPU_1_MSMC_REGION_COUNT                                               (5U)

/* Properties of firewall at master: NAVSS0 */
#define CSL_ISC_NAVSS0_PROXY0_DST_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_NAVSS0_PROXY0_DST_ID                                                               (256U)
#define CSL_ISC_NAVSS0_PROXY0_DST_DEFAULT_PRIV_ID                                                  (64U)
#define CSL_ISC_NAVSS0_PROXY0_DST_MMR_BASE                                                         (0x45840000UL)
#define CSL_ISC_NAVSS0_PROXY0_DST_REGION_COUNT                                                     (1U)
#define CSL_ISC_NAVSS0_SEC_PROXY0_DST_TYPE                                                         (CSL_ISC_DEFAULT)
#define CSL_ISC_NAVSS0_SEC_PROXY0_DST_ID                                                           (257U)
#define CSL_ISC_NAVSS0_SEC_PROXY0_DST_DEFAULT_PRIV_ID                                              (65U)
#define CSL_ISC_NAVSS0_SEC_PROXY0_DST_MMR_BASE                                                     (0x45840400UL)
#define CSL_ISC_NAVSS0_SEC_PROXY0_DST_REGION_COUNT                                                 (1U)
#define CSL_ISC_NAVSS0_TCU_MSTR_TYPE                                                               (CSL_ISC_DEFAULT)
#define CSL_ISC_NAVSS0_TCU_MSTR_ID                                                                 (320U)
#define CSL_ISC_NAVSS0_TCU_MSTR_DEFAULT_PRIV_ID                                                    (255U)
#define CSL_ISC_NAVSS0_TCU_MSTR_MMR_BASE                                                           (0x45850000UL)
#define CSL_ISC_NAVSS0_TCU_MSTR_REGION_COUNT                                                       (1U)
#define CSL_ISC_NAVSS0_TCU_MSTW_TYPE                                                               (CSL_ISC_DEFAULT)
#define CSL_ISC_NAVSS0_TCU_MSTW_ID                                                                 (321U)
#define CSL_ISC_NAVSS0_TCU_MSTW_DEFAULT_PRIV_ID                                                    (255U)
#define CSL_ISC_NAVSS0_TCU_MSTW_MMR_BASE                                                           (0x45850400UL)
#define CSL_ISC_NAVSS0_TCU_MSTW_REGION_COUNT                                                       (1U)
#define CSL_ISC_NAVSS0_RING_TYPE                                                                   (CSL_ISC_CC)
#define CSL_ISC_NAVSS0_RING_ID                                                                     (448U)
#define CSL_ISC_NAVSS0_RING_DEFAULT_PRIV_ID                                                        (0U)
#define CSL_ISC_NAVSS0_RING_MMR_BASE                                                               (0x45870000UL)
#define CSL_ISC_NAVSS0_RING_REGION_COUNT                                                           (1024U)
#define CSL_ISC_NAVSS0_RINGACC0_DST_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_NAVSS0_RINGACC0_DST_ID                                                             (480U)
#define CSL_ISC_NAVSS0_RINGACC0_DST_DEFAULT_PRIV_ID                                                (74U)
#define CSL_ISC_NAVSS0_RINGACC0_DST_MMR_BASE                                                       (0x45878000UL)
#define CSL_ISC_NAVSS0_RINGACC0_DST_REGION_COUNT                                                   (1U)

/* Properties of firewall at master: DMPAC0 */
#define CSL_ISC_DMPAC0_SDE_MST_TYPE                                                                (CSL_ISC_DEFAULT)
#define CSL_ISC_DMPAC0_SDE_MST_ID                                                                  (356U)
#define CSL_ISC_DMPAC0_SDE_MST_DEFAULT_PRIV_ID                                                     (208U)
#define CSL_ISC_DMPAC0_SDE_MST_MMR_BASE                                                            (0x45859000UL)
#define CSL_ISC_DMPAC0_SDE_MST_REGION_COUNT                                                        (1U)
#define CSL_ISC_DMPAC0_DOF_RD_MST_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_DMPAC0_DOF_RD_MST_ID                                                               (357U)
#define CSL_ISC_DMPAC0_DOF_RD_MST_DEFAULT_PRIV_ID                                                  (209U)
#define CSL_ISC_DMPAC0_DOF_RD_MST_MMR_BASE                                                         (0x45859400UL)
#define CSL_ISC_DMPAC0_DOF_RD_MST_REGION_COUNT                                                     (1U)
#define CSL_ISC_DMPAC0_DOF_MST_TYPE                                                                (CSL_ISC_DEFAULT)
#define CSL_ISC_DMPAC0_DOF_MST_ID                                                                  (358U)
#define CSL_ISC_DMPAC0_DOF_MST_DEFAULT_PRIV_ID                                                     (210U)
#define CSL_ISC_DMPAC0_DOF_MST_MMR_BASE                                                            (0x45859800UL)
#define CSL_ISC_DMPAC0_DOF_MST_REGION_COUNT                                                        (1U)
#define CSL_ISC_DMPAC0_FOCO_0_MST_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_DMPAC0_FOCO_0_MST_ID                                                               (359U)
#define CSL_ISC_DMPAC0_FOCO_0_MST_DEFAULT_PRIV_ID                                                  (211U)
#define CSL_ISC_DMPAC0_FOCO_0_MST_MMR_BASE                                                         (0x45859c00UL)
#define CSL_ISC_DMPAC0_FOCO_0_MST_REGION_COUNT                                                     (1U)
#define CSL_ISC_DMPAC0_FOCO_1_MST_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_DMPAC0_FOCO_1_MST_ID                                                               (360U)
#define CSL_ISC_DMPAC0_FOCO_1_MST_DEFAULT_PRIV_ID                                                  (212U)
#define CSL_ISC_DMPAC0_FOCO_1_MST_MMR_BASE                                                         (0x4585a000UL)
#define CSL_ISC_DMPAC0_FOCO_1_MST_REGION_COUNT                                                     (1U)

/* Properties of firewall at master: VPAC0 */
#define CSL_ISC_VPAC0_VISS0_MST_TYPE                                                               (CSL_ISC_DEFAULT)
#define CSL_ISC_VPAC0_VISS0_MST_ID                                                                 (384U)
#define CSL_ISC_VPAC0_VISS0_MST_DEFAULT_PRIV_ID                                                    (213U)
#define CSL_ISC_VPAC0_VISS0_MST_MMR_BASE                                                           (0x45860000UL)
#define CSL_ISC_VPAC0_VISS0_MST_REGION_COUNT                                                       (2U)
#define CSL_ISC_VPAC0_LDC0_MST_TYPE                                                                (CSL_ISC_DEFAULT)
#define CSL_ISC_VPAC0_LDC0_MST_ID                                                                  (386U)
#define CSL_ISC_VPAC0_LDC0_MST_DEFAULT_PRIV_ID                                                     (215U)
#define CSL_ISC_VPAC0_LDC0_MST_MMR_BASE                                                            (0x45860800UL)
#define CSL_ISC_VPAC0_LDC0_MST_REGION_COUNT                                                        (2U)
#define CSL_ISC_VPAC0_MSC_MST_TYPE                                                                 (CSL_ISC_DEFAULT)
#define CSL_ISC_VPAC0_MSC_MST_ID                                                                   (388U)
#define CSL_ISC_VPAC0_MSC_MST_DEFAULT_PRIV_ID                                                      (217U)
#define CSL_ISC_VPAC0_MSC_MST_MMR_BASE                                                             (0x45861000UL)
#define CSL_ISC_VPAC0_MSC_MST_REGION_COUNT                                                         (4U)
#define CSL_ISC_VPAC0_NF_MST_TYPE                                                                  (CSL_ISC_DEFAULT)
#define CSL_ISC_VPAC0_NF_MST_ID                                                                    (389U)
#define CSL_ISC_VPAC0_NF_MST_DEFAULT_PRIV_ID                                                       (218U)
#define CSL_ISC_VPAC0_NF_MST_MMR_BASE                                                              (0x45861400UL)
#define CSL_ISC_VPAC0_NF_MST_REGION_COUNT                                                          (2U)
#define CSL_ISC_VPAC0_LDC0_M_MST_TYPE                                                              (CSL_ISC_DEFAULT)
#define CSL_ISC_VPAC0_LDC0_M_MST_ID                                                                (775U)
#define CSL_ISC_VPAC0_LDC0_M_MST_DEFAULT_PRIV_ID                                                   (220U)
#define CSL_ISC_VPAC0_LDC0_M_MST_MMR_BASE                                                          (0x458c1c00UL)
#define CSL_ISC_VPAC0_LDC0_M_MST_REGION_COUNT                                                      (3U)

/* Properties of firewall at master: PRU_ICSSG0 */
#define CSL_ISC_PRU_ICSSG0_PR1_EXT_VBUSM_TYPE                                                      (CSL_ISC_DEFAULT)
#define CSL_ISC_PRU_ICSSG0_PR1_EXT_VBUSM_ID                                                        (512U)
#define CSL_ISC_PRU_ICSSG0_PR1_EXT_VBUSM_DEFAULT_PRIV_ID                                           (136U)
#define CSL_ISC_PRU_ICSSG0_PR1_EXT_VBUSM_MMR_BASE                                                  (0x45880000UL)
#define CSL_ISC_PRU_ICSSG0_PR1_EXT_VBUSM_REGION_COUNT                                              (10U)

/* Properties of firewall at master: PRU_ICSSG1 */
#define CSL_ISC_PRU_ICSSG1_PR1_EXT_VBUSM_TYPE                                                      (CSL_ISC_DEFAULT)
#define CSL_ISC_PRU_ICSSG1_PR1_EXT_VBUSM_ID                                                        (513U)
#define CSL_ISC_PRU_ICSSG1_PR1_EXT_VBUSM_DEFAULT_PRIV_ID                                           (136U)
#define CSL_ISC_PRU_ICSSG1_PR1_EXT_VBUSM_MMR_BASE                                                  (0x45880400UL)
#define CSL_ISC_PRU_ICSSG1_PR1_EXT_VBUSM_REGION_COUNT                                              (10U)

/* Properties of firewall at master: C66SS0 */
#define CSL_ISC_C66SS0_C66_MDMA_TYPE                                                               (CSL_ISC_DEFAULT)
#define CSL_ISC_C66SS0_C66_MDMA_ID                                                                 (516U)
#define CSL_ISC_C66SS0_C66_MDMA_DEFAULT_PRIV_ID                                                    (220U)
#define CSL_ISC_C66SS0_C66_MDMA_MMR_BASE                                                           (0x45881000UL)
#define CSL_ISC_C66SS0_C66_MDMA_REGION_COUNT                                                       (4U)
#define CSL_ISC_C66SS0_C66_CFG_TYPE                                                                (CSL_ISC_DEFAULT)
#define CSL_ISC_C66SS0_C66_CFG_ID                                                                  (540U)
#define CSL_ISC_C66SS0_C66_CFG_DEFAULT_PRIV_ID                                                     (220U)
#define CSL_ISC_C66SS0_C66_CFG_MMR_BASE                                                            (0x45887000UL)
#define CSL_ISC_C66SS0_C66_CFG_REGION_COUNT                                                        (4U)

/* Properties of firewall at master: C66SS1 */
#define CSL_ISC_C66SS1_C66_MDMA_TYPE                                                               (CSL_ISC_DEFAULT)
#define CSL_ISC_C66SS1_C66_MDMA_ID                                                                 (517U)
#define CSL_ISC_C66SS1_C66_MDMA_DEFAULT_PRIV_ID                                                    (221U)
#define CSL_ISC_C66SS1_C66_MDMA_MMR_BASE                                                           (0x45881400UL)
#define CSL_ISC_C66SS1_C66_MDMA_REGION_COUNT                                                       (4U)
#define CSL_ISC_C66SS1_C66_CFG_TYPE                                                                (CSL_ISC_DEFAULT)
#define CSL_ISC_C66SS1_C66_CFG_ID                                                                  (541U)
#define CSL_ISC_C66SS1_C66_CFG_DEFAULT_PRIV_ID                                                     (221U)
#define CSL_ISC_C66SS1_C66_CFG_MMR_BASE                                                            (0x45887400UL)
#define CSL_ISC_C66SS1_C66_CFG_REGION_COUNT                                                        (4U)

/* Properties of firewall at master: MMCSD1 */
#define CSL_ISC_MMCSD1_EMMCSDSS_RD_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_MMCSD1_EMMCSDSS_RD_ID                                                              (520U)
#define CSL_ISC_MMCSD1_EMMCSDSS_RD_DEFAULT_PRIV_ID                                                 (129U)
#define CSL_ISC_MMCSD1_EMMCSDSS_RD_MMR_BASE                                                        (0x45882000UL)
#define CSL_ISC_MMCSD1_EMMCSDSS_RD_REGION_COUNT                                                    (1U)
#define CSL_ISC_MMCSD1_EMMCSDSS_WR_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_MMCSD1_EMMCSDSS_WR_ID                                                              (521U)
#define CSL_ISC_MMCSD1_EMMCSDSS_WR_DEFAULT_PRIV_ID                                                 (129U)
#define CSL_ISC_MMCSD1_EMMCSDSS_WR_MMR_BASE                                                        (0x45882400UL)
#define CSL_ISC_MMCSD1_EMMCSDSS_WR_REGION_COUNT                                                    (1U)

/* Properties of firewall at master: MMCSD2 */
#define CSL_ISC_MMCSD2_EMMCSDSS_RD_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_MMCSD2_EMMCSDSS_RD_ID                                                              (522U)
#define CSL_ISC_MMCSD2_EMMCSDSS_RD_DEFAULT_PRIV_ID                                                 (129U)
#define CSL_ISC_MMCSD2_EMMCSDSS_RD_MMR_BASE                                                        (0x45882800UL)
#define CSL_ISC_MMCSD2_EMMCSDSS_RD_REGION_COUNT                                                    (1U)
#define CSL_ISC_MMCSD2_EMMCSDSS_WR_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_MMCSD2_EMMCSDSS_WR_ID                                                              (523U)
#define CSL_ISC_MMCSD2_EMMCSDSS_WR_DEFAULT_PRIV_ID                                                 (129U)
#define CSL_ISC_MMCSD2_EMMCSDSS_WR_MMR_BASE                                                        (0x45882c00UL)
#define CSL_ISC_MMCSD2_EMMCSDSS_WR_REGION_COUNT                                                    (1U)

/* Properties of firewall at master: R5FSS0 */
#define CSL_ISC_R5FSS0_MEMBDG_RMST0_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_MEMBDG_RMST0_ID                                                             (528U)
#define CSL_ISC_R5FSS0_MEMBDG_RMST0_DEFAULT_PRIV_ID                                                (212U)
#define CSL_ISC_R5FSS0_MEMBDG_RMST0_MMR_BASE                                                       (0x45884000UL)
#define CSL_ISC_R5FSS0_MEMBDG_RMST0_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS0_MEMBDG_RMST1_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_MEMBDG_RMST1_ID                                                             (529U)
#define CSL_ISC_R5FSS0_MEMBDG_RMST1_DEFAULT_PRIV_ID                                                (213U)
#define CSL_ISC_R5FSS0_MEMBDG_RMST1_MMR_BASE                                                       (0x45884400UL)
#define CSL_ISC_R5FSS0_MEMBDG_RMST1_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS0_MEMBDG_WMST0_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_MEMBDG_WMST0_ID                                                             (530U)
#define CSL_ISC_R5FSS0_MEMBDG_WMST0_DEFAULT_PRIV_ID                                                (212U)
#define CSL_ISC_R5FSS0_MEMBDG_WMST0_MMR_BASE                                                       (0x45884800UL)
#define CSL_ISC_R5FSS0_MEMBDG_WMST0_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS0_MEMBDG_WMST1_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_MEMBDG_WMST1_ID                                                             (531U)
#define CSL_ISC_R5FSS0_MEMBDG_WMST1_DEFAULT_PRIV_ID                                                (213U)
#define CSL_ISC_R5FSS0_MEMBDG_WMST1_MMR_BASE                                                       (0x45884c00UL)
#define CSL_ISC_R5FSS0_MEMBDG_WMST1_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS0_PBDG_RMST0_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_PBDG_RMST0_ID                                                               (550U)
#define CSL_ISC_R5FSS0_PBDG_RMST0_DEFAULT_PRIV_ID                                                  (212U)
#define CSL_ISC_R5FSS0_PBDG_RMST0_MMR_BASE                                                         (0x45889800UL)
#define CSL_ISC_R5FSS0_PBDG_RMST0_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS0_PBDG_RMST1_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_PBDG_RMST1_ID                                                               (551U)
#define CSL_ISC_R5FSS0_PBDG_RMST1_DEFAULT_PRIV_ID                                                  (213U)
#define CSL_ISC_R5FSS0_PBDG_RMST1_MMR_BASE                                                         (0x45889c00UL)
#define CSL_ISC_R5FSS0_PBDG_RMST1_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS0_PBDG_WMST0_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_PBDG_WMST0_ID                                                               (552U)
#define CSL_ISC_R5FSS0_PBDG_WMST0_DEFAULT_PRIV_ID                                                  (212U)
#define CSL_ISC_R5FSS0_PBDG_WMST0_MMR_BASE                                                         (0x4588a000UL)
#define CSL_ISC_R5FSS0_PBDG_WMST0_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS0_PBDG_WMST1_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_PBDG_WMST1_ID                                                               (553U)
#define CSL_ISC_R5FSS0_PBDG_WMST1_DEFAULT_PRIV_ID                                                  (213U)
#define CSL_ISC_R5FSS0_PBDG_WMST1_MMR_BASE                                                         (0x4588a400UL)
#define CSL_ISC_R5FSS0_PBDG_WMST1_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS0_CPU0_PMST_TYPE                                                              (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_CPU0_PMST_ID                                                                (656U)
#define CSL_ISC_R5FSS0_CPU0_PMST_DEFAULT_PRIV_ID                                                   (212U)
#define CSL_ISC_R5FSS0_CPU0_PMST_MMR_BASE                                                          (0x458a4000UL)
#define CSL_ISC_R5FSS0_CPU0_PMST_REGION_COUNT                                                      (4U)
#define CSL_ISC_R5FSS0_CPU1_PMST_TYPE                                                              (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS0_CPU1_PMST_ID                                                                (657U)
#define CSL_ISC_R5FSS0_CPU1_PMST_DEFAULT_PRIV_ID                                                   (213U)
#define CSL_ISC_R5FSS0_CPU1_PMST_MMR_BASE                                                          (0x458a4400UL)
#define CSL_ISC_R5FSS0_CPU1_PMST_REGION_COUNT                                                      (4U)

/* Properties of firewall at master: R5FSS1 */
#define CSL_ISC_R5FSS1_MEMBDG_RMST0_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_MEMBDG_RMST0_ID                                                             (532U)
#define CSL_ISC_R5FSS1_MEMBDG_RMST0_DEFAULT_PRIV_ID                                                (214U)
#define CSL_ISC_R5FSS1_MEMBDG_RMST0_MMR_BASE                                                       (0x45885000UL)
#define CSL_ISC_R5FSS1_MEMBDG_RMST0_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS1_MEMBDG_RMST1_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_MEMBDG_RMST1_ID                                                             (533U)
#define CSL_ISC_R5FSS1_MEMBDG_RMST1_DEFAULT_PRIV_ID                                                (215U)
#define CSL_ISC_R5FSS1_MEMBDG_RMST1_MMR_BASE                                                       (0x45885400UL)
#define CSL_ISC_R5FSS1_MEMBDG_RMST1_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS1_MEMBDG_WMST0_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_MEMBDG_WMST0_ID                                                             (534U)
#define CSL_ISC_R5FSS1_MEMBDG_WMST0_DEFAULT_PRIV_ID                                                (214U)
#define CSL_ISC_R5FSS1_MEMBDG_WMST0_MMR_BASE                                                       (0x45885800UL)
#define CSL_ISC_R5FSS1_MEMBDG_WMST0_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS1_MEMBDG_WMST1_TYPE                                                           (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_MEMBDG_WMST1_ID                                                             (535U)
#define CSL_ISC_R5FSS1_MEMBDG_WMST1_DEFAULT_PRIV_ID                                                (215U)
#define CSL_ISC_R5FSS1_MEMBDG_WMST1_MMR_BASE                                                       (0x45885c00UL)
#define CSL_ISC_R5FSS1_MEMBDG_WMST1_REGION_COUNT                                                   (4U)
#define CSL_ISC_R5FSS1_PBDG_RMST0_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_PBDG_RMST0_ID                                                               (554U)
#define CSL_ISC_R5FSS1_PBDG_RMST0_DEFAULT_PRIV_ID                                                  (214U)
#define CSL_ISC_R5FSS1_PBDG_RMST0_MMR_BASE                                                         (0x4588a800UL)
#define CSL_ISC_R5FSS1_PBDG_RMST0_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS1_PBDG_RMST1_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_PBDG_RMST1_ID                                                               (555U)
#define CSL_ISC_R5FSS1_PBDG_RMST1_DEFAULT_PRIV_ID                                                  (215U)
#define CSL_ISC_R5FSS1_PBDG_RMST1_MMR_BASE                                                         (0x4588ac00UL)
#define CSL_ISC_R5FSS1_PBDG_RMST1_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS1_PBDG_WMST0_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_PBDG_WMST0_ID                                                               (556U)
#define CSL_ISC_R5FSS1_PBDG_WMST0_DEFAULT_PRIV_ID                                                  (214U)
#define CSL_ISC_R5FSS1_PBDG_WMST0_MMR_BASE                                                         (0x4588b000UL)
#define CSL_ISC_R5FSS1_PBDG_WMST0_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS1_PBDG_WMST1_TYPE                                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_PBDG_WMST1_ID                                                               (557U)
#define CSL_ISC_R5FSS1_PBDG_WMST1_DEFAULT_PRIV_ID                                                  (215U)
#define CSL_ISC_R5FSS1_PBDG_WMST1_MMR_BASE                                                         (0x4588b400UL)
#define CSL_ISC_R5FSS1_PBDG_WMST1_REGION_COUNT                                                     (4U)
#define CSL_ISC_R5FSS1_CPU0_PMST_TYPE                                                              (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_CPU0_PMST_ID                                                                (658U)
#define CSL_ISC_R5FSS1_CPU0_PMST_DEFAULT_PRIV_ID                                                   (214U)
#define CSL_ISC_R5FSS1_CPU0_PMST_MMR_BASE                                                          (0x458a4800UL)
#define CSL_ISC_R5FSS1_CPU0_PMST_REGION_COUNT                                                      (4U)
#define CSL_ISC_R5FSS1_CPU1_PMST_TYPE                                                              (CSL_ISC_DEFAULT)
#define CSL_ISC_R5FSS1_CPU1_PMST_ID                                                                (659U)
#define CSL_ISC_R5FSS1_CPU1_PMST_DEFAULT_PRIV_ID                                                   (215U)
#define CSL_ISC_R5FSS1_CPU1_PMST_MMR_BASE                                                          (0x458a4c00UL)
#define CSL_ISC_R5FSS1_CPU1_PMST_REGION_COUNT                                                      (4U)

/* Properties of firewall at master: COMPUTE_CLUSTER0 */
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_RD_VBUSM_TYPE                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_RD_VBUSM_ID                                               (536U)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_RD_VBUSM_DEFAULT_PRIV_ID                                  (154U)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_RD_VBUSM_MMR_BASE                                         (0x45886000UL)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_RD_VBUSM_REGION_COUNT                                     (1U)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_WR_VBUSM_TYPE                                             (CSL_ISC_DEFAULT)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_WR_VBUSM_ID                                               (537U)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_WR_VBUSM_DEFAULT_PRIV_ID                                  (154U)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_WR_VBUSM_MMR_BASE                                         (0x45886400UL)
#define CSL_ISC_COMPUTE_CLUSTER0_GIC_MEM_WR_VBUSM_REGION_COUNT                                     (1U)

/* Properties of firewall at master: LED0 */
#define CSL_ISC_LED0_VBUSP_TYPE                                                                    (CSL_ISC_DEFAULT)
#define CSL_ISC_LED0_VBUSP_ID                                                                      (544U)
#define CSL_ISC_LED0_VBUSP_DEFAULT_PRIV_ID                                                         (176U)
#define CSL_ISC_LED0_VBUSP_MMR_BASE                                                                (0x45888000UL)
#define CSL_ISC_LED0_VBUSP_REGION_COUNT                                                            (1U)

/* Properties of firewall at master: SA2_UL0 */
#define CSL_ISC_SA2_UL0_CTXCACH_EXT_DMA_TYPE                                                       (CSL_ISC_DEFAULT)
#define CSL_ISC_SA2_UL0_CTXCACH_EXT_DMA_ID                                                         (546U)
#define CSL_ISC_SA2_UL0_CTXCACH_EXT_DMA_DEFAULT_PRIV_ID                                            (152U)
#define CSL_ISC_SA2_UL0_CTXCACH_EXT_DMA_MMR_BASE                                                   (0x45888800UL)
#define CSL_ISC_SA2_UL0_CTXCACH_EXT_DMA_REGION_COUNT                                               (4U)

/* Properties of firewall at master: VPFE0 */
#define CSL_ISC_VPFE0_VBUSM_DMA_TYPE                                                               (CSL_ISC_DEFAULT)
#define CSL_ISC_VPFE0_VBUSM_DMA_ID                                                                 (560U)
#define CSL_ISC_VPFE0_VBUSM_DMA_DEFAULT_PRIV_ID                                                    (189U)
#define CSL_ISC_VPFE0_VBUSM_DMA_MMR_BASE                                                           (0x4588c000UL)
#define CSL_ISC_VPFE0_VBUSM_DMA_REGION_COUNT                                                       (1U)

/* Properties of firewall at master: PCIE0 */
#define CSL_ISC_PCIE0_PCIE_MST_RD_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE0_PCIE_MST_RD_HP_ID                                                            (576U)
#define CSL_ISC_PCIE0_PCIE_MST_RD_HP_DEFAULT_PRIV_ID                                               (178U)
#define CSL_ISC_PCIE0_PCIE_MST_RD_HP_MMR_BASE                                                      (0x45890000UL)
#define CSL_ISC_PCIE0_PCIE_MST_RD_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE0_PCIE_MST_RD_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE0_PCIE_MST_RD_LP_ID                                                            (577U)
#define CSL_ISC_PCIE0_PCIE_MST_RD_LP_DEFAULT_PRIV_ID                                               (179U)
#define CSL_ISC_PCIE0_PCIE_MST_RD_LP_MMR_BASE                                                      (0x45890400UL)
#define CSL_ISC_PCIE0_PCIE_MST_RD_LP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE0_PCIE_MST_WR_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE0_PCIE_MST_WR_HP_ID                                                            (578U)
#define CSL_ISC_PCIE0_PCIE_MST_WR_HP_DEFAULT_PRIV_ID                                               (178U)
#define CSL_ISC_PCIE0_PCIE_MST_WR_HP_MMR_BASE                                                      (0x45890800UL)
#define CSL_ISC_PCIE0_PCIE_MST_WR_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE0_PCIE_MST_WR_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE0_PCIE_MST_WR_LP_ID                                                            (579U)
#define CSL_ISC_PCIE0_PCIE_MST_WR_LP_DEFAULT_PRIV_ID                                               (179U)
#define CSL_ISC_PCIE0_PCIE_MST_WR_LP_MMR_BASE                                                      (0x45890c00UL)
#define CSL_ISC_PCIE0_PCIE_MST_WR_LP_REGION_COUNT                                                  (4U)

/* Properties of firewall at master: PCIE1 */
#define CSL_ISC_PCIE1_PCIE_MST_RD_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE1_PCIE_MST_RD_HP_ID                                                            (580U)
#define CSL_ISC_PCIE1_PCIE_MST_RD_HP_DEFAULT_PRIV_ID                                               (180U)
#define CSL_ISC_PCIE1_PCIE_MST_RD_HP_MMR_BASE                                                      (0x45891000UL)
#define CSL_ISC_PCIE1_PCIE_MST_RD_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE1_PCIE_MST_RD_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE1_PCIE_MST_RD_LP_ID                                                            (581U)
#define CSL_ISC_PCIE1_PCIE_MST_RD_LP_DEFAULT_PRIV_ID                                               (181U)
#define CSL_ISC_PCIE1_PCIE_MST_RD_LP_MMR_BASE                                                      (0x45891400UL)
#define CSL_ISC_PCIE1_PCIE_MST_RD_LP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE1_PCIE_MST_WR_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE1_PCIE_MST_WR_HP_ID                                                            (582U)
#define CSL_ISC_PCIE1_PCIE_MST_WR_HP_DEFAULT_PRIV_ID                                               (180U)
#define CSL_ISC_PCIE1_PCIE_MST_WR_HP_MMR_BASE                                                      (0x45891800UL)
#define CSL_ISC_PCIE1_PCIE_MST_WR_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE1_PCIE_MST_WR_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE1_PCIE_MST_WR_LP_ID                                                            (583U)
#define CSL_ISC_PCIE1_PCIE_MST_WR_LP_DEFAULT_PRIV_ID                                               (181U)
#define CSL_ISC_PCIE1_PCIE_MST_WR_LP_MMR_BASE                                                      (0x45891c00UL)
#define CSL_ISC_PCIE1_PCIE_MST_WR_LP_REGION_COUNT                                                  (4U)

/* Properties of firewall at master: PCIE2 */
#define CSL_ISC_PCIE2_PCIE_MST_RD_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE2_PCIE_MST_RD_HP_ID                                                            (584U)
#define CSL_ISC_PCIE2_PCIE_MST_RD_HP_DEFAULT_PRIV_ID                                               (182U)
#define CSL_ISC_PCIE2_PCIE_MST_RD_HP_MMR_BASE                                                      (0x45892000UL)
#define CSL_ISC_PCIE2_PCIE_MST_RD_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE2_PCIE_MST_RD_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE2_PCIE_MST_RD_LP_ID                                                            (585U)
#define CSL_ISC_PCIE2_PCIE_MST_RD_LP_DEFAULT_PRIV_ID                                               (183U)
#define CSL_ISC_PCIE2_PCIE_MST_RD_LP_MMR_BASE                                                      (0x45892400UL)
#define CSL_ISC_PCIE2_PCIE_MST_RD_LP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE2_PCIE_MST_WR_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE2_PCIE_MST_WR_HP_ID                                                            (586U)
#define CSL_ISC_PCIE2_PCIE_MST_WR_HP_DEFAULT_PRIV_ID                                               (182U)
#define CSL_ISC_PCIE2_PCIE_MST_WR_HP_MMR_BASE                                                      (0x45892800UL)
#define CSL_ISC_PCIE2_PCIE_MST_WR_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE2_PCIE_MST_WR_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE2_PCIE_MST_WR_LP_ID                                                            (587U)
#define CSL_ISC_PCIE2_PCIE_MST_WR_LP_DEFAULT_PRIV_ID                                               (183U)
#define CSL_ISC_PCIE2_PCIE_MST_WR_LP_MMR_BASE                                                      (0x45892c00UL)
#define CSL_ISC_PCIE2_PCIE_MST_WR_LP_REGION_COUNT                                                  (4U)

/* Properties of firewall at master: PCIE3 */
#define CSL_ISC_PCIE3_PCIE_MST_RD_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE3_PCIE_MST_RD_HP_ID                                                            (588U)
#define CSL_ISC_PCIE3_PCIE_MST_RD_HP_DEFAULT_PRIV_ID                                               (184U)
#define CSL_ISC_PCIE3_PCIE_MST_RD_HP_MMR_BASE                                                      (0x45893000UL)
#define CSL_ISC_PCIE3_PCIE_MST_RD_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE3_PCIE_MST_RD_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE3_PCIE_MST_RD_LP_ID                                                            (589U)
#define CSL_ISC_PCIE3_PCIE_MST_RD_LP_DEFAULT_PRIV_ID                                               (185U)
#define CSL_ISC_PCIE3_PCIE_MST_RD_LP_MMR_BASE                                                      (0x45893400UL)
#define CSL_ISC_PCIE3_PCIE_MST_RD_LP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE3_PCIE_MST_WR_HP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE3_PCIE_MST_WR_HP_ID                                                            (590U)
#define CSL_ISC_PCIE3_PCIE_MST_WR_HP_DEFAULT_PRIV_ID                                               (184U)
#define CSL_ISC_PCIE3_PCIE_MST_WR_HP_MMR_BASE                                                      (0x45893800UL)
#define CSL_ISC_PCIE3_PCIE_MST_WR_HP_REGION_COUNT                                                  (4U)
#define CSL_ISC_PCIE3_PCIE_MST_WR_LP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_PCIE3_PCIE_MST_WR_LP_ID                                                            (591U)
#define CSL_ISC_PCIE3_PCIE_MST_WR_LP_DEFAULT_PRIV_ID                                               (185U)
#define CSL_ISC_PCIE3_PCIE_MST_WR_LP_MMR_BASE                                                      (0x45893c00UL)
#define CSL_ISC_PCIE3_PCIE_MST_WR_LP_REGION_COUNT                                                  (4U)

/* Properties of firewall at master: MLB0 */
#define CSL_ISC_MLB0_MLBSS_DMA_VBUSP_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_MLB0_MLBSS_DMA_VBUSP_ID                                                            (615U)
#define CSL_ISC_MLB0_MLBSS_DMA_VBUSP_DEFAULT_PRIV_ID                                               (128U)
#define CSL_ISC_MLB0_MLBSS_DMA_VBUSP_MMR_BASE                                                      (0x45899c00UL)
#define CSL_ISC_MLB0_MLBSS_DMA_VBUSP_REGION_COUNT                                                  (1U)

/* Properties of firewall at master: MMCSD0 */
#define CSL_ISC_MMCSD0_EMMCSS_RD_TYPE                                                              (CSL_ISC_DEFAULT)
#define CSL_ISC_MMCSD0_EMMCSS_RD_ID                                                                (616U)
#define CSL_ISC_MMCSD0_EMMCSS_RD_DEFAULT_PRIV_ID                                                   (128U)
#define CSL_ISC_MMCSD0_EMMCSS_RD_MMR_BASE                                                          (0x4589a000UL)
#define CSL_ISC_MMCSD0_EMMCSS_RD_REGION_COUNT                                                      (1U)
#define CSL_ISC_MMCSD0_EMMCSS_WR_TYPE                                                              (CSL_ISC_DEFAULT)
#define CSL_ISC_MMCSD0_EMMCSS_WR_ID                                                                (617U)
#define CSL_ISC_MMCSD0_EMMCSS_WR_DEFAULT_PRIV_ID                                                   (128U)
#define CSL_ISC_MMCSD0_EMMCSS_WR_MMR_BASE                                                          (0x4589a400UL)
#define CSL_ISC_MMCSD0_EMMCSS_WR_REGION_COUNT                                                      (1U)

/* Properties of firewall at master: UFS0 */
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_RD_TYPE                                                        (CSL_ISC_DEFAULT)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_RD_ID                                                          (620U)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_RD_DEFAULT_PRIV_ID                                             (128U)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_RD_MMR_BASE                                                    (0x4589b000UL)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_RD_REGION_COUNT                                                (1U)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_WR_TYPE                                                        (CSL_ISC_DEFAULT)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_WR_ID                                                          (621U)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_WR_DEFAULT_PRIV_ID                                             (128U)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_WR_MMR_BASE                                                    (0x4589b400UL)
#define CSL_ISC_UFS0_UFSHCI_VBM_MST_WR_REGION_COUNT                                                (1U)

/* Properties of firewall at master: DEBUGSS_WRAP0 */
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMR_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMR_ID                                                            (640U)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMR_DEFAULT_PRIV_ID                                               (177U)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMR_MMR_BASE                                                      (0x458a0000UL)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMR_REGION_COUNT                                                  (1U)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMW_TYPE                                                          (CSL_ISC_DEFAULT)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMW_ID                                                            (641U)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMW_DEFAULT_PRIV_ID                                               (177U)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMW_MMR_BASE                                                      (0x458a0400UL)
#define CSL_ISC_DEBUGSS_WRAP0_VBUSMW_REGION_COUNT                                                  (1U)

/* Properties of firewall at master: DECODER0 */
#define CSL_ISC_DECODER0_M_VBUSM_R_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_DECODER0_M_VBUSM_R_ID                                                              (769U)
#define CSL_ISC_DECODER0_M_VBUSM_R_DEFAULT_PRIV_ID                                                 (186U)
#define CSL_ISC_DECODER0_M_VBUSM_R_MMR_BASE                                                        (0x458c0400UL)
#define CSL_ISC_DECODER0_M_VBUSM_R_REGION_COUNT                                                    (2U)
#define CSL_ISC_DECODER0_M_VBUSM_W_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_DECODER0_M_VBUSM_W_ID                                                              (770U)
#define CSL_ISC_DECODER0_M_VBUSM_W_DEFAULT_PRIV_ID                                                 (186U)
#define CSL_ISC_DECODER0_M_VBUSM_W_MMR_BASE                                                        (0x458c0800UL)
#define CSL_ISC_DECODER0_M_VBUSM_W_REGION_COUNT                                                    (2U)

/* Properties of firewall at master: ENCODER0 */
#define CSL_ISC_ENCODER0_M_VBUSM_R_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_ENCODER0_M_VBUSM_R_ID                                                              (771U)
#define CSL_ISC_ENCODER0_M_VBUSM_R_DEFAULT_PRIV_ID                                                 (190U)
#define CSL_ISC_ENCODER0_M_VBUSM_R_MMR_BASE                                                        (0x458c0c00UL)
#define CSL_ISC_ENCODER0_M_VBUSM_R_REGION_COUNT                                                    (5U)
#define CSL_ISC_ENCODER0_M_VBUSM_W_TYPE                                                            (CSL_ISC_DEFAULT)
#define CSL_ISC_ENCODER0_M_VBUSM_W_ID                                                              (772U)
#define CSL_ISC_ENCODER0_M_VBUSM_W_DEFAULT_PRIV_ID                                                 (190U)
#define CSL_ISC_ENCODER0_M_VBUSM_W_MMR_BASE                                                        (0x458c1000UL)
#define CSL_ISC_ENCODER0_M_VBUSM_W_REGION_COUNT                                                    (5U)

/* Properties of firewall at master: DSS0 */
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_DMA_TYPE                                                      (CSL_ISC_DEFAULT)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_DMA_ID                                                        (776U)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_DMA_DEFAULT_PRIV_ID                                           (173U)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_DMA_MMR_BASE                                                  (0x458c2000UL)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_DMA_REGION_COUNT                                              (10U)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_FBDC_TYPE                                                     (CSL_ISC_DEFAULT)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_FBDC_ID                                                       (777U)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_FBDC_DEFAULT_PRIV_ID                                          (173U)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_FBDC_MMR_BASE                                                 (0x458c2400UL)
#define CSL_ISC_DSS0_DSS_INST0_VBUSM_FBDC_REGION_COUNT                                             (10U)

/* Properties of firewall at master: GPU0 */
#define CSL_ISC_GPU0_M0_VBUSM_R_ASYNC_TYPE                                                         (CSL_ISC_DEFAULT)
#define CSL_ISC_GPU0_M0_VBUSM_R_ASYNC_ID                                                           (788U)
#define CSL_ISC_GPU0_M0_VBUSM_R_ASYNC_DEFAULT_PRIV_ID                                              (187U)
#define CSL_ISC_GPU0_M0_VBUSM_R_ASYNC_MMR_BASE                                                     (0x458c5000UL)
#define CSL_ISC_GPU0_M0_VBUSM_R_ASYNC_REGION_COUNT                                                 (48U)
#define CSL_ISC_GPU0_M0_VBUSM_W_ASYNC_TYPE                                                         (CSL_ISC_DEFAULT)
#define CSL_ISC_GPU0_M0_VBUSM_W_ASYNC_ID                                                           (790U)
#define CSL_ISC_GPU0_M0_VBUSM_W_ASYNC_DEFAULT_PRIV_ID                                              (187U)
#define CSL_ISC_GPU0_M0_VBUSM_W_ASYNC_MMR_BASE                                                     (0x458c5800UL)
#define CSL_ISC_GPU0_M0_VBUSM_W_ASYNC_REGION_COUNT                                                 (48U)
#define CSL_ISC_GPU0_M1_VBUSM_R_ASYNC_TYPE                                                         (CSL_ISC_DEFAULT)
#define CSL_ISC_GPU0_M1_VBUSM_R_ASYNC_ID                                                           (792U)
#define CSL_ISC_GPU0_M1_VBUSM_R_ASYNC_DEFAULT_PRIV_ID                                              (187U)
#define CSL_ISC_GPU0_M1_VBUSM_R_ASYNC_MMR_BASE                                                     (0x458c6000UL)
#define CSL_ISC_GPU0_M1_VBUSM_R_ASYNC_REGION_COUNT                                                 (48U)
#define CSL_ISC_GPU0_M1_VBUSM_W_ASYNC_TYPE                                                         (CSL_ISC_DEFAULT)
#define CSL_ISC_GPU0_M1_VBUSM_W_ASYNC_ID                                                           (794U)
#define CSL_ISC_GPU0_M1_VBUSM_W_ASYNC_DEFAULT_PRIV_ID                                              (187U)
#define CSL_ISC_GPU0_M1_VBUSM_W_ASYNC_MMR_BASE                                                     (0x458c6800UL)
#define CSL_ISC_GPU0_M1_VBUSM_W_ASYNC_REGION_COUNT                                                 (48U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_SOC_ISC_H_ */

