/********************************************************************
*
* MCU_R5FSS0_CORE0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_MCU_R5FSS0_CORE0_INTERRUPT_MAP_H_
#define CSLR_MCU_R5FSS0_CORE0_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: MCU_R5FSS0_CORE0
*/

#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCAN0_MCANSS_MCAN_LVL_INT_0                                 (0U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCAN0_MCANSS_MCAN_LVL_INT_1                                 (1U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCAN1_MCANSS_MCAN_LVL_INT_0                                 (2U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCAN1_MCANSS_MCAN_LVL_INT_1                                 (3U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                      (4U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                      (5U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_ADC0_GEN_LEVEL_0                                            (6U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_ADC1_GEN_LEVEL_0                                            (7U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_SA2_UL0_SA_UL_PKA_0                                         (14U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_SA2_UL0_SA_UL_TRNG_0                                        (15U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_I3C0_I3C__INT_0                                             (16U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_I3C1_I3C__INT_0                                             (17U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_I2C1_POINTRPEND_0                                           (18U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCSPI0_INTR_SPI_0                                           (20U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCSPI1_INTR_SPI_0                                           (21U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_MCSPI2_INTR_SPI_0                                           (22U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_I2C0_POINTRPEND_0                                           (23U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_FSS0_OSPI_0_OSPI_LVL_INTR_0                                 (24U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_FSS0_OSPI_1_OSPI_LVL_INTR_0                                 (25U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_FSS0_HYPERBUS1P0_0_HPB_INTR_0                               (26U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_FSS0_FSAS_0_OTFA_INTR_ERR_PEND_0                            (27U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_FSS0_FSAS_0_ECC_INTR_ERR_PEND_0                             (28U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_UART0_USART_IRQ_0                                           (30U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_CPSW0_STAT_PEND_0                                           (32U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_CPSW0_EVNT_PEND_0                                           (34U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_CPSW0_MDIO_PEND_0                                           (35U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_PBIST1_DFT_PBIST_CPU_0                                      (37U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER0_INTR_PEND_0                                          (38U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER1_INTR_PEND_0                                          (39U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER2_INTR_PEND_0                                          (40U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER3_INTR_PEND_0                                          (41U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_RTI0_INTR_WWD_0                                             (42U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_RTI1_INTR_WWD_0                                             (43U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_CTRL_MMR0_IPC_SET0_IPC_SET_IPCFG_0                          (44U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_CTRL_MMR0_IPC_SET1_IPC_SET_IPCFG_0                          (45U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_CTRL_MMR0_ACCESS_ERR_0                                      (46U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_PBIST0_DFT_PBIST_CPU_0                                      (47U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_ESM0_ESM_INT_LOW_LVL_0                                      (48U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_ESM0_ESM_INT_HI_LVL_0                                       (49U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_DCC0_INTR_DONE_LEVEL_0                                      (50U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_DCC1_INTR_DONE_LEVEL_0                                      (51U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_DCC2_INTR_DONE_LEVEL_0                                      (52U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_ESM0_ESM_INT_CFG_LVL_0                                      (53U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_DEBUGSS1_AQCMPINTR_LEVEL_0                                      (54U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_DEBUGSS1_CTM_LEVEL_0                                            (55U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_CORE0_VALIRQ_0                                       (56U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_CORE0_VALFIQ_0                                       (57U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_CORE0_CTI_0                                          (58U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_CORE1_CTI_0                                          (59U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_COMMRX_LEVEL_0_0                                     (60U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_COMMTX_LEVEL_0_0                                     (61U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_0                            (64U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_1                            (65U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_2                            (66U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_3                            (67U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_4                            (68U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_5                            (69U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_6                            (70U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_7                            (71U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_8                            (72U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_9                            (73U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_10                           (74U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_11                           (75U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_12                           (76U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_13                           (77U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_14                           (78U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_15                           (79U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_16                           (80U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_17                           (81U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_18                           (82U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_19                           (83U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_20                           (84U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_21                           (85U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_22                           (86U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_23                           (87U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_24                           (88U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_25                           (89U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_26                           (90U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_27                           (91U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_28                           (92U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_29                           (93U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_30                           (94U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_NAVSS0_INTR_ROUTER_0_OUTL_INTR_31                           (95U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_I2C0_POINTRPEND_0                                          (96U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_UART0_USART_IRQ_0                                          (97U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_LOW_LVL_0                                     (98U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_HI_LVL_0                                      (99U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_CFG_LVL_0                                     (100U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_RAT_0_EXP_INTR_0                                     (102U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_DBG_AUTH_0_DEBUG_AUTH_INTR_0                         (103U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_AES_0_HIB_PUBLIC_0                                   (104U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_AES_0_HIB_SECURE_0                                   (105U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_CORTEX_M3_0_SEC_OUT_0                                (106U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_CORTEX_M3_0_SEC_OUT_1                                (107U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER4_INTR_PEND_0                                          (108U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER5_INTR_PEND_0                                          (109U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER6_INTR_PEND_0                                          (110U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER7_INTR_PEND_0                                          (111U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER8_INTR_PEND_0                                          (112U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_TIMER9_INTR_PEND_0                                          (113U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_CTRL_MMR0_ACCESS_ERR_0                                     (119U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_PORZ_SYNC0_MAIN_PORZ_LATCHED_0                             (120U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_RESETZ_SYNC0_MAIN_RESETZ_LATCHED_0                         (122U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_0                                     (124U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_1                                     (125U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_2                                     (126U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_3                                     (127U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_4                                     (128U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_5                                     (129U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_6                                     (130U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_7                                     (131U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_8                                     (132U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_9                                     (133U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_10                                    (134U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_11                                    (135U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_12                                    (136U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_13                                    (137U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_14                                    (138U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_15                                    (139U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_ESM0_ESM_INT_LOW_LVL_0                                          (140U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_ESM0_ESM_INT_HI_LVL_0                                           (141U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_ESM0_ESM_INT_CFG_LVL_0                                          (142U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_0       (144U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_1       (145U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_CORE0_EXP_INTR_0                                     (146U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_R5FSS0_CORE1_EXP_INTR_0                                     (147U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MCU_CBASS0_LPSC_MCU_COMMON_ERR_INTR_0                           (148U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_GLUELOGIC_DBG_CBASS_INTR_OR_GLUE_DBG_CBASS_AGG_ERR_INTR_0       (149U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_GLUELOGIC_FW_CBASS_INTR_OR_GLUE_FW_CBASS_AGG_ERR_INTR_0         (150U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_CBASS0_LPSC_WKUP_COMMON_ERR_INTR_0                         (151U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                               (156U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                               (157U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                               (158U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_0                                     (160U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_1                                     (161U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_2                                     (162U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_3                                     (163U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_4                                     (164U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_5                                     (165U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_6                                     (166U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_7                                     (167U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_8                                     (168U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_9                                     (169U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_10                                    (170U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_11                                    (171U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_12                                    (172U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_13                                    (173U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_14                                    (174U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_15                                    (175U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_16                                    (176U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_17                                    (177U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_18                                    (178U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_19                                    (179U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_20                                    (180U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_21                                    (181U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_22                                    (182U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_23                                    (183U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_24                                    (184U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_25                                    (185U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_26                                    (186U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_27                                    (187U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_28                                    (188U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_29                                    (189U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_30                                    (190U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_31                                    (191U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_32                                    (192U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_33                                    (193U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_34                                    (194U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_35                                    (195U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_36                                    (196U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_37                                    (197U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_38                                    (198U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_39                                    (199U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_40                                    (200U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_41                                    (201U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_42                                    (202U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_43                                    (203U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_44                                    (204U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_45                                    (205U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_46                                    (206U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_47                                    (207U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_48                                    (208U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_49                                    (209U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_50                                    (210U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_51                                    (211U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_52                                    (212U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_53                                    (213U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_54                                    (214U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_55                                    (215U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_56                                    (216U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_57                                    (217U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_58                                    (218U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_59                                    (219U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_60                                    (220U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_61                                    (221U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_62                                    (222U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_LVL_INTRTR0_OUTL_63                                    (223U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_0                                     (224U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_1                                     (225U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_2                                     (226U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_3                                     (227U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_4                                     (228U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_5                                     (229U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_6                                     (230U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_7                                     (231U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_8                                     (232U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_9                                     (233U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_10                                    (234U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_11                                    (235U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_12                                    (236U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_13                                    (237U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_14                                    (238U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_15                                    (239U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_16                                    (240U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_17                                    (241U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_18                                    (242U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_19                                    (243U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_20                                    (244U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_21                                    (245U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_22                                    (246U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_23                                    (247U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_24                                    (248U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_25                                    (249U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_26                                    (250U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_27                                    (251U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_28                                    (252U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_29                                    (253U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_30                                    (254U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_31                                    (255U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_32                                    (256U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_33                                    (257U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_34                                    (258U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_35                                    (259U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_36                                    (260U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_37                                    (261U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_38                                    (262U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_39                                    (263U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_40                                    (264U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_41                                    (265U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_42                                    (266U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_43                                    (267U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_44                                    (268U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_45                                    (269U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_46                                    (270U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_MAIN2MCU_PLS_INTRTR0_OUTP_47                                    (271U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_8                    (288U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_9                    (289U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_PBIST_WRAP_DFT_PBIST_CPU_0                     (290U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_ARM0_DFT_LBIST_DFT_LBIST_BIST_DONE_0           (291U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_12                   (293U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_CLEC_SOC_EVENTS_OUT_LEVEL_13                   (294U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_C7X_4_DFT_LBIST_DFT_LBIST_BIST_DONE_0          (295U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_GLUELOGIC_MAIN_PULSAR0_LBIST_GLUE_DFT_LBIST_BIST_DONE_0         (297U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_GLUELOGIC_MAIN_PULSAR1_LBIST_GLUE_DFT_LBIST_BIST_DONE_0         (298U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_GLUELOGIC_DMPAC_LBIST_GLUE_DFT_LBIST_BIST_DONE_0                (299U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_GLUELOGIC_VPAC_LBIST_GLUE_DFT_LBIST_BIST_DONE_0                 (300U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST2_DFT_PBIST_CPU_0                                          (302U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST0_DFT_PBIST_CPU_0                                          (303U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST1_DFT_PBIST_CPU_0                                          (304U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST3_DFT_PBIST_CPU_0                                          (305U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST4_DFT_PBIST_CPU_0                                          (306U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST5_DFT_PBIST_CPU_0                                          (307U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST7_DFT_PBIST_CPU_0                                          (308U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST9_DFT_PBIST_CPU_0                                          (309U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST10_DFT_PBIST_CPU_0                                         (310U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_PBIST6_DFT_PBIST_CPU_0                                          (312U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_C66SS0_PBIST0_DFT_PBIST_CPU_0                                   (315U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_C66SS1_PBIST0_DFT_PBIST_CPU_0                                   (316U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_GPU0_DFT_PBIST_0_DFT_PBIST_CPU_0                                (317U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_0                       (320U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_1                       (321U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_2                       (322U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_3                       (323U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_4                       (324U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_5                       (325U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_6                       (326U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_7                       (327U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_8                       (328U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_9                       (329U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_10                      (330U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_11                      (331U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_12                      (332U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_13                      (333U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_14                      (334U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_15                      (335U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_16                      (336U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_17                      (337U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_18                      (338U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_19                      (339U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_20                      (340U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_21                      (341U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_22                      (342U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_23                      (343U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_24                      (344U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_25                      (345U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_26                      (346U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_27                      (347U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_28                      (348U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_29                      (349U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_30                      (350U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_WKUP_DMSC0_INTAGGR_0_INTAGGR_VINTR_PEND_31                      (351U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_400                              (376U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_401                              (377U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_402                              (378U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_403                              (379U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_404                              (380U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_405                              (381U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_406                              (382U)
#define CSLR_MCU_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_407                              (383U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_MCU_R5FSS0_CORE0_INTERRUPT_MAP_H_ */

