/********************************************************************
 * Copyright (C) 2013-2014 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#ifndef CSLR_RESTORE_CM_CORE_H
#define CSLR_RESTORE_CM_CORE_H

#ifdef __cplusplus
extern "C"
{
#endif
#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>


/**************************************************************************
* Register Overlay Structure for __ALL__
**************************************************************************/
typedef struct {
    volatile Uint8  RSVD0[24];
    volatile Uint32 CM_L3MAIN1_CLKSTCTRL_RESTORE_REG;
    volatile Uint8  RSVD1[4];
    volatile Uint32 CM_L4CFG_CLKSTCTRL_RESTORE_REG;
    volatile Uint8  RSVD2[4];
    volatile Uint32 CM_L4PER_CLKSTCTRL_RESTORE_REG;
    volatile Uint32 CM_L3INIT_CLKSTCTRL_RESTORE_REG;
    volatile Uint32 CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG;
    volatile Uint32 CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG;
    volatile Uint32 CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG;
    volatile Uint32 CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG;
    volatile Uint8  RSVD3[8];
    volatile Uint32 CM_L3MAIN1_DYNAMICDEP_RESTORE_REG;
    volatile Uint8  RSVD4[12];
    volatile Uint32 CM_L4CFG_DYNAMICDEP_RESTORE_REG;
    volatile Uint32 CM_L4PER_DYNAMICDEP_RESTORE_REG;
    volatile Uint32 CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG;
    volatile Uint8  RSVD5[8];
    volatile Uint32 CM_DMA_STATICDEP_RESTORE_REG;
} CSL_restore_cm_coreRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

/* Second address map for register CM_L3MAIN1_CLKSTCTRL. Used only by
 * automatic restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG    (0x18U)
/* Below define for backward compatibility */
#define CM_L3MAIN1_CLKSTCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG)


/* Second address map for register CM_L4CFG_CLKSTCTRL. Used only by automatic
 * restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG      (0x20U)
/* Below define for backward compatibility */
#define CM_L4CFG_CLKSTCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG)


/* Second address map for register CM_L4PER_CLKSTCTRL. Used only by automatic
 * restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG      (0x28U)
/* Below define for backward compatibility */
#define CM_L4PER_CLKSTCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG)


/* Second address map for register CM_L3INIT_CLKSTCTRL. Used only by automatic
 * restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG     (0x2CU)
/* Below define for backward compatibility */
#define CM_L3INIT_CLKSTCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG)


/* Second address map for register CM_L3INSTR_L3_MAIN_2_CLKCTRL. Used only by
 * automatic restore upon wakeup from device OFF mode. [warm reset
 * insensitive] */
#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG  (0x30U)
/* Below define for backward compatibility */
#define CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG)


/* Second address map for register CM_L3INSTR_L3_INSTR_CLKCTRL. Used only by
 * automatic restore upon wakeup from device OFF mode. [warm reset
 * insensitive] */
#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG  (0x34U)
/* Below define for backward compatibility */
#define CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG)


/* Second address map for register CM_L3INSTR_OCP_WP_NOC_CLKCTRL. Used only by
 * automatic restore upon wakeup from device OFF mode. [warm reset
 * insensitive] */
#define CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG  (0x38U)
/* Below define for backward compatibility */
#define CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG)


/* Second address map for register CM_CM_CORE_PROFILING_CLKCTRL. Used only by
 * automatic restore upon wakeup from device OFF mode. [warm reset
 * insensitive] */
#define CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG  (0x3CU)
/* Below define for backward compatibility */
#define CM_CM_CORE_PROFILING_CLKCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG)


/* Second address map for register CM_L3MAIN1_DYNAMICDEP. Used only by
 * automatic restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG   (0x48U)
/* Below define for backward compatibility */
#define CM_L3MAIN1_DYNAMICDEP_RESTORE  (CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG)


/* Second address map for register CM_L4CFG_DYNAMICDEP. Used only by automatic
 * restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG     (0x58U)
/* Below define for backward compatibility */
#define CM_L4CFG_DYNAMICDEP_RESTORE  (CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG)


/* Second address map for register CM_L4PER_DYNAMICDEP. Used only by automatic
 * restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG     (0x5CU)
/* Below define for backward compatibility */
#define CM_L4PER_DYNAMICDEP_RESTORE  (CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG)


/* Second address map for register CM_COREAON_IO_SRCOMP_CLKCTRL. Used only by
 * automatic restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG  (0x60U)
/* Below define for backward compatibility */
#define CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE  (CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG)


/* Second address map for register CM_DMA_STATICDEP. Used only by automatic
 * restore upon wakeup from device OFF mode. */
#define CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG        (0x6CU)
/* Below define for backward compatibility */
#define CM_DMA_STATICDEP_RESTORE  (CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG)



/**************************************************************************
* Field Definition Macros
**************************************************************************/

/* CM_L3MAIN1_CLKSTCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L3MAIN1_CLKSTCTRL_RESTORE_RESTORE_MASK     (CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00000000U)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L3MAIN1_CLKSTCTRL_RESTORE_RESTORE_SHIFT    (CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_CLKSTCTRL_RESTORE_REG_RESETVAL  (0x00000000U)

/* CM_L4CFG_CLKSTCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L4CFG_CLKSTCTRL_RESTORE_RESTORE_MASK       (CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00000000U)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L4CFG_CLKSTCTRL_RESTORE_RESTORE_SHIFT      (CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_CLKSTCTRL_RESTORE_REG_RESETVAL  (0x00000000U)

/* CM_L4PER_CLKSTCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L4PER_CLKSTCTRL_RESTORE_RESTORE_MASK       (CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00000000U)

#define CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L4PER_CLKSTCTRL_RESTORE_RESTORE_SHIFT      (CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L4PER_CLKSTCTRL_RESTORE_REG_RESETVAL  (0x00000000U)

/* CM_L3INIT_CLKSTCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L3INIT_CLKSTCTRL_RESTORE_RESTORE_MASK      (CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00000000U)

#define CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L3INIT_CLKSTCTRL_RESTORE_RESTORE_SHIFT     (CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L3INIT_CLKSTCTRL_RESTORE_REG_RESETVAL  (0x00000000U)

/* CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_RESTORE_MASK  (CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00030001U)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_RESTORE_SHIFT  (CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_MAIN_2_CLKCTRL_RESTORE_REG_RESETVAL  (0x00030001U)

/* CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_RESTORE_MASK  (CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00030001U)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_RESTORE_SHIFT  (CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_L3_INSTR_CLKCTRL_RESTORE_REG_RESETVAL  (0x00030001U)

/* CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_RESTORE_MASK  (CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00030001U)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_RESTORE_SHIFT  (CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L3INSTR_OCP_WP_NOC_CLKCTRL_RESTORE_REG_RESETVAL  (0x00030001U)

/* CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_RESTORE_MASK  (CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00030001U)

#define CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_RESTORE_SHIFT  (CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_CM_CORE_PROFILING_CLKCTRL_RESTORE_REG_RESETVAL  (0x00030001U)

/* CM_L3MAIN1_DYNAMICDEP_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L3MAIN1_DYNAMICDEP_RESTORE_RESTORE_MASK    (CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG_RESTORE_RESETVAL  (0x04001058U)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L3MAIN1_DYNAMICDEP_RESTORE_RESTORE_SHIFT   (CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L3MAIN1_DYNAMICDEP_RESTORE_REG_RESETVAL  (0x04001058U)

/* CM_L4CFG_DYNAMICDEP_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L4CFG_DYNAMICDEP_RESTORE_RESTORE_MASK      (CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG_RESTORE_RESETVAL  (0x040789f2U)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L4CFG_DYNAMICDEP_RESTORE_RESTORE_SHIFT     (CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L4CFG_DYNAMICDEP_RESTORE_REG_RESETVAL  (0x040789f2U)

/* CM_L4PER_DYNAMICDEP_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_L4PER_DYNAMICDEP_RESTORE_RESTORE_MASK      (CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG_RESTORE_RESETVAL  (0x04004180U)

#define CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_L4PER_DYNAMICDEP_RESTORE_RESTORE_SHIFT     (CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_L4PER_DYNAMICDEP_RESTORE_REG_RESETVAL  (0x04004180U)

/* CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_RESTORE_MASK  (CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG_RESTORE_RESETVAL  (0x00000020U)

#define CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_RESTORE_SHIFT  (CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_COREAON_IO_SRCOMP_CLKCTRL_RESTORE_REG_RESETVAL  (0x00000020U)

/* CM_DMA_STATICDEP_RESTORE_REG */

#define CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG_RESTORE_MASK  (0xFFFFFFFFU)
/* Below define for backward compatibility */
#define CM_DMA_STATICDEP_RESTORE_RESTORE_MASK         (CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG_RESTORE_MASK)

#define CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG_RESTORE_RESETVAL  (0x0000b0f0U)

#define CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG_RESTORE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_DMA_STATICDEP_RESTORE_RESTORE_SHIFT        (CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG_RESTORE_SHIFT)

#define CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG_RESTORE_MAX  (0xffffffffU)

#define CSL_RESTORE_CM_CORE_CM_DMA_STATICDEP_RESTORE_REG_RESETVAL  (0x0000b0f0U)

#ifdef __cplusplus
}
#endif
#endif
