/********************************************************************
 * Copyright (C) 2013-2014 Texas Instruments Incorporated.
 * 
 *  Redistribution and use in source and binary forms, with or without 
 *  modification, are permitted provided that the following conditions 
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the   
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#ifndef CSLR_RTC_PRM_H
#define CSLR_RTC_PRM_H

#ifdef __cplusplus
extern "C"
{
#endif
#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>


/**************************************************************************
* Register Overlay Structure for __ALL__
**************************************************************************/
typedef struct {
    volatile Uint32 PM_RTC_RTCSS_WKDEP_REG;
    volatile Uint32 RM_RTC_RTCSS_CONTEXT_REG;
} CSL_rtc_prmRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

/* This register controls wakeup dependency based on RTCSS service requests. */
#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG                      (0x20U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP        (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG)


/* This register contains dedicated RTCSS context statuses. [warm reset 
 * insensitive] */
#define CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG                    (0x24U)
/* Below define for backward compatibility */
#define RM_RTC_RTCSS_CONTEXT      (CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG)



/**************************************************************************
* Field Definition Macros
**************************************************************************/

/* PM_RTC_RTCSS_WKDEP_REG */

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_MPU_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_SHIFT  (0U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_MPU_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_MPU_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_MPU_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_MPU_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_MASK  (0x00000002U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU2_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_SHIFT  (1U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU2_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU2_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU2_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU2_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_MASK  (0x00000004U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP1_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_SHIFT  (2U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP1_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP1_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP1_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP1_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_MASK  (0x00000010U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU1_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_SHIFT  (4U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU1_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU1_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_IPU1_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_IPU1_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_MASK  (0x00000020U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP2_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_SHIFT  (5U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP2_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP2_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_DSP2_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_DSP2_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_MASK  (0x00000040U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE1_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_SHIFT  (6U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE1_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE1_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE1_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE1_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_MASK  (0x00000080U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE2_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_SHIFT  (7U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE2_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE2_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE2_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE2_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE3_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_SHIFT  (8U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE3_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE3_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE3_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE3_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_MASK  (0x00000200U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE4_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_SHIFT  (9U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE4_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE4_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ1_EVE4_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ1_EVE4_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_MASK  (0x00000400U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_MPU_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_SHIFT  (10U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_MPU_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_MPU_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_MPU_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_MPU_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_MASK  (0x00000800U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU2_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_SHIFT  (11U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU2_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU2_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU2_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU2_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_MASK  (0x00001000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP1_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_SHIFT  (12U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP1_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP1_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP1_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP1_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_MASK  (0x00004000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU1_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_SHIFT  (14U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU1_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU1_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_IPU1_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_IPU1_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_MASK  (0x00008000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP2_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_SHIFT  (15U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP2_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP2_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_DSP2_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_DSP2_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_MASK  (0x00010000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE1_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_SHIFT  (16U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE1_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE1_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE1_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE1_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_MASK  (0x00020000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE2_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_SHIFT  (17U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE2_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE2_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE2_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE2_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_MASK  (0x00040000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE3_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_SHIFT  (18U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE3_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE3_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE3_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE3_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_MASK  (0x00080000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE4_MASK  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_MASK)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_RESETVAL  (0x00000000U)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_SHIFT  (19U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE4_SHIFT  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_SHIFT)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE4_ENABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_ENABLED)

#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_RTC_RTCSS_WKDEP_WKUPDEP_RTC_IRQ2_EVE4_DISABLED  (CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_WKUPDEP_RTC_IRQ2_EVE4_DISABLED)


#define CSL_RTC_PRM_PM_RTC_RTCSS_WKDEP_REG_RESETVAL             (0x00000000U)

/* RM_RTC_RTCSS_CONTEXT_REG */

#define CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define RM_RTC_RTCSS_CONTEXT_LOSTCONTEXT_DFF_MASK     (CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_MASK)

#define CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_RESETVAL  (0x00000001U)

#define CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT  (0U)
/* Below define for backward compatibility */
#define RM_RTC_RTCSS_CONTEXT_LOSTCONTEXT_DFF_SHIFT    (CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT)

#define CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_RTC_RTCSS_CONTEXT_LOSTCONTEXT_DFF_LOST     (CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_LOST)

#define CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_RTC_RTCSS_CONTEXT_LOSTCONTEXT_DFF_MAINTAINED  (CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED)


#define CSL_RTC_PRM_RM_RTC_RTCSS_CONTEXT_REG_RESETVAL           (0x00000001U)

#ifdef __cplusplus
}
#endif
#endif
