/* =============================================================================
 *   Copyright (c) Texas Instruments Incorporated 2016
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *  \file      hw_pmhal_data_names.c
 *
 *  \brief     PRCM enum names are defined in this file.
 *
 *  \warning   This file is auto generated. So avoid manual changes.
 *              If manual changes are required the implications of the
 *              change in this and other auto generated files has to be
 *              completely understood.
 */

/* ========================================================================== */
/*                                Include Files                               */
/* ========================================================================== */

#include "stdint.h"
#include "stdio.h"
#include "hw_pmhal_data_names.h"
#include "hw_pmhal_data.h"
#include "pmhal_prcm.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* ========================================================================== */
/*                             Macros and Typedefs                            */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                            Structures and Enums                            */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                 Internal Function Declarations                             */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/**
 * \brief Voltage Domains
 */
const char *pmhalVoltageDomain_t_names[] =
{
    "PMHAL_PRCM_VD_MPU",
    "PMHAL_PRCM_VD_CORE",
    "PMHAL_PRCM_VD_RTC",
    "PMHAL_PRCM_VD_TAMPER"
};

/**
 * \brief Power Domains
 */
const char *pmhalPowerDomain_t_names[] =
{
    "PMHAL_PRCM_PD_CUSTEFUSE",
    "PMHAL_PRCM_PD_GFX",
    "PMHAL_PRCM_PD_MPU",
    "PMHAL_PRCM_PD_RTC",
    "PMHAL_PRCM_PD_WKUP",
    "PMHAL_PRCM_PD_PER",
    "PMHAL_PRCM_PD_STDEFUSE",
    "PMHAL_PRCM_PD_TAMPER"
};

/**
 * \brief Clock Domains
 */
const char *pmhalClkDomain_t_names[] =
{
    "PMHAL_PRCM_CD_L4LS",
    "PMHAL_PRCM_CD_L3S",
    "PMHAL_PRCM_CD_L3",
    "PMHAL_PRCM_CD_OCPWP_L3",
    "PMHAL_PRCM_CD_ICSS_OCP",
    "PMHAL_PRCM_CD_CPSW_125MHZ",
    "PMHAL_PRCM_CD_LCD_L3",
    "PMHAL_PRCM_CD_EMIF_L3",
    "PMHAL_PRCM_CD_DSS_L3",
    "PMHAL_PRCM_CD_L4_WKUP",
    "PMHAL_PRCM_CD_L3_AON",
    "PMHAL_PRCM_CD_L4_WKUP_AON",
    "PMHAL_PRCM_CD_L32_TSC",
    "PMHAL_PRCM_CD_MPU",
    "PMHAL_PRCM_CD_L4_RTC",
    "PMHAL_PRCM_CD_GFX_L3",
    "PMHAL_PRCM_CD_L4_CEFUSE"
};

/**
 * \brief Clocks
 */
const char *pmhalClockList_names[] =
{
    "PMHAL_PRCM_CLK_CUST_EFUSE_SYSCLK",
    "PMHAL_PRCM_CLK_L4_CEFUSE_GCLK",
    "PMHAL_PRCM_CLK_GFX_GFCLK",
    "PMHAL_PRCM_CLK_GFX_L3_GCLK",
    "PMHAL_PRCM_CLK_L4LS_GFX_GCLK",
    "PMHAL_PRCM_CLK_MPU_CLK",
    "PMHAL_PRCM_CLK_CAN_CLK",
    "PMHAL_PRCM_CLK_CPSW_125MHZ_GCLK",
    "PMHAL_PRCM_CLK_CPSW_250MHZ_CLK",
    "PMHAL_PRCM_CLK_CPSW_50MHZ_CLK",
    "PMHAL_PRCM_CLK_CPSW_5MHZ_CLK",
    "PMHAL_PRCM_CLK_CPSW_CPTS_RFT_CLK",
    "PMHAL_PRCM_CLK_DDR_DLL_GCLK",
    "PMHAL_PRCM_CLK_DLL_AGING_GCLK",
    "PMHAL_PRCM_CLK_DSS_GCLK",
    "PMHAL_PRCM_CLK_DSS_L3_GCLK",
    "PMHAL_PRCM_CLK_DSS_L4_GCLK_EN",
    "PMHAL_PRCM_CLK_DSS_SYSCLK",
    "PMHAL_PRCM_CLK_EMIF_L3_GCLK",
    "PMHAL_PRCM_CLK_EMIF_PHY_GCLK",
    "PMHAL_PRCM_CLK_GPIO_1_GDBCLK",
    "PMHAL_PRCM_CLK_GPIO_2_GDBCLK",
    "PMHAL_PRCM_CLK_GPIO_3_GDBCLK",
    "PMHAL_PRCM_CLK_GPIO_4_GDBCLK",
    "PMHAL_PRCM_CLK_GPIO_5_GDBCLK",
    "PMHAL_PRCM_CLK_HDQ1W_GCLK",
    "PMHAL_PRCM_CLK_I2C_FCLK",
    "PMHAL_PRCM_CLK_ICSS_IEP_GCLK",
    "PMHAL_PRCM_CLK_ICSS_OCP_GCLK",
    "PMHAL_PRCM_CLK_ICSS_UART_GCLK",
    "PMHAL_PRCM_CLK_L3D2_GCLK",
    "PMHAL_PRCM_CLK_L3S_GCLK",
    "PMHAL_PRCM_CLK_L3_GCLK",
    "PMHAL_PRCM_CLK_L4LS_GCLK",
    "PMHAL_PRCM_CLK_LCD_GCLK",
    "PMHAL_PRCM_CLK_LCD_L3_GCLK",
    "PMHAL_PRCM_CLK_LCD_L4S_GCLK",
    "PMHAL_PRCM_CLK_MCASP_FCLK",
    "PMHAL_PRCM_CLK_MGC_FCLK",
    "PMHAL_PRCM_CLK_MMC_FCLK",
    "PMHAL_PRCM_CLK_OCPWP_L3_GCLK",
    "PMHAL_PRCM_CLK_OCPWP_L4_GCLK_EN",
    "PMHAL_PRCM_CLK_SPI_GCLK",
    "PMHAL_PRCM_CLK_TIMER10_GCLK",
    "PMHAL_PRCM_CLK_TIMER11_GCLK",
    "PMHAL_PRCM_CLK_TIMER2_GCLK",
    "PMHAL_PRCM_CLK_TIMER3_GCLK",
    "PMHAL_PRCM_CLK_TIMER4_GCLK",
    "PMHAL_PRCM_CLK_TIMER5_GCLK",
    "PMHAL_PRCM_CLK_TIMER6_GCLK",
    "PMHAL_PRCM_CLK_TIMER7_GCLK",
    "PMHAL_PRCM_CLK_TIMER8_GCLK",
    "PMHAL_PRCM_CLK_TIMER9_GCLK",
    "PMHAL_PRCM_CLK_UART_GFCLK",
    "PMHAL_PRCM_CLK_USB_OTG_SS_REFCLK",
    "PMHAL_PRCM_CLK_USB_PLL_CLK",
    "PMHAL_PRCM_CLK_USIM0_FCLK",
    "PMHAL_PRCM_CLK_USIM0_FCLK32",
    "PMHAL_PRCM_CLK_USIM1_FCLK",
    "PMHAL_PRCM_CLK_USIM1_FCLK32",
    "PMHAL_PRCM_CLK_L4_RTC_GCLK",
    "PMHAL_PRCM_CLK_RTC_32KCLK",
    "PMHAL_PRCM_CLK_STD_EFUSE_SYSCLK",
    "PMHAL_PRCM_CLK_TAMPER_L4_GCLK",
    "PMHAL_PRCM_CLK_ADC_FCLK",
    "PMHAL_PRCM_CLK_CLK_24MHZ",
    "PMHAL_PRCM_CLK_DBGSYSCLK",
    "PMHAL_PRCM_CLK_DEBUG_CLKA_GCLK",
    "PMHAL_PRCM_CLK_DEBUG_CLKB_GCLK",
    "PMHAL_PRCM_CLK_DEBUG_CLKC_GCLK",
    "PMHAL_PRCM_CLK_GPIO0_GDBCLK",
    "PMHAL_PRCM_CLK_I2C0_GFCLK",
    "PMHAL_PRCM_CLK_L3S_TSC_GCLK",
    "PMHAL_PRCM_CLK_L3_AON_GCLK",
    "PMHAL_PRCM_CLK_L4_WKUP_AON_GCLK",
    "PMHAL_PRCM_CLK_L4_WKUP_GCLK",
    "PMHAL_PRCM_CLK_SR_SYSCLK",
    "PMHAL_PRCM_CLK_SYNCTIMER32K_GFCLK",
#if 0 /* TIMER0 is not supported according to AM335x TRM and CTT */
    "PMHAL_PRCM_CLK_TIMER0_GCLK",
#endif
    "PMHAL_PRCM_CLK_TIMER1_GCLK",
    "PMHAL_PRCM_CLK_UART0_GFCLK",
    "PMHAL_PRCM_CLK_USBPHY_32KHZ_GCLK",
#if 0 /* WDT0 is not supported according to AM335x TRM and CTT */
    "PMHAL_PRCM_CLK_WDT0_GCLK",
#endif
    "PMHAL_PRCM_CLK_WDT1_GCLK",
    "PMHAL_PRCM_CLK_COUNT",
    "PMHAL_PRCM_CLK_GENERIC"
};

/**
 * \brief Reset Groups
 */
const char *pmhalResetGroupList_names[] =
{
    "PMHAL_PRCM_RG_ICSS_RST",
    "PMHAL_PRCM_RG_WKUP_M3_RST",
    "PMHAL_PRCM_RG_GFX_RST",
    "PMHAL_PRCM_RG_PROGRAMMABLE_RST_COUNT",
    "PMHAL_PRCM_RG_CUST_EFUSE_RST",
    "PMHAL_PRCM_RG_GFX_DOM_RST",
    "PMHAL_PRCM_RG_MPU_AO_RST",
    "PMHAL_PRCM_RG_MPU_PWRON_RST",
    "PMHAL_PRCM_RG_MPU_RST",
    "PMHAL_PRCM_RG_DLL_RST",
    "PMHAL_PRCM_RG_EMIF_DDR_PHY_PWRON_RST",
    "PMHAL_PRCM_RG_PER_DOM_RST",
    "PMHAL_PRCM_RG_USB_POR_RST",
    "PMHAL_PRCM_RG_RTC_DOM_RST",
    "PMHAL_PRCM_RG_STD_EFUSE_PWRON_RST",
    "PMHAL_PRCM_RG_TAMPER_DOM_RST",
    "PMHAL_PRCM_RG_DPLL_RST",
    "PMHAL_PRCM_RG_EMU_EARLY_PWRON_RST",
    "PMHAL_PRCM_RG_EMU_PWRON_RST",
    "PMHAL_PRCM_RG_EMU_RST",
    "PMHAL_PRCM_RG_WKUP_DOM_RST",
    "PMHAL_PRCM_RG_WKUP_PWRON_RST",
    "PMHAL_PRCM_RG_WKUP_SYS_PWRON_RST"
};

/**
 * \brief Global Reset Group List
 */
const char *pmhalGlobalResetGroupList_names[] =
{
    "PMHAL_PRCM_GLB_RG_GLOBAL_COLD_RST",
    "PMHAL_PRCM_GLB_RG_GLOBAL_WARM_SW_RST",
#if 0 /* WDT0 is not supported according to AM437x TRM and CTT */
    "PMHAL_PRCM_GLB_RG_WDT0_RST",
#endif
    "PMHAL_PRCM_GLB_RG_WDT1_RST",
    "PMHAL_PRCM_GLB_RG_EXTERNAL_WARM_RST",
    "PMHAL_PRCM_GLB_RG_ICEPICK_RST",
    "PMHAL_PRCM_GLB_RG_MPU_SECURITY_VIOL_RST"
};

/**
 * \brief Reset List
 */
const char *pmhalResetList_names[] =
{
    ""
};

/**
 * \brief Physical Memories
 */
const char *pmhalPhysicalMemory_t_names[] =
{
    "PMHAL_PRCM_PHY_MEM_GFX",
    "PMHAL_PRCM_PHY_MEM_MPU_L1",
    "PMHAL_PRCM_PHY_MEM_MPU_L2",
    "PMHAL_PRCM_PHY_MEM_MPU_RAM",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_CPPI",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_RX_ADDR",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_RX_DB",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_RX_INFO",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_RX_ST",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_STATE",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_STATISTICS",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_TX_DB",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_TX_INFO",
    "PMHAL_PRCM_PHY_MEM_CPGMACSS_R_RAM_TX_ST",
    "PMHAL_PRCM_PHY_MEM_DSSMEM",
    "PMHAL_PRCM_PHY_MEM_MSHSI2COCP",
    "PMHAL_PRCM_PHY_MEM_DMEM0",
    "PMHAL_PRCM_PHY_MEM_DMEM1",
    "PMHAL_PRCM_PHY_MEM_DMEM2",
    "PMHAL_PRCM_PHY_MEM_DMEM3",
    "PMHAL_PRCM_PHY_MEM_IMEM0",
    "PMHAL_PRCM_PHY_MEM_IMEM1",
    "PMHAL_PRCM_PHY_MEM_IMEM2",
    "PMHAL_PRCM_PHY_MEM_IMEM3",
    "PMHAL_PRCM_PHY_MEM_PRUSS0",
    "PMHAL_PRCM_PHY_MEM_PRUSS1",
    "PMHAL_PRCM_PHY_MEM_LCD_CORE_PALETTE_RAM",
    "PMHAL_PRCM_PHY_MEM_LCD_DMA_FIFO_RAM",
    "PMHAL_PRCM_PHY_MEM_UART",
    "PMHAL_PRCM_PHY_MEM_MBOXSRAM",
    "PMHAL_PRCM_PHY_MEM_MSTR_EXPS",
    "PMHAL_PRCM_PHY_MEM_BANK1",
    "PMHAL_PRCM_PHY_MEM_BANK2",
    "PMHAL_PRCM_PHY_MEM_PKA",
    "PMHAL_PRCM_PHY_MEM_TPCC",
    "PMHAL_PRCM_PHY_MEM_TPTC0",
    "PMHAL_PRCM_PHY_MEM_TPTC1",
    "PMHAL_PRCM_PHY_MEM_TPTC2",
    "PMHAL_PRCM_PHY_MEM_USB",
    "PMHAL_PRCM_PHY_MEM_WB0",
    "PMHAL_PRCM_PHY_MEM_WB1",
    "PMHAL_PRCM_PHY_MEM_DEBUGSS"
};

/**
 * \brief Physical Memory Bank
 */
const char *pmhalPhysicalMemoryBank_t_names[] =
{
    "PMHAL_PRCM_PHY_BANK_GFX_MEM",
    "PMHAL_PRCM_PHY_BANK_MPU_L1",
    "PMHAL_PRCM_PHY_BANK_MPU_L2",
    "PMHAL_PRCM_PHY_BANK_MPU_RAM",
    "PMHAL_PRCM_PHY_BANK_PER_MEM",
    "PMHAL_PRCM_PHY_BANK_ICSS_MEM",
    "PMHAL_PRCM_PHY_BANK_RAM1_MEM",
    "PMHAL_PRCM_PHY_BANK_RAM2_MEM",
    "PMHAL_PRCM_PHY_BANK_DEBUGSS_MEM"
};

/**
 *  \brief Enum defining modules with SysConfig
 */
const char *pmhalSysConfigModuleId_t_names[] =
{
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPMC
    "PMHAL_PRCM_SYSCFG_GPMC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPMC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ELM
    "PMHAL_PRCM_SYSCFG_ELM",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ELM */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_CONTROL
    "PMHAL_PRCM_SYSCFG_CONTROL",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_CONTROL */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPCC
    "PMHAL_PRCM_SYSCFG_TPCC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPCC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPTC0
    "PMHAL_PRCM_SYSCFG_TPTC0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPTC0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPTC1
    "PMHAL_PRCM_SYSCFG_TPTC1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPTC1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPTC2
    "PMHAL_PRCM_SYSCFG_TPTC2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPTC2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ADC_TSC
    "PMHAL_PRCM_SYSCFG_ADC_TSC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ADC_TSC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAG_CARD
    "PMHAL_PRCM_SYSCFG_MAG_CARD",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAG_CARD */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DSS
    "PMHAL_PRCM_SYSCFG_DSS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DSS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_VPFE0
    "PMHAL_PRCM_SYSCFG_VPFE0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_VPFE0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_VPFE1
    "PMHAL_PRCM_SYSCFG_VPFE1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_VPFE1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS0
    "PMHAL_PRCM_SYSCFG_EPWMSS0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS1
    "PMHAL_PRCM_SYSCFG_EPWMSS1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS2
    "PMHAL_PRCM_SYSCFG_EPWMSS2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS3
    "PMHAL_PRCM_SYSCFG_EPWMSS3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS4
    "PMHAL_PRCM_SYSCFG_EPWMSS4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS5
    "PMHAL_PRCM_SYSCFG_EPWMSS5",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX0
    "PMHAL_PRCM_SYSCFG_MAILBOX0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPINLOCK
    "PMHAL_PRCM_SYSCFG_SPINLOCK",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPINLOCK */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC0
    "PMHAL_PRCM_SYSCFG_MMC0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC1
    "PMHAL_PRCM_SYSCFG_MMC1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC2
    "PMHAL_PRCM_SYSCFG_MMC2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SYNCTIMER
    "PMHAL_PRCM_SYSCFG_SYNCTIMER",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SYNCTIMER */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_RTCSS
    "PMHAL_PRCM_SYSCFG_RTCSS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_RTCSS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP0
    "PMHAL_PRCM_SYSCFG_MCASP0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP1
    "PMHAL_PRCM_SYSCFG_MCASP1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI0
    "PMHAL_PRCM_SYSCFG_SPI0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI1
    "PMHAL_PRCM_SYSCFG_SPI1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI2
    "PMHAL_PRCM_SYSCFG_SPI2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI3
    "PMHAL_PRCM_SYSCFG_SPI3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI4
    "PMHAL_PRCM_SYSCFG_SPI4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_QSPI
    "PMHAL_PRCM_SYSCFG_QSPI",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_QSPI */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO0
    "PMHAL_PRCM_SYSCFG_GPIO0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO1
    "PMHAL_PRCM_SYSCFG_GPIO1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO2
    "PMHAL_PRCM_SYSCFG_GPIO2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO3
    "PMHAL_PRCM_SYSCFG_GPIO3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO4
    "PMHAL_PRCM_SYSCFG_GPIO4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO5
    "PMHAL_PRCM_SYSCFG_GPIO5",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C0
    "PMHAL_PRCM_SYSCFG_I2C0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C1
    "PMHAL_PRCM_SYSCFG_I2C1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C2
    "PMHAL_PRCM_SYSCFG_I2C2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C2 */
};

/**
 * \brief Clock Tree nodes - RootClk, Div, Mux, Pll
 */

const char *pmhalNodeList_names[] =
{
    "PMHAL_PRCM_ROOT_CLK_SYS_CLKIN",
    "PMHAL_PRCM_ROOT_CLK_TCLKIN",
    "PMHAL_PRCM_ROOT_CLK_32K_PER",
    "PMHAL_PRCM_ROOT_CLK_32K_RC",
    "PMHAL_PRCM_ROOT_CLK_32K_RTC",
    "PMHAL_PRCM_ROOT_CLK_32K_TPM",
    "PMHAL_PRCM_ROOT_CLK_32K_MOSC",
    "PMHAL_PRCM_MUX_GFX_GFCLK_MUX",
    "PMHAL_PRCM_MUX_CLKOUT_32K_MUX",
    "PMHAL_PRCM_MUX_CLKOUT1SEL2_PREDIV_MUX",
    "PMHAL_PRCM_MUX_CLKOUT1_MUX",
    "PMHAL_PRCM_MUX_CLKOUT2_MUX",
    "PMHAL_PRCM_MUX_MGC_FGCLK_MUX",
    "PMHAL_PRCM_MUX_DISP_CLK_MUX",
    "PMHAL_PRCM_MUX_ICSS_OCP_GCLK_MUX",
    "PMHAL_PRCM_MUX_TIMER7_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER2_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER3_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER4_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER5_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER6_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER8_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER9_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER10_CLK_MUX",
    "PMHAL_PRCM_MUX_TIMER11_CLK_MUX",
    "PMHAL_PRCM_MUX_CPSW_CPTS_RFT_CLK_MUX",
    "PMHAL_PRCM_MUX_USIM0_FCLK_MUX",
    "PMHAL_PRCM_MUX_USIM0_FCLK32_MUX",
    "PMHAL_PRCM_MUX_USIM1_FCLK_MUX",
    "PMHAL_PRCM_MUX_TIMER1_GCLK_MUX",
#if 0 /* TIMER0 and WDT0 are not supported according to AM437x TRM and CTT */
    "PMHAL_PRCM_MUX_TIMER0_GCLK_MUX",
    "PMHAL_PRCM_MUX_WDT0_GCLK_MUX",
#endif
    "PMHAL_PRCM_MUX_WDT1_GCLK_MUX",
    "PMHAL_PRCM_MUX_USBPHY_32KHZ_GCLK_MUX",
    "PMHAL_PRCM_MUX_GPIO0_GDBCLK_MUX",
    "PMHAL_PRCM_MUX_SYNCTIMER32K_GFCLK_MUX",
    "PMHAL_PRCM_DIV_GFX_GFCLK",
    "PMHAL_PRCM_DIV_CLKOUT1SEL2_PREDIV1",
    "PMHAL_PRCM_DIV_CLKOUT1SEL2_PREDIV2",
    "PMHAL_PRCM_DIV_CLKIN",
    "PMHAL_PRCM_DIV_CLKOUT2_PREDIV1",
    "PMHAL_PRCM_DIV_CLKOUT2_PREDIV2",
    "PMHAL_PRCM_DIV_DLL_AGING_GCLK",
    "PMHAL_PRCM_DIV_UART_CLK",
    "PMHAL_PRCM_DIV_MMC_CLK",
    "PMHAL_PRCM_DIV_FUNC_12M_CLK",
    "PMHAL_PRCM_DIV_CPSW_125MHZ_GCLK",
    "PMHAL_PRCM_DIV_CPSW_50MHZ_CLK",
    "PMHAL_PRCM_DIV_CPSW_5MHZ_CLK",
    "PMHAL_PRCM_DIV_CORE_200M",
    "PMHAL_PRCM_DIV_SYSCLK1",
    "PMHAL_PRCM_DIV_CORE_100M",
    "PMHAL_PRCM_DIV_CORE_25M",
    "PMHAL_PRCM_DIV_VTP_CLK",
    "PMHAL_PRCM_DIV_UART0_CLK",
    "PMHAL_PRCM_DIV_CLK_24MHZ",
    "PMHAL_PRCM_DPLL_PER",
    "PMHAL_PRCM_DPLL_MPU",
    "PMHAL_PRCM_DPLL_DDR",
    "PMHAL_PRCM_DPLL_DISP",
    "PMHAL_PRCM_DPLL_CORE",
    "PMHAL_PRCM_DPLL_EXTDEV",
#ifdef BUILDCFG_PMHAL_PRCM_MOD_AES0
    "PMHAL_PRCM_MOD_AES0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_AES0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_CPGMAC0
    "PMHAL_PRCM_MOD_CPGMAC0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_CPGMAC0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_CRYPTODMA
    "PMHAL_PRCM_MOD_CRYPTODMA",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_CRYPTODMA */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DCAN0
    "PMHAL_PRCM_MOD_DCAN0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DCAN0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DCAN1
    "PMHAL_PRCM_MOD_DCAN1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DCAN1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DDRPHY
    "PMHAL_PRCM_MOD_DDRPHY",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DDRPHY */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DES
    "PMHAL_PRCM_MOD_DES",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DES */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DLL
    "PMHAL_PRCM_MOD_DLL",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DLL */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DLL_AGING
    "PMHAL_PRCM_MOD_DLL_AGING",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DLL_AGING */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DSS
    "PMHAL_PRCM_MOD_DSS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DSS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ELM
    "PMHAL_PRCM_MOD_ELM",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ELM */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EMIF
    "PMHAL_PRCM_MOD_EMIF",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EMIF */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EMIF_FW
    "PMHAL_PRCM_MOD_EMIF_FW",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EMIF_FW */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS0
    "PMHAL_PRCM_MOD_EPWMSS0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS1
    "PMHAL_PRCM_MOD_EPWMSS1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS2
    "PMHAL_PRCM_MOD_EPWMSS2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS3
    "PMHAL_PRCM_MOD_EPWMSS3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS4
    "PMHAL_PRCM_MOD_EPWMSS4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EPWMSS5
    "PMHAL_PRCM_MOD_EPWMSS5",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EPWMSS5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ERMC
    "PMHAL_PRCM_MOD_ERMC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ERMC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO1
    "PMHAL_PRCM_MOD_GPIO1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO2
    "PMHAL_PRCM_MOD_GPIO2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO3
    "PMHAL_PRCM_MOD_GPIO3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO4
    "PMHAL_PRCM_MOD_GPIO4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO5
    "PMHAL_PRCM_MOD_GPIO5",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPMC
    "PMHAL_PRCM_MOD_GPMC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPMC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_HDQ1W
    "PMHAL_PRCM_MOD_HDQ1W",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_HDQ1W */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C1
    "PMHAL_PRCM_MOD_I2C1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C2
    "PMHAL_PRCM_MOD_I2C2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ICSS
    "PMHAL_PRCM_MOD_ICSS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ICSS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_IEEE5000
    "PMHAL_PRCM_MOD_IEEE5000",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_IEEE5000 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L3
    "PMHAL_PRCM_MOD_L3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L3_INSTR
    "PMHAL_PRCM_MOD_L3_INSTR",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L3_INSTR */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4FW
    "PMHAL_PRCM_MOD_L4FW",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L4FW */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4LS
    "PMHAL_PRCM_MOD_L4LS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L4LS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4_HS
    "PMHAL_PRCM_MOD_L4_HS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L4_HS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_LCDC
    "PMHAL_PRCM_MOD_LCDC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_LCDC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAG_CARD
    "PMHAL_PRCM_MOD_MAG_CARD",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAG_CARD */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX0
    "PMHAL_PRCM_MOD_MAILBOX0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP0
    "PMHAL_PRCM_MOD_MCASP0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP1
    "PMHAL_PRCM_MOD_MCASP1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC0
    "PMHAL_PRCM_MOD_MMC0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC1
    "PMHAL_PRCM_MOD_MMC1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC2
    "PMHAL_PRCM_MOD_MMC2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MSTR_EXPS
    "PMHAL_PRCM_MOD_MSTR_EXPS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MSTR_EXPS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_OCMCRAM
    "PMHAL_PRCM_MOD_OCMCRAM",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_OCMCRAM */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_OCP_WP_NOC
    "PMHAL_PRCM_MOD_OCP_WP_NOC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_OCP_WP_NOC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_OTFA_EMIF
    "PMHAL_PRCM_MOD_OTFA_EMIF",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_OTFA_EMIF */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PKA
    "PMHAL_PRCM_MOD_PKA",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PKA */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_QSPI
    "PMHAL_PRCM_MOD_QSPI",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_QSPI */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_RNG
    "PMHAL_PRCM_MOD_RNG",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_RNG */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SHA0
    "PMHAL_PRCM_MOD_SHA0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SHA0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SLV_EXPS
    "PMHAL_PRCM_MOD_SLV_EXPS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SLV_EXPS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPARE0
    "PMHAL_PRCM_MOD_SPARE0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPARE0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPARE1
    "PMHAL_PRCM_MOD_SPARE1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPARE1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI0
    "PMHAL_PRCM_MOD_SPI0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI1
    "PMHAL_PRCM_MOD_SPI1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI2
    "PMHAL_PRCM_MOD_SPI2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI3
    "PMHAL_PRCM_MOD_SPI3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPI4
    "PMHAL_PRCM_MOD_SPI4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPI4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPINLOCK
    "PMHAL_PRCM_MOD_SPINLOCK",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPINLOCK */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER10
    "PMHAL_PRCM_MOD_TIMER10",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER10 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER11
    "PMHAL_PRCM_MOD_TIMER11",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER11 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER2
    "PMHAL_PRCM_MOD_TIMER2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER3
    "PMHAL_PRCM_MOD_TIMER3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER4
    "PMHAL_PRCM_MOD_TIMER4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER5
    "PMHAL_PRCM_MOD_TIMER5",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER6
    "PMHAL_PRCM_MOD_TIMER6",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER6 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER7
    "PMHAL_PRCM_MOD_TIMER7",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER7 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER8
    "PMHAL_PRCM_MOD_TIMER8",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER8 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER9
    "PMHAL_PRCM_MOD_TIMER9",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER9 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPCC
    "PMHAL_PRCM_MOD_TPCC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPCC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPTC0
    "PMHAL_PRCM_MOD_TPTC0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPTC0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPTC1
    "PMHAL_PRCM_MOD_TPTC1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPTC1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPTC2
    "PMHAL_PRCM_MOD_TPTC2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPTC2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART1
    "PMHAL_PRCM_MOD_UART1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART2
    "PMHAL_PRCM_MOD_UART2",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART3
    "PMHAL_PRCM_MOD_UART3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART4
    "PMHAL_PRCM_MOD_UART4",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART5
    "PMHAL_PRCM_MOD_UART5",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USBPHYOCP2SCP0
    "PMHAL_PRCM_MOD_USBPHYOCP2SCP0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USBPHYOCP2SCP0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USBPHYOCP2SCP1
    "PMHAL_PRCM_MOD_USBPHYOCP2SCP1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USBPHYOCP2SCP1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS0
    "PMHAL_PRCM_MOD_USB_OTG_SS0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS1
    "PMHAL_PRCM_MOD_USB_OTG_SS1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USIM0
    "PMHAL_PRCM_MOD_USIM0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USIM0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USIM1
    "PMHAL_PRCM_MOD_USIM1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USIM1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_VPFE0
    "PMHAL_PRCM_MOD_VPFE0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_VPFE0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_VPFE1
    "PMHAL_PRCM_MOD_VPFE1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_VPFE1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GFX
    "PMHAL_PRCM_MOD_GFX",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GFX */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ADC_TSC
    "PMHAL_PRCM_MOD_ADC_TSC",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ADC_TSC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_CLKDIV32K
    "PMHAL_PRCM_MOD_CLKDIV32K",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_CLKDIV32K */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_CONTROL
    "PMHAL_PRCM_MOD_CONTROL",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_CONTROL */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DEBUGSS
    "PMHAL_PRCM_MOD_DEBUGSS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DEBUGSS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO0
    "PMHAL_PRCM_MOD_GPIO0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C0
    "PMHAL_PRCM_MOD_I2C0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4WKUP
    "PMHAL_PRCM_MOD_L4WKUP",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L2WKUP */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX0
    "PMHAL_PRCM_MOD_SMARTREFLEX0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX1
    "PMHAL_PRCM_MOD_SMARTREFLEX1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SYNCTIMER
    "PMHAL_PRCM_MOD_SYNCTIMER",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SYNCTIMER */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER0
    "PMHAL_PRCM_MOD_TIMER0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER1
    "PMHAL_PRCM_MOD_TIMER1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART0
    "PMHAL_PRCM_MOD_UART0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_PHY0_ALWAYS_ON
    "PMHAL_PRCM_MOD_USB_PHY0_ALWAYS_ON",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_PHY0_ALWAYS_ON */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_PHY1_ALWAYS_ON
    "PMHAL_PRCM_MOD_USB_PHY1_ALWAYS_ON",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_PHY1_ALWAYS_ON */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_WDT0
    "PMHAL_PRCM_MOD_WDT0",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_WDT0 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_WDT1
    "PMHAL_PRCM_MOD_WDT1",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_WDT1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_WKUP_M3
    "PMHAL_PRCM_MOD_WKUP_M3",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_WKUP_M3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_CEFUSE
    "PMHAL_PRCM_MOD_CEFUSE",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_CEFUSE */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_RTCSS
    "PMHAL_PRCM_MOD_RTCSS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_RTCSS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MPU
    "PMHAL_PRCM_MOD_MPU",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MPU */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EFUSE
    "PMHAL_PRCM_MOD_EFUSE",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EFUSE */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TPMSS
    "PMHAL_PRCM_MOD_TPMSS",
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TPMSS */
};

/**
 * \brief DPLL Post Divider Names
 */
const char *pmhalPostDivList_names[] =
{
    "PMHAL_PRCM_DPLL_POST_DIV_M2",
    "PMHAL_PRCM_DPLL_POST_DIV_M2X2",
    "PMHAL_PRCM_DPLL_POST_DIV_M4",
    "PMHAL_PRCM_DPLL_POST_DIV_M3",
    "PMHAL_PRCM_DPLL_POST_DIV_M5",
    "PMHAL_PRCM_DPLL_POST_DIV_M6",
    "PMHAL_PRCM_DPLL_POST_DIV_DCO_LDO"
};
/* ========================================================================== */
/*                            Function Declarations                           */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
}
#endif

