/********************************************************************
*
* R5FSS0_CORE0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2019 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_R5FSS0_CORE0_INTERRUPT_MAP_H_
#define CSLR_R5FSS0_CORE0_INTERRUPT_MAP_H_

#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: R5FSS0_CORE0
*/

#define CSLR_R5FSS0_CORE0_INTR_CTRL_MMR0_IPC_SET16_IPC_SET_IPCFG_0                                 (0U)
#define CSLR_R5FSS0_CORE0_INTR_CTRL_MMR0_IPC_SET17_IPC_SET_IPCFG_0                                 (1U)
#define CSLR_R5FSS0_CORE0_INTR_RTI28_INTR_WWD_0                                                    (2U)
#define CSLR_R5FSS0_CORE0_INTR_RTI29_INTR_WWD_0                                                    (3U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_COMMON0_COMMRX_LEVEL_0_0                                     (4U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_COMMON0_COMMTX_LEVEL_0_0                                     (5U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_VALFIQ_0                                               (6U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_VALIRQ_0                                               (7U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_CTI_0                                                  (8U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE1_CTI_0                                                  (9U)
#define CSLR_R5FSS0_CORE0_INTR_ESM0_ESM_INT_LOW_LVL_0                                              (10U)
#define CSLR_R5FSS0_CORE0_INTR_ESM0_ESM_INT_HI_LVL_0                                               (11U)
#define CSLR_R5FSS0_CORE0_INTR_ESM0_ESM_INT_CFG_LVL_0                                              (12U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_EXT_INTN_GLUE_EXT_INT_LVL_0                               (13U)
#define CSLR_R5FSS0_CORE0_INTR_PSC0_PSC_ALLINT_0                                                   (15U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE0_EXP_INTR_0                                             (16U)
#define CSLR_R5FSS0_CORE0_INTR_R5FSS0_CORE1_EXP_INTR_0                                             (17U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN14_MCANSS_MCAN_LVL_INT_0                                        (20U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN14_MCANSS_MCAN_LVL_INT_1                                        (21U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN14_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (22U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN15_MCANSS_MCAN_LVL_INT_0                                        (23U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN15_MCANSS_MCAN_LVL_INT_1                                        (24U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN15_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (25U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN16_MCANSS_MCAN_LVL_INT_0                                        (26U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN16_MCANSS_MCAN_LVL_INT_1                                        (27U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN16_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (28U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN17_MCANSS_MCAN_LVL_INT_0                                        (29U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN17_MCANSS_MCAN_LVL_INT_1                                        (30U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN17_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (31U)
#define CSLR_R5FSS0_CORE0_INTR_CPSW0_STAT_PEND_0                                                   (96U)
#define CSLR_R5FSS0_CORE0_INTR_CPSW0_MDIO_PEND_0                                                   (97U)
#define CSLR_R5FSS0_CORE0_INTR_CPSW0_EVNT_PEND_0                                                   (98U)
#define CSLR_R5FSS0_CORE0_INTR_MMCSD0_EMMCSS_INTR_0                                                (99U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM0_EPWM_ETINT_0                                                (104U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM1_EPWM_ETINT_0                                                (105U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM2_EPWM_ETINT_0                                                (106U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM3_EPWM_ETINT_0                                                (107U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM4_EPWM_ETINT_0                                                (108U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM5_EPWM_ETINT_0                                                (109U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM0_EPWM_TRIPZINT_0                                             (110U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM1_EPWM_TRIPZINT_0                                             (111U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM2_EPWM_TRIPZINT_0                                             (112U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM3_EPWM_TRIPZINT_0                                             (113U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM4_EPWM_TRIPZINT_0                                             (114U)
#define CSLR_R5FSS0_CORE0_INTR_EHRPWM5_EPWM_TRIPZINT_0                                             (115U)
#define CSLR_R5FSS0_CORE0_INTR_EQEP0_EQEP_INT_0                                                    (116U)
#define CSLR_R5FSS0_CORE0_INTR_EQEP1_EQEP_INT_0                                                    (117U)
#define CSLR_R5FSS0_CORE0_INTR_EQEP2_EQEP_INT_0                                                    (118U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (120U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN0_MCANSS_MCAN_LVL_INT_0                                         (121U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN0_MCANSS_MCAN_LVL_INT_1                                         (122U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (123U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN1_MCANSS_MCAN_LVL_INT_0                                         (124U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN1_MCANSS_MCAN_LVL_INT_1                                         (125U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN2_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (126U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN2_MCANSS_MCAN_LVL_INT_0                                         (127U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN2_MCANSS_MCAN_LVL_INT_1                                         (128U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN3_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (129U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN3_MCANSS_MCAN_LVL_INT_0                                         (130U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN3_MCANSS_MCAN_LVL_INT_1                                         (131U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP0_XMIT_INTR_PEND_0                                             (132U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP0_REC_INTR_PEND_0                                              (133U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP1_XMIT_INTR_PEND_0                                             (134U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP1_REC_INTR_PEND_0                                              (135U)
#define CSLR_R5FSS0_CORE0_INTR_I2C0_POINTRPEND_0                                                   (150U)
#define CSLR_R5FSS0_CORE0_INTR_I2C1_POINTRPEND_0                                                   (151U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI0_INTR_SPI_0                                                   (152U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI1_INTR_SPI_0                                                   (153U)
#define CSLR_R5FSS0_CORE0_INTR_UART0_USART_IRQ_0                                                   (158U)
#define CSLR_R5FSS0_CORE0_INTR_UART1_USART_IRQ_0                                                   (159U)
#define CSLR_R5FSS0_CORE0_INTR_UART2_USART_IRQ_0                                                   (160U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER12_INTR_PEND_0                                                 (168U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER13_INTR_PEND_0                                                 (169U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER14_INTR_PEND_0                                                 (170U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER15_INTR_PEND_0                                                 (171U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER16_INTR_PEND_0                                                 (172U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER17_INTR_PEND_0                                                 (173U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER18_INTR_PEND_0                                                 (174U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER19_INTR_PEND_0                                                 (175U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_16                                             (176U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_17                                             (177U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_18                                             (178U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_19                                             (179U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_20                                             (180U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_21                                             (181U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_22                                             (182U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_23                                             (183U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_24                                             (184U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_25                                             (185U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_26                                             (186U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_27                                             (187U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_28                                             (188U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_29                                             (189U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_30                                             (190U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_31                                             (191U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN4_MCANSS_MCAN_LVL_INT_0                                         (192U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN4_MCANSS_MCAN_LVL_INT_1                                         (193U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN4_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (194U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN5_MCANSS_MCAN_LVL_INT_0                                         (195U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN5_MCANSS_MCAN_LVL_INT_1                                         (196U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN5_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (197U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN6_MCANSS_MCAN_LVL_INT_0                                         (198U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN6_MCANSS_MCAN_LVL_INT_1                                         (199U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN6_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (200U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN7_MCANSS_MCAN_LVL_INT_0                                         (201U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN7_MCANSS_MCAN_LVL_INT_1                                         (202U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN7_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (203U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN8_MCANSS_MCAN_LVL_INT_0                                         (204U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN8_MCANSS_MCAN_LVL_INT_1                                         (205U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN8_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (206U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN9_MCANSS_MCAN_LVL_INT_0                                         (207U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN9_MCANSS_MCAN_LVL_INT_1                                         (208U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN9_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                              (209U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN10_MCANSS_MCAN_LVL_INT_0                                        (210U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN10_MCANSS_MCAN_LVL_INT_1                                        (211U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN10_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (212U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN11_MCANSS_MCAN_LVL_INT_0                                        (213U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN11_MCANSS_MCAN_LVL_INT_1                                        (214U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN11_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (215U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN12_MCANSS_MCAN_LVL_INT_0                                        (216U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN12_MCANSS_MCAN_LVL_INT_1                                        (217U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN12_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (218U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN13_MCANSS_MCAN_LVL_INT_0                                        (219U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN13_MCANSS_MCAN_LVL_INT_1                                        (220U)
#define CSLR_R5FSS0_CORE0_INTR_MCAN13_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                             (221U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_192                                  (224U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_193                                  (225U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_194                                  (226U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_195                                  (227U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_196                                  (228U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_197                                  (229U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_198                                  (230U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_199                                  (231U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_200                                  (232U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_201                                  (233U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_202                                  (234U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_203                                  (235U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_204                                  (236U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_205                                  (237U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_206                                  (238U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_207                                  (239U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_208                                  (240U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_209                                  (241U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_210                                  (242U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_211                                  (243U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_212                                  (244U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_213                                  (245U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_214                                  (246U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_215                                  (247U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_216                                  (248U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_217                                  (249U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_218                                  (250U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_219                                  (251U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_220                                  (252U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_221                                  (253U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_222                                  (254U)
#define CSLR_R5FSS0_CORE0_INTR_NAVSS0_INTR_ROUTER_0_OUTL_INTR_223                                  (255U)
#define CSLR_R5FSS0_CORE0_INTR_I2C2_POINTRPEND_0                                                   (256U)
#define CSLR_R5FSS0_CORE0_INTR_I2C3_POINTRPEND_0                                                   (257U)
#define CSLR_R5FSS0_CORE0_INTR_I2C4_POINTRPEND_0                                                   (258U)
#define CSLR_R5FSS0_CORE0_INTR_I2C5_POINTRPEND_0                                                   (259U)
#define CSLR_R5FSS0_CORE0_INTR_I2C6_POINTRPEND_0                                                   (260U)
#define CSLR_R5FSS0_CORE0_INTR_UART3_USART_IRQ_0                                                   (261U)
#define CSLR_R5FSS0_CORE0_INTR_UART4_USART_IRQ_0                                                   (262U)
#define CSLR_R5FSS0_CORE0_INTR_UART5_USART_IRQ_0                                                   (263U)
#define CSLR_R5FSS0_CORE0_INTR_UART6_USART_IRQ_0                                                   (264U)
#define CSLR_R5FSS0_CORE0_INTR_UART7_USART_IRQ_0                                                   (265U)
#define CSLR_R5FSS0_CORE0_INTR_UART8_USART_IRQ_0                                                   (266U)
#define CSLR_R5FSS0_CORE0_INTR_UART9_USART_IRQ_0                                                   (267U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI2_INTR_SPI_0                                                   (268U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI3_INTR_SPI_0                                                   (269U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI4_INTR_SPI_0                                                   (270U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI5_INTR_SPI_0                                                   (271U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI6_INTR_SPI_0                                                   (272U)
#define CSLR_R5FSS0_CORE0_INTR_MCSPI7_INTR_SPI_0                                                   (273U)
#define CSLR_R5FSS0_CORE0_INTR_I3C0_I3C__INT_0                                                     (274U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP2_XMIT_INTR_PEND_0                                             (276U)
#define CSLR_R5FSS0_CORE0_INTR_MCASP2_REC_INTR_PEND_0                                              (277U)
#define CSLR_R5FSS0_CORE0_INTR_GPMC0_GPMC_SINTERRUPT_0                                             (278U)
#define CSLR_R5FSS0_CORE0_INTR_ELM0_ELM_POROCPSINTERRUPT_LVL_0                                     (279U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_OTGIRQ_0                                                       (280U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_0                                                          (281U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_1                                                          (282U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_2                                                          (283U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_3                                                          (284U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_4                                                          (285U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_5                                                          (286U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_6                                                          (287U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_IRQ_7                                                          (288U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER0_INTR_PEND_0                                                  (289U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER1_INTR_PEND_0                                                  (290U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER2_INTR_PEND_0                                                  (291U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER3_INTR_PEND_0                                                  (292U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER4_INTR_PEND_0                                                  (293U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER5_INTR_PEND_0                                                  (294U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER6_INTR_PEND_0                                                  (295U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER7_INTR_PEND_0                                                  (296U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER8_INTR_PEND_0                                                  (297U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER9_INTR_PEND_0                                                  (298U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER10_INTR_PEND_0                                                 (299U)
#define CSLR_R5FSS0_CORE0_INTR_TIMER11_INTR_PEND_0                                                 (300U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_LEGACY_PULSE_0                                           (301U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_DOWNSTREAM_PULSE_0                                       (302U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_FLR_PULSE_0                                              (303U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_PHY_LEVEL_0                                              (304U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_LOCAL_LEVEL_0                                            (305U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_ERROR_PULSE_0                                            (306U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_LINK_STATE_PULSE_0                                       (307U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_PWR_STATE_PULSE_0                                        (308U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_PTM_VALID_PULSE_0                                        (309U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_HOT_RESET_PULSE_0                                        (310U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_CPTS_PEND_0                                              (311U)
#define CSLR_R5FSS0_CORE0_INTR_PCIE1_PCIE_DPA_PULSE_0                                              (312U)
#define CSLR_R5FSS0_CORE0_INTR_DDR0_DDRSS_CONTROLLER_0                                             (313U)
#define CSLR_R5FSS0_CORE0_INTR_DDR0_DDRSS_V2A_OTHER_ERR_LVL_0                                      (314U)
#define CSLR_R5FSS0_CORE0_INTR_DDR0_DDRSS_HS_PHY_GLOBAL_ERROR_0                                    (315U)
#define CSLR_R5FSS0_CORE0_INTR_DDR0_DDRSS_PLL_FREQ_CHANGE_REQ_0                                    (316U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_DMSC0_RAT_0_EXP_INTR_0                                         (317U)
#define CSLR_R5FSS0_CORE0_INTR_DCC0_INTR_DONE_LEVEL_0                                              (318U)
#define CSLR_R5FSS0_CORE0_INTR_DCC1_INTR_DONE_LEVEL_0                                              (319U)
#define CSLR_R5FSS0_CORE0_INTR_DCC2_INTR_DONE_LEVEL_0                                              (320U)
#define CSLR_R5FSS0_CORE0_INTR_DCC3_INTR_DONE_LEVEL_0                                              (321U)
#define CSLR_R5FSS0_CORE0_INTR_DCC4_INTR_DONE_LEVEL_0                                              (322U)
#define CSLR_R5FSS0_CORE0_INTR_DCC5_INTR_DONE_LEVEL_0                                              (323U)
#define CSLR_R5FSS0_CORE0_INTR_DCC6_INTR_DONE_LEVEL_0                                              (324U)
#define CSLR_R5FSS0_CORE0_INTR_CMPEVENT_INTRTR0_OUTP_8                                             (326U)
#define CSLR_R5FSS0_CORE0_INTR_CMPEVENT_INTRTR0_OUTP_9                                             (327U)
#define CSLR_R5FSS0_CORE0_INTR_CMPEVENT_INTRTR0_OUTP_10                                            (328U)
#define CSLR_R5FSS0_CORE0_INTR_CMPEVENT_INTRTR0_OUTP_11                                            (329U)
#define CSLR_R5FSS0_CORE0_INTR_MMCSD1_EMMCSDSS_INTR_0                                              (348U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP0_ECAP_INT_0                                                    (354U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP1_ECAP_INT_0                                                    (355U)
#define CSLR_R5FSS0_CORE0_INTR_ECAP2_ECAP_INT_0                                                    (356U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_SOCA_INT_GLUE_SOCA_INT_0                                  (357U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_SOCB_INT_GLUE_SOCB_INT_0                                  (358U)
#define CSLR_R5FSS0_CORE0_INTR_USB0_HOST_SYSTEM_ERROR_0                                            (361U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_MAIN_CBASS_INTR_OR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0         (362U)
#define CSLR_R5FSS0_CORE0_INTR_CBASS_INFRA0_DEFAULT_ERR_INTR_0                                     (363U)
#define CSLR_R5FSS0_CORE0_INTR_CBASS_INFRA_NON_SAFE0_DEFAULT_ERR_INTR_0                            (364U)
#define CSLR_R5FSS0_CORE0_INTR_CTRL_MMR0_ACCESS_ERR_0                                              (365U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                                   (366U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                                   (367U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                                   (368U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_0           (370U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_GIC_OUTPUT_WAKER_GIC_PWR0_WAKE_REQUEST_1           (371U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCAN0_MCANSS_MCAN_LVL_INT_0                                     (374U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCAN0_MCANSS_MCAN_LVL_INT_1                                     (375U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (376U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCAN1_MCANSS_MCAN_LVL_INT_0                                     (377U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCAN1_MCANSS_MCAN_LVL_INT_1                                     (378U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (379U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_0                                              (396U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_1                                              (397U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_2                                              (398U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_3                                              (399U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_4                                              (400U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_5                                              (401U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_6                                              (402U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_7                                              (403U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_8                                              (404U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_9                                              (405U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_10                                             (406U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_11                                             (407U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_12                                             (408U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_13                                             (409U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_14                                             (410U)
#define CSLR_R5FSS0_CORE0_INTR_GPIOMUX_INTRTR0_OUTP_15                                             (411U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_0                     (412U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_1                     (413U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_2                     (414U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_3                     (415U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_4                     (416U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_5                     (417U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_6                     (418U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_7                     (419U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_8                     (420U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_9                     (421U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_10                    (422U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_11                    (423U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_12                    (424U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_13                    (425U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_14                    (426U)
#define CSLR_R5FSS0_CORE0_INTR_COMPUTE_CLUSTER0_MSMC_EN_SOC_EVENTS_OUT_LEVEL_15                    (427U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_ADC0_GEN_LEVEL_0                                                (444U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_ADC1_GEN_LEVEL_0                                                (445U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_CPSW0_STAT_PEND_0                                               (446U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_CPSW0_MDIO_PEND_0                                               (447U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_CPSW0_EVNT_PEND_0                                               (448U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_DCC0_INTR_DONE_LEVEL_0                                          (449U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_DCC1_INTR_DONE_LEVEL_0                                          (450U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_DCC2_INTR_DONE_LEVEL_0                                          (451U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER0_INTR_PEND_0                                              (452U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER1_INTR_PEND_0                                              (453U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER2_INTR_PEND_0                                              (454U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER3_INTR_PEND_0                                              (455U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER4_INTR_PEND_0                                              (456U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER5_INTR_PEND_0                                              (457U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER6_INTR_PEND_0                                              (458U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER7_INTR_PEND_0                                              (459U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER8_INTR_PEND_0                                              (460U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_TIMER9_INTR_PEND_0                                              (461U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_I2C0_POINTRPEND_0                                               (462U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_I2C1_POINTRPEND_0                                               (463U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCSPI0_INTR_SPI_0                                               (464U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCSPI1_INTR_SPI_0                                               (465U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_MCSPI2_INTR_SPI_0                                               (466U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_UART0_USART_IRQ_0                                               (467U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_I3C0_I3C__INT_0                                                 (468U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_I3C1_I3C__INT_0                                                 (469U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_FSS0_OSPI_0_OSPI_LVL_INTR_0                                     (470U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_FSS0_OSPI_1_OSPI_LVL_INTR_0                                     (471U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_FSS0_HYPERBUS1P0_0_HPB_INTR_0                                   (472U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_FSS0_FSAS_0_OTFA_INTR_ERR_PEND_0                                (473U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_FSS0_FSAS_0_ECC_INTR_ERR_PEND_0                                 (474U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_SA2_UL0_SA_UL_PKA_0                                             (475U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_SA2_UL0_SA_UL_TRNG_0                                            (476U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_ESM0_ESM_INT_LOW_LVL_0                                          (477U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_ESM0_ESM_INT_HI_LVL_0                                           (478U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_ESM0_ESM_INT_CFG_LVL_0                                          (479U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_CTRL_MMR0_ACCESS_ERR_0                                          (480U)
#define CSLR_R5FSS0_CORE0_INTR_MCU_CBASS0_LPSC_MCU_COMMON_ERR_INTR_0                               (481U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_DBG_CBASS_INTR_OR_GLUE_DBG_CBASS_AGG_ERR_INTR_0           (482U)
#define CSLR_R5FSS0_CORE0_INTR_GLUELOGIC_FW_CBASS_INTR_OR_GLUE_FW_CBASS_AGG_ERR_INTR_0             (483U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_CBASS0_LPSC_WKUP_COMMON_ERR_INTR_0                             (485U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_I2C0_POINTRPEND_0                                              (486U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_UART0_USART_IRQ_0                                              (487U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_16                                        (488U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_17                                        (489U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_18                                        (490U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_19                                        (491U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_20                                        (492U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_21                                        (493U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_22                                        (494U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_23                                        (495U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_24                                        (496U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_25                                        (497U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_26                                        (498U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_27                                        (499U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_28                                        (500U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_29                                        (501U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_30                                        (502U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_GPIOMUX_INTRTR0_OUTP_31                                        (503U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_LOW_LVL_0                                         (504U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_HI_LVL_0                                          (505U)
#define CSLR_R5FSS0_CORE0_INTR_WKUP_ESM0_ESM_INT_CFG_LVL_0                                         (506U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_R5FSS0_CORE0_INTERRUPT_MAP_H_ */

