/**
* File: csl_wiz8_sb_PhyB_aneg_lane2
*
* Version: SnowBushRel_PHY_B_18.2_20150626 - Change VREGg/h
*
* Brief:
*  Autogenerated SERDES CONFIG Functions.
*
*  It contains the various enumerations, structure definitions and function
*  declarations
*
*  
*  ============================================================================
*  (C) Copyright 2014, Texas Instruments, Inc.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSL_WIZ8_SB_PHYB_ANEG_LANE2_C
#define CSL_WIZ8_SB_PHYB_ANEG_LANE2_C

#include <stdint.h>
#include <ti/csl/soc.h>
#include <ti/csl/csl.h>

/*for misra warning*/
void csl_wiz8_sb_PhyB_aneg_lane2(uint32_t base_addr);
void csl_wiz8_sb_PhyB_aneg_lane2(uint32_t base_addr)
  {
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0404), 7, 0, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0404),31,24, (uint32_t)0x70);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0408), 7, 0, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0408),15, 8, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0408),23,16, (uint32_t)0x01);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0410),31,24, (uint32_t)0x1b);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0414), 7, 0, (uint32_t)0xf8);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0414),15, 8, (uint32_t)0x6b);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0414),23,16, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0418), 7, 0, (uint32_t)0x74);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0418),23,16, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0418),31,24, (uint32_t)0x75);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x042c),23,16, (uint32_t)0x30);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0430),15, 8, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x044c),23,16, (uint32_t)0x8f);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0450),31,24, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0460), 7, 0, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0464), 7, 0, (uint32_t)0x57);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0468),15, 8, (uint32_t)0x57);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0468),23,16, (uint32_t)0x57);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0478),31,24, (uint32_t)0xff);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0480), 7, 0, (uint32_t)0x50);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0480),23,16, (uint32_t)0x50);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0484), 7, 0, (uint32_t)0x05);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0494),15, 8, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0494),23,16, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0494),31,24, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0498), 7, 0, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0498),15, 8, (uint32_t)0x08);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0498),31,24, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x049c), 7, 0, (uint32_t)0x01);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x04a4), 7, 0, (uint32_t)0x0a);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x04a4),15, 8, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x04a8),15, 8, (uint32_t)0xb6);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x04a8),23,16, (uint32_t)0x01);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0580), 7, 0, (uint32_t)0xb0);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0580), 7, 0, (uint32_t)0x30);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x05c0),15, 8, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x05cc), 7, 0, (uint32_t)0x18);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x05cc), 7, 0, (uint32_t)0x18);
  }
#endif
