/**
* File: csl_wiz8_sb_PhyB_10p3125G_156p25MHz_cmu1
*
* Version: SnowBushRel_PHY_B_18.2_20150626 - Change VREGg/h
*
* Brief:
*  Autogenerated SERDES CONFIG Functions.
*
*  It contains the various enumerations, structure definitions and function
*  declarations
*
*  
*  ============================================================================
*  (C) Copyright 2014, Texas Instruments, Inc.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSL_WIZ8_SB_PHYB_10P3125G_156P25MHZ_CMU1_C
#define CSL_WIZ8_SB_PHYB_10P3125G_156P25MHZ_CMU1_C

#include <stdint.h>
#include <ti/csl/soc.h>
#include <ti/csl/csl.h>

/*for misra warning*/
void csl_wiz8_sb_PhyB_10p3125G_156p25MHz_cmu1(uint32_t base_addr);
void csl_wiz8_sb_PhyB_10p3125G_156p25MHz_cmu1(uint32_t base_addr)
  {
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c00), 7, 0, (uint32_t)0x02);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c00),23,16, (uint32_t)0x03);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c14), 7, 0, (uint32_t)0x52);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c14),15, 8, (uint32_t)0x52);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c28),31,24, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c2c), 7, 0, (uint32_t)0xf6);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c3c), 7, 0, (uint32_t)0x05);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c3c),15, 8, (uint32_t)0x04);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c3c),31,24, (uint32_t)0x04);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c40),23,16, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c40),31,24, (uint32_t)0xc0);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c44), 7, 0, (uint32_t)0x62);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c44),15, 8, (uint32_t)0x20);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c44),23,16, (uint32_t)0x20);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c44),31,24, (uint32_t)0x5a);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c48), 7, 0, (uint32_t)0x24);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c48),15, 8, (uint32_t)0x04);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c48),23,16, (uint32_t)0x04);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c48),31,24, (uint32_t)0x40);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c4c), 7, 0, (uint32_t)0x02);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c4c),15, 8, (uint32_t)0x40);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c50),15, 8, (uint32_t)0x1c);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c50),31,24, (uint32_t)0x19);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c54),15, 8, (uint32_t)0x21);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c58), 7, 0, (uint32_t)0x60);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c60), 7, 0, (uint32_t)0x7c);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c60),15, 8, (uint32_t)0x1e);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c60),23,16, (uint32_t)0x13);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c60),31,24, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c64), 7, 0, (uint32_t)0x02);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c64),15, 8, (uint32_t)0xcb);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c64),31,24, (uint32_t)0x84);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c68),15, 8, (uint32_t)0x82);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c68),23,16, (uint32_t)0x07);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c68),31,24, (uint32_t)0x17);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c6c), 7, 0, (uint32_t)0x16);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c74),15, 8, (uint32_t)0x04);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c78),15, 8, (uint32_t)0xc0);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0c00), 7, 0, (uint32_t)0x03);
  }
#endif
