/**
* File: csl_wiz8_sb_PhyB_10p3125G_16bit_lane1
*
* Version: SnowBushRel_PHY_B_18.2_20150626 - Change VREGg/h
*
* Brief:
*  Autogenerated SERDES CONFIG Functions.
*
*  It contains the various enumerations, structure definitions and function
*  declarations
*
*  
*  ============================================================================
*  (C) Copyright 2014, Texas Instruments, Inc.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSL_WIZ8_SB_PHYB_10P3125G_16BIT_LANE1_C
#define CSL_WIZ8_SB_PHYB_10P3125G_16BIT_LANE1_C

#include <stdint.h>
#include <ti/csl/soc.h>
#include <ti/csl/csl.h>

/*for misra warning*/
void csl_wiz8_sb_PhyB_10p3125G_16bit_lane1(uint32_t base_addr);
void csl_wiz8_sb_PhyB_10p3125G_16bit_lane1(uint32_t base_addr)
  {
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0204), 7, 0, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0208), 7, 0, (uint32_t)0x0d);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0208),15, 8, (uint32_t)0x92);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0204),31,24, (uint32_t)0xfc);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0208), 7, 0, (uint32_t)0x04);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0208),15, 8, (uint32_t)0x91);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0208),23,16, (uint32_t)0x01);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0210),31,24, (uint32_t)0x1a);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0214), 7, 0, (uint32_t)0x5c);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0214),15, 8, (uint32_t)0x6b);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0214),23,16, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0218), 7, 0, (uint32_t)0x84);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0218),23,16, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0218),31,24, (uint32_t)0x7a);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x022c),23,16, (uint32_t)0x30);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0230),15, 8, (uint32_t)0x08);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x024c),23,16, (uint32_t)0x80);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0250),31,24, (uint32_t)0x30);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0260), 7, 0, (uint32_t)0x02);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0264), 7, 0, (uint32_t)0x57);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0268),15, 8, (uint32_t)0x57);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0268),23,16, (uint32_t)0x57);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0278),31,24, (uint32_t)0xff);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0280), 7, 0, (uint32_t)0x50);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0280),23,16, (uint32_t)0x50);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0284), 7, 0, (uint32_t)0x15);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0284),15, 8, (uint32_t)0x1f);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x028c),15, 8, (uint32_t)0x6f);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0294),15, 8, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0294),23,16, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0294),31,24, (uint32_t)0x01);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0298), 7, 0, (uint32_t)0x41);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0298),15, 8, (uint32_t)0x26);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0298),31,24, (uint32_t)0x00);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x029c), 7, 0, (uint32_t)0x03);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x02a4), 7, 0, (uint32_t)0x13);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x02a4),15, 8, (uint32_t)0x0f);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x02a8),15, 8, (uint32_t)0xb6);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x02a8),23,16, (uint32_t)0x01);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x0380), 7, 0, (uint32_t)0x30);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x03c0),15, 8, (uint32_t)0x02);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x03cc), 7, 0, (uint32_t)0x18);
  CSL_FINSR(*(volatile uint32_t *)(base_addr + 0x03cc), 7, 0, (uint32_t)0x00);
  }
#endif
