/* =============================================================================
 *   Copyright (c) Texas Instruments Incorporated 2014
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *  \file      pmhal/tda2xx/hw_pmhal_clocktree_data.h
 *
 *  \brief     This file contains macros and data-structures pertaining to
 *              StarterWare PRCM (internal) clocktree implementation.
 *
 *  \warning   This file is auto generated. So avoid manual changes.
 *              If manual changes are required the implications of the
 *              change in this and other auto generated files has to be
 *              completely understood.
 */

#ifndef HW_PMHAL_CLOCKTREE_DATA_H_
#define HW_PMHAL_CLOCKTREE_DATA_H_

/* ========================================================================== */
/*                                Include Files                               */
/* ========================================================================== */

#include "pmhal_clocktree.h"
#include "pmhal_prcm.h"

/* ========================================================================== */
/*                             Macros and Typedefs                            */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                            Structures and Enums                            */
/* ========================================================================== */

/**
 * \brief Clock-tree Edge Availble Clock Nodes
 */
typedef enum pmhalEdgeNodes
{
    PMHAL_EDGE_LOWER_BOUND = (-(int32_t)1),
    /**< Lower bound Place Holder(inclusive) */
    PMHAL_EDGE_DPLL_APLL_PCIE,
    /**< PM HAL Dpll Element APLL PCIE */
    PMHAL_EDGE_DPLL_ABE,
    /**< PM HAL Dpll Element ABE */
    PMHAL_EDGE_DPLL_CORE,
    /**< PM HAL Dpll Element CORE */
    PMHAL_EDGE_DPLL_DDR,
    /**< PM HAL Dpll Element DDR */
    PMHAL_EDGE_DPLL_GMAC,
    /**< PM HAL Dpll Element GMAC */
    PMHAL_EDGE_DPLL_GPU,
    /**< PM HAL Dpll Element GPU */
    PMHAL_EDGE_DPLL_IVA,
    /**< PM HAL Dpll Element IVA */
    PMHAL_EDGE_DPLL_PCIE_REF,
    /**< PM HAL Dpll Element PCIE REF */
    PMHAL_EDGE_DPLL_PER,
    /**< PM HAL Dpll Element PER */
    PMHAL_EDGE_DPLL_USB,
    /**< PM HAL Dpll Element USB */
    PMHAL_EDGE_DPLL_DSP,
    /**< PM HAL Dpll Element DSP */
    PMHAL_EDGE_DPLL_EVE,
    /**< PM HAL Dpll Element EVE */
    PMHAL_EDGE_DPLL_MPU,
    /**< PM HAL Dpll Element EVE */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ATL
    PMHAL_EDGE_MOD_ATL,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ATL */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_CORE
    PMHAL_EDGE_MOD_SMARTREFLEX_CORE,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_CORE */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_DSPEVE
    PMHAL_EDGE_MOD_SMARTREFLEX_DSPEVE,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_DSPEVE */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_GPU
    PMHAL_EDGE_MOD_SMARTREFLEX_GPU,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_GPU */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_IVAHD
    PMHAL_EDGE_MOD_SMARTREFLEX_IVAHD,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_IVAHD */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_MPU
    PMHAL_EDGE_MOD_SMARTREFLEX_MPU,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_MPU */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EFUSE_CTRL_CUST
    PMHAL_EDGE_MOD_EFUSE_CTRL_CUST,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EFUSE_CTRL_CUST */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DMA_SYSTEM
    PMHAL_EDGE_MOD_DMA_SYSTEM,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DMA_SYSTEM */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_BB2D
    PMHAL_EDGE_MOD_BB2D,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_BB2D */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DSS
    PMHAL_EDGE_MOD_DSS,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DSS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SDVENC
    PMHAL_EDGE_MOD_SDVENC,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SDVENC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EMIF1
    PMHAL_EDGE_MOD_EMIF1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EMIF1 */
#if defined (SOC_TDA2XX) || defined (SOC_AM572x) || defined (SOC_DRA75x)
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EMIF2
    PMHAL_EDGE_MOD_EMIF2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EMIF2 */
#endif
#ifdef BUILDCFG_PMHAL_PRCM_MOD_EMIF_OCP_FW
    PMHAL_EDGE_MOD_EMIF_OCP_FW,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_EMIF_OCP_FW */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_CPGMAC
    PMHAL_EDGE_MOD_CPGMAC,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_CPGMAC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPU
    PMHAL_EDGE_MOD_GPU,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPU */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C5
    PMHAL_EDGE_MOD_I2C5,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP1
    PMHAL_EDGE_MOD_MCASP1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER5
    PMHAL_EDGE_MOD_TIMER5,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER6
    PMHAL_EDGE_MOD_TIMER6,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER6 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER7
    PMHAL_EDGE_MOD_TIMER7,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER7 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER8
    PMHAL_EDGE_MOD_TIMER8,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER8 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART6
    PMHAL_EDGE_MOD_UART6,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART6 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_IEEE1500_2_OCP
    PMHAL_EDGE_MOD_IEEE1500_2_OCP,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_IEEE1500_2_OCP */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC1
    PMHAL_EDGE_MOD_MMC1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC2
    PMHAL_EDGE_MOD_MMC2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MLB_SS
    PMHAL_EDGE_MOD_MLB_SS,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MLB_SS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SATA
    PMHAL_EDGE_MOD_SATA,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SATA */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS1
    PMHAL_EDGE_MOD_USB_OTG_SS1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS2
    PMHAL_EDGE_MOD_USB_OTG_SS2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS3
    PMHAL_EDGE_MOD_USB_OTG_SS3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS3 */
#if defined (SOC_TDA2XX) || defined (SOC_AM572x) || defined (SOC_DRA75x)
#ifdef BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS4
    PMHAL_EDGE_MOD_USB_OTG_SS4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS4 */
#endif
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L3_MAIN_2
    PMHAL_EDGE_MOD_L3_MAIN_2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L3_MAIN_2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_OCP_WP_NOC
    PMHAL_EDGE_MOD_OCP_WP_NOC,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_OCP_WP_NOC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L3_MAIN_1
    PMHAL_EDGE_MOD_L3_MAIN_1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L3_MAIN_1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMU_EDMA
    PMHAL_EDGE_MOD_MMU_EDMA,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMU_EDMA */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMU_PCIESS
    PMHAL_EDGE_MOD_MMU_PCIESS,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMU_PCIESS */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM1
    PMHAL_EDGE_MOD_OCMC_RAM1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM1 */
#if defined (SOC_TDA2XX) || defined (SOC_AM572x) || defined (SOC_DRA75x)
#ifdef BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM2
    PMHAL_EDGE_MOD_OCMC_RAM2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM3
    PMHAL_EDGE_MOD_OCMC_RAM3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM3 */
#endif
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4_CFG
    PMHAL_EDGE_MOD_L4_CFG,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L4_CFG */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SAR_ROM
    PMHAL_EDGE_MOD_SAR_ROM,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SAR_ROM */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_SPINLOCK
    PMHAL_EDGE_MOD_SPINLOCK,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_SPINLOCK */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_IO_DELAY_BLOCK
    PMHAL_EDGE_MOD_IO_DELAY_BLOCK,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_IO_DELAY_BLOCK */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX1
    PMHAL_EDGE_MOD_MAILBOX1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX10
    PMHAL_EDGE_MOD_MAILBOX10,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX10 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX11
    PMHAL_EDGE_MOD_MAILBOX11,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX11 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX12
    PMHAL_EDGE_MOD_MAILBOX12,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX12 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX13
    PMHAL_EDGE_MOD_MAILBOX13,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX13 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX2
    PMHAL_EDGE_MOD_MAILBOX2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX3
    PMHAL_EDGE_MOD_MAILBOX3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX4
    PMHAL_EDGE_MOD_MAILBOX4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX5
    PMHAL_EDGE_MOD_MAILBOX5,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX6
    PMHAL_EDGE_MOD_MAILBOX6,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX6 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX7
    PMHAL_EDGE_MOD_MAILBOX7,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX7 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX8
    PMHAL_EDGE_MOD_MAILBOX8,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX8 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MAILBOX9
    PMHAL_EDGE_MOD_MAILBOX9,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MAILBOX9 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C1
    PMHAL_EDGE_MOD_I2C1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C2
    PMHAL_EDGE_MOD_I2C2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C3
    PMHAL_EDGE_MOD_I2C3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C4
    PMHAL_EDGE_MOD_I2C4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4_PER1
    PMHAL_EDGE_MOD_L4_PER1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L4_PER1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER10
    PMHAL_EDGE_MOD_TIMER10,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER10 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER11
    PMHAL_EDGE_MOD_TIMER11,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER11 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER2
    PMHAL_EDGE_MOD_TIMER2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER3
    PMHAL_EDGE_MOD_TIMER3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER4
    PMHAL_EDGE_MOD_TIMER4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER9
    PMHAL_EDGE_MOD_TIMER9,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER9 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ELM
    PMHAL_EDGE_MOD_ELM,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ELM */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_HDQ1W
    PMHAL_EDGE_MOD_HDQ1W,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_HDQ1W */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCSPI1
    PMHAL_EDGE_MOD_MCSPI1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCSPI1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCSPI2
    PMHAL_EDGE_MOD_MCSPI2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCSPI2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCSPI3
    PMHAL_EDGE_MOD_MCSPI3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCSPI3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCSPI4
    PMHAL_EDGE_MOD_MCSPI4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCSPI4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART1
    PMHAL_EDGE_MOD_UART1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART2
    PMHAL_EDGE_MOD_UART2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART3
    PMHAL_EDGE_MOD_UART3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART4
    PMHAL_EDGE_MOD_UART4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART5
    PMHAL_EDGE_MOD_UART5,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO2
    PMHAL_EDGE_MOD_GPIO2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO3
    PMHAL_EDGE_MOD_GPIO3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO4
    PMHAL_EDGE_MOD_GPIO4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO5
    PMHAL_EDGE_MOD_GPIO5,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO6
    PMHAL_EDGE_MOD_GPIO6,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO6 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO7
    PMHAL_EDGE_MOD_GPIO7,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO7 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO8
    PMHAL_EDGE_MOD_GPIO8,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO8 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC3
    PMHAL_EDGE_MOD_MMC3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MMC4
    PMHAL_EDGE_MOD_MMC4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MMC4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DCAN2
    PMHAL_EDGE_MOD_DCAN2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DCAN2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4_PER2
    PMHAL_EDGE_MOD_L4_PER2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L4_PER2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART7
    PMHAL_EDGE_MOD_UART7,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART7 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART8
    PMHAL_EDGE_MOD_UART8,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART8 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART9
    PMHAL_EDGE_MOD_UART9,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART9 */
#if defined (SOC_TDA2XX) || defined (SOC_AM572x) || defined (SOC_DRA75x)
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PRUSS1
    PMHAL_EDGE_MOD_PRUSS1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PRUSS1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PRUSS2
    PMHAL_EDGE_MOD_PRUSS2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PRUSS2 */
#endif
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP2
    PMHAL_EDGE_MOD_MCASP2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP3
    PMHAL_EDGE_MOD_MCASP3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP4
    PMHAL_EDGE_MOD_MCASP4,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP4 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP5
    PMHAL_EDGE_MOD_MCASP5,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP5 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP6
    PMHAL_EDGE_MOD_MCASP6,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP6 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP7
    PMHAL_EDGE_MOD_MCASP7,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP7 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_MCASP8
    PMHAL_EDGE_MOD_MCASP8,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_MCASP8 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PWMSS1
    PMHAL_EDGE_MOD_PWMSS1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PWMSS1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PWMSS2
    PMHAL_EDGE_MOD_PWMSS2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PWMSS2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PWMSS3
    PMHAL_EDGE_MOD_PWMSS3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PWMSS3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_QSPI
    PMHAL_EDGE_MOD_QSPI,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_QSPI */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_L4_PER3
    PMHAL_EDGE_MOD_L4_PER3,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_L4_PER3 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER13
    PMHAL_EDGE_MOD_TIMER13,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER13 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER14
    PMHAL_EDGE_MOD_TIMER14,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER14 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER15
    PMHAL_EDGE_MOD_TIMER15,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER15 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER16
    PMHAL_EDGE_MOD_TIMER16,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER16 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DES3DES
    PMHAL_EDGE_MOD_DES3DES,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DES3DES */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DMA_CRYPTO
    PMHAL_EDGE_MOD_DMA_CRYPTO,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DMA_CRYPTO */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_FPKA
    PMHAL_EDGE_MOD_FPKA,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_FPKA */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_RNG
    PMHAL_EDGE_MOD_RNG,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_RNG */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PCIESS1
    PMHAL_EDGE_MOD_PCIESS1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PCIESS1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_PCIESS2
    PMHAL_EDGE_MOD_PCIESS2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_PCIESS2 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_RTCSS
    PMHAL_EDGE_MOD_RTCSS,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_RTCSS */
#if defined (SOC_TDA2EX) || defined (SOC_AM571x)
#ifdef BUILDCFG_PMHAL_PRCM_MOD_LVDSRX
    PMHAL_EDGE_MOD_LVDSRX,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_LVDSRX */
#endif
#ifdef BUILDCFG_PMHAL_PRCM_MOD_ADC
    PMHAL_EDGE_MOD_ADC,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_ADC */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_COUNTER_32K
    PMHAL_EDGE_MOD_COUNTER_32K,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_COUNTER_32K */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_DCAN1
    PMHAL_EDGE_MOD_DCAN1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_DCAN1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_GPIO1
    PMHAL_EDGE_MOD_GPIO1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_GPIO1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_KBD
    PMHAL_EDGE_MOD_KBD,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_KBD */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER1
    PMHAL_EDGE_MOD_TIMER1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_TIMER12
    PMHAL_EDGE_MOD_TIMER12,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_TIMER12 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_UART10
    PMHAL_EDGE_MOD_UART10,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_UART10 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_WD_TIMER1
    PMHAL_EDGE_MOD_WD_TIMER1,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_WD_TIMER1 */
#ifdef BUILDCFG_PMHAL_PRCM_MOD_WD_TIMER2
    PMHAL_EDGE_MOD_WD_TIMER2,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_WD_TIMER2 */
#if defined (SOC_TDA2EX) || defined (SOC_AM571x)
#ifdef BUILDCFG_PMHAL_PRCM_MOD_I2C6
    PMHAL_EDGE_MOD_I2C6,
#endif /* BUILDCFG_PMHAL_PRCM_MOD_I2C6 */
#endif
    PMHAL_EDGE_MOD_COUNT,
    /**< Enum Upper bound placeholder */
    PMHAL_EDGE_UNDEF
    /**< Undefined value */
} pmhalEdgeNodes_t;

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/**< Device PM Clock tree graph  */
extern pmhalClockTree prcmGraph;

/* ========================================================================== */
/*                            Function Declarations                           */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
}
#endif

#endif /* HW_PMHAL_DATA_H_ */
