/**
 * Note: This file was auto-generated by TI PinMux on 10/9/2014 at 3:11:11 PM.
 *
 * \file  am43xx_gpevm_pinmux_data.c
 *
 * \brief  This file contains the pin mux configurations for the boards.
 *         These are prepared based on how the peripherals are extended on
 *         the boards.
 *
 * \copyright Copyright (CU) 2014 - 2018 Texas Instruments Incorporated -
 *             http://www.ti.com/
 */

/**
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "types.h"
#include "pinmux.h"
#include "am43xx_pinmux.h"

/** Peripheral Pin Configurations */
#ifndef BUILDCFG_MOD_UART
#define BUILDCFG_MOD_UART
#endif /* BUILDCFG_MOD_UART */

#ifndef BUILDCFG_MOD_USB
#define BUILDCFG_MOD_USB
#endif /* BUILDCFG_MOD_USB */

#ifndef BUILDCFG_MOD_PWMSS
#define BUILDCFG_MOD_PWMSS
#endif /* BUILDCFG_MOD_PWMSS */

#ifndef BUILDCFG_MOD_PRU_ICSS
#define BUILDCFG_MOD_PRU_ICSS
#endif /* BUILDCFG_MOD_PRU_ICSS */

#ifndef BUILDCFG_MOD_CPSW
#define BUILDCFG_MOD_CPSW
#endif /* BUILDCFG_MOD_CPSW */

#ifndef BUILDCFG_MOD_MCASP
#define BUILDCFG_MOD_MCASP
#endif /* BUILDCFG_MOD_MCASP */

#ifndef BUILDCFG_MOD_I2C
#define BUILDCFG_MOD_I2C
#endif /* BUILDCFG_MOD_I2C */

#ifndef BUILDCFG_MOD_MMCSD
#define BUILDCFG_MOD_MMCSD
#endif /* BUILDCFG_MOD_MMCSD */

#ifndef BUILDCFG_MOD_QSPI
#define BUILDCFG_MOD_QSPI
#endif /* BUILDCFG_MOD_QSPI */

#ifndef BUILDCFG_MOD_VPFE
#define BUILDCFG_MOD_VPFE
#endif /* BUILDCFG_MOD_VPFE */

#ifndef BUILDCFG_MOD_MCSPI
#define BUILDCFG_MOD_MCSPI
#endif /* BUILDCFG_MOD_MCSPI */

#ifndef BUILDCFG_MOD_GPIO
#define BUILDCFG_MOD_GPIO
#endif /* BUILDCFG_MOD_GPIO */

#ifndef BUILDCFG_MOD_ADC
#define BUILDCFG_MOD_ADC
#endif /* BUILDCFG_MOD_ADC */

#if defined(BUILDCFG_MOD_UART)

static pinmuxPerCfg_t gUart0PinCfg[] =
{
	{
		/* My UART 0 -> uart0_rxd -> K25 */
		PIN_UART0_RXD, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My UART 0 -> uart0_txd -> J24 */
		PIN_UART0_TXD, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gUartPinCfg[] =
{
    {0, TRUE, gUart0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_UART) */

#if defined(BUILDCFG_MOD_USB)

static pinmuxPerCfg_t gUsb0PinCfg[] =
{
	{
		/* My USB 0 -> USB0_DRVVBUS -> G21 */
		PIN_USB0_DRVVBUS, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gUsb1PinCfg[] =
{
	{
		/* My USB 1 -> USB1_DRVVBUS -> F25 */
		PIN_USB1_DRVVBUS, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gUsbPinCfg[] =
{
    {0, TRUE, gUsb0PinCfg},
    {1, TRUE, gUsb1PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_USB) */


#if defined(BUILDCFG_MOD_PWMSS)

static pinmuxPerCfg_t gPwmss3PinCfg[] =
{
	{
		/* My eHRPWM 3 -> ehrpwm3A -> AE19 */
		PIN_CAM0_DATA4, (uint16_t)PINMUX_SS_PWMSS_EHRPWM3, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eHRPWM 3 -> ehrpwm3_tripzone_input -> N25 */
		PIN_SPI4_CS0, (uint16_t)PINMUX_SS_PWMSS_EHRPWM3, \
		( \
			PIN_MODE(6) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eHRPWM 3 -> ehrpwm3_synci -> R24 */
		PIN_SPI4_D0, (uint16_t)PINMUX_SS_PWMSS_EHRPWM3, \
		( \
			PIN_MODE(6) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eHRPWM 3 -> ehrpwm3_synco -> AB18 */
		PIN_CAM0_DATA1, (uint16_t)PINMUX_SS_PWMSS_EHRPWM3, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gPwmss4PinCfg[] =
{
	{
		/* My eHRPWM 4 -> ehrpwm4A -> H25 */
		PIN_UART3_RXD, (uint16_t)PINMUX_SS_PWMSS_EHRPWM4, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eHRPWM 4 -> ehrpwm4_tripzone_input -> N20 */
		PIN_SPI2_SCLK, (uint16_t)PINMUX_SS_PWMSS_EHRPWM4, \
		( \
			PIN_MODE(6) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gPwmss5PinCfg[] =
{
	{
		/* My eHRPWM 5 -> ehrpwm5A -> H22 */
		PIN_UART3_CTSN, (uint16_t)PINMUX_SS_PWMSS_EHRPWM5, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eHRPWM 5 -> ehrpwm5_tripzone_input -> P22 */
		PIN_SPI2_D0, (uint16_t)PINMUX_SS_PWMSS_EHRPWM5, \
		( \
			PIN_MODE(6) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gPwmss0PinCfg[] =
{
	{
		/* My eHRPWM 0 -> ehrpwm0_tripzone_input -> P24 */
		PIN_SPI4_D1, (uint16_t)PINMUX_SS_PWMSS_EHRPWM0, \
		( \
			PIN_MODE(6) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gPwmss2PinCfg[] =
{
	{
		/* My eQEP 2 -> eQEP2A_in -> E11 */
		PIN_GPMC_AD12, (uint16_t)PINMUX_SS_PWMSS_EQEP2, \
		( \
			PIN_MODE(4) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eQEP 2 -> eQEP2B_in -> C11 */
		PIN_GPMC_AD13, (uint16_t)PINMUX_SS_PWMSS_EQEP2, \
		( \
			PIN_MODE(4) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eQEP 2 -> eQEP2_index -> B11 */
		PIN_GPMC_AD14, (uint16_t)PINMUX_SS_PWMSS_EQEP2, \
		( \
			PIN_MODE(4) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My eQEP 2 -> eQEP2_strobe -> A11 */
		PIN_GPMC_AD15, (uint16_t)PINMUX_SS_PWMSS_EQEP2, \
		( \
			PIN_MODE(4) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gPwmssPinCfg[] =
{
    {3, TRUE, gPwmss3PinCfg},
    {4, TRUE, gPwmss4PinCfg},
    {5, TRUE, gPwmss5PinCfg},
    {0, TRUE, gPwmss0PinCfg},
    {2, TRUE, gPwmss2PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_PWMSS) */

#if defined(BUILDCFG_MOD_PRU_ICSS)

static pinmuxPerCfg_t gPru_icss1PinCfg[] =
{
	{
		/* My MDIO_PRUSS1 1 -> pr1_mdio_mdclk -> A12 */
		PIN_GPMC_CLK, (uint16_t)PINMUX_SS_PRU_ICSS_MDIO, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MDIO_PRUSS1 1 -> pr1_mdio_data -> D24 */
		PIN_XDMA_EVENT_INTR0, (uint16_t)PINMUX_SS_PRU_ICSS_MDIO, \
		( \
			PIN_MODE(8) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS1 2 -> pr1_pru0_gpo[6] -> C20 */
		PIN_DSS_DATA6, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edc_sync0_out -> L25 */
		PIN_UART0_CTSN, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edc_sync1_out -> J25 */
		PIN_UART0_RTSN, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edc_latch0_in -> AE22 */
		PIN_CAM1_DATA3, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(6) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edc_latch1_in -> AD22 */
		PIN_CAM1_DATA4, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(6) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out0 -> T21 */
		PIN_SPI0_D1, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out1 -> T20 */
		PIN_SPI0_CS0, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(6) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
		{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out6 -> B9 */
		PIN_GPMC_CSN1, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(4) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out7 -> F10 */
		PIN_GPMC_CSN2, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(4) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii_mt1_clk -> E8 */
		PIN_GPMC_A6, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_txd0 -> E7 */
		PIN_GPMC_A5, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_txd1 -> D7 */
		PIN_GPMC_A4, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_txd2 -> A4 */
		PIN_GPMC_A3, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_txd3 -> C6 */
		PIN_GPMC_A2, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_rxd0 -> D8 */
		PIN_GPMC_A11, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_rxd1 -> G8 */
		PIN_GPMC_A10, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_rxd2 -> B4 */
		PIN_GPMC_A9, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_rxd3 -> F7 */
		PIN_GPMC_A8, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_txen -> C3 */
		PIN_GPMC_A0, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii_mr1_clk -> F6 */
		PIN_GPMC_A7, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_rxdv -> C5 */
		PIN_GPMC_A1, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_rxer -> B3 */
		PIN_GPMC_WPN, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_rxlink -> E24 */
		PIN_GPIO5_13, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_crs -> F23 */
		PIN_GPIO5_11, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 1 -> pr1_mii1_col -> F24 */
		PIN_GPIO5_9, (uint16_t)PINMUX_SS_PRU_ICSS_MII1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii_mt0_clk -> B22 */
		PIN_DSS_DATA0, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(2) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_txd0 -> B20 */
		PIN_DSS_DATA5, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_txd1 -> A20 */
		PIN_DSS_DATA4, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_txd2 -> C21 */
		PIN_DSS_DATA3, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_txd3 -> B21 */
		PIN_DSS_DATA2, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_rxd0 -> B18 */
		PIN_DSS_DATA11, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_rxd1 -> A18 */
		PIN_DSS_DATA10, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_rxd2 -> B19 */
		PIN_DSS_DATA9, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_rxd3 -> A19 */
		PIN_DSS_DATA8, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_txen -> A21 */
		PIN_DSS_DATA1, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii_mr0_clk -> C17 */
		PIN_DSS_DATA14, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_rxdv -> D17 */
		PIN_DSS_DATA15, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_rxer -> D19 */
		PIN_DSS_DATA13, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_rxlink -> C19 */
		PIN_DSS_DATA12, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_crs -> G20 */
		PIN_GPIO5_10, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MII_PRUSS1 0 -> pr1_mii0_col -> D25 */
		PIN_GPIO5_8, (uint16_t)PINMUX_SS_PRU_ICSS_MII0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
		{
		/* My PRU_PRUSS0 1 -> pr0_pru0_gpo[8] -> B1 */
		PIN_MMC0_DAT3, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru0_gpi[9] -> B2 */
		PIN_MMC0_DAT2, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(6) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru0_gpi[10] -> C2 */
		PIN_MMC0_DAT1, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(6) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru0_gpi[11] -> C1 */
		PIN_MMC0_DAT0, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(6) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out2 -> B23 */
		PIN_DSS_VSYNC, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(4) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out4 -> A22 */
		PIN_DSS_PCLK, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(4) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
		{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out3 -> A23 */
		PIN_DSS_HSYNC, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(4) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My ECAT_PRUSS1 1 -> pr1_edio_data_out5 -> A24 */
		PIN_DSS_AC_BIAS_EN, (uint16_t)PINMUX_SS_PRU_ICSS_ECAT, \
		( \
			PIN_MODE(4) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gPru_icss0PinCfg[] =
{
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[0] -> N24 */
		PIN_MCASP0_ACLKX, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[1] -> N22 */
		PIN_MCASP0_FSX, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[2] -> H23 */
		PIN_MCASP0_AXR0, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[3] -> M24 */
		PIN_MCASP0_AHCLKR, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[4] -> L23 */
		PIN_MCASP0_ACLKR, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[5] -> K23 */
		PIN_MCASP0_FSR, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[6] -> M25 */
		PIN_MCASP0_AXR1, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 0 -> pr0_pru0_gpo[7] -> L24 */
		PIN_MCASP0_AHCLKX, (uint16_t)PINMUX_SS_PRU_ICSS_PRU0, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru1_gpi[13] -> AE23 */
		PIN_CAM1_DATA5, (uint16_t)PINMUX_SS_PRU_ICSS_PRU1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru1_gpi[15] -> AE24 */
		PIN_CAM1_DATA7, (uint16_t)PINMUX_SS_PRU_ICSS_PRU1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru1_gpi[16] -> AE18 */
		PIN_CAM0_DATA0, (uint16_t)PINMUX_SS_PRU_ICSS_PRU1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
		{
		/* My PRU_PRUSS0 1 -> pr0_pru1_gpo[6] -> B23 */
		PIN_DSS_VSYNC, (uint16_t)PINMUX_SS_PRU_ICSS_PRU1, \
		( \
			PIN_MODE(5) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru1_gpo[1] -> AD25 */
		PIN_CAM1_HD, (uint16_t)PINMUX_SS_PRU_ICSS_PRU1, \
		( \
			PIN_MODE(3) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru1_gpi[3] -> AE21 */
		PIN_CAM1_PCLK, (uint16_t)PINMUX_SS_PRU_ICSS_PRU1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My PRU_PRUSS0 1 -> pr0_pru1_gpi[11] -> AE22 */
		PIN_CAM1_DATA3, (uint16_t)PINMUX_SS_PRU_ICSS_PRU1, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gPru_icssPinCfg[] =
{
    {1, TRUE, gPru_icss1PinCfg},
    {0, TRUE, gPru_icss0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_PRU_ICSS) */

#if defined(BUILDCFG_MOD_CPSW)

static pinmuxPerCfg_t gCpsw0PinCfg[] =
{
	{
		/* My RGMII 1 -> rgmii1_tctl -> A13 */
		PIN_MII1_TX_EN, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_rctl -> A15 */
		PIN_MII1_RX_DV, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_tclk -> D14 */
		PIN_MII1_TX_CLK, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_rclk -> D13 */
		PIN_MII1_RX_CLK, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_td0 -> B15 */
		PIN_MII1_TXD0, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_td1 -> A14 */
		PIN_MII1_TXD1, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_td2 -> C13 */
		PIN_MII1_TXD2, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_td3 -> C16 */
		PIN_MII1_TXD3, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_rd0 -> F17 */
		PIN_MII1_RXD0, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_rd1 -> B16 */
		PIN_MII1_RXD1, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_rd2 -> E16 */
		PIN_MII1_RXD2, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My RGMII 1 -> rgmii1_rd3 -> C14 */
		PIN_MII1_RXD3, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MDIO 1 -> mdio_clk -> B17 */
		PIN_MDIO_CLK, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MDIO 1 -> mdio_data -> A17 */
		PIN_MDIO_DATA, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gCpswPinCfg[] =
{
    {0, TRUE, gCpsw0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_CPSW) */

#if defined(BUILDCFG_MOD_MCASP)

static pinmuxPerCfg_t gMcasp0PinCfg[] =
{
	{
		/* My MCASP 0 -> mcasp0_ahclkx -> L24 */
		PIN_MCASP0_AHCLKX, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MCASP 0 -> mcasp0_ahclkr -> M24 */
		PIN_MCASP0_AHCLKR, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MCASP 0 -> mcasp0_aclkx -> N24 */
		PIN_MCASP0_ACLKX, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MCASP 0 -> mcasp0_fsx -> N22 */
		PIN_MCASP0_FSX, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MCASP 0 -> mcasp0_fsr -> K23 */
		PIN_MCASP0_FSR, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MCASP 0 -> mcasp0_axr0 -> H23 */
		PIN_MCASP0_AXR0, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MCASP 0 -> mcasp0_axr1 -> M25 */
		PIN_MCASP0_AXR1, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gMcaspPinCfg[] =
{
    {0, TRUE, gMcasp0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_MCASP) */

#if defined(BUILDCFG_MOD_I2C)
static pinmuxPerCfg_t gI2c0PinCfg[] =
{
	{
		/* I2C 0 -> I2C0_SCL -> Y22 */
		PIN_I2C0_SCL, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* I2C 0 -> I2C0_SDA -> AB24 */
		PIN_I2C0_SDA, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gI2c2PinCfg[] =
{
	{
		/* My I2C 2 -> I2C2_SCL -> AC21 */
		PIN_CAM1_DATA1, 0, \
		( \
			PIN_MODE(3) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My I2C 2 -> I2C2_SDA -> AB20 */
		PIN_CAM1_DATA0, 0, \
		( \
			PIN_MODE(3) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gI2cPinCfg[] =
{
    {0, TRUE, gI2c0PinCfg},
    {2, TRUE, gI2c2PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_I2C) */

#if defined(BUILDCFG_MOD_MMCSD)

static pinmuxPerCfg_t gMmcsd0PinCfg[] =
{
	{
		/* My MMC 0 -> mmc0_clk -> D1 */
		PIN_MMC0_CLK, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MMC 0 -> mmc0_cmd -> D2 */
		PIN_MMC0_CMD, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MMC 0 -> mmc0_dat0 -> C1 */
		PIN_MMC0_DAT0, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MMC 0 -> mmc0_dat1 -> C2 */
		PIN_MMC0_DAT1, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MMC 0 -> mmc0_dat2 -> B2 */
		PIN_MMC0_DAT2, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MMC 0 -> mmc0_dat3 -> B1 */
		PIN_MMC0_DAT3, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MMC 0 -> mmc0_sdcd -> R25 */
		PIN_SPI0_CS1, 0, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My MMC 0 -> mmc0_pow -> A16 */
		PIN_RMII1_REF_CLK, 0, \
		( \
			PIN_MODE(5) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gMmcsdPinCfg[] =
{
    {0, TRUE, gMmcsd0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_MMCSD) */

#if defined(BUILDCFG_MOD_QSPI)

static pinmuxPerCfg_t gQspi0PinCfg[] =
{
	{
		/* My QSPI 1 -> qspi_clk -> B12 */
		PIN_GPMC_CSN3, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My QSPI 1 -> qspi_csn -> A8 */
		PIN_GPMC_CSN0, 0, \
		( \
			PIN_MODE(3) | \
			((PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My QSPI 1 -> qspi_d0 -> A9 */
		PIN_GPMC_ADVN_ALE, 0, \
		( \
			PIN_MODE(3) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My QSPI 1 -> qspi_d1 -> E10 */
		PIN_GPMC_OEN_REN, 0, \
		( \
			PIN_MODE(3) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My QSPI 1 -> qspi_d2 -> D10 */
		PIN_GPMC_WEN, 0, \
		( \
			PIN_MODE(3) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My QSPI 1 -> qspi_d3 -> C10 */
		PIN_GPMC_BE0N_CLE, 0, \
		( \
			PIN_MODE(3) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gQspiPinCfg[] =
{
    {0, TRUE, gQspi0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_QSPI) */

#if defined(BUILDCFG_MOD_VPFE)

static pinmuxPerCfg_t gVpfe0PinCfg[] =
{
	{
		/* My CAM 0 -> cam0_hd -> AE17 */
		PIN_CAM0_HD, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_vd -> AD18 */
		PIN_CAM0_VD, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_pclk -> AC20 */
		PIN_CAM0_PCLK, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data0 -> AE18 */
		PIN_CAM0_DATA0, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data1 -> AB18 */
		PIN_CAM0_DATA1, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data2 -> Y18 */
		PIN_CAM0_DATA2, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data3 -> AA18 */
		PIN_CAM0_DATA3, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data4 -> AE19 */
		PIN_CAM0_DATA4, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data5 -> AD19 */
		PIN_CAM0_DATA5, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data6 -> AE20 */
		PIN_CAM0_DATA6, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data7 -> AD20 */
		PIN_CAM0_DATA7, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data8 -> AB19 */
		PIN_CAM0_DATA8, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam0_data9 -> AA19 */
		PIN_CAM0_DATA9, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gVpfe1PinCfg[] =
{
	{
		/* My CAM 0 -> cam1_hd -> AD25 */
		PIN_CAM1_HD, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_vd -> AC23 */
		PIN_CAM1_VD, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_pclk -> AE21 */
		PIN_CAM1_PCLK, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data0 -> AB20 */
		PIN_CAM1_DATA0, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data1 -> AC21 */
		PIN_CAM1_DATA1, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data2 -> AD21 */
		PIN_CAM1_DATA2, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data3 -> AE22 */
		PIN_CAM1_DATA3, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data4 -> AD22 */
		PIN_CAM1_DATA4, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data5 -> AE23 */
		PIN_CAM1_DATA5, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data6 -> AD23 */
		PIN_CAM1_DATA6, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data7 -> AE24 */
		PIN_CAM1_DATA7, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data8 -> AD24 */
		PIN_CAM1_DATA8, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My CAM 0 -> cam1_data9 -> AC24 */
		PIN_CAM1_DATA9, 0, \
		( \
			PIN_MODE(0) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gVpfePinCfg[] =
{
    {0, TRUE, gVpfe0PinCfg},
    {1, TRUE, gVpfe1PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};
#endif/* if defined(BUILDCFG_MOD_VPFE) */

#if defined(BUILDCFG_MOD_GPIO)

static pinmuxPerCfg_t gGpio0PinCfg[] =
{
	{
		/* My GPIO 0 -> gpio0[12] -> K22 */
		PIN_UART1_CTSN, 12, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 0 -> gpio0[13] -> L22 */
		PIN_UART1_RTSN, 13, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 0 -> gpio0[14] -> K21 */
		PIN_UART1_RXD, 14, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 0 -> gpio0[15] -> L21 */
		PIN_UART1_TXD, 15, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 0 -> gpio0[26] -> F11 */
		PIN_GPMC_AD10, 26, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 0 -> gpio0[30] -> A2 */
		PIN_GPMC_WAIT0, 30, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gGpio5PinCfg[] =
{
	{
		/* My GPIO 5 -> gpio5[1] -> K24 */
		PIN_UART3_RTSN, 1, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 5 -> gpio5[3] -> H24 */
		PIN_UART3_TXD, 3, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 5 -> gpio5[12] -> E25 */
		PIN_GPIO5_12, 12, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gGpio4PinCfg[] =
{
	{
		/* My GPIO 4 -> gpio4[8] -> AD24 */
		PIN_CAM1_DATA8, 8, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 4 -> gpio4[10] -> AC23 */
		PIN_CAM1_VD, 10, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 4 -> gpio4[11] -> AE21 */
		PIN_CAM1_PCLK, 11, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 4 -> gpio4[13] -> AB25 */
		PIN_CAM1_WEN, 13, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 4 -> gpio4[16] -> AD21 */
		PIN_CAM1_DATA2, 16, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 4 -> gpio4[20] -> AD23 */
		PIN_CAM1_DATA6, 20, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 4 -> gpio4[27] -> AD19 */
		PIN_CAM0_DATA5, 27, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 4 -> gpio4[9] -> AD25 */
		PIN_CAM1_HD, 9, \
		( \
			PIN_MODE(7) | \
			((PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_PULL_UP_EN & ~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gGpio2PinCfg[] =
{
	{
		/* My GPIO 2 -> gpio2[22] -> B23 */
		PIN_DSS_VSYNC, 22, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 2 -> gpio2[23] -> A23 */
		PIN_DSS_HSYNC, 23, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 2 -> gpio2[24] -> A22 */
		PIN_DSS_PCLK, 24, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My GPIO 2 -> gpio2[25] -> A24 */
		PIN_DSS_AC_BIAS_EN, 25, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gGpio3PinCfg[] =
{
	{
		/* My GPIO 3 -> gpio3[1] -> B14 */
		PIN_MII1_CRS, 1, \
		( \
			PIN_MODE(7) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gGpioPinCfg[] =
{
    {0, TRUE, gGpio0PinCfg},
    {5, TRUE, gGpio5PinCfg},
    {4, TRUE, gGpio4PinCfg},
    {2, TRUE, gGpio2PinCfg},
    {3, TRUE, gGpio3PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_GPIO) */

#if defined(BUILDCFG_MOD_MCSPI)

static pinmuxPerCfg_t gMcspi1PinCfg[] =
{
	{
		/* My SPI 1 -> spi1_sclk -> D16 */
		PIN_MII1_COL, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My SPI 1 -> spi1_d1 -> B13 */
		PIN_MII1_RX_ER, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{
		/* My SPI 1 -> spi1_cs0 -> A16 */
		PIN_RMII1_REF_CLK, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_RX_ACTIVE & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxPerCfg_t gMcspi0PinCfg[] =
{
    {
       /* SPI0 -> spi0_sclk -> P23 */
       PIN_SPI0_SCLK, 0, \
       ( \
           PIN_MODE(0) | \
           ((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
           (~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
       ) \
    },
    {
       /* SPI0 -> spi0_d0 -> T22 */
       PIN_SPI0_D0, 0, \
       ( \
           PIN_MODE(0) | \
           ((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
           (~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
       ) \
    },
    {
       /* SPI0 -> spi0_d1 -> T21 */
       PIN_SPI0_D1, 0, \
       ( \
           PIN_MODE(0) | \
           ((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
           (~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
       ) \
    },
    {
       /* SPI0 -> spi0_cs0 -> T20 */
       PIN_SPI0_CS0, 0, \
       ( \
           PIN_MODE(0) | \
           ((PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
           (~PIN_PULL_UD_DIS & ~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
       ) \
    },
    {PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gMcspiPinCfg[] =
{
    {1, TRUE, gMcspi1PinCfg},
    {0, TRUE, gMcspi0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};
#endif /* if defined(BUILDCFG_MOD_SPI) */
#if defined(BUILDCFG_MOD_ADC)

static pinmuxPerCfg_t gAdc0PinCfg[] =
{
	{
		/* My ADC 7 -> ext_hw_trigger -> AC25 */
		PIN_CAM1_FIELD, 0, \
		( \
			PIN_MODE(2) | \
			((PIN_PULL_UD_DIS | PIN_PULL_UP_EN | PIN_RX_ACTIVE | PIN_DS_VALUE_OVERRIDE_EN | PIN_DS_OP_DIS | PIN_DS_PULL_UP_EN) & \
			(~PIN_DS_OP_VAL_1 & ~PIN_DS_PULL_UD_EN & ~PIN_WAKE_UP_EN))
		) \
	},
	{PINMUX_INVALID_PIN}
};

static pinmuxModuleCfg_t gAdcPinCfg[] =
{
    {0, TRUE, gAdc0PinCfg},
    {CHIPDB_INVALID_INSTANCE_NUM}
};

#endif /* if defined(BUILDCFG_MOD_ADC) */

/** EVM pin configurations for EVM */

pinmuxBoardCfg_t gIdkevmPinmuxData[] =
{
#if defined(BUILDCFG_MOD_UART)
	{CHIPDB_MOD_ID_UART, gUartPinCfg},
#endif /* if defined(BUILDCFG_MOD_UART) */
#if defined(BUILDCFG_MOD_USB)
	{CHIPDB_MOD_ID_USB, gUsbPinCfg},
#endif /* if defined(BUILDCFG_MOD_USB) */
#if defined(BUILDCFG_MOD_PWMSS)
	{CHIPDB_MOD_ID_PWMSS, gPwmssPinCfg},
#endif /* if defined(BUILDCFG_MOD_PWMSS) */
#if defined(BUILDCFG_MOD_PRU_ICSS)
	{CHIPDB_MOD_ID_PRU_ICSS, gPru_icssPinCfg},
#endif /* if defined(BUILDCFG_MOD_PRU_ICSS) */
#if defined(BUILDCFG_MOD_CPSW)
	{CHIPDB_MOD_ID_CPSW, gCpswPinCfg},
#endif /* if defined(BUILDCFG_MOD_CPSW) */
#if defined(BUILDCFG_MOD_MCASP)
	{CHIPDB_MOD_ID_MCASP, gMcaspPinCfg},
#endif /* if defined(BUILDCFG_MOD_MCASP) */
#if defined(BUILDCFG_MOD_I2C)
	{CHIPDB_MOD_ID_I2C, gI2cPinCfg},
#endif /* if defined(BUILDCFG_MOD_I2C) */
#if defined(BUILDCFG_MOD_MMCSD)
	{CHIPDB_MOD_ID_MMCSD, gMmcsdPinCfg},
#endif /* if defined(BUILDCFG_MOD_MMCSD) */
#if defined(BUILDCFG_MOD_QSPI)
	{CHIPDB_MOD_ID_QSPI, gQspiPinCfg},
#endif /* if defined(BUILDCFG_MOD_QSPI) */
#if defined(BUILDCFG_MOD_VPFE)
	{CHIPDB_MOD_ID_VPFE, gVpfePinCfg},
#endif /* if defined(BUILDCFG_MOD_VPFE) */
#if defined(BUILDCFG_MOD_MCSPI)
	{CHIPDB_MOD_ID_MCSPI, gMcspiPinCfg},
#endif /* if defined(BUILDCFG_MOD_SPI) */
#if defined(BUILDCFG_MOD_GPIO)
	{CHIPDB_MOD_ID_GPIO, gGpioPinCfg},
#endif /* if defined(BUILDCFG_MOD_GPIO) */
#if defined(BUILDCFG_MOD_ADC)
	{CHIPDB_MOD_ID_ADC0, gAdcPinCfg},
#endif /* if defined(BUILDCFG_MOD_ADC) */
    {CHIPDB_MOD_ID_INVALID}
};
