/**
 * Note: This file was auto-generated by TI PinMux on 6/14/2017 at 6:14:30 PM.
 *
 * \file  boardPadDelayInit.c
 *
 * \brief   This file contain manual/vritual iodelay mode definitions
 *
 * \copyright Copyright (CU) 2015-2018 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

/**
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdint.h>
#include "boardPadDelay.h"
#include "boardPadDelayTune.h"


#if defined(_TMS320C6X) || defined(__TI_ARM_V7M4__)
#ifndef __cplusplus
#pragma DATA_SECTION (pad, "BOARD_IO_DELAY_DATA");
#else
#pragma DATA_SECTION ("BOARD_IO_DELAY_DATA");
#endif
const boardPadDelayCfg_t pad[] = {
#else
const boardPadDelayCfg_t pad[] __attribute__((section("BOARD_IO_DELAY_DATA"))) = {
#endif
/** {PADCONF_REG_OFFSET, PADCONF_VALUE, {CFG_X_IN offset, aDelay, gDelay}, {CFG_X_OEN offset, aDelay, gDelay}, {CFG_X_OUT offset, aDelay, gDelay}} **/

/* HDMI1 - hdmi1_data2x on AG19 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_data2y on AH19 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_data1x on AG18 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_data1y on AH18 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_data0x on AG17 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_data0y on AH17 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_clockx on AG16 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_clocky on AH16 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI1 - hdmi1_cec on B20 - MyHDMI1 */
     {0x17BC, 0xD0006, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* HDMI1 - hdmi1_ddc_scl on C25 - MyHDMI1 */
     {0x1808, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* HDMI1 - hdmi1_ddc_sda on F17 - MyHDMI1 */
     {0x180C, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PCIE - ljcb_clkp on AG15 - MyPCIE1 */
     /* {NOT FOUND, 0x00000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - ljcb_clkn on AH15 - MyPCIE1 */
     /* {NOT FOUND, 0x00000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_rxn0 on AG13 - MyPCIE1 */
     /* {NOT FOUND, 0x00000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_rxp0 on AH13 - MyPCIE1 */
     /* {NOT FOUND, 0x00000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_txn0 on AG14 - MyPCIE1 */
     /* {NOT FOUND, 0x00000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_txp0 on AH14 - MyPCIE1 */
     /* {NOT FOUND, 0x00000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_rxn1 on AF12 - MyPCIE1 */
     /* {NOT FOUND, 0x00001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_rxp1 on AE12 - MyPCIE1 */
     /* {NOT FOUND, 0x00001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_txn1 on AC11 - MyPCIE1 */
     /* {NOT FOUND, 0x00001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PCIE - pcie_txp1 on AD11 - MyPCIE1 */
     /* {NOT FOUND, 0x00001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* UART2 - uart2_rxd on D28 - MyUART2 */
     {0x17F0, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART2 - uart2_txd on D26 - MyUART2 */
     {0x17F4, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART3 - uart3_rxd on D27 - MyUART3 */
     {0x17F8, 0x50002, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART3 - uart3_txd on C28 - MyUART3 */
     {0x17FC, 0x10001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* RTCSS - rtc_osc_xi_clkin32 on AE14 - MyRTCSS1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* RTCSS - rtc_osc_xo on AD14 - MyRTCSS1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* RTCSS - rtc_iso on AF14 - MyRTCSS1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* RTCSS - rtc_porz on AB17 - MyRTCSS1 */
     {0x182C, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* RTCSS - on_off on Y11 - MyRTCSS1 */
     {0x1828, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* RTCSS - Wakeup0 on AD17 - MyRTCSS1 */
     {0x1818, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* RTCSS - Wakeup3 on AC16 - MyRTCSS1 */
     {0x1824, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* eCAP1 - eCAP1_in_PWM1_out on D1 - MyeCAP1 */
     {0x1570, 0x1000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* ddr1 - ddr1_csn0 on AH23 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_cke on AG22 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ck on AG24 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_nck on AH24 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_odt0 on AE20 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_casn on AC18 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_rasn on AF20 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_wen on AH21 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_rst on AG21 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ba0 on AF17 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ba1 on AE18 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ba2 on AB18 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a0 on AD20 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a1 on AC19 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a2 on AC20 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a3 on AB19 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a4 on AF21 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a5 on AH22 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a6 on AG23 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a7 on AE21 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a8 on AF22 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a9 on AE22 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a10 on AD21 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a11 on AD22 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a12 on AC21 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a13 on AF18 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a14 on AE17 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_a15 on AD18 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d0 on AF25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d1 on AF26 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d2 on AG26 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d3 on AH26 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d4 on AF24 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d5 on AE24 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d6 on AF23 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d7 on AE23 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d8 on AC23 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d9 on AF27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d10 on AG27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d11 on AF28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d12 on AE26 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d13 on AC25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d14 on AC24 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d15 on AD25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d16 on V20 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d17 on W20 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d18 on AB28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d19 on AC28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d20 on AC27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d21 on Y19 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d22 on AB27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d23 on Y20 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d24 on AA23 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d25 on Y22 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d26 on Y23 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d27 on AA24 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d28 on Y24 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d29 on AA26 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d30 on AA25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_d31 on AA28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d0 on W22 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d1 on V23 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d2 on W19 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d3 on W23 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d4 on Y25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d5 on V24 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d6 on V25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_ecc_d7 on Y26 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqm0 on AD23 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqm1 on AB23 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqm2 on AC26 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqm3 on AA27 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqm_ecc on V26 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqs0 on AH25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqsn0 on AG25 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqs1 on AE27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqsn1 on AE28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqs2 on AD27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqsn2 on AD28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqs3 on Y28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqsn3 on Y27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqs_ecc on V27 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_dqsn_ecc on V28 - Myddr1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* ddr1 - ddr1_vref0 on Y18 - Myddr1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDQ - hdq0 on C23 - MyHDQ1 */
     {0x16A0, 0x50007, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C1 - i2c1_scl on C20 - MyI2C1 */
     {0x1804, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C1 - i2c1_sda on C21 - MyI2C1 */
     {0x1800, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRCM - rstoutn on F23 - MyPRCM1 */
     {0x1864, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRCM - resetn on E23 - MyPRCM1 */
     {0x185C, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRCM - porz on F22 - MyPRCM1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* PRUSS2_MDIO - pr2_mdio_data on D14 - MyPRUSS2_MDIO1 */
     {0x16A8, 0xD000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MDIO - pr2_mdio_mdclk on C14 - MyPRUSS2_MDIO1 */
     {0x16A4, 0x0000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii_mt0_clk on F12 - MyPRUSS2_MII1 */
     {0x16B8, 0xE000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_txen on B12 - MyPRUSS2_MII1 */
     {0x16D4, 0xA000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_txd3 on A11 - MyPRUSS2_MII1 */
     {0x16D8, 0xA000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_txd2 on B13 - MyPRUSS2_MII1 */
     {0x16DC, 0xA000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_txd1 on A12 - MyPRUSS2_MII1 */
     {0x16E0, 0xA000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_txd0 on E14 - MyPRUSS2_MII1 */
     {0x16E4, 0xA000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_rxdv on G14 - MyPRUSS2_MII1 */
     {0x16EC, 0xC000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii_mr0_clk on A13 - MyPRUSS2_MII1 */
     {0x16E8, 0xE000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_rxd3 on F14 - MyPRUSS2_MII1 */
     {0x16F0, 0xC000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_rxd2 on A19 - MyPRUSS2_MII1 */
     {0x16F4, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_crs on B18 - MyPRUSS2_MII1 */
     {0x1724, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_rxer on G12 - MyPRUSS2_MII1 */
     {0x16B4, 0xE000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_rxd1 on A18 - MyPRUSS2_MII1 */
     {0x16F8, 0xC000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_rxd0 on C15 - MyPRUSS2_MII1 */
     {0x170C, 0xC000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_col on F15 - MyPRUSS2_MII1 */
     {0x1728, 0xC000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII0 - pr2_mii0_rxlink on A16 - MyPRUSS2_MII1 */
     {0x1710, 0xC000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii_mt1_clk on AC5 - MyPRUSS2_MII2 */
     {0x1774, 0x6000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_txen on AB4 - MyPRUSS2_MII2 */
     {0x1778, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_txd3 on AD4 - MyPRUSS2_MII2 */
     {0x177C, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_txd2 on AC4 - MyPRUSS2_MII2 */
     {0x1780, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_txd1 on AC7 - MyPRUSS2_MII2 */
     {0x1784, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_txd0 on AC6 - MyPRUSS2_MII2 */
     {0x1788, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_rxdv on AC3 - MyPRUSS2_MII2 */
     {0x1790, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii_mr1_clk on AC9 - MyPRUSS2_MII2 */
     {0x178C, 0x6000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_rxd3 on AC8 - MyPRUSS2_MII2 */
     {0x1794, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_rxd2 on AD6 - MyPRUSS2_MII2 */
     {0x1798, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_crs on E17 - MyPRUSS2_MII2 */
     {0x1698, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_rxer on B19 - MyPRUSS2_MII2 */
     {0x172C, 0xE000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_rxd1 on AB8 - MyPRUSS2_MII2 */
     {0x179C, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_rxd0 on AB5 - MyPRUSS2_MII2 */
     {0x17A0, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_col on D18 - MyPRUSS2_MII2 */
     {0x1694, 0x4000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS2_MII1 - pr2_mii1_rxlink on C17 - MyPRUSS2_MII2 */
     {0x1730, 0xE000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MDIO - pr1_mdio_data on F6 - MyPRUSS1_MDIO1 */
     {0x1594, 0x5000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MDIO - pr1_mdio_mdclk on D3 - MyPRUSS1_MDIO1 */
     {0x1590, 0x0000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* USB1 - usb1_dp on AD12 - MyUSB1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB1 - usb1_dm on AC12 - MyUSB1 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB1 - usb1_drvvbus on AB10 - MyUSB1 */
     {0x1680, 0x90000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* USB2 - usb2_dp on AE11 - MyUSB2 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB2 - usb2_dm on AF11 - MyUSB2 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB2 - usb2_drvvbus on AC10 - MyUSB2 */
     {0x1684, 0x90000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - tms on F18 - MyDEBUGSS1 */
     {0x1830, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - tdi on D23 - MyDEBUGSS1 */
     {0x1834, 0xE0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - tdo on F19 - MyDEBUGSS1 */
     {0x1838, 0x20000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - tclk on E20 - MyDEBUGSS1 */
     {0x183C, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - trstn on D20 - MyDEBUGSS1 */
     {0x1840, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - rtck on E18 - MyDEBUGSS1 */
     {0x1844, 0x20000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - emu0 on G21 - MyDEBUGSS1 */
     {0x1848, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - emu1 on D24 - MyDEBUGSS1 */
     {0x184C, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* MDIO - mdio_mclk on V1 - MyGMAC_MDIO1 */
     {0x163C, 0x80000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* MDIO - mdio_d on U4 - MyGMAC_MDIO1 */
     {0x1640, 0xD0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO1 - gpio1_4 on D15 - MyGPIO1 */
     {0x1714, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO1 - gpio1_5 on A17 - MyGPIO1 */
     {0x1720, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_19 on T1 - MyGPIO2 */
     {0x14B4, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_21 on P1 - MyGPIO2 */
     {0x14BC, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_22 on P7 - MyGPIO2 */
     {0x14C0, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_23 on N1 - MyGPIO2 */
     {0x14C4, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_24 on M5 - MyGPIO2 */
     {0x14C8, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_25 on M3 - MyGPIO2 */
     {0x14CC, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_26 on N6 - MyGPIO2 */
     {0x14D0, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_27 on M4 - MyGPIO2 */
     {0x14D4, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_28 on N2 - MyGPIO2 */
     {0x14D8, 0x9000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO2 - gpio2_29 on B17 - MyGPIO2 */
     {0x171C, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_28 on E1 - MyGPIO3 */
     {0x1554, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_29 on G2 - MyGPIO3 */
     {0x1558, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_30 on H7 - MyGPIO3 */
     {0x155C, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_31 on G1 - MyGPIO3 */
     {0x1560, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_0 on G6 - MyGPIO4 */
     {0x1564, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_21 on B11 - MyGPIO4 */
     {0x15D0, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_0 on B14 - MyGPIO5 */
     {0x16AC, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_1 on J14 - MyGPIO5 */
     {0x16B0, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_4 on G13 - MyGPIO5 */
     {0x16BC, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_5 on J11 - MyGPIO5 */
     {0x16C0, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_6 on E12 - MyGPIO5 */
     {0x16C4, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_7 on F13 - MyGPIO5 */
     {0x16C8, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_8 on C12 - MyGPIO5 */
     {0x16CC, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_9 on D12 - MyGPIO5 */
     {0x16D0, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_18 on V2 - MyGPIO5 */
     {0x1648, 0xA000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_19 on Y1 - MyGPIO5 */
     {0x164C, 0x8000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_7 on B16 - MyGPIO6 */
     {0x1718, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_14 on E21 - MyGPIO6 */
     {0x1688, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_15 on F20 - MyGPIO6 */
     {0x168C, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_16 on F21 - MyGPIO6 */
     {0x1690, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_19 on B26 - MyGPIO6 */
     {0x169C, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_27 on W7 - MyGPIO6 */
     {0x176C, 0xD000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_28 on Y9 - MyGPIO6 */
     {0x1770, 0xD000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_7 on A25 - MyGPIO7 */
     {0x17A4, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_8 on F16 - MyGPIO7 */
     {0x17A8, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_9 on B25 - MyGPIO7 */
     {0x17AC, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_10 on A24 - MyGPIO7 */
     {0x17B0, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_11 on A22 - MyGPIO7 */
     {0x17B4, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_12 on B21 - MyGPIO7 */
     {0x17B8, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_22 on B27 - MyGPIO7 */
     {0x17E0, 0xD000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_24 on E25 - MyGPIO7 */
     {0x17E8, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_25 on C27 - MyGPIO7 */
     {0x17EC, 0x1000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii_mt0_clk on E8 - MyPRUSS1_MII1 */
     {0x15FC, 0x6000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_txen on D8 - MyPRUSS1_MII1 */
     {0x1608, 0x2000D, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_txd3 on D9 - MyPRUSS1_MII1 */
     {0x1600, 0x2000D, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_txd2 on D7 - MyPRUSS1_MII1 */
     {0x1604, 0x2000D, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_txd1 on A5 - MyPRUSS1_MII1 */
     {0x160C, 0x2000D, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_txd0 on C6 - MyPRUSS1_MII1 */
     {0x1610, 0x2000D, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_rxdv on C7 - MyPRUSS1_MII1 */
     {0x1618, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii_mr0_clk on C8 - MyPRUSS1_MII1 */
     {0x1614, 0x6000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_rxd3 on B7 - MyPRUSS1_MII1 */
     {0x161C, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_rxd2 on B8 - MyPRUSS1_MII1 */
     {0x1620, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_crs on A10 - MyPRUSS1_MII1 */
     {0x1638, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_rxer on C9 - MyPRUSS1_MII1 */
     {0x162C, 0x6000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_rxd1 on A7 - MyPRUSS1_MII1 */
     {0x1624, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_rxd0 on A8 - MyPRUSS1_MII1 */
     {0x1628, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_col on B9 - MyPRUSS1_MII1 */
     {0x1634, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii0_rxlink on A9 - MyPRUSS1_MII1 */
     {0x1630, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii_mt1_clk on C1 - MyPRUSS1_MII1 */
     {0x1580, 0x6000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_txen on E4 - MyPRUSS1_MII1 */
     {0x1584, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_txd3 on F5 - MyPRUSS1_MII1 */
     {0x1588, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_txd2 on E6 - MyPRUSS1_MII1 */
     {0x158C, 0x2000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_txd1 on D2 - MyPRUSS1_MII1 */
     {0x1578, 0x2000D, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_txd0 on F4 - MyPRUSS1_MII1 */
     {0x157C, 0x2000D, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_rxdv on G11 - MyPRUSS1_MII1 */
     {0x15E8, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii_mr1_clk on F10 - MyPRUSS1_MII1 */
     {0x15E4, 0x6000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_rxd3 on E9 - MyPRUSS1_MII1 */
     {0x15EC, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_rxd2 on F9 - MyPRUSS1_MII1 */
     {0x15F0, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_crs on G10 - MyPRUSS1_MII1 */
     {0x15E0, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_rxer on E11 - MyPRUSS1_MII1 */
     {0x15D8, 0x6000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_rxd1 on F8 - MyPRUSS1_MII1 */
     {0x15F4, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_rxd0 on E7 - MyPRUSS1_MII1 */
     {0x15F8, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_col on E2 - MyPRUSS1_MII1 */
     {0x1574, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_MII - pr1_mii1_rxlink on F11 - MyPRUSS1_MII1 */
     {0x15DC, 0x6000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_UART - pr1_uart0_rxd on F2 - MyPRUSS1_UART1 */
     {0x1568, 0x5000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_UART - pr1_uart0_txd on F3 - MyPRUSS1_UART1 */
     {0x156C, 0x1000B, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GMAC1 - rgmii1_rxd1 on B5 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15C0, 0x60103, {0xAEC, 171, 1331}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC1 - rgmii1_rxd2 on B4 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15BC, 0x60103, {0xAE0, 114, 1517}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC1 - rgmii1_rxd3 on B3 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15B8, 0x60103, {0xAD4, 142, 1337}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC1 - rgmii1_rxd0 on A4 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15C4, 0x60103, {0xAF8, 0, 1328}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC1 - rgmii1_txd0 on D6 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15AC, 0x00103, {0x0, 0, 0}, {0x0, 0, 0}, {0xAAC, 60, 0}},
#endif

/* GMAC1 - rgmii1_txd1 on B2 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15A8, 0x00103, {0x0, 0, 0}, {0x0, 0, 0}, {0xAA0, 60, 0}},
#endif

/* GMAC1 - rgmii1_txd2 on C4 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15A4, 0x00103, {0x0, 0, 0}, {0x0, 0, 0}, {0xA94, 0, 0}},
#endif

/* GMAC1 - rgmii1_txd3 on C3 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15A0, 0x00103, {0x0, 0, 0}, {0x0, 0, 0}, {0xA88, 150, 0}},
#endif

/* GMAC1 - rgmii1_txc on D5 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x1598, 0x00103, {0x0, 0, 0}, {0x0, 0, 0}, {0xA70, 0, 0}},
#endif

/* GMAC1 - rgmii1_txctl on C2 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x159C, 0x00103, {0x0, 0, 0}, {0x0, 0, 0}, {0xA7C, 170, 0}},
#endif

/* GMAC1 - rgmii1_rxc on C5 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15B0, 0x40103, {0xAB0, 530, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC1 - rgmii1_rxctl on A3 - MyGMAC_SW11 */
#ifdef GMAC_RGMII1_MANUAL1
     {0x15B4, 0x40103, {0xABC, 71, 1099}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_clk on W6 - MyMMC11 */
#ifdef MMC1_DEFAULT
     {0x1754, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_MANUAL1
     {0x1754, 0x60100, {0x618, 588, 0}, {0x0, 0, 0}, {0x620, 1230, 0}},
#endif
#ifdef MMC1_MANUAL2
     {0x1754, 0x60100, {0x0, 0, 0}, {0x0, 0, 0}, {0x620, 520, 320}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1754, 0x601F0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL4
     {0x1754, 0x601C0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1754, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1754, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_cmd on Y6 - MyMMC11 */
#ifdef MMC1_DEFAULT
     {0x1758, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_MANUAL1
     {0x1758, 0x60100, {0x624, 1000, 0}, {0x628, 0, 0}, {0x62C, 0, 0}},
#endif
#ifdef MMC1_MANUAL2
     {0x1758, 0x60100, {0x0, 0, 0}, {0x628, 51, 0}, {0x62C, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1758, 0x601F0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL4
     {0x1758, 0x601C0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1758, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1758, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat0 on AA6 - MyMMC11 */
#ifdef MMC1_DEFAULT
     {0x175C, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_MANUAL1
     {0x175C, 0x60100, {0x630, 1375, 0}, {0x634, 0, 0}, {0x638, 56, 0}},
#endif
#ifdef MMC1_MANUAL2
     {0x175C, 0x60100, {0x0, 0, 0}, {0x634, 0, 0}, {0x638, 40, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x175C, 0x601F0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL4
     {0x175C, 0x601C0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x175C, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x175C, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat1 on Y4 - MyMMC11 */
#ifdef MMC1_DEFAULT
     {0x1760, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_MANUAL1
     {0x1760, 0x60100, {0x63C, 1000, 0}, {0x640, 0, 0}, {0x644, 76, 0}},
#endif
#ifdef MMC1_MANUAL2
     {0x1760, 0x60100, {0x0, 0, 0}, {0x640, 363, 0}, {0x644, 83, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1760, 0x601F0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL4
     {0x1760, 0x601C0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1760, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1760, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat2 on AA5 - MyMMC11 */
#ifdef MMC1_DEFAULT
     {0x1764, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_MANUAL1
     {0x1764, 0x60100, {0x648, 1000, 0}, {0x64C, 0, 0}, {0x650, 91, 0}},
#endif
#ifdef MMC1_MANUAL2
     {0x1764, 0x60100, {0x0, 0, 0}, {0x64C, 199, 0}, {0x650, 98, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1764, 0x601F0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL4
     {0x1764, 0x601C0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1764, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1764, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat3 on Y3 - MyMMC11 */
#ifdef MMC1_DEFAULT
     {0x1768, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_MANUAL1
     {0x1768, 0x60100, {0x654, 1000, 0}, {0x658, 0, 0}, {0x65C, 99, 0}},
#endif
#ifdef MMC1_MANUAL2
     {0x1768, 0x60100, {0x0, 0, 0}, {0x658, 273, 0}, {0x65C, 106, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1768, 0x601F0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL4
     {0x1768, 0x601C0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1768, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1768, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_hsync1 on N7 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1460, 0x50106, {0x24C, 1758, 653}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_vsync1 on R4 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1464, 0x50106, {0x258, 1705, 899}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_fld1 on P4 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1470, 0x50106, {0x138, 2009, 601}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_de1 on P9 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x146C, 0x50106, {0x12C, 1851, 1011}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_clk1 on N9 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1468, 0x50106, {0x120, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d0 on R6 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1440, 0x50106, {0x114, 1873, 702}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d1 on T9 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1444, 0x50106, {0x198, 1629, 772}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d2 on T6 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1448, 0x50106, {0x204, 1734, 898}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d3 on T7 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x144C, 0x50106, {0x210, 1757, 1076}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d4 on P6 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1450, 0x50106, {0x21C, 1794, 893}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d5 on R9 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1454, 0x50106, {0x228, 1726, 853}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d6 on R5 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x1458, 0x50106, {0x234, 1792, 612}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* VIN1B - vin1b_d7 on P5 - MyVIN1 */
#ifdef VIP_MANUAL9
     {0x145C, 0x50106, {0x240, 2117, 610}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxd1 on Y2 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1678, 0x60100, {0x714, 134, 1786}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxd2 on V3 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1674, 0x60100, {0x720, 40, 1966}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxd3 on V4 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1670, 0x60100, {0x72C, 0, 2057}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxd0 on W2 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x167C, 0x60100, {0x708, 3, 1721}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_txd0 on U6 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1664, 0x00100, {0x0, 0, 0}, {0x0, 0, 0}, {0x758, 0, 60}},
#endif

/* GMAC0 - rgmii0_txd1 on V6 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1660, 0x00100, {0x0, 0, 0}, {0x0, 0, 0}, {0x764, 0, 0}},
#endif

/* GMAC0 - rgmii0_txd2 on U7 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x165C, 0x00100, {0x0, 0, 0}, {0x0, 0, 0}, {0x770, 0, 60}},
#endif

/* GMAC0 - rgmii0_txd3 on V7 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1658, 0x00100, {0x0, 0, 0}, {0x0, 0, 0}, {0x77C, 0, 120}},
#endif

/* GMAC0 - rgmii0_txc on W9 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1650, 0x00100, {0x0, 0, 0}, {0x0, 0, 0}, {0x740, 0, 60}},
#endif

/* GMAC0 - rgmii0_txctl on V9 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1654, 0x00100, {0x0, 0, 0}, {0x0, 0, 0}, {0x74C, 0, 60}},
#endif

/* GMAC0 - rgmii0_rxc on U5 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1668, 0x40100, {0x6F0, 413, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxctl on V5 - MyGMAC_SW01 */
#ifdef GMAC_RGMII0_MANUAL1
     {0x166C, 0x40100, {0x6FC, 27, 2296}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* SPI2 - spi2_sclk on A26 - MySPI2 */
     {0x17C0, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* SPI2 - spi2_d0 on G17 - MySPI2 */
     {0x17C8, 0xD0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* SPI2 - spi2_d1 on B22 - MySPI2 */
     {0x17C4, 0xD0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* SPI2 - spi2_cs0 on B24 - MySPI2 */
     {0x17CC, 0xD0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* SPI3 - spi3_sclk on C18 - MySPI3 */
     {0x1734, 0x50002, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* SPI3 - spi3_cs0 on D17 - MySPI3 */
     {0x1740, 0x20002, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* SPI3 - spi3_d1 on A21 - MySPI3 */
     {0x1738, 0x50002, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* OSC0 - xi_osc0 on AE15 - MyOSC01 */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* OSC0 - xo_osc0 on AD15 - MyOSC01 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* QSPI1 - qspi1_sclk on R2 - MyQSPI1 */
#ifdef QSPI1_DEFAULT
     {0x1488, 0x10001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef QSPI1_MANUAL1
     {0x1488, 0x10101, {0x0, 0, 0}, {0x0, 0, 0}, {0x188, 0, 0}},
#endif

/* QSPI1 - qspi1_rtclk on R3 - MyQSPI1 */
#ifdef QSPI1_DEFAULT
     {0x1474, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef QSPI1_MANUAL1
     {0x1474, 0x50101, {0x144, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* QSPI1 - qspi1_cs0 on P2 - MyQSPI1 */
#ifdef QSPI1_DEFAULT
     {0x14B8, 0x10001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef QSPI1_MANUAL1
     {0x14B8, 0x10101, {0x0, 0, 0}, {0x0, 0, 0}, {0x374, 0, 0}},
#endif

/* QSPI1 - qspi1_d0 on U1 - MyQSPI1 */
#ifdef QSPI1_DEFAULT
     {0x1480, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef QSPI1_MANUAL1
     {0x1480, 0x50101, {0x168, 2229, 1268}, {0x0, 0, 0}, {0x170, 0, 0}},
#endif

/* QSPI1 - qspi1_d1 on P3 - MyQSPI1 */
#ifdef QSPI1_DEFAULT
     {0x1484, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef QSPI1_MANUAL1
     {0x1484, 0x50101, {0x174, 2251, 1217}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* QSPI1 - qspi1_d2 on U2 - MyQSPI1 */
#ifdef QSPI1_DEFAULT
     {0x147C, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef QSPI1_MANUAL1
     {0x147C, 0x50101, {0x15C, 2176, 1197}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* QSPI1 - qspi1_d3 on T2 - MyQSPI1 */
#ifdef QSPI1_DEFAULT
     {0x1478, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef QSPI1_MANUAL1
     {0x1478, 0x50101, {0x150, 2247, 1186}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_clk on J7 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x149C, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x149C, 0x60101, {0x1C8, 894, 0}, {0x0, 0, 0}, {0x1D0, 266, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x149C, 0x60101, {0x1C8, 410, 4000}, {0x0, 0, 0}, {0x1D0, 266, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x149C, 0x60101, {0x0, 0, 0}, {0x0, 0, 0}, {0x1D0, 730, 360}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x149C, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_cmd on H6 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x14B0, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x14B0, 0x60101, {0x360, 0, 0}, {0x364, 0, 0}, {0x368, 0, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x14B0, 0x60101, {0x360, 0, 0}, {0x364, 0, 0}, {0x368, 0, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x14B0, 0x60101, {0x0, 0, 0}, {0x364, 360, 0}, {0x368, 0, 120}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x14B0, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat0 on J4 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x14A0, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x14A0, 0x60101, {0x1D4, 30, 0}, {0x1D8, 0, 0}, {0x1DC, 0, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x14A0, 0x60101, {0x1D4, 82, 0}, {0x1D8, 0, 0}, {0x1DC, 0, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x14A0, 0x60101, {0x0, 0, 0}, {0x1D8, 176, 0}, {0x1DC, 0, 0}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x14A0, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat1 on J6 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x14A4, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x14A4, 0x60101, {0x1E0, 0, 0}, {0x1E4, 0, 0}, {0x1E8, 0, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x14A4, 0x60101, {0x1E0, 0, 0}, {0x1E4, 0, 0}, {0x1E8, 0, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x14A4, 0x60101, {0x0, 0, 0}, {0x1E4, 0, 0}, {0x1E8, 0, 0}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x14A4, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat2 on H4 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x14A8, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x14A8, 0x60101, {0x1EC, 23, 0}, {0x1F0, 0, 0}, {0x1F4, 43, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x14A8, 0x60101, {0x1EC, 77, 0}, {0x1F0, 0, 0}, {0x1F4, 43, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x14A8, 0x60101, {0x0, 0, 0}, {0x1F0, 101, 0}, {0x1F4, 70, 0}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x14A8, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat3 on H5 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x14AC, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x14AC, 0x60101, {0x1F8, 0, 0}, {0x1FC, 0, 0}, {0x200, 0, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x14AC, 0x60101, {0x1F8, 0, 0}, {0x1FC, 0, 0}, {0x200, 0, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x14AC, 0x60101, {0x0, 0, 0}, {0x1FC, 0, 0}, {0x200, 0, 0}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x14AC, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat4 on K7 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x148C, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x148C, 0x60101, {0x18C, 0, 0}, {0x190, 0, 0}, {0x194, 152, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x148C, 0x60101, {0x18C, 0, 14}, {0x190, 0, 0}, {0x194, 152, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x148C, 0x60101, {0x0, 0, 0}, {0x190, 0, 0}, {0x194, 285, 0}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x148C, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat5 on M7 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x1490, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x1490, 0x60101, {0x1A4, 119, 0}, {0x1A8, 0, 0}, {0x1AC, 206, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x1490, 0x60101, {0x1A4, 127, 0}, {0x1A8, 0, 0}, {0x1AC, 206, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x1490, 0x60101, {0x0, 0, 0}, {0x1A8, 231, 0}, {0x1AC, 189, 0}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x1490, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat6 on J5 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x1494, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x1494, 0x60101, {0x1B0, 0, 0}, {0x1B4, 0, 0}, {0x1B8, 78, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x1494, 0x60101, {0x1B0, 22, 0}, {0x1B4, 0, 0}, {0x1B8, 78, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x1494, 0x60101, {0x0, 0, 0}, {0x1B4, 39, 0}, {0x1B8, 0, 120}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x1494, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC2 - mmc2_dat7 on K6 - MyMMC21 */
#ifdef MMC2_DEFAULT
     {0x1498, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_MANUAL1
     {0x1498, 0x60101, {0x1BC, 18, 0}, {0x1C0, 0, 0}, {0x1C4, 2, 0}},
#endif
#ifdef MMC2_MANUAL2
     {0x1498, 0x60101, {0x1BC, 72, 0}, {0x1C0, 0, 0}, {0x1C4, 2, 0}},
#endif
#ifdef MMC2_MANUAL3
     {0x1498, 0x60101, {0x0, 0, 0}, {0x1C0, 91, 0}, {0x1C4, 0, 70}},
#endif
#ifdef MMC2_VIRTUAL2
     {0x1498, 0x601D1, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
};

#ifdef BOARD_PAD_DELAY_ALT_GRP_ENABLE
#if defined(_TMS320C6X) || defined(__TI_ARM_V7M4__)
#ifndef __cplusplus
#pragma DATA_SECTION (altPad, "BOARD_IO_DELAY_DATA");
#else
#pragma DATA_SECTION ("BOARD_IO_DELAY_DATA");
#endif
const boardPadDelayAltGpCfg_t altPad[] = {
#else
const boardPadDelayAltGpCfg_t altPad[] __attribute__((section("BOARD_IO_DELAY_DATA"))) = {
#endif
/** {ALTERNATE_PADCONF_ADDRESS/PRUSS_REG_ADDRESS, ALTERNATE_PADCONF_VALUE/PRUSS_REG_VALUE} **/

/* PRUSS1_MII - pr1_mii_mt0_clk on E8 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_txen on D8 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_txd3 on D9 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_txd2 on D7 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_txd1 on A5 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_txd0 on C6 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_rxdv on C7 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii_mr0_clk on C8 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_rxd3 on B7 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_rxd2 on B8 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_crs on A10 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_rxer on C9 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_rxd1 on A7 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_rxd0 on A8 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_col on B9 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii0_rxlink on A9 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii1_txd1 on D2 - MyPRUSS1_MII1 */
     {0x4B22600C, 0x10000000},
/* PRUSS1_MII - pr1_mii1_txd0 on F4 - MyPRUSS1_MII1 */
     {0x4B22600C, 0x10000000},
/* PRUSS1_MII - pr1_mii1_rxdv on G11 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii_mr1_clk on F10 - MyPRUSS1_MII1 */
     {0x4B2A600C, 0x10000000},
/* PRUSS1_MII - pr1_mii1_rxd3 on E9 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii1_rxd2 on F9 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii1_crs on G10 - MyPRUSS1_MII1 */
     {0x4B2A600C, 0x10000000},
/* PRUSS1_MII - pr1_mii1_rxer on E11 - MyPRUSS1_MII1 */
     {0x4B2A600C, 0x10000000},
/* PRUSS1_MII - pr1_mii1_rxd1 on F8 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii1_rxd0 on E7 - MyPRUSS1_MII1 */
     {0x4B2A6008, 0x10000000},
/* PRUSS1_MII - pr1_mii1_col on E2 - MyPRUSS1_MII1 */
     {0x4B22600C, 0x10000000},
/* PRUSS1_MII - pr1_mii1_rxlink on F11 - MyPRUSS1_MII1 */
     {0x4B2A600C, 0x10000000},
/* VIN1B - vin1b_hsync1 on N7 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_vsync1 on R4 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_fld1 on P4 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_de1 on P9 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_clk1 on N9 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d0 on R6 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d1 on T9 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d2 on T6 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d3 on T7 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d4 on P6 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d5 on R9 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d6 on R5 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
/* VIN1B - vin1b_d7 on P5 - MyVIN1 */
#ifdef VIP_MANUAL9			
     {0x4A002E8C, 0x0},
#endif
};
#endif

#ifdef __cplusplus
#if defined(_TMS320C6X) || defined(__TI_ARM_V7M4__)
#pragma CODE_SECTION ("BOARD_IO_DELAY_CODE");
#endif
#endif
uint32_t boardPadGetSize()
{
     return (sizeof(pad) / sizeof(boardPadDelayCfg_t));
}

#ifdef BOARD_PAD_DELAY_ALT_GRP_ENABLE
#ifdef __cplusplus
#if defined(_TMS320C6X) || defined(__TI_ARM_V7M4__)
#pragma CODE_SECTION ("BOARD_IO_DELAY_CODE");
#endif
#endif
uint32_t boardAltPadGetSize()
{
     return (sizeof(altPad) / sizeof(boardPadDelayAltGpCfg_t));
}
#endif

#ifdef __cplusplus
/* Function to avoid build errors for c++ build */
boardPadDelayCfg_t dummy1(void)
{
    return(pad[0]);
}

/* Function to avoid build errors for c++ build */
boardPadDelayAltGpCfg_t dummy2(void)
{
    return(altPad[0]);
}
#endif
