/**
 * Note: This file was auto-generated by TI PinMux on 6/14/2017 at 6:14:30 PM.
 *
 * \file  boardPadDelayTune.h
 *
 * \brief   This file contain manual/vritual iodelay mode definitions
 *
 * \copyright Copyright (CU) 2015 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

/**
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
 
 #ifdef __cplusplus
extern "C" {
#endif

#define GMAC_RGMII1_MANUAL1 /* GMAC RGMII1 with Transmit Clock Internal Delay Enabled Timings */
#define MMC1_DS_HS_SDR12_SDR25_PLB_ILB_DEFAULT /* MMC1 DS (Pad Loopback), HS (Internal Loopback and Pad Loopback), SDR12 (Internal Loopback and Pad Loopback), and SDR25 Timings (Internal Loopback and Pad Loopback) Timings */
/*#define MMC1_DDR50_PLB */ /* MMC1 DDR50 (Pad Loopback) Timings */
/*#define MMC1_SDR_104 */ /* MMC1 SDR104 Timings */
/*#define MMC1_SDR50_PLB */ /* MMC1 SDR50 (Pad Loopback) Timings */
/*#define MMC1_DS_ILB */ /* MMC1 DS (Internal Loopback) Timings */
/*#define MMC1_SDR50_ILB */ /* MMC1 SDR50 (Internal Loopback) Timings */
/*#define MMC1_DDR50_ILB */ /* MMC1 DDR50 (Internal Loopback) Timings */
/*#define VIN1A_IOSET2_3_4_VIN1B_IOSET4_VIN2B_IOSET1_10_REC */ /* VIN1A (IOSET2/3/4) and VIN1B (IOSET4) and VIN2B (IOSET1/10) Rise-Edge Capture Mode Timings */
/*#define VIN1A_IOSET2_3_4_VIN1B_IOSET4_VIN2B_IOSET1_10_FEC */ /* VIN1A (IOSET2/3/4) and VIN1B (IOSET4) and VIN2B (IOSET1/10) Fall-Edge Capture Mode Timings */
#define VIN1B_IOSET6_7_REC /* VIN1B (IOSET6/7) Rise-Edge Capture Mode Timings */
/*#define VIN1B_IOSET6_7_FEC */ /* VIN1B (IOSET6/7) Fall-Edge Capture Mode Timings */
#define GMAC_RGMII0_MANUAL1 /* GMAC RGMII0 with Transmit Clock Internal Delay Enabled Timings */
/*#define QSPI_MODE3 */ /* QSPI Mode 3 */
#define QSPI_MODE0 /* QSPI Mode 0 */
#define MMC2_STD_PLB_HS_PLB /* MMC2 Standard (Pad Loopback), High Speed (Pad Loopback) */
/*#define MMC2_DDR_PLB */ /* MMC2 DDR (Pad Loopback) Timings */
/*#define MMC2_DDR_ILB */ /* MMC2 DDR (Internal Loopback) Timings */
/*#define MMC2_HS200 */ /* MMC2 HS200 Timings */
/*#define MMC2_STD_ILB_HS_ILB */ /* MMC2 Standard (Internal Loopback), High Speed (Internal Loopback) */

/* MODE RE-DEFINITIONS */

#ifdef GMAC_RGMII1_MANUAL1
     #define GMAC_RGMII1_MANUAL1
#endif
#ifdef MMC1_DS_HS_SDR12_SDR25_PLB_ILB_DEFAULT
     #define MMC1_DEFAULT
#endif
#ifdef MMC1_DDR50_PLB
     #define MMC1_MANUAL1
#endif
#ifdef MMC1_SDR_104
     #define MMC1_MANUAL2
#endif
#ifdef MMC1_SDR50_PLB
     #define MMC1_VIRTUAL1
#endif
#ifdef MMC1_DS_ILB
     #define MMC1_VIRTUAL4
#endif
#ifdef MMC1_SDR50_ILB
     #define MMC1_VIRTUAL5
#endif
#ifdef MMC1_DDR50_ILB
     #define MMC1_VIRTUAL6
#endif
#ifdef VIN1A_IOSET2_3_4_VIN1B_IOSET4_VIN2B_IOSET1_10_REC
     #define VIP_MANUAL7
#endif
#ifdef VIN1A_IOSET2_3_4_VIN1B_IOSET4_VIN2B_IOSET1_10_FEC
     #define VIP_MANUAL12
#endif
#ifdef VIN1B_IOSET6_7_REC
     #define VIP_MANUAL9
#endif
#ifdef VIN1B_IOSET6_7_FEC
     #define VIP_MANUAL14
#endif
#ifdef GMAC_RGMII0_MANUAL1
     #define GMAC_RGMII0_MANUAL1
#endif
#ifdef QSPI_MODE3
     #define QSPI1_DEFAULT
#endif
#ifdef QSPI_MODE0
     #define QSPI1_MANUAL1
#endif
#ifdef MMC2_STD_PLB_HS_PLB
     #define MMC2_DEFAULT
#endif
#ifdef MMC2_DDR_PLB
     #define MMC2_MANUAL1
#endif
#ifdef MMC2_DDR_ILB
     #define MMC2_MANUAL2
#endif
#ifdef MMC2_HS200
     #define MMC2_MANUAL3
#endif
#ifdef MMC2_STD_ILB_HS_ILB
     #define MMC2_VIRTUAL2
#endif

#ifdef __cplusplus
}
#endif
