/**
 * \file hw_chipdb_baseaddr.c
 *
 * \brief   Base addresses of all the modules in SoC as seen by MPU
 *          There is one hw_chipdb_baseaddr.c file per processing unit in the
 *          SoC. It is the users' responsibility to include the right
 *          base address file.
 *
 *   WARNING: THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY !!!
 *
 * \version 0.0 (Aug 2013) : [AE] First version
 *
 */

/*
 * Copyright (C) 2013 Texas Instruments Incorporated - http://www.ti.com/
 */

/*
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include <types.h>
#include <hw_types.h>
#include <chipdb.h>
#include <chipdb_defs.h>
#include "hw_chipdb.h"
#include "soc_am335x.h"

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/**
 *
 * \brief Base address table.
 *
 *        This Table is auto-generted
 *
 */
const uint32_t gChipDBBaseAddrTable[CHIPDB_RESOURCE_COUNT] =
{
    /*
    baseaddr_of_res0,
    baseaddr_of_res1,
    baseaddr_of_res2,
    baseaddr_of_res3,
    baseaddr_of_res4,
    ...
    */
    0x0, /* MPU_CORE */
    0x0, /* MPU */
    SOC_EMIF_0_REGS,
    SOC_GPMC_0_REGS,
    SOC_DCAN_0_REGS,
    SOC_DCAN_1_REGS,
    SOC_GPIO_0_REGS,
    SOC_GPIO_1_REGS,
    SOC_GPIO_2_REGS,
    SOC_GPIO_3_REGS,
    SOC_I2C_0_REGS, /*10*/
    SOC_I2C_1_REGS,
    SOC_I2C_2_REGS,
    SOC_MCASP_0_CTRL_REGS,
    SOC_MCASP_1_CTRL_REGS,
    SOC_USB_0_BASE,
    SOC_USB_1_BASE,
    0x481D8000, /* MMC */
    SOC_SPI_0_REGS,
    SOC_SPI_1_REGS,
    SOC_UART_0_REGS, /*20*/
    SOC_UART_1_REGS,
    SOC_UART_2_REGS,
    SOC_UART_3_REGS,
    SOC_UART_4_REGS,
    SOC_UART_5_REGS,
    SOC_PWMSS0_REGS,
    SOC_PWMSS1_REGS,
    SOC_PWMSS2_REGS,
    SOC_SPINLOCK_0_REGS, /* SPINLOCK */
    0x0, /* AES: TBD */ /*30*/
    0x0, /* RNG: TBD */
    0x0, /* PKA: TBD */
    0x0, /* CRYPTODMA: TBD */
    0x0, /* DES: TBD */
    0x0, /* SHA: TBD */
    0x56000000, /* GFX / SGX530 */
    SOC_EDMA30CC_0_REGS,
    SOC_EDMA3TC_0_REGS, /* EDMA3TC0 */
    SOC_EDMA3TC_1_REGS,/* EDMA3TC1 */
    SOC_EDMA3TC_2_REGS, /* EDMA3TC2 */ /*40*/
    SOC_CPSW_SS_REGS,
    SOC_ADC_TSC_0_REGS,
    SOC_MMCHS_0_REGS,
    SOC_MMCHS_1_REGS,
    SOC_MMCHS_2_REGS,
    SOC_DMTIMER_0_REGS,
    0x0, /* DMTIMER1 is ms timer */
    SOC_DMTIMER_2_REGS,
    SOC_DMTIMER_3_REGS,
    SOC_DMTIMER_4_REGS, /*50*/
    SOC_DMTIMER_5_REGS,
    SOC_DMTIMER_6_REGS,
    SOC_DMTIMER_7_REGS,
    SOC_DMTIMER_1_REGS, /* SOC_DMTIMER_1_MS_REGS*/
    SOC_WDT_0_REGS,
    SOC_WDT_1_REGS,
    0x44000000, /* L3F_CFG */
    0x44800000, /* L3S_CFG */
    SOC_MAILBOX_0_REGS, /* MAILBOX */
    0x4818C000, /* OCP_WP_NOC */ /*60*/
    SOC_PRCM_REGS,
    0x44E37000, /* SMARTREFLEX0 */
    0x44E39000, /* SMARTREFLEX1 */
    SOC_RTC_0_REGS,
    0x4A300000, /* PRU_ICSS */
    SOC_CONTROL_REGS,
    0x4B000000, /* DEBUGSS */
    0x40300000, /* L3 OCMC SRAM */
    SOC_ELM_0_REGS,
    0x44D00000, /*70*/ /* WKUP_PROC_UMEM */
    0x44D80000, /* WKUP_PROC_DMEM */
    0x40000000, /* MPU_ROM_PUBLIC */
    0x402F0400, /* MPU_SRAM */
    SOC_AINTC_REGS, /* MPU_INTC */
    0x48240000, /* MPU_SS_CFG */
    0x44C00000, /* MPU_WAKEUP_GEN / L4_WKUP */
    SOC_LCDC_0_REGS,
    SOC_PRU_ICSS_DATA_RAM0,
    SOC_PRU_ICSS_DATA_RAM1, /*80*/
    SOC_PRU_ICSS_SHARED_RAM,
    SOC_PRU_ICSS_IEP_REG,
    SOC_PRU_ICSS_MII_MDIO_REG,
    SOC_PRU_ICSS_INTC_REG,
    SOC_PRU_ICSS_PRU0_CTRL_REG,
    SOC_PRU_ICSS_PRU1_CTRL_REG,
    SOC_PRU_ICSS_PRU0_DEBUG_REG,
    SOC_PRU_ICSS_PRU1_DEBUG_REG,
    SOC_PRU_ICSS_CFG_REG,
    SOC_PRU_ICSS_UART_REG,
    SOC_PRU_ICSS_ECAP_REG,
    SOC_PRU_ICSS_MII_RT_CFG_REG,
};
