/**
 * \file hw_chipdb.c
 *
 * \brief   Chip DB API Implementation
 *
 *          Chip DB API uses the pair (moduleID, instance) to uniquely
 *          identify a resource. The moduleID is unique across multiple SOCs.
 *          To make the implementation straight forward, the above pair is
 *          converted into a unique Resource ID to query the database.
 *
 *   WARNING: THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY !!!
 *
 *
 * \version 0.0 (Aug 2013) : [AE] First version
 *
 */

/*
 * Copyright (C) 2013 Texas Instruments Incorporated - http://www.ti.com/
 */

/*
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include <types.h>
#include <hw_types.h>
#include "hw_am335x_chipdb.h"


/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */


/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/**
 *
 * \brief Resource ID Map
 *
 *        The ResourceIDMap is used to map the pair (moduleID, instance) to
 *        unique resource ID. For this mapping, the number of instances of
 *        each module (IP) in a given SOC is needed. This array is defined
 *        as below:
 *
 *        gChipDBResourceIDMap[i] =    0                            when i == 0
 *                                     gChipDBResourceIDMap[i-1] +
 *                                       num_instance_of_module(i)  when i > 0
 *
 *        So, this array has the resource ID of the first instance of the
 *        module. For example, say modules 0 and 1 have 3 and 2 instances
 *        respectively then the array has the following values:
 *            gChipDBResourceIDMap[0] = 0;
 *            gChipDBResourceIDMap[1] = 3;
 *            gChipDBResourceIDMap[2] = 5;
 *
 *        The mapping of the pair (moduleID, instance) to the unique resource
 *        ID is done as follows:
 *            Resource ID = gChipDBResourceIDMap[moduleID] + instance;
 *
 *        This table can also be used to get the number of instances of a
 *        module in the SOC:
 *            Number of instance = gChipDBResourceIDMap[moduleID + 1] -
 *                                   gChipDBResourceIDMap[moduleID]
 *
 *        To make the above calculation seamless for all values of moduleID,
 *        this array has the last entry as below:
 *           gChipDBResourceIDMap[CHIPDB_MOD_ID_COUNT] = CHIPDB_RESOURCE_COUNT;
 *
 *        Note that if a module is not in an SOC the instance is zero. Also,
 *        the Module ID may not be contiguous as there could be holes for
 *        IPs not relevant for a SOC. Yet these holes are represented in this
 *        table with instance = 0.
 *
 *        This Table is auto-generated.
 *
 */

const uint32_t gChipDBResourceIDMap[CHIPDB_MOD_ID_COUNT + 1] =
{
    /*
     * The table values are to be auto-generated
     */

    /*
    0,
    prev_entry + mod0_ninst,
    prev_entry + mod1_ninst,
    ...
    CHIPDB_RESOURCE_COUNT
    */
    0U, /* MPU_CORE */
    1U, /* DSP */
    1U, /* IVA */
    1U, /* IPU_CORE */
    1U, /* EVE */
    1U, /* GPU */
    1U, /* L3 */
    1U, /* DDR */
    1U, /* MPU */
    2U, /* IPU */
    2U, /* BB2D */
    2U, /* ATL */
    2U, /* VCP */
    2U, /* PRUSS */
    2U, /* VIP */
    2U, /* VIP_VINA */
    2U, /* VIP_VINB */
    2U, /* VPE */
    2U, /* DSS */
    2U, /* DSS_VIDEO */
    2U, /* DSS_HDMI */
    2U, /* OCMC_RAM */
    2U, /* EMIF */
    3U, /* GPMC */
    4U, /* DMM */
    4U, /* SYSTEM_DMA */
    4U, /* CRYPTO_DMA */
    4U, /* EDMA */
    4U, /* DCAN */
    6U, /* GMAC_SW */
    6U, /* GMAC_SW_PORT */
    6U, /* GMAC_SW_SWITCH */
    6U, /* GPIO */
    10U, /* I2C */
    13U, /* MCASP */
    15U, /* PCIE */
    15U, /* USB */
    17U, /* SATA */
    17U, /* MMC */
    18U, /* MLB */
    18U, /* MCSPI */
    20U, /* QSPI */
    20U, /* UART */
    26U, /* PWMSS */
    29U, /* RTC_SS */
    29U, /* TIMER */
    29U, /* COUNTER_32K */
    29U, /* WD_TIMER */
    29U, /* SPINLOCK */
    30U, /* HDQ1W */
    30U, /* KDB */
    30U, /* DES3DES */
    30U, /* SHAMD5 */
    30U, /* AES */
    31U, /* RNG */
    32U, /* FPKA */
    32U, /* PKA */
    33U, /* MPU_SCU */
    33U, /* CRYPTODMA */
    34U, /* DES */
    35U, /* SHA */
    36U, /* ADC1 */
    36U, /* GFX */
    37U, /* EDMA3CC */
    38U, /* EDMA3TC */
    41U, /* OTFA */
    41U, /* TPMSS */
    41U, /* VPFE */
    41U, /* CPSW */
    42U, /* USIM */
    42U, /* ADC0 */
    43U, /* MMCSD */
    46U, /* DMTIMER */
    54U, /* DMTIMER1_1MS */
    55U, /* WDT */
    57U, /* L3F_CFG */
    58U, /* L3S_CFG */
    59U, /* MAILBOX */
    60U, /* OCP_WP_NOC */
    61U, /* PRCM */
    62U, /* SMARTREFLEX */
    64U, /* RTCSS */
    65U, /* PRU_ICSS */
    66U, /* CONTROL_MODULE */
    67U, /* DEBUGSS */
    68U, /* OCMCRAM */
    69U, /* RTC */
    69U, /* SYNCTIMER */
    69U, /* ERMC */
    69U, /* ELM */
    70U, /* EMIF_FW */
    70U, /* GPMC_FW */
    70U, /* OCMCRAM_FW */
    70U, /* GFX_FW */
    70U, /* MMCSD2_FW */
    70U, /* MCASP0_FW */
    70U, /* MCASP1_FW */
    70U, /* EDMA3TC_FW */
    70U, /* QSPI_FW */
    70U, /* PRU_ICSS_FW */
    70U, /* EDMA3CC_FW */
    70U, /* DEBUGSS_FW */
    70U, /* AES_FW */
    70U, /* DES_FW */
    70U, /* SHA_FW */
    70U, /* ADC0_FW */
    70U, /* ADC1_FW */
    70U, /* MPU_L2_CACHE_FW */
    70U, /* MPU_CMU */
    70U, /* MPU_AXI2OCP */
    70U, /* P1500 */
    70U, /* WKUP_PROC */
    70U, /* WKUP_PROC_UMEM */
    71U, /* WKUP_PROC_DMEM */
    72U, /* WKUP_PROC_BIT_BAND_REG */
    72U, /* WKUP_PROC_NVIC */
    72U, /* WKUP_PROC_ROM_TAB */
    72U, /* MPU_ROM_SECURE */
    72U, /* MPU_ROM_PUBLIC */
    73U, /* MPU_SRAM */
    74U, /* MPU_L2_CACHE */
    74U, /* MPU_INTC */
    75U, /* MPU_SS_CFG */
    76U, /* MPU_PL310 */
    76U, /* MPU_SCM */
    76U, /* MPU_WAKEUP_GEN */
    77U, /* LCDC */
    78U, /* PRUSS(N)_DATARAM0*/
    79U, /* PRUSS(N)_DATARAM1*/
    80U, /* PRUSS(N)_SHARED_RAM */
    81U, /* PRUSS(N)_IEP_REG */
    82U, /* PRUSS(N)_MII_MDIO */
    83U, /* PRUSS(N)_INTC_REG */
    84U, /* PRUSS(N)_PRU0_CTRL */
    85U, /* PRUSS(N)_PRU1_CTRL */
    86U, /* PRUSS(N)_PRU0_DBG */
    87U, /* PRUSS(N)_PRU1_DBG */
    88U, /* PRUSS(N)_CFG_REG */
    89U, /* PRUSS(N)_UART_REG */
    90U, /* PRUSS(N)_ECAP_REG */
    91U, /* PRUSS(N)_MIIRT_REG */
    CHIPDB_RESOURCE_COUNT
};

/**
 *
 * \brief Resource Table
 *
 *        The ResourceTable encodes the device definition. It is a bitmap that
 *        encodes if a resource is present or not. The bitmap is indexed using
 *        the SOC specific unique resource id.
 *
 *        The Table is auto-generated. The sample below assumes 4-words which
 *        can encode a maximum of 128 resources.
 *
 *        This Table is auto-generated.
 *
 */
const uint32_t
gChipDBResourceTable[CHIPDB_DEVICE_COUNT][CHIPDB_RESOURCE_RECORD_SIZE] =
{
    /*
     * The table values are to be auto-generated
     */
    /*
    {part0_bit_enc_31_0, part0_bit_enc_63_32, part0_bit_enc_95_64,
     part0_bit_enc_127_96},

    {part1_bit_enc_31_0, part1_bit_enc_63_32, part1_bit_enc_95_64,
       part1_bit_enc_127_96},

    {part63_bit_enc_31_0, part63_bit_enc_63_32, part63_bit_enc_95_64,
       Part63_bit_enc_127_96}
   */
    {
        0x7FFFFFFFU,
        0xFFFF7FE0U,
        0x3FFFFFFFU
    },
    {
        0xFFFFFFFFU,
        0xFFFF7FEFU,
        0x3FFFFFFFU
    }
};

/**
 * \brief Speed Grade Table
 *
 *        The SpeedGrade encodes the maximum frequency allowed for a processing
 *        unit.
 *
 *        This Table is auto-generated.
 *
 */

const uint32_t gChipDBSpeedGrade[CHIPDB_SG_COUNT][CHIPDB_SG_MODULE_COUNT] =
{
    /*
   {sg0_mpu_freq, sg0_dsp_freq, sg0_iva_freq, sg0_ipu_freq,
    sg0_eve_freq, sg0_gpu_freq, sg0_l3_freq, sg0_ddr_freq},
   {sg1_mpu_freq, sg1_dsp_freq, sg1_iva_freq, sg1_ipu_freq,
    Sg1_eve_freq, sg1_gpu_freq, sg1_l3_freq, sg1_ddr_freq},
       ...
   {sg26_mpu_freq, sg26_dsp_freq, sg26_iva_freq, sg26_ipu_freq,
    Sg26_eve_freq, sg26_gpu_freq, sg26_l3_freq, sg26_ddr_freq},
    */
};

/* ========================================================================== */
/*                          Function Definitions                              */
/* ========================================================================== */

/**
 *
 * \brief   Map the moduleID to the processor ID used to lookup speed grade.
 *
 *          This function is auto-generated
 *
 * \param   moduleID    Unique ID that identifies a Module (IP)
 *
 * \return  The processor ID
 *
 */
uint32_t CHIPDBSpeedGradeProcID(const chipdbModuleID_t moduleID)
{
    /*
     * There is a 1-1 mapping of moduleID to SpeedGrade ProcID so just
     * return the moduleID for Vayu. If there is a change to this mapping
     * later or for other SoC, the function should comprehend the mapping.
     */
    return moduleID;
}

/**
 *
 * \brief   Is the given ModuleID is a secure IP
 *
 *          This function is auto-generated
 *
 * \param   moduleID    Unique ID that identifies a Module (IP)
 *
 * \return  Return TRUE if the given moduleID is a secure IP; FALSE
 *          otherwise.
 *
 */
uint32_t CHIPDBIsSecureModule(const chipdbModuleID_t moduleID)
{
    switch (moduleID)
    {
        case CHIPDB_MOD_ID_CRYPTODMA:
        case CHIPDB_MOD_ID_DES:
        case CHIPDB_MOD_ID_SHA:
        case CHIPDB_MOD_ID_AES:
        case CHIPDB_MOD_ID_ADC1:
        case CHIPDB_MOD_ID_RNG:
        case CHIPDB_MOD_ID_PKA:
            return TRUE;
        default:
            return FALSE;
    }

    return FALSE;
}
