/********************************************************************
 * Copyright (C) 2013-2014 Texas Instruments Incorporated.
 * 
 *  Redistribution and use in source and binary forms, with or without 
 *  modification, are permitted provided that the following conditions 
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the   
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#ifndef CSLR_CAM_PRM_H
#define CSLR_CAM_PRM_H

#ifdef __cplusplus
extern "C"
{
#endif
#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>


/**************************************************************************
* Register Overlay Structure for __ALL__
**************************************************************************/
typedef struct {
    volatile Uint32 PM_CAM_PWRSTCTRL_REG;
    volatile Uint32 PM_CAM_PWRSTST_REG;
    volatile Uint8  RSVD0[24];
    volatile Uint32 PM_CAM_VIP1_WKDEP_REG;
    volatile Uint32 RM_CAM_VIP1_CONTEXT_REG;
    volatile Uint32 PM_CAM_VIP2_WKDEP_REG;
    volatile Uint32 RM_CAM_VIP2_CONTEXT_REG;
    volatile Uint32 PM_CAM_VIP3_WKDEP_REG;
    volatile Uint32 RM_CAM_VIP3_CONTEXT_REG;
    volatile Uint8  RSVD1[4];
    volatile Uint32 RM_CAM_LVDSRX_CONTEXT_REG;
    volatile Uint8  RSVD2[4];
    volatile Uint32 RM_CAM_CSI1_CONTEXT_REG;
    volatile Uint8  RSVD3[4];
    volatile Uint32 RM_CAM_CSI2_CONTEXT_REG;
} CSL_cam_prmRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

/* This register controls the CAM power state to reach upon a domain sleep
 * transition */
#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG                        (0x0U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL          (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG)


/* This register provides a status on the current CAM power domain state.
 * [warm reset insensitive] */
#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG                          (0x4U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST            (CSL_CAM_PRM_PM_CAM_PWRSTST_REG)


/* This register controls wakeup dependency based on VIP1 service requests. */
#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG                       (0x20U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP         (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG)


/* This register contains dedicated VIP1 context statuses. [warm reset
 * insensitive] */
#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG                     (0x24U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT       (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG)


/* This register controls wakeup dependency based on VIP2 service requests. */
#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG                       (0x28U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP         (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG)


/* This register contains dedicated VIP2 context statuses. [warm reset
 * insensitive] */
#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG                     (0x2CU)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT       (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG)


/* This register controls wakeup dependency based on VIP3 service requests. */
#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG                       (0x30U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP         (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG)


/* This register contains dedicated VIP3 context statuses. [warm reset
 * insensitive] */
#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG                     (0x34U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT       (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG)


/* This register contains dedicated LVDSRX context statuses. [warm reset
 * insensitive] */
#define CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG                   (0x3CU)
/* Below define for backward compatibility */
#define RM_CAM_LVDSRX_CONTEXT     (CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG)


/* This register contains dedicated CSI1 context statuses. [warm reset
 * insensitive] */
#define CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG                     (0x44U)
/* Below define for backward compatibility */
#define RM_CAM_CSI1_CONTEXT       (CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG)


/* This register contains dedicated CSI2 context statuses. [warm reset
 * insensitive] */
#define CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG                     (0x4CU)
/* Below define for backward compatibility */
#define RM_CAM_CSI2_CONTEXT       (CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG)



/**************************************************************************
* Field Definition Macros
**************************************************************************/

/* PM_CAM_PWRSTCTRL_REG */

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_VIP_BANK_ONSTATE_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_VIP_BANK_ONSTATE_MASK        (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_VIP_BANK_ONSTATE_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_VIP_BANK_ONSTATE_RESETVAL  (0x00000003U)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_VIP_BANK_ONSTATE_SHIFT  (16U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_VIP_BANK_ONSTATE_SHIFT       (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_VIP_BANK_ONSTATE_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_VIP_BANK_ONSTATE_MEM_ON  (0x00000003U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_VIP_BANK_ONSTATE_MEM_ON      (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_VIP_BANK_ONSTATE_MEM_ON)


#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_MASK        (0x00000003U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_POWERSTATE_MASK              (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_RESETVAL    (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_SHIFT       (0U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_POWERSTATE_SHIFT             (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_OFF         (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_POWERSTATE_OFF               (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_OFF)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_INACT       (0x00000002U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_POWERSTATE_INACT             (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_INACT)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_RESERVED    (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_POWERSTATE_RESERVED          (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_RESERVED)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_ON          (0x00000003U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_POWERSTATE_ON                (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_POWERSTATE_ON)


#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_MASK  (0x00000010U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_LOWPOWERSTATECHANGE_MASK     (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_SHIFT  (4U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_LOWPOWERSTATECHANGE_SHIFT    (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_EN  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_LOWPOWERSTATECHANGE_EN       (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_EN)

#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_DIS  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTCTRL_LOWPOWERSTATECHANGE_DIS      (CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_LOWPOWERSTATECHANGE_DIS)


#define CSL_CAM_PRM_PM_CAM_PWRSTCTRL_REG_RESETVAL               (0x00030000U)

/* PM_CAM_PWRSTST_REG */

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_MASK        (0x00000003U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_POWERSTATEST_MASK              (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_RESETVAL    (0x00000003U)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_SHIFT       (0U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_POWERSTATEST_SHIFT             (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_ON          (0x00000003U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_POWERSTATEST_ON                (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_ON)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_OFF         (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_POWERSTATEST_OFF               (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_OFF)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_RESERVED    (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_POWERSTATEST_RESERVED          (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_RESERVED)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_INACTIVE    (0x00000002U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_POWERSTATEST_INACTIVE          (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_POWERSTATEST_INACTIVE)


#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_MASK        (0x00100000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_INTRANSITION_MASK              (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_RESETVAL    (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_SHIFT       (20U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_INTRANSITION_SHIFT             (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_NO          (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_INTRANSITION_NO                (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_NO)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_ONGOING     (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_INTRANSITION_ONGOING           (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_INTRANSITION_ONGOING)


#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_MASK        (0x00000004U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LOGICSTATEST_MASK              (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_RESETVAL    (0x00000001U)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_SHIFT       (2U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LOGICSTATEST_SHIFT             (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_ON          (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LOGICSTATEST_ON                (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_ON)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_OFF         (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LOGICSTATEST_OFF               (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LOGICSTATEST_OFF)


#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_MASK    (0x00000030U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_VIP_BANK_STATEST_MASK          (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_RESETVAL  (0x00000003U)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_SHIFT   (4U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_VIP_BANK_STATEST_SHIFT         (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_MEM_ON  (0x00000003U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_VIP_BANK_STATEST_MEM_ON        (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_MEM_ON)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_RESERVED1  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_VIP_BANK_STATEST_RESERVED1     (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_RESERVED1)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_MEM_OFF  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_VIP_BANK_STATEST_MEM_OFF       (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_MEM_OFF)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_RESERVED  (0x00000002U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_VIP_BANK_STATEST_RESERVED      (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_VIP_BANK_STATEST_RESERVED)


#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_MASK  (0x03000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LASTPOWERSTATEENTERED_MASK     (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_MASK)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_SHIFT  (24U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LASTPOWERSTATEENTERED_SHIFT    (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_SHIFT)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_ON  (0x00000003U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LASTPOWERSTATEENTERED_ON       (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_ON)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_OFF  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LASTPOWERSTATEENTERED_OFF      (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_OFF)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_RET  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LASTPOWERSTATEENTERED_RET      (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_RET)

#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_INACTIVE  (0x00000002U)
/* Below define for backward compatibility */
#define PM_CAM_PWRSTST_LASTPOWERSTATEENTERED_INACTIVE  (CSL_CAM_PRM_PM_CAM_PWRSTST_REG_LASTPOWERSTATEENTERED_INACTIVE)


#define CSL_CAM_PRM_PM_CAM_PWRSTST_REG_RESETVAL                 (0x00000037U)

/* PM_CAM_VIP1_WKDEP_REG */

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_MPU_MASK       (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_SHIFT  (0U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_MPU_SHIFT      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_MPU_ENABLED    (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_MPU_DISABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_MPU_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_MASK  (0x00000004U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP1_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_SHIFT  (2U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_MASK  (0x00000002U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU2_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_SHIFT  (1U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_MASK  (0x00000010U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU1_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_SHIFT  (4U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_IPU1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_IPU1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_MASK  (0x00000020U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP2_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_SHIFT  (5U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_DSP2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_DSP2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_MASK  (0x00000040U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE1_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_SHIFT  (6U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_MASK  (0x00000080U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE2_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_SHIFT  (7U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE3_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_SHIFT  (8U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE3_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE3_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE3_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE3_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_MASK  (0x00000200U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE4_MASK      (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_SHIFT  (9U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE4_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE4_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP1_WKDEP_WKUPDEP_VIP1_EVE4_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_WKUPDEP_VIP1_EVE4_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP1_WKDEP_REG_RESETVAL              (0x00000000U)

/* RM_CAM_VIP1_CONTEXT_REG */

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTCONTEXT_DFF_MASK      (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_MASK)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT  (0U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTCONTEXT_DFF_SHIFT     (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTCONTEXT_DFF_LOST      (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_LOST)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTCONTEXT_DFF_MAINTAINED  (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTMEM_VIP_BANK_MASK     (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_MASK)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_SHIFT  (8U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTMEM_VIP_BANK_SHIFT    (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_SHIFT)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTMEM_VIP_BANK_LOST     (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_LOST)

#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_VIP1_CONTEXT_LOSTMEM_VIP_BANK_MAINTAINED  (CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_LOSTMEM_VIP_BANK_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_VIP1_CONTEXT_REG_RESETVAL            (0x00000101U)

/* PM_CAM_VIP2_WKDEP_REG */

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_MPU_MASK       (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_SHIFT  (0U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_MPU_SHIFT      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_MPU_ENABLED    (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_MPU_DISABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_MPU_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_MASK  (0x00000004U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP1_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_SHIFT  (2U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_MASK  (0x00000002U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU2_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_SHIFT  (1U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_MASK  (0x00000010U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU1_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_SHIFT  (4U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_IPU1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_IPU1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_MASK  (0x00000020U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP2_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_SHIFT  (5U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_DSP2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_DSP2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_MASK  (0x00000040U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE1_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_SHIFT  (6U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_MASK  (0x00000080U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE2_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_SHIFT  (7U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE3_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_SHIFT  (8U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE3_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE3_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE3_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE3_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_MASK  (0x00000200U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE4_MASK      (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_SHIFT  (9U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE4_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE4_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP2_WKDEP_WKUPDEP_VIP2_EVE4_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_WKUPDEP_VIP2_EVE4_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP2_WKDEP_REG_RESETVAL              (0x00000000U)

/* RM_CAM_VIP2_CONTEXT_REG */

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTCONTEXT_DFF_MASK      (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_MASK)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT  (0U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTCONTEXT_DFF_SHIFT     (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTCONTEXT_DFF_LOST      (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_LOST)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTCONTEXT_DFF_MAINTAINED  (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTMEM_VIP_BANK_MASK     (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_MASK)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_SHIFT  (8U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTMEM_VIP_BANK_SHIFT    (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_SHIFT)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTMEM_VIP_BANK_LOST     (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_LOST)

#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_VIP2_CONTEXT_LOSTMEM_VIP_BANK_MAINTAINED  (CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_LOSTMEM_VIP_BANK_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_VIP2_CONTEXT_REG_RESETVAL            (0x00000101U)

/* PM_CAM_VIP3_WKDEP_REG */

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_MPU_MASK       (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_SHIFT  (0U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_MPU_SHIFT      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_MPU_ENABLED    (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_MPU_DISABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_MPU_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_MASK  (0x00000004U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP1_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_SHIFT  (2U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_MASK  (0x00000002U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU2_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_SHIFT  (1U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_MASK  (0x00000010U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU1_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_SHIFT  (4U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_IPU1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_IPU1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_MASK  (0x00000020U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP2_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_SHIFT  (5U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_DSP2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_DSP2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_MASK  (0x00000040U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE1_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_SHIFT  (6U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE1_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE1_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE1_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE1_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_MASK  (0x00000080U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE2_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_SHIFT  (7U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE2_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE2_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE2_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE2_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE3_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_SHIFT  (8U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE3_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE3_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE3_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE3_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_MASK  (0x00000200U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE4_MASK      (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_MASK)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_RESETVAL  (0x00000000U)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_SHIFT  (9U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE4_SHIFT     (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_SHIFT)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_ENABLED  (0x00000001U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE4_ENABLED   (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_ENABLED)

#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define PM_CAM_VIP3_WKDEP_WKUPDEP_VIP3_EVE4_DISABLED  (CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_WKUPDEP_VIP3_EVE4_DISABLED)


#define CSL_CAM_PRM_PM_CAM_VIP3_WKDEP_REG_RESETVAL              (0x00000000U)

/* RM_CAM_VIP3_CONTEXT_REG */

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTCONTEXT_DFF_MASK      (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_MASK)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT  (0U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTCONTEXT_DFF_SHIFT     (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTCONTEXT_DFF_LOST      (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_LOST)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTCONTEXT_DFF_MAINTAINED  (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTMEM_VIP_BANK_MASK     (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_MASK)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_SHIFT  (8U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTMEM_VIP_BANK_SHIFT    (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_SHIFT)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTMEM_VIP_BANK_LOST     (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_LOST)

#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_VIP3_CONTEXT_LOSTMEM_VIP_BANK_MAINTAINED  (CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_LOSTMEM_VIP_BANK_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_VIP3_CONTEXT_REG_RESETVAL            (0x00000101U)

/* RM_CAM_LVDSRX_CONTEXT_REG */

#define CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_LVDSRX_CONTEXT_LOSTCONTEXT_DFF_MASK    (CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_MASK)

#define CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT  (0U)
/* Below define for backward compatibility */
#define RM_CAM_LVDSRX_CONTEXT_LOSTCONTEXT_DFF_SHIFT   (CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT)

#define CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_LVDSRX_CONTEXT_LOSTCONTEXT_DFF_LOST    (CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_LOST)

#define CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_LVDSRX_CONTEXT_LOSTCONTEXT_DFF_MAINTAINED  (CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_LVDSRX_CONTEXT_REG_RESETVAL          (0x00000001U)

/* RM_CAM_CSI1_CONTEXT_REG */

#define CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_CSI1_CONTEXT_LOSTCONTEXT_DFF_MASK      (CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_MASK)

#define CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT  (0U)
/* Below define for backward compatibility */
#define RM_CAM_CSI1_CONTEXT_LOSTCONTEXT_DFF_SHIFT     (CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT)

#define CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_CSI1_CONTEXT_LOSTCONTEXT_DFF_LOST      (CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_LOST)

#define CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_CSI1_CONTEXT_LOSTCONTEXT_DFF_MAINTAINED  (CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_CSI1_CONTEXT_REG_RESETVAL            (0x00000001U)

/* RM_CAM_CSI2_CONTEXT_REG */

#define CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_MASK  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_CSI2_CONTEXT_LOSTCONTEXT_DFF_MASK      (CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_MASK)

#define CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_RESETVAL  (0x00000001U)

#define CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT  (0U)
/* Below define for backward compatibility */
#define RM_CAM_CSI2_CONTEXT_LOSTCONTEXT_DFF_SHIFT     (CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_SHIFT)

#define CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_LOST  (0x00000001U)
/* Below define for backward compatibility */
#define RM_CAM_CSI2_CONTEXT_LOSTCONTEXT_DFF_LOST      (CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_LOST)

#define CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED  (0x00000000U)
/* Below define for backward compatibility */
#define RM_CAM_CSI2_CONTEXT_LOSTCONTEXT_DFF_MAINTAINED  (CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_LOSTCONTEXT_DFF_MAINTAINED)


#define CSL_CAM_PRM_RM_CAM_CSI2_CONTEXT_REG_RESETVAL            (0x00000001U)

#ifdef __cplusplus
}
#endif
#endif
