/*
 * CSLR_INTERRUPT.h - SOC interrupt map header file
 */
/*
 *
 * Copyright (CU) 2013 - 2014 Texas Instruments Incorporated - http://www.ti.com/
 *
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTIONU) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISEU) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>

#ifndef CSLR_INTERRUPT_H
#define CSLR_INTERRUPT_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************
 * IRQ XBAR instance mapping for each core interrupts.
 * This is the IRQ XBAR instance to which a particular interrupt of the core is
 * mapped. This macro could be used to pass the IRQ XBAR instance to the IRQ
 * XBAR connect API of starterware.
 ******************************************************************************/
/* IRQ XBAR Mapping for MPU */
#define CSL_XBAR_INST_MPU_EVENT_CNT         (152UU)
#define CSL_XBAR_INST_MPU_IRQ_4             (1U)
#define CSL_XBAR_INST_MPU_IRQ_7             (2U)
#define CSL_XBAR_INST_MPU_IRQ_8             (3U)
#define CSL_XBAR_INST_MPU_IRQ_9             (4U)
#define CSL_XBAR_INST_MPU_IRQ_10            (5U)
#define CSL_XBAR_INST_MPU_IRQ_11            (6U)
#define CSL_XBAR_INST_MPU_IRQ_12            (7U)
#define CSL_XBAR_INST_MPU_IRQ_13            (8U)
#define CSL_XBAR_INST_MPU_IRQ_14            (9U)
#define CSL_XBAR_INST_MPU_IRQ_15            (10U)
#define CSL_XBAR_INST_MPU_IRQ_16            (11U)
#define CSL_XBAR_INST_MPU_IRQ_17            (12U)
#define CSL_XBAR_INST_MPU_IRQ_18            (13U)
#define CSL_XBAR_INST_MPU_IRQ_19            (14U)
#define CSL_XBAR_INST_MPU_IRQ_20            (15U)
#define CSL_XBAR_INST_MPU_IRQ_21            (16U)
#define CSL_XBAR_INST_MPU_IRQ_22            (17U)
#define CSL_XBAR_INST_MPU_IRQ_23            (18U)
#define CSL_XBAR_INST_MPU_IRQ_24            (19U)
#define CSL_XBAR_INST_MPU_IRQ_25            (20U)
#define CSL_XBAR_INST_MPU_IRQ_26            (21U)
#define CSL_XBAR_INST_MPU_IRQ_27            (22U)
#define CSL_XBAR_INST_MPU_IRQ_28            (23U)
#define CSL_XBAR_INST_MPU_IRQ_29            (24U)
#define CSL_XBAR_INST_MPU_IRQ_30            (25U)
#define CSL_XBAR_INST_MPU_IRQ_31            (26U)
#define CSL_XBAR_INST_MPU_IRQ_32            (27U)
#define CSL_XBAR_INST_MPU_IRQ_33            (28U)
#define CSL_XBAR_INST_MPU_IRQ_34            (29U)
#define CSL_XBAR_INST_MPU_IRQ_35            (30U)
#define CSL_XBAR_INST_MPU_IRQ_36            (31U)
#define CSL_XBAR_INST_MPU_IRQ_37            (32U)
#define CSL_XBAR_INST_MPU_IRQ_38            (33U)
#define CSL_XBAR_INST_MPU_IRQ_39            (34U)
#define CSL_XBAR_INST_MPU_IRQ_40            (35U)
#define CSL_XBAR_INST_MPU_IRQ_41            (36U)
#define CSL_XBAR_INST_MPU_IRQ_42            (37U)
#define CSL_XBAR_INST_MPU_IRQ_43            (38U)
#define CSL_XBAR_INST_MPU_IRQ_44            (39U)
#define CSL_XBAR_INST_MPU_IRQ_45            (40U)
#define CSL_XBAR_INST_MPU_IRQ_46            (41U)
#define CSL_XBAR_INST_MPU_IRQ_47            (42U)
#define CSL_XBAR_INST_MPU_IRQ_48            (43U)
#define CSL_XBAR_INST_MPU_IRQ_49            (44U)
#define CSL_XBAR_INST_MPU_IRQ_50            (45U)
#define CSL_XBAR_INST_MPU_IRQ_51            (46U)
#define CSL_XBAR_INST_MPU_IRQ_52            (47U)
#define CSL_XBAR_INST_MPU_IRQ_53            (48U)
#define CSL_XBAR_INST_MPU_IRQ_54            (49U)
#define CSL_XBAR_INST_MPU_IRQ_55            (50U)
#define CSL_XBAR_INST_MPU_IRQ_56            (51U)
#define CSL_XBAR_INST_MPU_IRQ_57            (52U)
#define CSL_XBAR_INST_MPU_IRQ_58            (53U)
#define CSL_XBAR_INST_MPU_IRQ_59            (54U)
#define CSL_XBAR_INST_MPU_IRQ_60            (55U)
#define CSL_XBAR_INST_MPU_IRQ_61            (56U)
#define CSL_XBAR_INST_MPU_IRQ_62            (57U)
#define CSL_XBAR_INST_MPU_IRQ_63            (58U)
#define CSL_XBAR_INST_MPU_IRQ_64            (59U)
#define CSL_XBAR_INST_MPU_IRQ_65            (60U)
#define CSL_XBAR_INST_MPU_IRQ_66            (61U)
#define CSL_XBAR_INST_MPU_IRQ_67            (62U)
#define CSL_XBAR_INST_MPU_IRQ_68            (63U)
#define CSL_XBAR_INST_MPU_IRQ_69            (64U)
#define CSL_XBAR_INST_MPU_IRQ_70            (65U)
#define CSL_XBAR_INST_MPU_IRQ_71            (66U)
#define CSL_XBAR_INST_MPU_IRQ_72            (67U)
#define CSL_XBAR_INST_MPU_IRQ_73            (68U)
#define CSL_XBAR_INST_MPU_IRQ_74            (69U)
#define CSL_XBAR_INST_MPU_IRQ_75            (70U)
#define CSL_XBAR_INST_MPU_IRQ_76            (71U)
#define CSL_XBAR_INST_MPU_IRQ_77            (72U)
#define CSL_XBAR_INST_MPU_IRQ_78            (73U)
#define CSL_XBAR_INST_MPU_IRQ_79            (74U)
#define CSL_XBAR_INST_MPU_IRQ_80            (75U)
#define CSL_XBAR_INST_MPU_IRQ_81            (76U)
#define CSL_XBAR_INST_MPU_IRQ_82            (77U)
#define CSL_XBAR_INST_MPU_IRQ_83            (78U)
#define CSL_XBAR_INST_MPU_IRQ_84            (79U)
#define CSL_XBAR_INST_MPU_IRQ_85            (80U)
#define CSL_XBAR_INST_MPU_IRQ_86            (81U)
#define CSL_XBAR_INST_MPU_IRQ_87            (82U)
#define CSL_XBAR_INST_MPU_IRQ_88            (83U)
#define CSL_XBAR_INST_MPU_IRQ_89            (84U)
#define CSL_XBAR_INST_MPU_IRQ_90            (85U)
#define CSL_XBAR_INST_MPU_IRQ_91            (86U)
#define CSL_XBAR_INST_MPU_IRQ_92            (87U)
#define CSL_XBAR_INST_MPU_IRQ_93            (88U)
#define CSL_XBAR_INST_MPU_IRQ_94            (89U)
#define CSL_XBAR_INST_MPU_IRQ_95            (90U)
#define CSL_XBAR_INST_MPU_IRQ_96            (91U)
#define CSL_XBAR_INST_MPU_IRQ_97            (92U)
#define CSL_XBAR_INST_MPU_IRQ_98            (93U)
#define CSL_XBAR_INST_MPU_IRQ_99            (94U)
#define CSL_XBAR_INST_MPU_IRQ_100           (95U)
#define CSL_XBAR_INST_MPU_IRQ_101           (96U)
#define CSL_XBAR_INST_MPU_IRQ_102           (97U)
#define CSL_XBAR_INST_MPU_IRQ_103           (98U)
#define CSL_XBAR_INST_MPU_IRQ_104           (99U)
#define CSL_XBAR_INST_MPU_IRQ_105           (100U)
#define CSL_XBAR_INST_MPU_IRQ_106           (101U)
#define CSL_XBAR_INST_MPU_IRQ_107           (102U)
#define CSL_XBAR_INST_MPU_IRQ_108           (103U)
#define CSL_XBAR_INST_MPU_IRQ_109           (104U)
#define CSL_XBAR_INST_MPU_IRQ_110           (105U)
#define CSL_XBAR_INST_MPU_IRQ_111           (106U)
#define CSL_XBAR_INST_MPU_IRQ_112           (107U)
#define CSL_XBAR_INST_MPU_IRQ_113           (108U)
#define CSL_XBAR_INST_MPU_IRQ_114           (109U)
#define CSL_XBAR_INST_MPU_IRQ_115           (110U)
#define CSL_XBAR_INST_MPU_IRQ_116           (111U)
#define CSL_XBAR_INST_MPU_IRQ_117           (112U)
#define CSL_XBAR_INST_MPU_IRQ_118           (113U)
#define CSL_XBAR_INST_MPU_IRQ_119           (114U)
#define CSL_XBAR_INST_MPU_IRQ_120           (115U)
#define CSL_XBAR_INST_MPU_IRQ_121           (116U)
#define CSL_XBAR_INST_MPU_IRQ_122           (117U)
#define CSL_XBAR_INST_MPU_IRQ_123           (118U)
#define CSL_XBAR_INST_MPU_IRQ_124           (119U)
#define CSL_XBAR_INST_MPU_IRQ_125           (120U)
#define CSL_XBAR_INST_MPU_IRQ_126           (121U)
#define CSL_XBAR_INST_MPU_IRQ_127           (122U)
#define CSL_XBAR_INST_MPU_IRQ_128           (123U)
#define CSL_XBAR_INST_MPU_IRQ_129           (124U)
#define CSL_XBAR_INST_MPU_IRQ_130           (125U)
#define CSL_XBAR_INST_MPU_IRQ_133           (126U)
#define CSL_XBAR_INST_MPU_IRQ_134           (127U)
#define CSL_XBAR_INST_MPU_IRQ_135           (128U)
#define CSL_XBAR_INST_MPU_IRQ_136           (129U)
#define CSL_XBAR_INST_MPU_IRQ_137           (130U)
#define CSL_XBAR_INST_MPU_IRQ_138           (131U)
#define CSL_XBAR_INST_MPU_IRQ_141           (134U)
#define CSL_XBAR_INST_MPU_IRQ_142           (135U)
#define CSL_XBAR_INST_MPU_IRQ_143           (136U)
#define CSL_XBAR_INST_MPU_IRQ_144           (137U)
#define CSL_XBAR_INST_MPU_IRQ_145           (138U)
#define CSL_XBAR_INST_MPU_IRQ_146           (139U)
#define CSL_XBAR_INST_MPU_IRQ_147           (140U)
#define CSL_XBAR_INST_MPU_IRQ_148           (141U)
#define CSL_XBAR_INST_MPU_IRQ_149           (142U)
#define CSL_XBAR_INST_MPU_IRQ_150           (143U)
#define CSL_XBAR_INST_MPU_IRQ_151           (144U)
#define CSL_XBAR_INST_MPU_IRQ_152           (145U)
#define CSL_XBAR_INST_MPU_IRQ_153           (146U)
#define CSL_XBAR_INST_MPU_IRQ_154           (147U)
#define CSL_XBAR_INST_MPU_IRQ_155           (148U)
#define CSL_XBAR_INST_MPU_IRQ_156           (149U)
#define CSL_XBAR_INST_MPU_IRQ_157           (150U)
#define CSL_XBAR_INST_MPU_IRQ_158           (151U)
#define CSL_XBAR_INST_MPU_IRQ_159           (152U)

/* IRQ XBAR Mapping for DSP1 */
#define CSL_XBAR_INST_DSP1_EVENT_CNT        (64U)
#define CSL_XBAR_INST_DSP1_IRQ_32           (1U)
#define CSL_XBAR_INST_DSP1_IRQ_33           (2U)
#define CSL_XBAR_INST_DSP1_IRQ_34           (3U)
#define CSL_XBAR_INST_DSP1_IRQ_35           (4U)
#define CSL_XBAR_INST_DSP1_IRQ_36           (5U)
#define CSL_XBAR_INST_DSP1_IRQ_37           (6U)
#define CSL_XBAR_INST_DSP1_IRQ_38           (7U)
#define CSL_XBAR_INST_DSP1_IRQ_39           (8U)
#define CSL_XBAR_INST_DSP1_IRQ_40           (9U)
#define CSL_XBAR_INST_DSP1_IRQ_41           (10U)
#define CSL_XBAR_INST_DSP1_IRQ_42           (11U)
#define CSL_XBAR_INST_DSP1_IRQ_43           (12U)
#define CSL_XBAR_INST_DSP1_IRQ_44           (13U)
#define CSL_XBAR_INST_DSP1_IRQ_45           (14U)
#define CSL_XBAR_INST_DSP1_IRQ_46           (15U)
#define CSL_XBAR_INST_DSP1_IRQ_47           (16U)
#define CSL_XBAR_INST_DSP1_IRQ_48           (17U)
#define CSL_XBAR_INST_DSP1_IRQ_49           (18U)
#define CSL_XBAR_INST_DSP1_IRQ_50           (19U)
#define CSL_XBAR_INST_DSP1_IRQ_51           (20U)
#define CSL_XBAR_INST_DSP1_IRQ_52           (21U)
#define CSL_XBAR_INST_DSP1_IRQ_53           (22U)
#define CSL_XBAR_INST_DSP1_IRQ_54           (23U)
#define CSL_XBAR_INST_DSP1_IRQ_55           (24U)
#define CSL_XBAR_INST_DSP1_IRQ_56           (25U)
#define CSL_XBAR_INST_DSP1_IRQ_57           (26U)
#define CSL_XBAR_INST_DSP1_IRQ_58           (27U)
#define CSL_XBAR_INST_DSP1_IRQ_59           (28U)
#define CSL_XBAR_INST_DSP1_IRQ_60           (29U)
#define CSL_XBAR_INST_DSP1_IRQ_61           (30U)
#define CSL_XBAR_INST_DSP1_IRQ_62           (31U)
#define CSL_XBAR_INST_DSP1_IRQ_63           (32U)
#define CSL_XBAR_INST_DSP1_IRQ_64           (33U)
#define CSL_XBAR_INST_DSP1_IRQ_65           (34U)
#define CSL_XBAR_INST_DSP1_IRQ_66           (35U)
#define CSL_XBAR_INST_DSP1_IRQ_67           (36U)
#define CSL_XBAR_INST_DSP1_IRQ_68           (37U)
#define CSL_XBAR_INST_DSP1_IRQ_69           (38U)
#define CSL_XBAR_INST_DSP1_IRQ_70           (39U)
#define CSL_XBAR_INST_DSP1_IRQ_71           (40U)
#define CSL_XBAR_INST_DSP1_IRQ_72           (41U)
#define CSL_XBAR_INST_DSP1_IRQ_73           (42U)
#define CSL_XBAR_INST_DSP1_IRQ_74           (43U)
#define CSL_XBAR_INST_DSP1_IRQ_75           (44U)
#define CSL_XBAR_INST_DSP1_IRQ_76           (45U)
#define CSL_XBAR_INST_DSP1_IRQ_77           (46U)
#define CSL_XBAR_INST_DSP1_IRQ_78           (47U)
#define CSL_XBAR_INST_DSP1_IRQ_79           (48U)
#define CSL_XBAR_INST_DSP1_IRQ_80           (49U)
#define CSL_XBAR_INST_DSP1_IRQ_81           (50U)
#define CSL_XBAR_INST_DSP1_IRQ_82           (51U)
#define CSL_XBAR_INST_DSP1_IRQ_83           (52U)
#define CSL_XBAR_INST_DSP1_IRQ_84           (53U)
#define CSL_XBAR_INST_DSP1_IRQ_85           (54U)
#define CSL_XBAR_INST_DSP1_IRQ_86           (55U)
#define CSL_XBAR_INST_DSP1_IRQ_87           (56U)
#define CSL_XBAR_INST_DSP1_IRQ_88           (57U)
#define CSL_XBAR_INST_DSP1_IRQ_89           (58U)
#define CSL_XBAR_INST_DSP1_IRQ_90           (59U)
#define CSL_XBAR_INST_DSP1_IRQ_91           (60U)
#define CSL_XBAR_INST_DSP1_IRQ_92           (61U)
#define CSL_XBAR_INST_DSP1_IRQ_93           (62U)
#define CSL_XBAR_INST_DSP1_IRQ_94           (63U)
#define CSL_XBAR_INST_DSP1_IRQ_95           (64U)

/* IRQ XBAR Mapping for DSP2 */
#define CSL_XBAR_INST_DSP2_EVENT_CNT        (64U)
#define CSL_XBAR_INST_DSP2_IRQ_32           (1U)
#define CSL_XBAR_INST_DSP2_IRQ_33           (2U)
#define CSL_XBAR_INST_DSP2_IRQ_34           (3U)
#define CSL_XBAR_INST_DSP2_IRQ_35           (4U)
#define CSL_XBAR_INST_DSP2_IRQ_36           (5U)
#define CSL_XBAR_INST_DSP2_IRQ_37           (6U)
#define CSL_XBAR_INST_DSP2_IRQ_38           (7U)
#define CSL_XBAR_INST_DSP2_IRQ_39           (8U)
#define CSL_XBAR_INST_DSP2_IRQ_40           (9U)
#define CSL_XBAR_INST_DSP2_IRQ_41           (10U)
#define CSL_XBAR_INST_DSP2_IRQ_42           (11U)
#define CSL_XBAR_INST_DSP2_IRQ_43           (12U)
#define CSL_XBAR_INST_DSP2_IRQ_44           (13U)
#define CSL_XBAR_INST_DSP2_IRQ_45           (14U)
#define CSL_XBAR_INST_DSP2_IRQ_46           (15U)
#define CSL_XBAR_INST_DSP2_IRQ_47           (16U)
#define CSL_XBAR_INST_DSP2_IRQ_48           (17U)
#define CSL_XBAR_INST_DSP2_IRQ_49           (18U)
#define CSL_XBAR_INST_DSP2_IRQ_50           (19U)
#define CSL_XBAR_INST_DSP2_IRQ_51           (20U)
#define CSL_XBAR_INST_DSP2_IRQ_52           (21U)
#define CSL_XBAR_INST_DSP2_IRQ_53           (22U)
#define CSL_XBAR_INST_DSP2_IRQ_54           (23U)
#define CSL_XBAR_INST_DSP2_IRQ_55           (24U)
#define CSL_XBAR_INST_DSP2_IRQ_56           (25U)
#define CSL_XBAR_INST_DSP2_IRQ_57           (26U)
#define CSL_XBAR_INST_DSP2_IRQ_58           (27U)
#define CSL_XBAR_INST_DSP2_IRQ_59           (28U)
#define CSL_XBAR_INST_DSP2_IRQ_60           (29U)
#define CSL_XBAR_INST_DSP2_IRQ_61           (30U)
#define CSL_XBAR_INST_DSP2_IRQ_62           (31U)
#define CSL_XBAR_INST_DSP2_IRQ_63           (32U)
#define CSL_XBAR_INST_DSP2_IRQ_64           (33U)
#define CSL_XBAR_INST_DSP2_IRQ_65           (34U)
#define CSL_XBAR_INST_DSP2_IRQ_66           (35U)
#define CSL_XBAR_INST_DSP2_IRQ_67           (36U)
#define CSL_XBAR_INST_DSP2_IRQ_68           (37U)
#define CSL_XBAR_INST_DSP2_IRQ_69           (38U)
#define CSL_XBAR_INST_DSP2_IRQ_70           (39U)
#define CSL_XBAR_INST_DSP2_IRQ_71           (40U)
#define CSL_XBAR_INST_DSP2_IRQ_72           (41U)
#define CSL_XBAR_INST_DSP2_IRQ_73           (42U)
#define CSL_XBAR_INST_DSP2_IRQ_74           (43U)
#define CSL_XBAR_INST_DSP2_IRQ_75           (44U)
#define CSL_XBAR_INST_DSP2_IRQ_76           (45U)
#define CSL_XBAR_INST_DSP2_IRQ_77           (46U)
#define CSL_XBAR_INST_DSP2_IRQ_78           (47U)
#define CSL_XBAR_INST_DSP2_IRQ_79           (48U)
#define CSL_XBAR_INST_DSP2_IRQ_80           (49U)
#define CSL_XBAR_INST_DSP2_IRQ_81           (50U)
#define CSL_XBAR_INST_DSP2_IRQ_82           (51U)
#define CSL_XBAR_INST_DSP2_IRQ_83           (52U)
#define CSL_XBAR_INST_DSP2_IRQ_84           (53U)
#define CSL_XBAR_INST_DSP2_IRQ_85           (54U)
#define CSL_XBAR_INST_DSP2_IRQ_86           (55U)
#define CSL_XBAR_INST_DSP2_IRQ_87           (56U)
#define CSL_XBAR_INST_DSP2_IRQ_88           (57U)
#define CSL_XBAR_INST_DSP2_IRQ_89           (58U)
#define CSL_XBAR_INST_DSP2_IRQ_90           (59U)
#define CSL_XBAR_INST_DSP2_IRQ_91           (60U)
#define CSL_XBAR_INST_DSP2_IRQ_92           (61U)
#define CSL_XBAR_INST_DSP2_IRQ_93           (62U)
#define CSL_XBAR_INST_DSP2_IRQ_94           (63U)
#define CSL_XBAR_INST_DSP2_IRQ_95           (64U)

/* IRQ XBAR Mapping for IPU1 */
#define CSL_XBAR_INST_IPU1_EVENT_CNT        (57U)
#define CSL_XBAR_INST_IPU1_IRQ_23           (1U)
#define CSL_XBAR_INST_IPU1_IRQ_24           (2U)
#define CSL_XBAR_INST_IPU1_IRQ_25           (3U)
#define CSL_XBAR_INST_IPU1_IRQ_26           (4U)
#define CSL_XBAR_INST_IPU1_IRQ_27           (5U)
#define CSL_XBAR_INST_IPU1_IRQ_28           (6U)
#define CSL_XBAR_INST_IPU1_IRQ_29           (7U)
#define CSL_XBAR_INST_IPU1_IRQ_30           (8U)
#define CSL_XBAR_INST_IPU1_IRQ_31           (9U)
#define CSL_XBAR_INST_IPU1_IRQ_32           (10U)
#define CSL_XBAR_INST_IPU1_IRQ_33           (11U)
#define CSL_XBAR_INST_IPU1_IRQ_34           (12U)
#define CSL_XBAR_INST_IPU1_IRQ_35           (13U)
#define CSL_XBAR_INST_IPU1_IRQ_36           (14U)
#define CSL_XBAR_INST_IPU1_IRQ_37           (15U)
#define CSL_XBAR_INST_IPU1_IRQ_38           (16U)
#define CSL_XBAR_INST_IPU1_IRQ_39           (17U)
#define CSL_XBAR_INST_IPU1_IRQ_40           (18U)
#define CSL_XBAR_INST_IPU1_IRQ_41           (19U)
#define CSL_XBAR_INST_IPU1_IRQ_42           (20U)
#define CSL_XBAR_INST_IPU1_IRQ_43           (21U)
#define CSL_XBAR_INST_IPU1_IRQ_44           (22U)
#define CSL_XBAR_INST_IPU1_IRQ_45           (23U)
#define CSL_XBAR_INST_IPU1_IRQ_46           (24U)
#define CSL_XBAR_INST_IPU1_IRQ_47           (25U)
#define CSL_XBAR_INST_IPU1_IRQ_48           (26U)
#define CSL_XBAR_INST_IPU1_IRQ_49           (27U)
#define CSL_XBAR_INST_IPU1_IRQ_50           (28U)
#define CSL_XBAR_INST_IPU1_IRQ_51           (29U)
#define CSL_XBAR_INST_IPU1_IRQ_52           (30U)
#define CSL_XBAR_INST_IPU1_IRQ_53           (31U)
#define CSL_XBAR_INST_IPU1_IRQ_54           (32U)
#define CSL_XBAR_INST_IPU1_IRQ_55           (33U)
#define CSL_XBAR_INST_IPU1_IRQ_56           (34U)
#define CSL_XBAR_INST_IPU1_IRQ_57           (35U)
#define CSL_XBAR_INST_IPU1_IRQ_58           (36U)
#define CSL_XBAR_INST_IPU1_IRQ_59           (37U)
#define CSL_XBAR_INST_IPU1_IRQ_60           (38U)
#define CSL_XBAR_INST_IPU1_IRQ_61           (39U)
#define CSL_XBAR_INST_IPU1_IRQ_62           (40U)
#define CSL_XBAR_INST_IPU1_IRQ_63           (41U)
#define CSL_XBAR_INST_IPU1_IRQ_64           (42U)
#define CSL_XBAR_INST_IPU1_IRQ_65           (43U)
#define CSL_XBAR_INST_IPU1_IRQ_66           (44U)
#define CSL_XBAR_INST_IPU1_IRQ_67           (45U)
#define CSL_XBAR_INST_IPU1_IRQ_68           (46U)
#define CSL_XBAR_INST_IPU1_IRQ_69           (47U)
#define CSL_XBAR_INST_IPU1_IRQ_70           (48U)
#define CSL_XBAR_INST_IPU1_IRQ_71           (49U)
#define CSL_XBAR_INST_IPU1_IRQ_72           (50U)
#define CSL_XBAR_INST_IPU1_IRQ_73           (51U)
#define CSL_XBAR_INST_IPU1_IRQ_74           (52U)
#define CSL_XBAR_INST_IPU1_IRQ_75           (53U)
#define CSL_XBAR_INST_IPU1_IRQ_76           (54U)
#define CSL_XBAR_INST_IPU1_IRQ_77           (55U)
#define CSL_XBAR_INST_IPU1_IRQ_78           (56U)
#define CSL_XBAR_INST_IPU1_IRQ_79           (57U)

/* IRQ XBAR Mapping for IPU2 */
#define CSL_XBAR_INST_IPU2_EVENT_CNT        (57U)
#define CSL_XBAR_INST_IPU2_IRQ_23           (1U)
#define CSL_XBAR_INST_IPU2_IRQ_24           (2U)
#define CSL_XBAR_INST_IPU2_IRQ_25           (3U)
#define CSL_XBAR_INST_IPU2_IRQ_26           (4U)
#define CSL_XBAR_INST_IPU2_IRQ_27           (5U)
#define CSL_XBAR_INST_IPU2_IRQ_28           (6U)
#define CSL_XBAR_INST_IPU2_IRQ_29           (7U)
#define CSL_XBAR_INST_IPU2_IRQ_30           (8U)
#define CSL_XBAR_INST_IPU2_IRQ_31           (9U)
#define CSL_XBAR_INST_IPU2_IRQ_32           (10U)
#define CSL_XBAR_INST_IPU2_IRQ_33           (11U)
#define CSL_XBAR_INST_IPU2_IRQ_34           (12U)
#define CSL_XBAR_INST_IPU2_IRQ_35           (13U)
#define CSL_XBAR_INST_IPU2_IRQ_36           (14U)
#define CSL_XBAR_INST_IPU2_IRQ_37           (15U)
#define CSL_XBAR_INST_IPU2_IRQ_38           (16U)
#define CSL_XBAR_INST_IPU2_IRQ_39           (17U)
#define CSL_XBAR_INST_IPU2_IRQ_40           (18U)
#define CSL_XBAR_INST_IPU2_IRQ_41           (19U)
#define CSL_XBAR_INST_IPU2_IRQ_42           (20U)
#define CSL_XBAR_INST_IPU2_IRQ_43           (21U)
#define CSL_XBAR_INST_IPU2_IRQ_44           (22U)
#define CSL_XBAR_INST_IPU2_IRQ_45           (23U)
#define CSL_XBAR_INST_IPU2_IRQ_46           (24U)
#define CSL_XBAR_INST_IPU2_IRQ_47           (25U)
#define CSL_XBAR_INST_IPU2_IRQ_48           (26U)
#define CSL_XBAR_INST_IPU2_IRQ_49           (27U)
#define CSL_XBAR_INST_IPU2_IRQ_50           (28U)
#define CSL_XBAR_INST_IPU2_IRQ_51           (29U)
#define CSL_XBAR_INST_IPU2_IRQ_52           (30U)
#define CSL_XBAR_INST_IPU2_IRQ_53           (31U)
#define CSL_XBAR_INST_IPU2_IRQ_54           (32U)
#define CSL_XBAR_INST_IPU2_IRQ_55           (33U)
#define CSL_XBAR_INST_IPU2_IRQ_56           (34U)
#define CSL_XBAR_INST_IPU2_IRQ_57           (35U)
#define CSL_XBAR_INST_IPU2_IRQ_58           (36U)
#define CSL_XBAR_INST_IPU2_IRQ_59           (37U)
#define CSL_XBAR_INST_IPU2_IRQ_60           (38U)
#define CSL_XBAR_INST_IPU2_IRQ_61           (39U)
#define CSL_XBAR_INST_IPU2_IRQ_62           (40U)
#define CSL_XBAR_INST_IPU2_IRQ_63           (41U)
#define CSL_XBAR_INST_IPU2_IRQ_64           (42U)
#define CSL_XBAR_INST_IPU2_IRQ_65           (43U)
#define CSL_XBAR_INST_IPU2_IRQ_66           (44U)
#define CSL_XBAR_INST_IPU2_IRQ_67           (45U)
#define CSL_XBAR_INST_IPU2_IRQ_68           (46U)
#define CSL_XBAR_INST_IPU2_IRQ_69           (47U)
#define CSL_XBAR_INST_IPU2_IRQ_70           (48U)
#define CSL_XBAR_INST_IPU2_IRQ_71           (49U)
#define CSL_XBAR_INST_IPU2_IRQ_72           (50U)
#define CSL_XBAR_INST_IPU2_IRQ_73           (51U)
#define CSL_XBAR_INST_IPU2_IRQ_74           (52U)
#define CSL_XBAR_INST_IPU2_IRQ_75           (53U)
#define CSL_XBAR_INST_IPU2_IRQ_76           (54U)
#define CSL_XBAR_INST_IPU2_IRQ_77           (55U)
#define CSL_XBAR_INST_IPU2_IRQ_78           (56U)
#define CSL_XBAR_INST_IPU2_IRQ_79           (57U)

/******************************************************************************
 * DMA XBAR instance mapping for each DMA instances.
 * This is the DMA XBAR instance to which a particular DMA event is
 * mapped. This macro could be used to pass the DMA XBAR instance to the DMA
 * XBAR connect API of starterware.
 ******************************************************************************/
/* DMA XBAR Mapping for System DMA */
#define CSL_XBAR_INST_DMA_SYSTEM_EVENT_CNT  (127U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_0     (1U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_1     (2U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_2     (3U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_3     (4U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_4     (5U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_5     (6U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_6     (7U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_7     (8U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_8     (9U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_9     (10U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_10    (11U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_11    (12U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_12    (13U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_13    (14U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_14    (15U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_15    (16U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_16    (17U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_17    (18U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_18    (19U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_19    (20U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_20    (21U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_21    (22U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_22    (23U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_23    (24U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_24    (25U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_25    (26U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_26    (27U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_27    (28U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_28    (29U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_29    (30U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_30    (31U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_31    (32U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_32    (33U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_33    (34U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_34    (35U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_35    (36U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_36    (37U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_37    (38U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_38    (39U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_39    (40U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_40    (41U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_41    (42U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_42    (43U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_43    (44U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_44    (45U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_45    (46U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_46    (47U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_47    (48U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_48    (49U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_49    (50U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_50    (51U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_51    (52U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_52    (53U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_53    (54U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_54    (55U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_55    (56U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_56    (57U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_57    (58U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_58    (59U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_59    (60U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_60    (61U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_61    (62U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_62    (63U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_63    (64U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_64    (65U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_65    (66U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_66    (67U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_67    (68U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_68    (69U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_69    (70U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_70    (71U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_71    (72U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_72    (73U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_73    (74U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_74    (75U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_75    (76U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_76    (77U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_77    (78U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_78    (79U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_79    (80U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_80    (81U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_81    (82U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_82    (83U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_83    (84U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_84    (85U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_85    (86U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_86    (87U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_87    (88U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_88    (89U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_89    (90U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_90    (91U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_91    (92U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_92    (93U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_93    (94U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_94    (95U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_95    (96U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_96    (97U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_97    (98U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_98    (99U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_99    (100U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_100   (101U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_101   (102U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_102   (103U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_103   (104U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_104   (105U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_105   (106U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_106   (107U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_107   (108U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_108   (109U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_109   (110U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_110   (111U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_111   (112U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_112   (113U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_113   (114U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_114   (115U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_115   (116U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_116   (117U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_117   (118U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_118   (119U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_119   (120U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_120   (121U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_121   (122U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_122   (123U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_123   (124U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_124   (125U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_125   (126U)
#define CSL_XBAR_INST_DMA_SYSTEM_DREQ_126   (127U)

/* DMA XBAR Mapping for EDMA3 DMA */
#define CSL_XBAR_INST_DMA_EDMA_EVENT_CNT    (64U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_0       (1U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_1       (2U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_2       (3U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_3       (4U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_4       (5U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_5       (6U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_6       (7U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_7       (8U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_8       (9U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_9       (10U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_10      (11U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_11      (12U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_12      (13U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_13      (14U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_14      (15U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_15      (16U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_16      (17U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_17      (18U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_18      (19U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_19      (20U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_20      (21U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_21      (22U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_22      (23U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_23      (24U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_24      (25U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_25      (26U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_26      (27U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_27      (28U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_28      (29U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_29      (30U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_30      (31U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_31      (32U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_32      (33U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_33      (34U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_34      (35U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_35      (36U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_36      (37U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_37      (38U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_38      (39U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_39      (40U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_40      (41U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_41      (42U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_42      (43U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_43      (44U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_44      (45U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_45      (46U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_46      (47U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_47      (48U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_48      (49U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_49      (50U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_50      (51U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_51      (52U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_52      (53U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_53      (54U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_54      (55U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_55      (56U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_56      (57U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_57      (58U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_58      (59U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_59      (60U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_60      (61U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_61      (62U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_62      (63U)
#define CSL_XBAR_INST_DMA_EDMA_DREQ_63      (64U)

/* DMA XBAR Mapping for DSP1 DMA */
#define CSL_XBAR_INST_DMA_DSP1_EVENT_CNT    (20U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_0       (1U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_1       (2U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_2       (3U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_3       (4U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_4       (5U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_5       (6U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_6       (7U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_7       (8U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_8       (9U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_9       (10U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_10      (11U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_11      (12U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_12      (13U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_13      (14U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_14      (15U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_15      (16U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_16      (17U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_17      (18U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_18      (19U)
#define CSL_XBAR_INST_DMA_DSP1_DREQ_19      (20U)

/* DMA XBAR Mapping for DSP2 DMA */
#define CSL_XBAR_INST_DMA_DSP2_EVENT_CNT    (20U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_0       (1U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_1       (2U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_2       (3U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_3       (4U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_4       (5U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_5       (6U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_6       (7U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_7       (8U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_8       (9U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_9       (10U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_10      (11U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_11      (12U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_12      (13U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_13      (14U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_14      (15U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_15      (16U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_16      (17U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_17      (18U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_18      (19U)
#define CSL_XBAR_INST_DMA_DSP2_DREQ_19      (20U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_INTERRUPT_H */
