/********************************************************************
 * Copyright (C) 2013-2014 Texas Instruments Incorporated.
 * 
 *  Redistribution and use in source and binary forms, with or without 
 *  modification, are permitted provided that the following conditions 
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the   
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/
#ifndef CSLR_WKUPAON_CM_H
#define CSLR_WKUPAON_CM_H

#ifdef __cplusplus
extern "C"
{
#endif
#include <ti/csl/cslr.h>
#include <ti/csl/tistdtypes.h>


/**************************************************************************
* Register Overlay Structure for __ALL__
**************************************************************************/
typedef struct {
    volatile Uint32 CM_WKUPAON_CLKSTCTRL_REG;
    volatile Uint8  RSVD0[28];
    volatile Uint32 CM_WKUPAON_L4_WKUP_CLKCTRL_REG;
    volatile Uint8  RSVD1[4];
    volatile Uint32 CM_WKUPAON_WD_TIMER1_CLKCTRL_REG;
    volatile Uint8  RSVD2[4];
    volatile Uint32 CM_WKUPAON_WD_TIMER2_CLKCTRL_REG;
    volatile Uint8  RSVD3[4];
    volatile Uint32 CM_WKUPAON_GPIO1_CLKCTRL_REG;
    volatile Uint8  RSVD4[4];
    volatile Uint32 CM_WKUPAON_TIMER1_CLKCTRL_REG;
    volatile Uint8  RSVD5[4];
    volatile Uint32 CM_WKUPAON_TIMER12_CLKCTRL_REG;
    volatile Uint8  RSVD6[4];
    volatile Uint32 CM_WKUPAON_COUNTER_32K_CLKCTRL_REG;
    volatile Uint8  RSVD7[12];
    volatile Uint32 CM_WKUPAON_SAR_RAM_CLKCTRL_REG;
    volatile Uint8  RSVD8[20];
    volatile Uint32 CM_WKUPAON_KBD_CLKCTRL_REG;
    volatile Uint8  RSVD9[4];
    volatile Uint32 CM_WKUPAON_UART10_CLKCTRL_REG;
    volatile Uint8  RSVD10[4];
    volatile Uint32 CM_WKUPAON_DCAN1_CLKCTRL_REG;
    volatile Uint8  RSVD11[4];
    volatile Uint32 CM_WKUPAON_SCRM_CLKCTRL_REG;
    volatile Uint8  RSVD12[4];
    volatile Uint32 CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG;
    volatile Uint8  RSVD13[4];
    volatile Uint32 CM_WKUPAON_ADC_CLKCTRL_REG;
    volatile Uint8  RSVD14[12];
    volatile Uint32 CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG;
    volatile Uint8  RSVD15[4];
    volatile Uint32 CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG;
    volatile Uint8  RSVD16[4];
    volatile Uint32 CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG;
    volatile Uint8  RSVD17[4];
    volatile Uint32 CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG;
    volatile Uint8  RSVD18[4];
    volatile Uint32 CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG;
    volatile Uint8  RSVD19[4];
    volatile Uint32 CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG;
} CSL_wkupaon_cmRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

/* This register enables the domain power state transition. It controls the HW
 * supervised domain power state transition between ON-ACTIVE and ON-INACTIVE
 * states. It also hold one status bit per clock input of the domain. */
#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG                 (0x0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL   (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG)


/* This register manages the WKUPAON clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG           (0x20U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG)


/* This register manages the WD_TIMER1 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG         (0x28U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG)


/* This register manages the WD_TIMER2 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG         (0x30U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG)


/* This register manages the GPIO1 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG             (0x38U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG)


/* This register manages the TIMER1 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG            (0x40U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG)


/* This register manages the TIMER12 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG           (0x48U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG)


/* This register manages the COUNTER_32K clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG       (0x50U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG)


/* This register manages the SAR_RAM clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG           (0x60U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG)


/* This register manages the KBD clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG               (0x78U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG)


/* This register manages the UART10 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG            (0x80U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG)


/* This register manages the DCAN1 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG             (0x88U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG)


/* This register manages the SCRM clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG              (0x90U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG)


/* This register manages the clock delivered to the IO Slew rate compensation
 * cells. [warm reset insensitive] */
#define CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG         (0x98U)
/* Below define for backward compatibility */
#define CM_WKUPAON_IO_SRCOMP_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG)


/* This register manages the ADC clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG               (0xA0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG)


/* This register manages the SPARE_SAFETY1 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG     (0xB0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG)


/* This register manages the SPARE_SAFETY2 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG     (0xB8U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG)


/* This register manages the SPARE_SAFETY3 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG     (0xC0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG)


/* This register manages the SPARE_SAFETY4 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG     (0xC8U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG)


/* This register manages the SPARE_UNKNOWN2 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG    (0xD0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG)


/* This register manages the SPARE_UNKNOWN3 clocks. */
#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG    (0xD8U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG)



/**************************************************************************
* Field Definition Macros
**************************************************************************/

/* CM_WKUPAON_CLKSTCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKTRCTRL_MASK           (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKTRCTRL_SHIFT          (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_NO_SLEEP  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKTRCTRL_NO_SLEEP       (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_NO_SLEEP)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_RESERVED_1  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKTRCTRL_RESERVED_1     (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_RESERVED_1)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_SW_WKUP  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKTRCTRL_SW_WKUP        (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_SW_WKUP)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_HW_AUTO  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKTRCTRL_HW_AUTO        (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKTRCTRL_HW_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_SHIFT  (8U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_MASK  (0x00000200U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ABE_LP_CLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_SHIFT  (9U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ABE_LP_CLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ABE_LP_CLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ABE_LP_CLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ABE_LP_CLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_MASK  (0x00000800U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_SYS_GFCLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_SHIFT  (11U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_SYS_GFCLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_SYS_GFCLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_SYS_GFCLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_SYS_GFCLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_MASK  (0x00001000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_GICLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_SHIFT  (12U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_GICLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_GICLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_GICLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_GICLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_MASK  (0x00002000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_SHIFT  (13U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_WKUPAON_IO_SRCOMP_GFCLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_MASK  (0x00004000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_FUNC_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_SHIFT  (14U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_FUNC_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_FUNC_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_FUNC_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_FUNC_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_MASK  (0x00008000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_ALL_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_SHIFT  (15U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_ALL_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_ALL_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_SYS_CLK_ALL_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_SYS_CLK_ALL_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_MASK  (0x00010000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_DCAN1_SYS_CLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_DCAN1_SYS_CLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_DCAN1_SYS_CLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_DCAN1_SYS_CLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_DCAN1_SYS_CLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_MASK  (0x00020000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_TIMER1_GFCLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_SHIFT  (17U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_TIMER1_GFCLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_TIMER1_GFCLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_TIMER1_GFCLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_TIMER1_GFCLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_MASK  (0x00040000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_UART10_GFCLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_SHIFT  (18U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_UART10_GFCLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_UART10_GFCLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_UART10_GFCLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_UART10_GFCLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_MASK  (0x00000400U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_GFCLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_SHIFT  (10U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_GFCLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_GFCLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_GFCLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_GFCLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_MASK  (0x00080000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_L3_GICLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_SHIFT  (19U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_L3_GICLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_INACT  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_L3_GICLK_INACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_INACT)

#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_ACT  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_CLKSTCTRL_CLKACTIVITY_ADC_L3_GICLK_ACT  (CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_CLKACTIVITY_ADC_L3_GICLK_ACT)


#define CSL_WKUPAON_CM_CM_WKUPAON_CLKSTCTRL_REG_RESETVAL        (0x00000000U)

/* CM_WKUPAON_L4_WKUP_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_MODULEMODE_MASK    (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_MODULEMODE_SHIFT   (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_MODULEMODE_AUTO    (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_IDLEST_MASK        (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_IDLEST_SHIFT       (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_IDLEST_DISABLE     (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_IDLEST_IDLE        (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_IDLEST_FUNC        (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_L4_WKUP_CLKCTRL_IDLEST_TRANS       (CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_L4_WKUP_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_WD_TIMER1_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_IDLEST_MASK      (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_IDLEST_SHIFT     (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_IDLEST_DISABLE   (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_IDLEST_IDLE      (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_IDLEST_FUNC      (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_IDLEST_TRANS     (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER1_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER1_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_WD_TIMER2_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_IDLEST_MASK      (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_IDLEST_SHIFT     (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_IDLEST_DISABLE   (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_IDLEST_IDLE      (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_IDLEST_FUNC      (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_IDLEST_TRANS     (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_MODULEMODE_DISABLED  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_DISABLED)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_RESERVED_1  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_MODULEMODE_RESERVED_1  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_RESERVED_1)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_ENABLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_MODULEMODE_ENABLE  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_ENABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_RESERVED  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_WD_TIMER2_CLKCTRL_MODULEMODE_RESERVED  (CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_MODULEMODE_RESERVED)


#define CSL_WKUPAON_CM_CM_WKUPAON_WD_TIMER2_CLKCTRL_REG_RESETVAL  (0x00030000U)

/* CM_WKUPAON_GPIO1_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_IDLEST_MASK          (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_IDLEST_SHIFT         (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_IDLEST_DISABLE       (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_IDLEST_IDLE          (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_IDLEST_FUNC          (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_IDLEST_TRANS         (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_OPTFCLKEN_DBCLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_SHIFT  (8U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_OPTFCLKEN_DBCLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_FCLK_EN  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_OPTFCLKEN_DBCLK_FCLK_EN  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_FCLK_EN)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_FCLK_DIS  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_OPTFCLKEN_DBCLK_FCLK_DIS  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_OPTFCLKEN_DBCLK_FCLK_DIS)


#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_MODULEMODE_MASK      (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_MODULEMODE_SHIFT     (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_MODULEMODE_DISABLED  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_DISABLED)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_MODULEMODE_AUTO      (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_AUTO)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_RESERVED_2  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_MODULEMODE_RESERVED_2  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_RESERVED_2)

#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_RESERVED  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_GPIO1_CLKCTRL_MODULEMODE_RESERVED  (CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_MODULEMODE_RESERVED)


#define CSL_WKUPAON_CM_CM_WKUPAON_GPIO1_CLKCTRL_REG_RESETVAL    (0x00030000U)

/* CM_WKUPAON_TIMER1_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_IDLEST_MASK         (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_IDLEST_SHIFT        (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_IDLEST_DISABLE      (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_IDLEST_IDLE         (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_IDLEST_FUNC         (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_IDLEST_TRANS        (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_MODULEMODE_MASK     (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_MODULEMODE_SHIFT    (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_MODULEMODE_DISABLED  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_DISABLED)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_RESERVED_1  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_MODULEMODE_RESERVED_1  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_RESERVED_1)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_ENABLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_MODULEMODE_ENABLE   (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_ENABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_RESERVED  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_MODULEMODE_RESERVED  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_MODULEMODE_RESERVED)


#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_MASK  (0x0F000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_MASK         (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SHIFT  (24U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SHIFT        (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_TIMER_SYS_CLK  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_TIMER_SYS_CLK  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_TIMER_SYS_CLK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK1_32K_CLK  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_SYS_CLK1_32K_CLK  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK1_32K_CLK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK2  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_SYS_CLK2  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK2)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK0  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_XREF_CLK0  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK0)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK1  (0x00000004U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_XREF_CLK1  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK1)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK2  (0x00000005U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_XREF_CLK2  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK2)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK3  (0x00000006U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_XREF_CLK3  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_XREF_CLK3)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_PER_ABE_X1_GFCLK  (0x00000007U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_PER_ABE_X1_GFCLK  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_PER_ABE_X1_GFCLK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_VIDEO1_CLK  (0x00000008U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_VIDEO1_CLK  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_VIDEO1_CLK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_VIDEO2_CLK  (0x00000009U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_VIDEO2_CLK  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_VIDEO2_CLK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_HDMI_CLK  (0x0000000aU)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_SEL_HDMI_CLK  (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_SEL_HDMI_CLK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED  (0x0000000bU)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_RESERVED     (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED1  (0x0000000cU)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_RESERVED1    (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED1)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED2  (0x0000000dU)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_RESERVED2    (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED2)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED3  (0x0000000eU)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_RESERVED3    (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED3)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED4  (0x0000000fU)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER1_CLKCTRL_CLKSEL_RESERVED4    (CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_CLKSEL_RESERVED4)


#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER1_CLKCTRL_REG_RESETVAL   (0x00030000U)

/* CM_WKUPAON_TIMER12_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_IDLEST_MASK        (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_IDLEST_SHIFT       (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_IDLEST_DISABLE     (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_IDLEST_IDLE        (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_IDLEST_FUNC        (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_IDLEST_TRANS       (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_MODULEMODE_MASK    (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_MODULEMODE_SHIFT   (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_TIMER12_CLKCTRL_MODULEMODE_AUTO    (CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_TIMER12_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_COUNTER_32K_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_IDLEST_MASK    (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_IDLEST_SHIFT   (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_IDLEST_DISABLE  (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_IDLEST_IDLE    (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_IDLEST_FUNC    (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_IDLEST_TRANS   (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_COUNTER_32K_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_COUNTER_32K_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_SAR_RAM_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_MODULEMODE_MASK    (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_MODULEMODE_SHIFT   (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_MODULEMODE_AUTO    (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_IDLEST_MASK        (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_IDLEST_SHIFT       (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_IDLEST_DISABLE     (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_IDLEST_IDLE        (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_IDLEST_FUNC        (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SAR_RAM_CLKCTRL_IDLEST_TRANS       (CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SAR_RAM_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_KBD_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_MASK   (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_IDLEST_MASK            (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_IDLEST_SHIFT           (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_IDLEST_DISABLE         (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_IDLE   (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_IDLEST_IDLE            (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_FUNC   (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_IDLEST_FUNC            (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_IDLEST_TRANS           (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_MODULEMODE_MASK        (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_MODULEMODE_SHIFT       (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_MODULEMODE_DISABLED    (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_DISABLED)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_RESERVED_1  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_MODULEMODE_RESERVED_1  (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_RESERVED_1)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_ENABLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_MODULEMODE_ENABLE      (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_ENABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_RESERVED  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_KBD_CLKCTRL_MODULEMODE_RESERVED    (CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_MODULEMODE_RESERVED)


#define CSL_WKUPAON_CM_CM_WKUPAON_KBD_CLKCTRL_REG_RESETVAL      (0x00030000U)

/* CM_WKUPAON_UART10_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_IDLEST_MASK         (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_IDLEST_SHIFT        (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_IDLEST_DISABLE      (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_IDLEST_IDLE         (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_IDLEST_FUNC         (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_IDLEST_TRANS        (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_MODULEMODE_MASK     (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_MODULEMODE_SHIFT    (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_MODULEMODE_DISABLED  (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_DISABLED)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_RESERVED_1  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_MODULEMODE_RESERVED_1  (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_RESERVED_1)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_ENABLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_MODULEMODE_ENABLE   (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_ENABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_RESERVED  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_MODULEMODE_RESERVED  (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_MODULEMODE_RESERVED)


#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_MASK  (0x01000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_CLKSEL_MASK         (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_SHIFT  (24U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_CLKSEL_SHIFT        (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_SEL_FUNC_48M_CLK  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_CLKSEL_SEL_FUNC_48M_CLK  (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_SEL_FUNC_48M_CLK)

#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_SEL_FUNC_192M_CLK  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_UART10_CLKCTRL_CLKSEL_SEL_FUNC_192M_CLK  (CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_CLKSEL_SEL_FUNC_192M_CLK)


#define CSL_WKUPAON_CM_CM_WKUPAON_UART10_CLKCTRL_REG_RESETVAL   (0x00030000U)

/* CM_WKUPAON_DCAN1_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_IDLEST_MASK          (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_IDLEST_SHIFT         (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_IDLEST_DISABLE       (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_IDLEST_IDLE          (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_IDLEST_FUNC          (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_IDLEST_TRANS         (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_MODULEMODE_MASK      (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_MODULEMODE_SHIFT     (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_MODULEMODE_DISABLED  (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_DISABLED)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_RESERVED_1  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_MODULEMODE_RESERVED_1  (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_RESERVED_1)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_ENABLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_MODULEMODE_ENABLE    (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_ENABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_RESERVED  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_MODULEMODE_RESERVED  (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_MODULEMODE_RESERVED)


#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_MASK  (0x01000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_CLKSEL_MASK          (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_SHIFT  (24U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_CLKSEL_SHIFT         (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK1  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_CLKSEL_SEL_SYS_CLK1  (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK1)

#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK2  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_DCAN1_CLKCTRL_CLKSEL_SEL_SYS_CLK2  (CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_CLKSEL_SEL_SYS_CLK2)


#define CSL_WKUPAON_CM_CM_WKUPAON_DCAN1_CLKCTRL_REG_RESETVAL    (0x00030000U)

/* CM_WKUPAON_SCRM_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_CORE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_SHIFT  (8U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_CORE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_FCLK_EN  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_CORE_FCLK_EN  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_FCLK_EN)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_FCLK_DIS  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_CORE_FCLK_DIS  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_CORE_FCLK_DIS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_MASK  (0x00000200U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_PER_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_SHIFT  (9U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_PER_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_FCLK_EN  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_PER_FCLK_EN  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_FCLK_EN)

#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_FCLK_DIS  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SCRM_CLKCTRL_OPTFCLKEN_SCRM_PER_FCLK_DIS  (CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_OPTFCLKEN_SCRM_PER_FCLK_DIS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SCRM_CLKCTRL_REG_RESETVAL     (0x00000000U)

/* CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_MASK  (0x00000100U)
/* Below define for backward compatibility */
#define CM_WKUPAON_IO_SRCOMP_CLKCTRL_CLKEN_SRCOMP_FCLK_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_SHIFT  (8U)
/* Below define for backward compatibility */
#define CM_WKUPAON_IO_SRCOMP_CLKCTRL_CLKEN_SRCOMP_FCLK_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_FCLK_DIS  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_IO_SRCOMP_CLKCTRL_CLKEN_SRCOMP_FCLK_FCLK_DIS  (CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_FCLK_DIS)

#define CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_FCLK_EN  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_IO_SRCOMP_CLKCTRL_CLKEN_SRCOMP_FCLK_FCLK_EN  (CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_CLKEN_SRCOMP_FCLK_FCLK_EN)


#define CSL_WKUPAON_CM_CM_WKUPAON_IO_SRCOMP_CLKCTRL_REG_RESETVAL  (0x00000000U)

/* CM_WKUPAON_ADC_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_MASK   (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_IDLEST_MASK            (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_IDLEST_SHIFT           (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_IDLEST_DISABLE         (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_IDLE   (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_IDLEST_IDLE            (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_FUNC   (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_IDLEST_FUNC            (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_IDLEST_TRANS           (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_MODULEMODE_MASK        (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000000U)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_MODULEMODE_SHIFT       (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_DISABLED  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_MODULEMODE_DISABLED    (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_DISABLED)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_RESERVED_1  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_MODULEMODE_RESERVED_1  (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_RESERVED_1)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_ENABLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_MODULEMODE_ENABLE      (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_ENABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_RESERVED  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_ADC_CLKCTRL_MODULEMODE_RESERVED    (CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_MODULEMODE_RESERVED)


#define CSL_WKUPAON_CM_CM_WKUPAON_ADC_CLKCTRL_REG_RESETVAL      (0x00030000U)

/* CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_IDLEST_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_IDLEST_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_IDLEST_DISABLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_IDLEST_IDLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_IDLEST_FUNC  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_IDLEST_TRANS  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY1_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_IDLEST_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_IDLEST_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_IDLEST_DISABLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_IDLEST_IDLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_IDLEST_FUNC  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_IDLEST_TRANS  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY2_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_IDLEST_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_IDLEST_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_IDLEST_DISABLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_IDLEST_IDLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_IDLEST_FUNC  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_IDLEST_TRANS  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY3_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_IDLEST_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_IDLEST_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_IDLEST_DISABLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_IDLEST_IDLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_IDLEST_FUNC  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_IDLEST_TRANS  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_SAFETY4_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_IDLEST_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_IDLEST_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_IDLEST_DISABLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_IDLEST_IDLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_IDLEST_FUNC  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_IDLEST_TRANS  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN2_CLKCTRL_REG_RESETVAL  (0x00030001U)

/* CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG */

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_MASK  (0x00030000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_IDLEST_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_RESETVAL  (0x00000003U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_SHIFT  (16U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_IDLEST_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_DISABLE  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_IDLEST_DISABLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_DISABLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_IDLE  (0x00000002U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_IDLEST_IDLE  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_IDLE)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_FUNC  (0x00000000U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_IDLEST_FUNC  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_FUNC)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_TRANS  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_IDLEST_TRANS  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_IDLEST_TRANS)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_MODULEMODE_MASK  (0x00000003U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_MODULEMODE_MASK  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_MODULEMODE_MASK)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_MODULEMODE_RESETVAL  (0x00000001U)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_MODULEMODE_SHIFT  (0U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_MODULEMODE_SHIFT  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_MODULEMODE_SHIFT)

#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_MODULEMODE_AUTO  (0x00000001U)
/* Below define for backward compatibility */
#define CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_MODULEMODE_AUTO  (CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_MODULEMODE_AUTO)


#define CSL_WKUPAON_CM_CM_WKUPAON_SPARE_UNKNOWN3_CLKCTRL_REG_RESETVAL  (0x00030001U)

#ifdef __cplusplus
}
#endif
#endif
