/********************************************************************
 * Copyright (C) 2020 Texas Instruments Incorporated.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  Name        : cslr_rcss_rcm.h
*/
#ifndef CSLR_RCSS_RCM_H_
#define CSLR_RCSS_RCM_H_

#ifdef __cplusplus
extern "C"
{
#endif
#include <ti/csl/cslr.h>
#include <stdint.h>

/**************************************************************************
* Hardware Region  :
**************************************************************************/


/**************************************************************************
* Register Overlay Structure
**************************************************************************/

typedef struct {
    volatile uint32_t PID;
    volatile uint32_t HW_REG0;
    volatile uint32_t HW_REG1;
    volatile uint32_t HW_REG2;
    volatile uint32_t HW_REG3;
    volatile uint32_t RCSS_I2CA_CLK_SRC_SEL;
    volatile uint32_t RCSS_I2CB_CLK_SRC_SEL;
    volatile uint32_t RCSS_SCIA_CLK_SRC_SEL;
    volatile uint32_t RCSS_SPIA_CLK_SRC_SEL;
    volatile uint32_t RCSS_SPIB_CLK_SRC_SEL;
    volatile uint32_t RCSS_ATL_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPA_REF0_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPA_REF1_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPA_AUX_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPB_REF0_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPB_REF1_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPB_AUX_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPC_REF0_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPC_REF1_CLK_SRC_SEL;
    volatile uint32_t RCSS_MCASPC_AUX_CLK_SRC_SEL;
    volatile uint32_t RCSS_I2CA_CLK_DIV_VAL;
    volatile uint32_t RCSS_I2CB_CLK_DIV_VAL;
    volatile uint32_t RCSS_SCIA_CLK_DIV_VAL;
    volatile uint32_t RCSS_SPIA_CLK_DIV_VAL;
    volatile uint32_t RCSS_SPIB_CLK_DIV_VAL;
    volatile uint32_t RCSS_ATL_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPA_REF0_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPA_REF1_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPA_AUX_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPB_REF0_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPB_REF1_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPB_AUX_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPC_REF0_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPC_REF1_CLK_DIV_VAL;
    volatile uint32_t RCSS_MCASPC_AUX_CLK_DIV_VAL;
    volatile uint32_t RCSS_I2CA_CLK_GATE;
    volatile uint32_t RCSS_I2CB_CLK_GATE;
    volatile uint32_t RCSS_SCIA_CLK_GATE;
    volatile uint32_t RCSS_SPIA_CLK_GATE;
    volatile uint32_t RCSS_SPIB_CLK_GATE;
    volatile uint32_t RCSS_ATL_CLK_GATE;
    volatile uint32_t RCSS_MCASPA_REF0_CLK_GATE;
    volatile uint32_t RCSS_MCASPA_REF1_CLK_GATE;
    volatile uint32_t RCSS_MCASPA_AUX_CLK_GATE;
    volatile uint32_t RCSS_MCASPB_REF0_CLK_GATE;
    volatile uint32_t RCSS_MCASPB_REF1_CLK_GATE;
    volatile uint32_t RCSS_MCASPB_AUX_CLK_GATE;
    volatile uint32_t RCSS_MCASPC_REF0_CLK_GATE;
    volatile uint32_t RCSS_MCASPC_REF1_CLK_GATE;
    volatile uint32_t RCSS_MCASPC_AUX_CLK_GATE;
    volatile uint32_t RCSS_ECAP_SYS_CLK_GATE;
    volatile uint32_t RCSS_CSI2A_SYS_CLK_GATE;
    volatile uint32_t RCSS_CSI2B_SYS_CLK_GATE;
    volatile uint32_t RCSS_I2CA_CLK_STATUS;
    volatile uint32_t RCSS_I2CB_CLK_STATUS;
    volatile uint32_t RCSS_SCIA_CLK_STATUS;
    volatile uint32_t RCSS_SPIA_CLK_STATUS;
    volatile uint32_t RCSS_SPIB_CLK_STATUS;
    volatile uint32_t RCSS_ATL_CLK_STATUS;
    volatile uint32_t RCSS_MCASPA_REF0_CLK_STATUS;
    volatile uint32_t RCSS_MCASPA_REF1_CLK_STATUS;
    volatile uint32_t RCSS_MCASPA_AUX_CLK_STATUS;
    volatile uint32_t RCSS_MCASPB_REF0_CLK_STATUS;
    volatile uint32_t RCSS_MCASPB_REF1_CLK_STATUS;
    volatile uint32_t RCSS_MCASPB_AUX_CLK_STATUS;
    volatile uint32_t RCSS_MCASPC_REF0_CLK_STATUS;
    volatile uint32_t RCSS_MCASPC_REF1_CLK_STATUS;
    volatile uint32_t RCSS_MCASPC_AUX_CLK_STATUS;
    volatile uint32_t RCSS_ECAP_RST_CTRL;
    volatile uint32_t RCSS_CSI2A_RST_CTRL;
    volatile uint32_t RCSS_CSI2B_RST_CTRL;
    volatile uint32_t RCSS_I2CA_RST_CTRL;
    volatile uint32_t RCSS_I2CB_RST_CTRL;
    volatile uint32_t RCSS_SCIA_RST_CTRL;
    volatile uint32_t RCSS_SPIA_RST_CTRL;
    volatile uint32_t RCSS_SPIB_RST_CTRL;
    volatile uint32_t RCSS_MCASPA_RST_CTRL;
    volatile uint32_t RCSS_MCASPB_RST_CTRL;
    volatile uint32_t RCSS_MCASPC_RST_CTRL;
    volatile uint8_t  Resv_4104[3788];
    volatile uint32_t LOCK0_KICK0;
    volatile uint32_t LOCK0_KICK1;
    volatile uint32_t INTR_RAW_STATUS;
    volatile uint32_t INTR_ENABLED_STATUS_CLEAR;
    volatile uint32_t INTR_ENABLE;
    volatile uint32_t INTR_ENABLE_CLEAR;
    volatile uint32_t EOI;
    volatile uint32_t FAULT_ADDRESS;
    volatile uint32_t FAULT_TYPE_STATUS;
    volatile uint32_t FAULT_ATTR_STATUS;
    volatile uint32_t FAULT_CLEAR;
} CSL_rcss_rcmRegs;


/**************************************************************************
* Register Macros
**************************************************************************/

#define CSL_RCSS_RCM_PID                                                       (0x00000000U)
#define CSL_RCSS_RCM_HW_REG0                                                   (0x00000004U)
#define CSL_RCSS_RCM_HW_REG1                                                   (0x00000008U)
#define CSL_RCSS_RCM_HW_REG2                                                   (0x0000000CU)
#define CSL_RCSS_RCM_HW_REG3                                                   (0x00000010U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_SRC_SEL                                     (0x00000014U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_SRC_SEL                                     (0x00000018U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_SRC_SEL                                     (0x0000001CU)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_SRC_SEL                                     (0x00000020U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_SRC_SEL                                     (0x00000024U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_SRC_SEL                                      (0x00000028U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_SRC_SEL                              (0x0000002CU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_SRC_SEL                              (0x00000030U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_SRC_SEL                               (0x00000034U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_SRC_SEL                              (0x00000038U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_SRC_SEL                              (0x0000003CU)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_SRC_SEL                               (0x00000040U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_SRC_SEL                              (0x00000044U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_SRC_SEL                              (0x00000048U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_SRC_SEL                               (0x0000004CU)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_DIV_VAL                                     (0x00000050U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_DIV_VAL                                     (0x00000054U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_DIV_VAL                                     (0x00000058U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_DIV_VAL                                     (0x0000005CU)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_DIV_VAL                                     (0x00000060U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_DIV_VAL                                      (0x00000064U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_DIV_VAL                              (0x00000068U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_DIV_VAL                              (0x0000006CU)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_DIV_VAL                               (0x00000070U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_DIV_VAL                              (0x00000074U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_DIV_VAL                              (0x00000078U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_DIV_VAL                               (0x0000007CU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_DIV_VAL                              (0x00000080U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_DIV_VAL                              (0x00000084U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_DIV_VAL                               (0x00000088U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_GATE                                        (0x0000008CU)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_GATE                                        (0x00000090U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_GATE                                        (0x00000094U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_GATE                                        (0x00000098U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_GATE                                        (0x0000009CU)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_GATE                                         (0x000000A0U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_GATE                                 (0x000000A4U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_GATE                                 (0x000000A8U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_GATE                                  (0x000000ACU)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_GATE                                 (0x000000B0U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_GATE                                 (0x000000B4U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_GATE                                  (0x000000B8U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_GATE                                 (0x000000BCU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_GATE                                 (0x000000C0U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_GATE                                  (0x000000C4U)
#define CSL_RCSS_RCM_RCSS_ECAP_SYS_CLK_GATE                                    (0x000000C8U)
#define CSL_RCSS_RCM_RCSS_CSI2A_SYS_CLK_GATE                                   (0x000000CCU)
#define CSL_RCSS_RCM_RCSS_CSI2B_SYS_CLK_GATE                                   (0x000000D0U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS                                      (0x000000D4U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS                                      (0x000000D8U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS                                      (0x000000DCU)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS                                      (0x000000E0U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS                                      (0x000000E4U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS                                       (0x000000E8U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS                               (0x000000ECU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS                               (0x000000F0U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS                                (0x000000F4U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS                               (0x000000F8U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS                               (0x000000FCU)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS                                (0x00000100U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS                               (0x00000104U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS                               (0x00000108U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS                                (0x0000010CU)
#define CSL_RCSS_RCM_RCSS_ECAP_RST_CTRL                                        (0x00000110U)
#define CSL_RCSS_RCM_RCSS_CSI2A_RST_CTRL                                       (0x00000114U)
#define CSL_RCSS_RCM_RCSS_CSI2B_RST_CTRL                                       (0x00000118U)
#define CSL_RCSS_RCM_RCSS_I2CA_RST_CTRL                                        (0x0000011CU)
#define CSL_RCSS_RCM_RCSS_I2CB_RST_CTRL                                        (0x00000120U)
#define CSL_RCSS_RCM_RCSS_SCIA_RST_CTRL                                        (0x00000124U)
#define CSL_RCSS_RCM_RCSS_SPIA_RST_CTRL                                        (0x00000128U)
#define CSL_RCSS_RCM_RCSS_SPIB_RST_CTRL                                        (0x0000012CU)
#define CSL_RCSS_RCM_RCSS_MCASPA_RST_CTRL                                      (0x00000130U)
#define CSL_RCSS_RCM_RCSS_MCASPB_RST_CTRL                                      (0x00000134U)
#define CSL_RCSS_RCM_RCSS_MCASPC_RST_CTRL                                      (0x00000138U)
#define CSL_RCSS_RCM_LOCK0_KICK0                                               (0x00001008U)
#define CSL_RCSS_RCM_LOCK0_KICK1                                               (0x0000100CU)
#define CSL_RCSS_RCM_INTR_RAW_STATUS                                           (0x00001010U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR                                 (0x00001014U)
#define CSL_RCSS_RCM_INTR_ENABLE                                               (0x00001018U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR                                         (0x0000101CU)
#define CSL_RCSS_RCM_EOI                                                       (0x00001020U)
#define CSL_RCSS_RCM_FAULT_ADDRESS                                             (0x00001024U)
#define CSL_RCSS_RCM_FAULT_TYPE_STATUS                                         (0x00001028U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS                                         (0x0000102CU)
#define CSL_RCSS_RCM_FAULT_CLEAR                                               (0x00001030U)

/**************************************************************************
* Field Definition Macros
**************************************************************************/


/* PID */

#define CSL_RCSS_RCM_PID_PID_MINOR_MASK                                        (0x0000003FU)
#define CSL_RCSS_RCM_PID_PID_MINOR_SHIFT                                       (0x00000000U)
#define CSL_RCSS_RCM_PID_PID_MINOR_RESETVAL                                    (0x00000013U)
#define CSL_RCSS_RCM_PID_PID_MINOR_MAX                                         (0x0000003FU)

#define CSL_RCSS_RCM_PID_PID_CUSTOM_MASK                                       (0x000000C0U)
#define CSL_RCSS_RCM_PID_PID_CUSTOM_SHIFT                                      (0x00000006U)
#define CSL_RCSS_RCM_PID_PID_CUSTOM_RESETVAL                                   (0x00000000U)
#define CSL_RCSS_RCM_PID_PID_CUSTOM_MAX                                        (0x00000003U)

#define CSL_RCSS_RCM_PID_PID_MAJOR_MASK                                        (0x00000700U)
#define CSL_RCSS_RCM_PID_PID_MAJOR_SHIFT                                       (0x00000008U)
#define CSL_RCSS_RCM_PID_PID_MAJOR_RESETVAL                                    (0x00000002U)
#define CSL_RCSS_RCM_PID_PID_MAJOR_MAX                                         (0x00000007U)

#define CSL_RCSS_RCM_PID_PID_MISC_MASK                                         (0x0000F800U)
#define CSL_RCSS_RCM_PID_PID_MISC_SHIFT                                        (0x0000000BU)
#define CSL_RCSS_RCM_PID_PID_MISC_RESETVAL                                     (0x00000000U)
#define CSL_RCSS_RCM_PID_PID_MISC_MAX                                          (0x0000001FU)

#define CSL_RCSS_RCM_PID_PID_MSB16_MASK                                        (0xFFFF0000U)
#define CSL_RCSS_RCM_PID_PID_MSB16_SHIFT                                       (0x00000010U)
#define CSL_RCSS_RCM_PID_PID_MSB16_RESETVAL                                    (0x00006180U)
#define CSL_RCSS_RCM_PID_PID_MSB16_MAX                                         (0x0000FFFFU)

#define CSL_RCSS_RCM_PID_RESETVAL                                              (0x61800213U)

/* HW_REG0 */

#define CSL_RCSS_RCM_HW_REG0_HW_REG0_HWREG_MASK                                (0xFFFFFFFFU)
#define CSL_RCSS_RCM_HW_REG0_HW_REG0_HWREG_SHIFT                               (0x00000000U)
#define CSL_RCSS_RCM_HW_REG0_HW_REG0_HWREG_RESETVAL                            (0x00000000U)
#define CSL_RCSS_RCM_HW_REG0_HW_REG0_HWREG_MAX                                 (0xFFFFFFFFU)

#define CSL_RCSS_RCM_HW_REG0_RESETVAL                                          (0x00000000U)

/* HW_REG1 */

#define CSL_RCSS_RCM_HW_REG1_HW_REG1_HWREG_MASK                                (0xFFFFFFFFU)
#define CSL_RCSS_RCM_HW_REG1_HW_REG1_HWREG_SHIFT                               (0x00000000U)
#define CSL_RCSS_RCM_HW_REG1_HW_REG1_HWREG_RESETVAL                            (0x00000000U)
#define CSL_RCSS_RCM_HW_REG1_HW_REG1_HWREG_MAX                                 (0xFFFFFFFFU)

#define CSL_RCSS_RCM_HW_REG1_RESETVAL                                          (0x00000000U)

/* HW_REG2 */

#define CSL_RCSS_RCM_HW_REG2_HW_REG2_HWREG_MASK                                (0xFFFFFFFFU)
#define CSL_RCSS_RCM_HW_REG2_HW_REG2_HWREG_SHIFT                               (0x00000000U)
#define CSL_RCSS_RCM_HW_REG2_HW_REG2_HWREG_RESETVAL                            (0x00000000U)
#define CSL_RCSS_RCM_HW_REG2_HW_REG2_HWREG_MAX                                 (0xFFFFFFFFU)

#define CSL_RCSS_RCM_HW_REG2_RESETVAL                                          (0x00000000U)

/* HW_REG3 */

#define CSL_RCSS_RCM_HW_REG3_HW_REG3_HWREG_MASK                                (0xFFFFFFFFU)
#define CSL_RCSS_RCM_HW_REG3_HW_REG3_HWREG_SHIFT                               (0x00000000U)
#define CSL_RCSS_RCM_HW_REG3_HW_REG3_HWREG_RESETVAL                            (0x00000000U)
#define CSL_RCSS_RCM_HW_REG3_HW_REG3_HWREG_MAX                                 (0xFFFFFFFFU)

#define CSL_RCSS_RCM_HW_REG3_RESETVAL                                          (0x00000000U)

/* RCSS_I2CA_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_SRC_SEL_RCSS_I2CA_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_SRC_SEL_RCSS_I2CA_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_SRC_SEL_RCSS_I2CA_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_SRC_SEL_RCSS_I2CA_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_SRC_SEL_RESETVAL                            (0x00000000U)

/* RCSS_I2CB_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_SRC_SEL_RCSS_I2CB_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_SRC_SEL_RCSS_I2CB_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_SRC_SEL_RCSS_I2CB_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_SRC_SEL_RCSS_I2CB_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_SRC_SEL_RESETVAL                            (0x00000000U)

/* RCSS_SCIA_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_SRC_SEL_RCSS_SCIA_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_SRC_SEL_RCSS_SCIA_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_SRC_SEL_RCSS_SCIA_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_SRC_SEL_RCSS_SCIA_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_SRC_SEL_RESETVAL                            (0x00000000U)

/* RCSS_SPIA_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_SRC_SEL_RCSS_SPIA_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_SRC_SEL_RCSS_SPIA_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_SRC_SEL_RCSS_SPIA_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_SRC_SEL_RCSS_SPIA_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_SRC_SEL_RESETVAL                            (0x00000000U)

/* RCSS_SPIB_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_SRC_SEL_RCSS_SPIB_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_SRC_SEL_RCSS_SPIB_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_SRC_SEL_RCSS_SPIB_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_SRC_SEL_RCSS_SPIB_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_SRC_SEL_RESETVAL                            (0x00000000U)

/* RCSS_ATL_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_ATL_CLK_SRC_SEL_RCSS_ATL_CLK_SRC_SEL_CLKSRCSEL_MASK  (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_SRC_SEL_RCSS_ATL_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_SRC_SEL_RCSS_ATL_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_SRC_SEL_RCSS_ATL_CLK_SRC_SEL_CLKSRCSEL_MAX   (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_ATL_CLK_SRC_SEL_RESETVAL                             (0x00000000U)

/* RCSS_MCASPA_REF0_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_SRC_SEL_RCSS_MCASPA_REF0_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_SRC_SEL_RCSS_MCASPA_REF0_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_SRC_SEL_RCSS_MCASPA_REF0_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_SRC_SEL_RCSS_MCASPA_REF0_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_SRC_SEL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPA_REF1_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_SRC_SEL_RCSS_MCASPA_REF1_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_SRC_SEL_RCSS_MCASPA_REF1_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_SRC_SEL_RCSS_MCASPA_REF1_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_SRC_SEL_RCSS_MCASPA_REF1_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_SRC_SEL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPA_AUX_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_SRC_SEL_RCSS_MCASPA_AUX_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_SRC_SEL_RCSS_MCASPA_AUX_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_SRC_SEL_RCSS_MCASPA_AUX_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_SRC_SEL_RCSS_MCASPA_AUX_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_SRC_SEL_RESETVAL                      (0x00000000U)

/* RCSS_MCASPB_REF0_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_SRC_SEL_RCSS_MCASPB_REF0_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_SRC_SEL_RCSS_MCASPB_REF0_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_SRC_SEL_RCSS_MCASPB_REF0_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_SRC_SEL_RCSS_MCASPB_REF0_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_SRC_SEL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPB_REF1_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_SRC_SEL_RCSS_MCASPB_REF1_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_SRC_SEL_RCSS_MCASPB_REF1_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_SRC_SEL_RCSS_MCASPB_REF1_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_SRC_SEL_RCSS_MCASPB_REF1_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_SRC_SEL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPB_AUX_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_SRC_SEL_RCSS_MCASPB_AUX_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_SRC_SEL_RCSS_MCASPB_AUX_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_SRC_SEL_RCSS_MCASPB_AUX_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_SRC_SEL_RCSS_MCASPB_AUX_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_SRC_SEL_RESETVAL                      (0x00000000U)

/* RCSS_MCASPC_REF0_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_SRC_SEL_RCSS_MCASPC_REF0_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_SRC_SEL_RCSS_MCASPC_REF0_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_SRC_SEL_RCSS_MCASPC_REF0_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_SRC_SEL_RCSS_MCASPC_REF0_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_SRC_SEL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPC_REF1_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_SRC_SEL_RCSS_MCASPC_REF1_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_SRC_SEL_RCSS_MCASPC_REF1_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_SRC_SEL_RCSS_MCASPC_REF1_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_SRC_SEL_RCSS_MCASPC_REF1_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_SRC_SEL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPC_AUX_CLK_SRC_SEL */

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_SRC_SEL_RCSS_MCASPC_AUX_CLK_SRC_SEL_CLKSRCSEL_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_SRC_SEL_RCSS_MCASPC_AUX_CLK_SRC_SEL_CLKSRCSEL_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_SRC_SEL_RCSS_MCASPC_AUX_CLK_SRC_SEL_CLKSRCSEL_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_SRC_SEL_RCSS_MCASPC_AUX_CLK_SRC_SEL_CLKSRCSEL_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_SRC_SEL_RESETVAL                      (0x00000000U)

/* RCSS_I2CA_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_DIV_VAL_RCSS_I2CA_CLK_DIV_VAL_CLKDIV_MASK   (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_DIV_VAL_RCSS_I2CA_CLK_DIV_VAL_CLKDIV_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_DIV_VAL_RCSS_I2CA_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_DIV_VAL_RCSS_I2CA_CLK_DIV_VAL_CLKDIV_MAX    (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_DIV_VAL_RESETVAL                            (0x00000000U)

/* RCSS_I2CB_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_DIV_VAL_RCSS_I2CB_CLK_DIV_VAL_CLKDIV_MASK   (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_DIV_VAL_RCSS_I2CB_CLK_DIV_VAL_CLKDIV_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_DIV_VAL_RCSS_I2CB_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_DIV_VAL_RCSS_I2CB_CLK_DIV_VAL_CLKDIV_MAX    (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_DIV_VAL_RESETVAL                            (0x00000000U)

/* RCSS_SCIA_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_DIV_VAL_RCSS_SCIA_CLK_DIV_VAL_CLKDIV_MASK   (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_DIV_VAL_RCSS_SCIA_CLK_DIV_VAL_CLKDIV_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_DIV_VAL_RCSS_SCIA_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_DIV_VAL_RCSS_SCIA_CLK_DIV_VAL_CLKDIV_MAX    (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_DIV_VAL_RESETVAL                            (0x00000000U)

/* RCSS_SPIA_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_DIV_VAL_RCSS_SPIA_CLK_DIV_VAL_CLKDIV_MASK   (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_DIV_VAL_RCSS_SPIA_CLK_DIV_VAL_CLKDIV_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_DIV_VAL_RCSS_SPIA_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_DIV_VAL_RCSS_SPIA_CLK_DIV_VAL_CLKDIV_MAX    (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_DIV_VAL_RESETVAL                            (0x00000000U)

/* RCSS_SPIB_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_DIV_VAL_RCSS_SPIB_CLK_DIV_VAL_CLKDIV_MASK   (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_DIV_VAL_RCSS_SPIB_CLK_DIV_VAL_CLKDIV_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_DIV_VAL_RCSS_SPIB_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_DIV_VAL_RCSS_SPIB_CLK_DIV_VAL_CLKDIV_MAX    (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_DIV_VAL_RESETVAL                            (0x00000000U)

/* RCSS_ATL_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_ATL_CLK_DIV_VAL_RCSS_ATL_CLK_DIV_VAL_CLKDIV_MASK     (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_DIV_VAL_RCSS_ATL_CLK_DIV_VAL_CLKDIV_SHIFT    (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_DIV_VAL_RCSS_ATL_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_DIV_VAL_RCSS_ATL_CLK_DIV_VAL_CLKDIV_MAX      (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_ATL_CLK_DIV_VAL_RESETVAL                             (0x00000000U)

/* RCSS_MCASPA_REF0_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_DIV_VAL_RCSS_MCASPA_REF0_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_DIV_VAL_RCSS_MCASPA_REF0_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_DIV_VAL_RCSS_MCASPA_REF0_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_DIV_VAL_RCSS_MCASPA_REF0_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_DIV_VAL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPA_REF1_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_DIV_VAL_RCSS_MCASPA_REF1_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_DIV_VAL_RCSS_MCASPA_REF1_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_DIV_VAL_RCSS_MCASPA_REF1_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_DIV_VAL_RCSS_MCASPA_REF1_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_DIV_VAL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPA_AUX_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_DIV_VAL_RCSS_MCASPA_AUX_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_DIV_VAL_RCSS_MCASPA_AUX_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_DIV_VAL_RCSS_MCASPA_AUX_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_DIV_VAL_RCSS_MCASPA_AUX_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_DIV_VAL_RESETVAL                      (0x00000000U)

/* RCSS_MCASPB_REF0_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_DIV_VAL_RCSS_MCASPB_REF0_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_DIV_VAL_RCSS_MCASPB_REF0_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_DIV_VAL_RCSS_MCASPB_REF0_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_DIV_VAL_RCSS_MCASPB_REF0_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_DIV_VAL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPB_REF1_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_DIV_VAL_RCSS_MCASPB_REF1_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_DIV_VAL_RCSS_MCASPB_REF1_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_DIV_VAL_RCSS_MCASPB_REF1_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_DIV_VAL_RCSS_MCASPB_REF1_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_DIV_VAL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPB_AUX_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_DIV_VAL_RCSS_MCASPB_AUX_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_DIV_VAL_RCSS_MCASPB_AUX_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_DIV_VAL_RCSS_MCASPB_AUX_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_DIV_VAL_RCSS_MCASPB_AUX_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_DIV_VAL_RESETVAL                      (0x00000000U)

/* RCSS_MCASPC_REF0_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_DIV_VAL_RCSS_MCASPC_REF0_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_DIV_VAL_RCSS_MCASPC_REF0_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_DIV_VAL_RCSS_MCASPC_REF0_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_DIV_VAL_RCSS_MCASPC_REF0_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_DIV_VAL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPC_REF1_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_DIV_VAL_RCSS_MCASPC_REF1_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_DIV_VAL_RCSS_MCASPC_REF1_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_DIV_VAL_RCSS_MCASPC_REF1_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_DIV_VAL_RCSS_MCASPC_REF1_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_DIV_VAL_RESETVAL                     (0x00000000U)

/* RCSS_MCASPC_AUX_CLK_DIV_VAL */

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_DIV_VAL_RCSS_MCASPC_AUX_CLK_DIV_VAL_CLKDIV_MASK (0x00000FFFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_DIV_VAL_RCSS_MCASPC_AUX_CLK_DIV_VAL_CLKDIV_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_DIV_VAL_RCSS_MCASPC_AUX_CLK_DIV_VAL_CLKDIV_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_DIV_VAL_RCSS_MCASPC_AUX_CLK_DIV_VAL_CLKDIV_MAX (0x00000FFFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_DIV_VAL_RESETVAL                      (0x00000000U)

/* RCSS_I2CA_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_GATE_RCSS_I2CA_CLK_GATE_GATED_MASK          (0x00000007U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_GATE_RCSS_I2CA_CLK_GATE_GATED_SHIFT         (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_GATE_RCSS_I2CA_CLK_GATE_GATED_RESETVAL      (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_GATE_RCSS_I2CA_CLK_GATE_GATED_MAX           (0x00000007U)

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_GATE_RESETVAL                               (0x00000000U)

/* RCSS_I2CB_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_GATE_RCSS_I2CB_CLK_GATE_GATED_MASK          (0x00000007U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_GATE_RCSS_I2CB_CLK_GATE_GATED_SHIFT         (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_GATE_RCSS_I2CB_CLK_GATE_GATED_RESETVAL      (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_GATE_RCSS_I2CB_CLK_GATE_GATED_MAX           (0x00000007U)

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_GATE_RESETVAL                               (0x00000000U)

/* RCSS_SCIA_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_GATE_RCSS_SCIA_CLK_GATE_GATED_MASK          (0x00000007U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_GATE_RCSS_SCIA_CLK_GATE_GATED_SHIFT         (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_GATE_RCSS_SCIA_CLK_GATE_GATED_RESETVAL      (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_GATE_RCSS_SCIA_CLK_GATE_GATED_MAX           (0x00000007U)

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_GATE_RESETVAL                               (0x00000000U)

/* RCSS_SPIA_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_GATE_RCSS_SPIA_CLK_GATE_GATED_MASK          (0x00000007U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_GATE_RCSS_SPIA_CLK_GATE_GATED_SHIFT         (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_GATE_RCSS_SPIA_CLK_GATE_GATED_RESETVAL      (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_GATE_RCSS_SPIA_CLK_GATE_GATED_MAX           (0x00000007U)

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_GATE_RESETVAL                               (0x00000000U)

/* RCSS_SPIB_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_GATE_RCSS_SPIB_CLK_GATE_GATED_MASK          (0x00000007U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_GATE_RCSS_SPIB_CLK_GATE_GATED_SHIFT         (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_GATE_RCSS_SPIB_CLK_GATE_GATED_RESETVAL      (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_GATE_RCSS_SPIB_CLK_GATE_GATED_MAX           (0x00000007U)

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_GATE_RESETVAL                               (0x00000000U)

/* RCSS_ATL_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_ATL_CLK_GATE_RCSS_ATL_CLK_GATE_GATED_MASK            (0x00000007U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_GATE_RCSS_ATL_CLK_GATE_GATED_SHIFT           (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_GATE_RCSS_ATL_CLK_GATE_GATED_RESETVAL        (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_GATE_RCSS_ATL_CLK_GATE_GATED_MAX             (0x00000007U)

#define CSL_RCSS_RCM_RCSS_ATL_CLK_GATE_RESETVAL                                (0x00000000U)

/* RCSS_MCASPA_REF0_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_GATE_RCSS_MCASPA_REF0_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_GATE_RCSS_MCASPA_REF0_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_GATE_RCSS_MCASPA_REF0_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_GATE_RCSS_MCASPA_REF0_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_GATE_RESETVAL                        (0x00000000U)

/* RCSS_MCASPA_REF1_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_GATE_RCSS_MCASPA_REF1_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_GATE_RCSS_MCASPA_REF1_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_GATE_RCSS_MCASPA_REF1_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_GATE_RCSS_MCASPA_REF1_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_GATE_RESETVAL                        (0x00000000U)

/* RCSS_MCASPA_AUX_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_GATE_RCSS_MCASPA_AUX_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_GATE_RCSS_MCASPA_AUX_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_GATE_RCSS_MCASPA_AUX_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_GATE_RCSS_MCASPA_AUX_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_GATE_RESETVAL                         (0x00000000U)

/* RCSS_MCASPB_REF0_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_GATE_RCSS_MCASPB_REF0_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_GATE_RCSS_MCASPB_REF0_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_GATE_RCSS_MCASPB_REF0_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_GATE_RCSS_MCASPB_REF0_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_GATE_RESETVAL                        (0x00000000U)

/* RCSS_MCASPB_REF1_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_GATE_RCSS_MCASPB_REF1_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_GATE_RCSS_MCASPB_REF1_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_GATE_RCSS_MCASPB_REF1_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_GATE_RCSS_MCASPB_REF1_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_GATE_RESETVAL                        (0x00000000U)

/* RCSS_MCASPB_AUX_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_GATE_RCSS_MCASPB_AUX_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_GATE_RCSS_MCASPB_AUX_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_GATE_RCSS_MCASPB_AUX_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_GATE_RCSS_MCASPB_AUX_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_GATE_RESETVAL                         (0x00000000U)

/* RCSS_MCASPC_REF0_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_GATE_RCSS_MCASPC_REF0_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_GATE_RCSS_MCASPC_REF0_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_GATE_RCSS_MCASPC_REF0_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_GATE_RCSS_MCASPC_REF0_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_GATE_RESETVAL                        (0x00000000U)

/* RCSS_MCASPC_REF1_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_GATE_RCSS_MCASPC_REF1_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_GATE_RCSS_MCASPC_REF1_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_GATE_RCSS_MCASPC_REF1_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_GATE_RCSS_MCASPC_REF1_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_GATE_RESETVAL                        (0x00000000U)

/* RCSS_MCASPC_AUX_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_GATE_RCSS_MCASPC_AUX_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_GATE_RCSS_MCASPC_AUX_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_GATE_RCSS_MCASPC_AUX_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_GATE_RCSS_MCASPC_AUX_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_GATE_RESETVAL                         (0x00000000U)

/* RCSS_ECAP_SYS_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_ECAP_SYS_CLK_GATE_RCSS_ECAP_SYS_CLK_GATE_GATED_MASK  (0x00000007U)
#define CSL_RCSS_RCM_RCSS_ECAP_SYS_CLK_GATE_RCSS_ECAP_SYS_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ECAP_SYS_CLK_GATE_RCSS_ECAP_SYS_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ECAP_SYS_CLK_GATE_RCSS_ECAP_SYS_CLK_GATE_GATED_MAX   (0x00000007U)

#define CSL_RCSS_RCM_RCSS_ECAP_SYS_CLK_GATE_RESETVAL                           (0x00000000U)

/* RCSS_CSI2A_SYS_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_CSI2A_SYS_CLK_GATE_RCSS_CSI2A_SYS_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_CSI2A_SYS_CLK_GATE_RCSS_CSI2A_SYS_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2A_SYS_CLK_GATE_RCSS_CSI2A_SYS_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2A_SYS_CLK_GATE_RCSS_CSI2A_SYS_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_CSI2A_SYS_CLK_GATE_RESETVAL                          (0x00000000U)

/* RCSS_CSI2B_SYS_CLK_GATE */

#define CSL_RCSS_RCM_RCSS_CSI2B_SYS_CLK_GATE_RCSS_CSI2B_SYS_CLK_GATE_GATED_MASK (0x00000007U)
#define CSL_RCSS_RCM_RCSS_CSI2B_SYS_CLK_GATE_RCSS_CSI2B_SYS_CLK_GATE_GATED_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2B_SYS_CLK_GATE_RCSS_CSI2B_SYS_CLK_GATE_GATED_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2B_SYS_CLK_GATE_RCSS_CSI2B_SYS_CLK_GATE_GATED_MAX (0x00000007U)

#define CSL_RCSS_RCM_RCSS_CSI2B_SYS_CLK_GATE_RESETVAL                          (0x00000000U)

/* RCSS_I2CA_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKINUSE_MASK   (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKINUSE_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKINUSE_MAX    (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKSWITCH_MASK  (0x00010000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RCSS_I2CA_CLK_STATUS_CLKSWITCH_MAX   (0x00000001U)

#define CSL_RCSS_RCM_RCSS_I2CA_CLK_STATUS_RESETVAL                             (0x00000000U)

/* RCSS_I2CB_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKINUSE_MASK   (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKINUSE_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKINUSE_MAX    (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKSWITCH_MASK  (0x00010000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RCSS_I2CB_CLK_STATUS_CLKSWITCH_MAX   (0x00000001U)

#define CSL_RCSS_RCM_RCSS_I2CB_CLK_STATUS_RESETVAL                             (0x00000000U)

/* RCSS_SCIA_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKINUSE_MASK   (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKINUSE_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKINUSE_MAX    (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKSWITCH_MASK  (0x00010000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RCSS_SCIA_CLK_STATUS_CLKSWITCH_MAX   (0x00000001U)

#define CSL_RCSS_RCM_RCSS_SCIA_CLK_STATUS_RESETVAL                             (0x00000000U)

/* RCSS_SPIA_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKINUSE_MASK   (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKINUSE_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKINUSE_MAX    (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKSWITCH_MASK  (0x00010000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RCSS_SPIA_CLK_STATUS_CLKSWITCH_MAX   (0x00000001U)

#define CSL_RCSS_RCM_RCSS_SPIA_CLK_STATUS_RESETVAL                             (0x00000000U)

/* RCSS_SPIB_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKINUSE_MASK   (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKINUSE_SHIFT  (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKINUSE_MAX    (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKSWITCH_MASK  (0x00010000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RCSS_SPIB_CLK_STATUS_CLKSWITCH_MAX   (0x00000001U)

#define CSL_RCSS_RCM_RCSS_SPIB_CLK_STATUS_RESETVAL                             (0x00000000U)

/* RCSS_ATL_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKINUSE_MASK     (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKINUSE_SHIFT    (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKINUSE_MAX      (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CURRDIVIDER_MASK  (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CURRDIVIDER_MAX   (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKSWITCH_MASK    (0x00010000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKSWITCH_SHIFT   (0x00000010U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RCSS_ATL_CLK_STATUS_CLKSWITCH_MAX     (0x00000001U)

#define CSL_RCSS_RCM_RCSS_ATL_CLK_STATUS_RESETVAL                              (0x00000000U)

/* RCSS_MCASPA_REF0_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RCSS_MCASPA_REF0_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF0_CLK_STATUS_RESETVAL                      (0x00000000U)

/* RCSS_MCASPA_REF1_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RCSS_MCASPA_REF1_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPA_REF1_CLK_STATUS_RESETVAL                      (0x00000000U)

/* RCSS_MCASPA_AUX_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RCSS_MCASPA_AUX_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPA_AUX_CLK_STATUS_RESETVAL                       (0x00000000U)

/* RCSS_MCASPB_REF0_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RCSS_MCASPB_REF0_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF0_CLK_STATUS_RESETVAL                      (0x00000000U)

/* RCSS_MCASPB_REF1_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RCSS_MCASPB_REF1_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPB_REF1_CLK_STATUS_RESETVAL                      (0x00000000U)

/* RCSS_MCASPB_AUX_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RCSS_MCASPB_AUX_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPB_AUX_CLK_STATUS_RESETVAL                       (0x00000000U)

/* RCSS_MCASPC_REF0_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RCSS_MCASPC_REF0_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF0_CLK_STATUS_RESETVAL                      (0x00000000U)

/* RCSS_MCASPC_REF1_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RCSS_MCASPC_REF1_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPC_REF1_CLK_STATUS_RESETVAL                      (0x00000000U)

/* RCSS_MCASPC_AUX_CLK_STATUS */

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKINUSE_MASK (0x000000FFU)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKINUSE_SHIFT (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKINUSE_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKINUSE_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CURRDIVIDER_MASK (0x0000FF00U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CURRDIVIDER_SHIFT (0x00000008U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CURRDIVIDER_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CURRDIVIDER_MAX (0x000000FFU)

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKSWITCH_MASK (0x00010000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKSWITCH_SHIFT (0x00000010U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKSWITCH_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RCSS_MCASPC_AUX_CLK_STATUS_CLKSWITCH_MAX (0x00000001U)

#define CSL_RCSS_RCM_RCSS_MCASPC_AUX_CLK_STATUS_RESETVAL                       (0x00000000U)

/* RCSS_ECAP_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_ECAP_RST_CTRL_RCSS_ECAP_RST_CTRL_ASSERT_MASK         (0x00000007U)
#define CSL_RCSS_RCM_RCSS_ECAP_RST_CTRL_RCSS_ECAP_RST_CTRL_ASSERT_SHIFT        (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ECAP_RST_CTRL_RCSS_ECAP_RST_CTRL_ASSERT_RESETVAL     (0x00000000U)
#define CSL_RCSS_RCM_RCSS_ECAP_RST_CTRL_RCSS_ECAP_RST_CTRL_ASSERT_MAX          (0x00000007U)

#define CSL_RCSS_RCM_RCSS_ECAP_RST_CTRL_RESETVAL                               (0x00000000U)

/* RCSS_CSI2A_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_CSI2A_RST_CTRL_RCSS_CSI2A_RST_CTRL_ASSERT_MASK       (0x00000007U)
#define CSL_RCSS_RCM_RCSS_CSI2A_RST_CTRL_RCSS_CSI2A_RST_CTRL_ASSERT_SHIFT      (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2A_RST_CTRL_RCSS_CSI2A_RST_CTRL_ASSERT_RESETVAL   (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2A_RST_CTRL_RCSS_CSI2A_RST_CTRL_ASSERT_MAX        (0x00000007U)

#define CSL_RCSS_RCM_RCSS_CSI2A_RST_CTRL_RESETVAL                              (0x00000000U)

/* RCSS_CSI2B_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_CSI2B_RST_CTRL_RCSS_CSI2B_RST_CTRL_ASSERT_MASK       (0x00000007U)
#define CSL_RCSS_RCM_RCSS_CSI2B_RST_CTRL_RCSS_CSI2B_RST_CTRL_ASSERT_SHIFT      (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2B_RST_CTRL_RCSS_CSI2B_RST_CTRL_ASSERT_RESETVAL   (0x00000000U)
#define CSL_RCSS_RCM_RCSS_CSI2B_RST_CTRL_RCSS_CSI2B_RST_CTRL_ASSERT_MAX        (0x00000007U)

#define CSL_RCSS_RCM_RCSS_CSI2B_RST_CTRL_RESETVAL                              (0x00000000U)

/* RCSS_I2CA_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_I2CA_RST_CTRL_RCSS_I2CA_RST_CTRL_ASSERT_MASK         (0x00000007U)
#define CSL_RCSS_RCM_RCSS_I2CA_RST_CTRL_RCSS_I2CA_RST_CTRL_ASSERT_SHIFT        (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_RST_CTRL_RCSS_I2CA_RST_CTRL_ASSERT_RESETVAL     (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CA_RST_CTRL_RCSS_I2CA_RST_CTRL_ASSERT_MAX          (0x00000007U)

#define CSL_RCSS_RCM_RCSS_I2CA_RST_CTRL_RESETVAL                               (0x00000000U)

/* RCSS_I2CB_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_I2CB_RST_CTRL_RCSS_I2CB_RST_CTRL_ASSERT_MASK         (0x00000007U)
#define CSL_RCSS_RCM_RCSS_I2CB_RST_CTRL_RCSS_I2CB_RST_CTRL_ASSERT_SHIFT        (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_RST_CTRL_RCSS_I2CB_RST_CTRL_ASSERT_RESETVAL     (0x00000000U)
#define CSL_RCSS_RCM_RCSS_I2CB_RST_CTRL_RCSS_I2CB_RST_CTRL_ASSERT_MAX          (0x00000007U)

#define CSL_RCSS_RCM_RCSS_I2CB_RST_CTRL_RESETVAL                               (0x00000000U)

/* RCSS_SCIA_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_SCIA_RST_CTRL_RCSS_SCIA_RST_CTRL_ASSERT_MASK         (0x00000007U)
#define CSL_RCSS_RCM_RCSS_SCIA_RST_CTRL_RCSS_SCIA_RST_CTRL_ASSERT_SHIFT        (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_RST_CTRL_RCSS_SCIA_RST_CTRL_ASSERT_RESETVAL     (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SCIA_RST_CTRL_RCSS_SCIA_RST_CTRL_ASSERT_MAX          (0x00000007U)

#define CSL_RCSS_RCM_RCSS_SCIA_RST_CTRL_RESETVAL                               (0x00000000U)

/* RCSS_SPIA_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_SPIA_RST_CTRL_RCSS_SPIA_RST_CTRL_ASSERT_MASK         (0x00000007U)
#define CSL_RCSS_RCM_RCSS_SPIA_RST_CTRL_RCSS_SPIA_RST_CTRL_ASSERT_SHIFT        (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_RST_CTRL_RCSS_SPIA_RST_CTRL_ASSERT_RESETVAL     (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIA_RST_CTRL_RCSS_SPIA_RST_CTRL_ASSERT_MAX          (0x00000007U)

#define CSL_RCSS_RCM_RCSS_SPIA_RST_CTRL_RESETVAL                               (0x00000000U)

/* RCSS_SPIB_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_SPIB_RST_CTRL_RCSS_SPIB_RST_CTRL_ASSERT_MASK         (0x00000007U)
#define CSL_RCSS_RCM_RCSS_SPIB_RST_CTRL_RCSS_SPIB_RST_CTRL_ASSERT_SHIFT        (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_RST_CTRL_RCSS_SPIB_RST_CTRL_ASSERT_RESETVAL     (0x00000000U)
#define CSL_RCSS_RCM_RCSS_SPIB_RST_CTRL_RCSS_SPIB_RST_CTRL_ASSERT_MAX          (0x00000007U)

#define CSL_RCSS_RCM_RCSS_SPIB_RST_CTRL_RESETVAL                               (0x00000000U)

/* RCSS_MCASPA_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_MCASPA_RST_CTRL_RCSS_MCASPA_RST_CTRL_ASSERT_MASK     (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPA_RST_CTRL_RCSS_MCASPA_RST_CTRL_ASSERT_SHIFT    (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_RST_CTRL_RCSS_MCASPA_RST_CTRL_ASSERT_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPA_RST_CTRL_RCSS_MCASPA_RST_CTRL_ASSERT_MAX      (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPA_RST_CTRL_RESETVAL                             (0x00000000U)

/* RCSS_MCASPB_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_MCASPB_RST_CTRL_RCSS_MCASPB_RST_CTRL_ASSERT_MASK     (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPB_RST_CTRL_RCSS_MCASPB_RST_CTRL_ASSERT_SHIFT    (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_RST_CTRL_RCSS_MCASPB_RST_CTRL_ASSERT_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPB_RST_CTRL_RCSS_MCASPB_RST_CTRL_ASSERT_MAX      (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPB_RST_CTRL_RESETVAL                             (0x00000000U)

/* RCSS_MCASPC_RST_CTRL */

#define CSL_RCSS_RCM_RCSS_MCASPC_RST_CTRL_RCSS_MCASPC_RST_CTRL_ASSERT_MASK     (0x00000007U)
#define CSL_RCSS_RCM_RCSS_MCASPC_RST_CTRL_RCSS_MCASPC_RST_CTRL_ASSERT_SHIFT    (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_RST_CTRL_RCSS_MCASPC_RST_CTRL_ASSERT_RESETVAL (0x00000000U)
#define CSL_RCSS_RCM_RCSS_MCASPC_RST_CTRL_RCSS_MCASPC_RST_CTRL_ASSERT_MAX      (0x00000007U)

#define CSL_RCSS_RCM_RCSS_MCASPC_RST_CTRL_RESETVAL                             (0x00000000U)

/* LOCK0_KICK0 */

#define CSL_RCSS_RCM_LOCK0_KICK0_LOCK0_KICK0_MASK                              (0xFFFFFFFFU)
#define CSL_RCSS_RCM_LOCK0_KICK0_LOCK0_KICK0_SHIFT                             (0x00000000U)
#define CSL_RCSS_RCM_LOCK0_KICK0_LOCK0_KICK0_RESETVAL                          (0x00000000U)
#define CSL_RCSS_RCM_LOCK0_KICK0_LOCK0_KICK0_MAX                               (0xFFFFFFFFU)

#define CSL_RCSS_RCM_LOCK0_KICK0_RESETVAL                                      (0x00000000U)

/* LOCK0_KICK1 */

#define CSL_RCSS_RCM_LOCK0_KICK1_LOCK0_KICK1_MASK                              (0xFFFFFFFFU)
#define CSL_RCSS_RCM_LOCK0_KICK1_LOCK0_KICK1_SHIFT                             (0x00000000U)
#define CSL_RCSS_RCM_LOCK0_KICK1_LOCK0_KICK1_RESETVAL                          (0x00000000U)
#define CSL_RCSS_RCM_LOCK0_KICK1_LOCK0_KICK1_MAX                               (0xFFFFFFFFU)

#define CSL_RCSS_RCM_LOCK0_KICK1_RESETVAL                                      (0x00000000U)

/* INTR_RAW_STATUS */

#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROT_ERR_MASK                             (0x00000001U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROT_ERR_SHIFT                            (0x00000000U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROT_ERR_RESETVAL                         (0x00000000U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROT_ERR_MAX                              (0x00000001U)

#define CSL_RCSS_RCM_INTR_RAW_STATUS_ADDR_ERR_MASK                             (0x00000002U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_ADDR_ERR_SHIFT                            (0x00000001U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_ADDR_ERR_RESETVAL                         (0x00000000U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_ADDR_ERR_MAX                              (0x00000001U)

#define CSL_RCSS_RCM_INTR_RAW_STATUS_KICK_ERR_MASK                             (0x00000004U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_KICK_ERR_SHIFT                            (0x00000002U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_KICK_ERR_RESETVAL                         (0x00000000U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_KICK_ERR_MAX                              (0x00000001U)

#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROXY_ERR_MASK                            (0x00000008U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROXY_ERR_SHIFT                           (0x00000003U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROXY_ERR_RESETVAL                        (0x00000000U)
#define CSL_RCSS_RCM_INTR_RAW_STATUS_PROXY_ERR_MAX                             (0x00000001U)

#define CSL_RCSS_RCM_INTR_RAW_STATUS_RESETVAL                                  (0x00000000U)

/* INTR_ENABLED_STATUS_CLEAR */

#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MASK           (0x00000001U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_SHIFT          (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_RESETVAL       (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROT_ERR_MAX            (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MASK           (0x00000002U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_SHIFT          (0x00000001U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_RESETVAL       (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_ADDR_ERR_MAX            (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MASK           (0x00000004U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_SHIFT          (0x00000002U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_RESETVAL       (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_KICK_ERR_MAX            (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MASK          (0x00000008U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_SHIFT         (0x00000003U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_RESETVAL      (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_ENABLED_PROXY_ERR_MAX           (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLED_STATUS_CLEAR_RESETVAL                        (0x00000000U)

/* INTR_ENABLE */

#define CSL_RCSS_RCM_INTR_ENABLE_PROT_ERR_EN_MASK                              (0x00000001U)
#define CSL_RCSS_RCM_INTR_ENABLE_PROT_ERR_EN_SHIFT                             (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_PROT_ERR_EN_RESETVAL                          (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_PROT_ERR_EN_MAX                               (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_ADDR_ERR_EN_MASK                              (0x00000002U)
#define CSL_RCSS_RCM_INTR_ENABLE_ADDR_ERR_EN_SHIFT                             (0x00000001U)
#define CSL_RCSS_RCM_INTR_ENABLE_ADDR_ERR_EN_RESETVAL                          (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_ADDR_ERR_EN_MAX                               (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_KICK_ERR_EN_MASK                              (0x00000004U)
#define CSL_RCSS_RCM_INTR_ENABLE_KICK_ERR_EN_SHIFT                             (0x00000002U)
#define CSL_RCSS_RCM_INTR_ENABLE_KICK_ERR_EN_RESETVAL                          (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_KICK_ERR_EN_MAX                               (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_PROXY_ERR_EN_MASK                             (0x00000008U)
#define CSL_RCSS_RCM_INTR_ENABLE_PROXY_ERR_EN_SHIFT                            (0x00000003U)
#define CSL_RCSS_RCM_INTR_ENABLE_PROXY_ERR_EN_RESETVAL                         (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_PROXY_ERR_EN_MAX                              (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_RESETVAL                                      (0x00000000U)

/* INTR_ENABLE_CLEAR */

#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MASK                    (0x00000001U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_SHIFT                   (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_RESETVAL                (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROT_ERR_EN_CLR_MAX                     (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MASK                    (0x00000002U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_SHIFT                   (0x00000001U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_RESETVAL                (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_ADDR_ERR_EN_CLR_MAX                     (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MASK                    (0x00000004U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_SHIFT                   (0x00000002U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_RESETVAL                (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_KICK_ERR_EN_CLR_MAX                     (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MASK                   (0x00000008U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_SHIFT                  (0x00000003U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_RESETVAL               (0x00000000U)
#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_PROXY_ERR_EN_CLR_MAX                    (0x00000001U)

#define CSL_RCSS_RCM_INTR_ENABLE_CLEAR_RESETVAL                                (0x00000000U)

/* EOI */

#define CSL_RCSS_RCM_EOI_EOI_VECTOR_MASK                                       (0x000000FFU)
#define CSL_RCSS_RCM_EOI_EOI_VECTOR_SHIFT                                      (0x00000000U)
#define CSL_RCSS_RCM_EOI_EOI_VECTOR_RESETVAL                                   (0x00000000U)
#define CSL_RCSS_RCM_EOI_EOI_VECTOR_MAX                                        (0x000000FFU)

#define CSL_RCSS_RCM_EOI_RESETVAL                                              (0x00000000U)

/* FAULT_ADDRESS */

#define CSL_RCSS_RCM_FAULT_ADDRESS_FAULT_ADDR_MASK                             (0xFFFFFFFFU)
#define CSL_RCSS_RCM_FAULT_ADDRESS_FAULT_ADDR_SHIFT                            (0x00000000U)
#define CSL_RCSS_RCM_FAULT_ADDRESS_FAULT_ADDR_RESETVAL                         (0x00000000U)
#define CSL_RCSS_RCM_FAULT_ADDRESS_FAULT_ADDR_MAX                              (0xFFFFFFFFU)

#define CSL_RCSS_RCM_FAULT_ADDRESS_RESETVAL                                    (0x00000000U)

/* FAULT_TYPE_STATUS */

#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_TYPE_MASK                         (0x0000003FU)
#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_TYPE_SHIFT                        (0x00000000U)
#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_TYPE_RESETVAL                     (0x00000000U)
#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_TYPE_MAX                          (0x0000003FU)

#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_NS_MASK                           (0x00000040U)
#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_NS_SHIFT                          (0x00000006U)
#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_NS_RESETVAL                       (0x00000000U)
#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_FAULT_NS_MAX                            (0x00000001U)

#define CSL_RCSS_RCM_FAULT_TYPE_STATUS_RESETVAL                                (0x00000000U)

/* FAULT_ATTR_STATUS */

#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_PRIVID_MASK                       (0x000000FFU)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_PRIVID_SHIFT                      (0x00000000U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_PRIVID_RESETVAL                   (0x00000000U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_PRIVID_MAX                        (0x000000FFU)

#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_ROUTEID_MASK                      (0x000FFF00U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_ROUTEID_SHIFT                     (0x00000008U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_ROUTEID_RESETVAL                  (0x00000000U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_ROUTEID_MAX                       (0x00000FFFU)

#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_XID_MASK                          (0xFFF00000U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_XID_SHIFT                         (0x00000014U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_XID_RESETVAL                      (0x00000000U)
#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_FAULT_XID_MAX                           (0x00000FFFU)

#define CSL_RCSS_RCM_FAULT_ATTR_STATUS_RESETVAL                                (0x00000000U)

/* FAULT_CLEAR */

#define CSL_RCSS_RCM_FAULT_CLEAR_FAULT_CLR_MASK                                (0x00000001U)
#define CSL_RCSS_RCM_FAULT_CLEAR_FAULT_CLR_SHIFT                               (0x00000000U)
#define CSL_RCSS_RCM_FAULT_CLEAR_FAULT_CLR_RESETVAL                            (0x00000000U)
#define CSL_RCSS_RCM_FAULT_CLEAR_FAULT_CLR_MAX                                 (0x00000001U)

#define CSL_RCSS_RCM_FAULT_CLEAR_RESETVAL                                      (0x00000000U)

#ifdef __cplusplus
}
#endif
#endif
